export const chatErrorMessages:Record<string,string>={
 'retrieval-not-ready':'Local transcripts are still being discovered. Wait, then refresh chat.',
 'retrieval-capacity':'The local transcript catalog reached its capacity. Reduce the stored meeting collection and refresh chat.',
 'retrieval-unavailable':'Local transcript retrieval is unavailable. Refresh chat and retry.',
 'question-context-too-large':'This question or its required evidence exceeds the local model input budget. Ask a shorter or narrower question.',

 "cancelled":"Answer cancelled.",
 "context-limit":"The model context limit was reached. Ask a shorter or narrower question.",
 "source-changed":"The transcript changed. Refresh before asking or retrying.",
 "history-changed":"Chat history changed. Refresh and retry.",
 "model-missing":"The selected local model is not installed. Choose another model.",
 "model-incompatible":"This model cannot answer questions. Choose an installed chat model.",
 "ollama-unavailable":"Local chat unavailable. Start Ollama and retry.",
 "local-only":"Chat requires an installed local model.",
 "invalid-evidence":"The model returned unsupported citations. Retry or choose another model.",
 "invalid-answer":"The model returned an invalid answer. Retry or choose another model.",
 "incomplete-output":"The answer was interrupted. Retry when ready.",
 "generation-failed":"Could not generate an answer. Retry or choose another model.",
 "interrupted":"The answer was interrupted. Retry when ready.",
 "resources-busy":"Answer stopped to prioritize recording or transcription.",
 "chat-storage-failed":"Could not save chat history. Refresh and retry.",
 "transcript-empty":"This meeting has no transcript evidence.",
 "transcript-not-final":"Chat becomes available after the final transcript is saved.",
 "history-full":"Chat history is full. Clear it before asking another question.",
};
