import type { Locale } from "./locale";
export const DETECTION_TRANSLATIONS: Record<string, Partial<Record<Locale,string>>> = {
 "Meeting detection could not save its state. Automation is disabled; stop the recording manually and reconfigure detection after fixing storage.": {"pt-BR": "Não foi possível salvar o estado da detecção. A automação está desativada; pare a gravação manualmente e reconfigure a detecção após corrigir o armazenamento.", "fr": "Impossible d’enregistrer l’état de détection. L’automatisation est désactivée ; arrêtez manuellement l’enregistrement et reconfigurez la détection après avoir corrigé le stockage.", "de": "Der Erkennungsstatus konnte nicht gespeichert werden. Die Automatisierung ist deaktiviert; beenden Sie die Aufnahme manuell und konfigurieren Sie die Erkennung nach Beheben des Speicherproblems erneut."},
 "Meeting detection settings could not be read. Reconfigure detection before using it.": {"pt-BR": "Não foi possível ler as configurações da detecção. Reconfigure a detecção antes de usá-la.", "fr": "Impossible de lire les paramètres de détection. Reconfigurez la détection avant de l’utiliser.", "de": "Die Erkennungseinstellungen konnten nicht gelesen werden. Konfigurieren Sie die Erkennung vor der Nutzung erneut."},

 "Waiting for reconnect — {seconds}s": {"pt-BR":"Aguardando reconexão — {seconds}s",fr:"En attente de reconnexion — {seconds}s",de:"Warten auf Wiederverbindung — {seconds}s"},
 "Automatic recording is waiting for capture permissions and a ready transcription model.": {"pt-BR":"A gravação automática aguarda permissões de captura e um modelo de transcrição pronto.",fr:"L’enregistrement automatique attend les autorisations de capture et un modèle de transcription prêt.",de:"Die automatische Aufnahme wartet auf Aufnahmeberechtigungen und ein bereites Transkriptionsmodell."},
 "Automatic meeting detection": {"pt-BR":"Detecção automática de reuniões",fr:"Détection automatique des réunions",de:"Automatische Besprechungserkennung"},
 "Choose the apps that may start a recording. Manual recordings always stay under your control.": {"pt-BR":"Escolha os aplicativos que podem iniciar uma gravação. As gravações manuais ficam sempre sob seu controle.",fr:"Choisissez les applications pouvant démarrer un enregistrement. Les enregistrements manuels restent sous votre contrôle.",de:"Wählen Sie die Apps, die eine Aufnahme starten dürfen. Manuelle Aufnahmen bleiben unter Ihrer Kontrolle."},
 "Paused for this call": {"pt-BR":"Pausado para esta chamada",fr:"En pause pour cet appel",de:"Für diesen Anruf pausiert"},
 "Accessibility permission needed": {"pt-BR":"Permissão de Acessibilidade necessária",fr:"Autorisation d’accessibilité nécessaire",de:"Berechtigung für Bedienungshilfen erforderlich"},
 "Detection unavailable — use manual recording": {"pt-BR":"Detecção indisponível — use a gravação manual",fr:"Détection indisponible — utilisez l’enregistrement manuel",de:"Erkennung nicht verfügbar — manuell aufnehmen"},
 "Meeting detected": {"pt-BR":"Reunião detectada",fr:"Réunion détectée",de:"Besprechung erkannt"},
 "Waiting for a meeting": {"pt-BR":"Aguardando uma reunião",fr:"En attente d’une réunion",de:"Warten auf eine Besprechung"},
 "Zoom and Teams use authorized Accessibility controls. Hidden or changed controls suspend detection. Meet requires the scoped Chrome or Edge extension and local native host.": {"pt-BR":"Zoom e Teams usam controles de Acessibilidade autorizados. Controles ocultos ou alterados suspendem a detecção. O Meet requer a extensão limitada ao Meet no Chrome ou Edge e o conector nativo local.",fr:"Zoom et Teams utilisent les contrôles d’accessibilité autorisés. Les contrôles masqués ou modifiés suspendent la détection. Meet nécessite l’extension limitée à Meet pour Chrome ou Edge et le connecteur natif local.",de:"Zoom und Teams nutzen freigegebene Bedienungshilfen. Verborgene oder geänderte Bedienelemente unterbrechen die Erkennung. Meet benötigt die auf Meet beschränkte Chrome- oder Edge-Erweiterung und den lokalen nativen Connector."},
 "Authorize Accessibility": {"pt-BR":"Autorizar Acessibilidade",fr:"Autoriser l’accessibilité",de:"Bedienungshilfen erlauben"},
 "Meeting detection setup and capabilities": {"pt-BR":"Configuração e recursos da detecção de reuniões",fr:"Configuration et capacités de détection des réunions",de:"Einrichtung und Funktionen der Besprechungserkennung"},
 "Join confirmation takes 3 seconds; a confirmed end waits 5 seconds for reconnects. Missing controls or permission never prove a call ended. Stop manually if detection becomes unavailable.": {"pt-BR":"A confirmação de entrada leva 3 segundos; um encerramento confirmado aguarda 5 segundos para reconexões. A ausência de controles ou permissão não comprova o fim da chamada. Pare manualmente se a detecção ficar indisponível.",fr:"La confirmation d’entrée prend 3 secondes ; une fin confirmée attend 5 secondes pour les reconnexions. L’absence de contrôles ou d’autorisation ne prouve jamais la fin d’un appel. Arrêtez manuellement si la détection devient indisponible.",de:"Der Beitritt wird nach 3 Sekunden bestätigt; nach einem bestätigten Ende bleiben 5 Sekunden für eine Wiederverbindung. Fehlende Bedienelemente oder Berechtigungen beweisen kein Anrufende. Beenden Sie die Aufnahme manuell, falls die Erkennung ausfällt."},
 "Stopping manually pauses automation for the same call. Rejoin after a confirmed end to allow a new recording. Disabling detection leaves an existing recording running for you to stop.": {"pt-BR":"Parar manualmente pausa a automação para a mesma chamada. Entre novamente após um fim confirmado para permitir uma nova gravação. Desativar a detecção mantém a gravação existente até você parar.",fr:"Un arrêt manuel suspend l’automatisation pour le même appel. Rejoignez après une fin confirmée pour permettre un nouvel enregistrement. Désactiver la détection laisse l’enregistrement en cours jusqu’à votre arrêt.",de:"Manuelles Beenden pausiert die Automatisierung für denselben Anruf. Treten Sie nach einem bestätigten Ende erneut bei, um eine neue Aufnahme zu ermöglichen. Beim Deaktivieren der Erkennung läuft eine bestehende Aufnahme weiter, bis Sie sie beenden."},
 "Heed owns this automatic recording; overlapping detected calls share one capture.": {"pt-BR":"O Heed controla esta gravação automática; chamadas detectadas simultâneas compartilham uma captura.",fr:"Heed contrôle cet enregistrement automatique ; les appels détectés simultanément partagent une capture.",de:"Heed steuert diese automatische Aufnahme; gleichzeitig erkannte Anrufe teilen eine Aufnahme."},
 "Could not check meeting detection. Open Heed and try again.": {"pt-BR":"Não foi possível verificar a detecção de reuniões. Abra o Heed e tente novamente.",fr:"Impossible de vérifier la détection des réunions. Ouvrez Heed et réessayez.",de:"Die Besprechungserkennung konnte nicht geprüft werden. Öffnen Sie Heed und versuchen Sie es erneut."},
 "Could not save meeting detection settings.": {"pt-BR":"Não foi possível salvar as configurações de detecção de reuniões.",fr:"Impossible d’enregistrer les paramètres de détection des réunions.",de:"Die Einstellungen der Besprechungserkennung konnten nicht gespeichert werden."},
 "Could not open Accessibility settings. Open the Heed menu app and try again.": {"pt-BR":"Não foi possível abrir os ajustes de Acessibilidade. Abra o aplicativo de menu do Heed e tente novamente.",fr:"Impossible d’ouvrir les réglages d’accessibilité. Ouvrez l’application de menu Heed et réessayez.",de:"Die Einstellungen für Bedienungshilfen konnten nicht geöffnet werden. Öffnen Sie die Heed-Menü-App und versuchen Sie es erneut."},
};
