import type {Locale} from './locale';
export const RECORDING_TRANSLATIONS:Record<string,Partial<Record<Locale,string>>>={
 'Real-time transcription':{'pt-BR':'Transcrição em tempo real',fr:'Transcription en temps réel',de:'Echtzeittranskription'},
 'When disabled, microphone and system audio are still saved. The final transcript and speaker labels are prepared after stopping.':{'pt-BR':'Quando desativada, o áudio do microfone e do sistema continua sendo salvo. A transcrição final e os nomes dos falantes são preparados após parar.',fr:'Lorsque cette option est désactivée, le son du microphone et du système reste enregistré. La transcription finale et les locuteurs sont préparés après l’arrêt.',de:'Bei deaktivierter Option werden Mikrofon- und Systemaudio weiterhin gespeichert. Das endgültige Transkript und die Sprecher werden nach dem Stoppen erstellt.'},
 'Turning this off reduces processing during capture. RAM savings depend on shared model residency; final processing may still peak.':{'pt-BR':'Desativar reduz o processamento durante a captura. A economia de RAM depende dos modelos compartilhados residentes; o processamento final ainda pode ter um pico.',fr:'La désactivation réduit le traitement pendant la capture. Les économies de RAM dépendent des modèles partagés résidents ; le traitement final peut toujours présenter un pic.',de:'Das Ausschalten reduziert die Verarbeitung während der Aufnahme. Die RAM-Ersparnis hängt von gemeinsam genutzten geladenen Modellen ab; die abschließende Verarbeitung kann weiterhin Spitzen verursachen.'},
 'Changes apply to the next recording. An active recording keeps its mode.':{'pt-BR':'As alterações valem para a próxima gravação. Uma gravação em andamento mantém seu modo.',fr:'Les modifications s’appliquent au prochain enregistrement. Un enregistrement en cours conserve son mode.',de:'Änderungen gelten für die nächste Aufnahme. Eine laufende Aufnahme behält ihren Modus.'},
 'Saved. Changes apply to the next recording; the current recording keeps its mode.':{'pt-BR':'Salvo. As alterações valem para a próxima gravação; a gravação atual mantém seu modo.',fr:'Enregistré. Les modifications s’appliquent au prochain enregistrement ; l’enregistrement actuel conserve son mode.',de:'Gespeichert. Änderungen gelten für die nächste Aufnahme; die aktuelle Aufnahme behält ihren Modus.'},
 'Live text is disabled. Audio is being recorded; the transcript and speakers will be prepared after stopping.':{'pt-BR':'O texto em tempo real está desativado. O áudio está sendo gravado; a transcrição e os falantes serão preparados após parar.',fr:'Le texte en direct est désactivé. Le son est enregistré ; la transcription et les locuteurs seront préparés après l’arrêt.',de:'Live-Text ist deaktiviert. Audio wird aufgenommen; das Transkript und die Sprecher werden nach dem Stoppen erstellt.'},
 'Could not save real-time transcription settings. Try again.':{'pt-BR':'Não foi possível salvar a configuração de transcrição em tempo real. Tente novamente.',fr:'Impossible d’enregistrer les paramètres de transcription en temps réel. Réessayez.',de:'Die Einstellungen für die Echtzeittranskription konnten nicht gespeichert werden. Versuchen Sie es erneut.'},
 'Could not load real-time transcription settings. Reopen Settings and try again.':{'pt-BR':'Não foi possível carregar a configuração de transcrição em tempo real. Reabra Configurações e tente novamente.',fr:'Impossible de charger les paramètres de transcription en temps réel. Rouvrez les paramètres et réessayez.',de:'Die Einstellungen für die Echtzeittranskription konnten nicht geladen werden. Öffnen Sie die Einstellungen erneut und versuchen Sie es noch einmal.'},
 'Preference saved. The transcription service is unavailable; retry after it is ready.':{'pt-BR':'Preferência salva. O serviço de transcrição está indisponível; tente novamente quando estiver pronto.',fr:'Préférence enregistrée. Le service de transcription est indisponible ; réessayez lorsqu’il sera prêt.',de:'Einstellung gespeichert. Der Transkriptionsdienst ist nicht verfügbar; versuchen Sie es erneut, sobald er bereit ist.'},
};
