import {expect,test} from 'bun:test';
import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync,readFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {driveFixture} from './google-drive-fixtures';
import {GoogleAuth,GOOGLE_SCOPES} from './google-auth';
import {GoogleDriveLibraryManager} from './google-drive-library';
import {GoogleDriveController} from './google-drive-http';
import {GoogleSourceProtection} from './google-source-protection';
import {ProviderRegistry} from '../provider-registry';
import {PortableLibrary} from '../portable-library';
import {SessionTags} from '../session-tags';
import {ManagedQuota} from '../managed-quota';
import {atomicWriteJson} from '../atomic-json';
import type {Session} from '@heed/shared';
function fixture(){
 const f=driveFixture(),authPath=join(f.root,'auth.json'),credentialRef=randomUUID(),connectionId=randomUUID();
 f.secrets.set(credentialRef,{accessToken:'SYNTHETIC_ACCESS',refreshToken:'SYNTHETIC_REFRESH',expiresAt:Date.now()+3600000,scopes:[GOOGLE_SCOPES['existing-readwrite']]});
 atomicWriteJson(authPath,{version:1,generation:1,connectionId,credentialRef,clientId:'registered.apps.googleusercontent.com',accessMode:'existing-readwrite',folder:{...f.folder,canUpload:false}});
 const authOptions={path:authPath,vault:f.vault,openBrowser:async()=>{},fetch:async(input:string|URL,init?:RequestInit)=>f.auth.request(String(input),init,init?.signal||undefined)};
 const auth=new GoogleAuth(authOptions);mkdirSync(join(f.root,'sessions'));mkdirSync(join(f.root,'media'));
 const sessionsDir=join(f.root,'sessions'),sessions=new SessionTags(sessionsDir),library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,quota:{reserve(){},release(){}}});
 let registryWrites=0,failAt=Infinity,persistent=false;const factories=new Map<string,()=>any>();
 const registryOptions={path:join(f.root,'preference.json'),getLibrary:()=>library,write(path:string,value:unknown){registryWrites++;if(registryWrites===failAt||persistent&&registryWrites>=failAt)throw new Error('Synthetic preference persistence failed');atomicWriteJson(path,value);}};
 const registry=new ProviderRegistry(registryOptions),register=registry.register.bind(registry);registry.register=(id,factory)=>{factories.set(id,factory);register(id,factory);};
 let journalFailure:'begin'|'clear'|undefined,protectionFailure=false;const managerOptions={root:join(f.root,'manager'),auth,vault:f.vault,write(path:string,value:any){if(path.endsWith('settings-intent.json')&&journalFailure===(value.intent?'begin':'clear'))throw new Error('Synthetic settings journal persistence failed');atomicWriteJson(path,value);}},manager=new GoogleDriveLibraryManager(managerOptions);
 const protectionOptions={path:join(f.root,'protection.json'),listSessions:()=>sessions.snapshot().sessions,write(path:string,value:unknown){if(protectionFailure)throw new Error('Synthetic source protection persistence failed');atomicWriteJson(path,value);}},protection=new GoogleSourceProtection(protectionOptions);
 const controller=new GoogleDriveController({auth,manager,registry,protection,audioBusy:()=>false});
 const expected=()=>({expectedGeneration:auth.snapshot().generation,expectedConnectionId:auth.snapshot().connectionId??null,expectedFolderId:auth.snapshot().folder?.id??null});
 const local=()=>{const wav=join(f.root,'media','only.wav');writeFileSync(wav,Buffer.alloc(1200000));sessions.create({id:'local',title:'Synthetic',createdAt:'2026-10-06T10:00:00Z',duration:1,language:'en',transcript:'LOCAL_SYNTHETIC_ONLY',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true,files:{wav}} as Session);return wav;};
 const quota=(paths:()=>string[])=>new ManagedQuota({ledgerPath:join(f.root,'quota.json'),roots:{media:[join(f.root,'media')]},getLimit:()=>3000000,setLimit(){},protectedPaths:paths});
 return {...f,auth,authPath,authOptions,credentialRef,sessions,library,registry,manager,managerOptions,protection,protectionOptions,controller,expected,local,quota,factories,failRegistry(after:number,sticky=false){failAt=registryWrites+after;persistent=sticky;},failJournal(phase:'begin'|'clear'){journalFailure=phase;},failProtection(){protectionFailure=true;},unlock(){failAt=Infinity;persistent=false;journalFailure=undefined;protectionFailure=false;}};
}
test('failed writable selection restores the exact readonly folder, provider and ordinary media projection',async()=>{
 const f=fixture();try{await f.controller.command({action:'enable',...f.expected()});const prior=f.auth.snapshot(),provider=f.registry.currentId(),wav=f.local();f.failRegistry(1);await expect(f.controller.command({action:'select',folderId:f.folder.id,...f.expected()})).rejects.toThrow();expect(f.auth.snapshot().folder?.canUpload).toBe(false);expect(f.auth.snapshot().generation).toBe(prior.generation);expect(f.registry.currentId()).toBe(provider);expect(f.registry.preferredId()).toBe(provider!);expect(f.controller.protectedPaths()).not.toContain(wav);expect(f.quota(()=>f.controller.protectedPaths()).preview(1048576).removals.map(file=>file.path)).toEqual([wav]);expect(f.sessions.read('local')?.transcript).toBe('LOCAL_SYNTHETIC_ONLY');expect(existsSync(wav)).toBe(true);}finally{f.cleanup();}
});
test('unresolved selection recovery protects new sole audio and blocks cached provider HTTP across restart',async()=>{
 const f=fixture();try{await f.controller.command({action:'enable',...f.expected()});const cached=f.factories.get(f.registry.currentId()!)!();f.failRegistry(2,true);await expect(f.controller.command({action:'select',folderId:f.folder.id,...f.expected()})).rejects.toThrow();const wav=f.local();expect(f.controller.unavailable()).toBe(true);expect(f.controller.protectedPaths()).toContain(wav);expect(()=>f.quota(()=>f.controller.protectedPaths()).preview(1048576)).toThrow('protected');const before=f.requests.length;await expect(cached.list(null,10)).rejects.toThrow('recovery');expect(f.requests.length).toBe(before);f.unlock();const auth=new GoogleAuth(f.authOptions),manager=new GoogleDriveLibraryManager({...f.managerOptions,auth}),protection=new GoogleSourceProtection(f.protectionOptions),controller=new GoogleDriveController({auth,manager,protection,registry:f.registry,audioBusy:()=>false});expect(controller.unavailable()).toBe(true);expect(controller.protectedPaths()).toContain(wav);expect(()=>f.quota(()=>controller.protectedPaths()).preview(1048576)).toThrow('protected');await expect(controller.command({action:'enable',...f.expected()})).rejects.toThrow('recovery');expect(f.requests.length).toBe(before);}finally{f.cleanup();}
});
test('disconnect failure after credential invalidation never reactivates the retired credential',async()=>{
 const f=fixture();try{await f.controller.command({action:'enable',...f.expected()});f.failRegistry(1,true);await expect(f.controller.command({action:'disconnect',revoke:false,...f.expected()})).rejects.toThrow();expect(f.auth.snapshot().connected).toBe(false);expect(JSON.parse(readFileSync(f.authPath,'utf8')).credentialRef).toBeUndefined();expect(f.secrets.has(f.credentialRef)).toBe(false);expect(f.controller.unavailable()).toBe(true);const restored=new GoogleAuth(f.authOptions);await expect(restored.accessToken()).rejects.toThrow('Authorization');const wav=f.local();expect(f.controller.protectedPaths()).toContain(wav);}finally{f.cleanup();}
});

test('settings intent is durable before remote selection and rejects early journal failure without settings effects',async()=>{
 const f=fixture();try{await f.controller.command({action:'enable',...f.expected()});const prior=f.auth.snapshot(),id=f.registry.currentId(),before=f.requests.length;f.failJournal('begin');await expect(f.controller.command({action:'select',folderId:f.folder.id,...f.expected()})).rejects.toThrow('journal');expect(f.auth.snapshot()).toEqual(prior);expect(f.registry.currentId()).toBe(id);expect(f.registry.preferredId()).toBe(id!);expect(f.requests.length).toBe(before);expect(f.controller.unavailable()).toBe(true);const wav=f.local();expect(f.controller.protectedPaths()).toContain(wav);}finally{f.cleanup();}
});
test('failed protection restoration retains intent and protects new audio across restart',async()=>{
 const f=fixture();try{await f.controller.command({action:'enable',...f.expected()});const cached=f.factories.get(f.registry.currentId()!)!();f.failProtection();await expect(f.controller.command({action:'select',folderId:f.folder.id,...f.expected()})).rejects.toThrow('protection');expect(f.manager.settingsIntent()).not.toBeNull();expect(f.controller.unavailable()).toBe(true);const wav=f.local();expect(f.controller.protectedPaths()).toContain(wav);const before=f.requests.length;await expect(cached.read('heed-library.json',4096)).rejects.toThrow('recovery');expect(f.requests.length).toBe(before);f.unlock();const auth=new GoogleAuth(f.authOptions),manager=new GoogleDriveLibraryManager({...f.managerOptions,auth}),protection=new GoogleSourceProtection(f.protectionOptions),controller=new GoogleDriveController({auth,manager,registry:f.registry,protection,audioBusy:()=>false});expect(controller.unavailable()).toBe(true);expect(controller.protectedPaths()).toContain(wav);}finally{f.cleanup();}
});
test('failed final intent clear preserves the coherent writable binding but blocks it until recovery',async()=>{
 const f=fixture();try{await f.controller.command({action:'enable',...f.expected()});const prior=f.auth.snapshot().generation;f.failJournal('clear');await expect(f.controller.command({action:'select',folderId:f.folder.id,...f.expected()})).rejects.toThrow('journal');expect(f.auth.snapshot().generation).toBe(prior+1);expect(f.auth.snapshot().folder?.canUpload).toBe(true);expect(f.registry.currentId()).toBe(f.manager.providerId());expect(f.manager.settingsIntent()).not.toBeNull();expect(f.controller.snapshot().recoveryRequired).toBe(true);const wav=f.local();expect(()=>f.quota(()=>f.controller.protectedPaths()).preview(1048576)).toThrow('protected');expect(existsSync(wav)).toBe(true);const before=f.requests.length;expect(()=>f.factories.get(f.registry.currentId()!)!()).toThrow('recovery');expect(f.requests.length).toBe(before);f.unlock();const auth=new GoogleAuth(f.authOptions),manager=new GoogleDriveLibraryManager({...f.managerOptions,auth}),protection=new GoogleSourceProtection(f.protectionOptions),controller=new GoogleDriveController({auth,manager,registry:f.registry,protection,audioBusy:()=>false});expect(controller.unavailable()).toBe(true);expect(controller.protectedPaths()).toContain(wav);expect(()=>f.quota(()=>controller.protectedPaths()).preview(1048576)).toThrow('protected');await expect(controller.command({action:'enable',...f.expected()})).rejects.toThrow('recovery');expect(f.requests.length).toBe(before);}finally{f.cleanup();}
});
test('folder-only restoration preserves auth-required and credential retirement state',async()=>{
 const f=fixture();try{const checkpoint=f.auth.selectionCheckpoint(),pending=randomUUID();const state=JSON.parse(readFileSync(f.authPath,'utf8'));atomicWriteJson(f.authPath,{...state,requiresAuthorization:true,pendingRemovalRefs:[pending],generation:2,folder:{...f.folder,canUpload:true}});const auth=new GoogleAuth(f.authOptions);auth.restoreSelection(checkpoint);expect(auth.snapshot().generation).toBe(checkpoint.generation);expect(auth.snapshot().folder).toEqual(checkpoint.folder);expect(auth.snapshot().connected).toBe(false);const saved=JSON.parse(readFileSync(f.authPath,'utf8'));expect(saved.requiresAuthorization).toBe(true);expect(saved.pendingRemovalRefs).toEqual([pending]);await expect(auth.accessToken()).rejects.toThrow('Authorization');}finally{f.cleanup();}
});

test('failed folder switch restores a writable destination and its pending source protection',async()=>{
 const f=fixture();try{f.auth.selectFolder({...f.folder,canUpload:true});await f.controller.command({action:'enable',...f.expected()});const prior=f.auth.snapshot(),id=f.registry.currentId(),cached=f.factories.get(id!)!(),wav=f.local();const otherId='other-library',destinationId=randomUUID(),header=f.files.get('header')!,bytes=Buffer.from(JSON.stringify({format:'heed-portable-library',schemaVersion:1,destinationId}));f.files.set(otherId,{...f.files.get(f.folder.id)!,id:otherId,name:'Other library'});f.files.set('other-header',{...header,id:'other-header',parents:[otherId],bytes,size:String(bytes.length)});f.failRegistry(1);await expect(f.controller.command({action:'select',folderId:otherId,...f.expected()})).rejects.toThrow();expect(f.auth.snapshot()).toEqual(prior);expect(f.registry.currentId()).toBe(id);expect(f.registry.preferredId()).toBe(id!);expect(f.controller.unavailable()).toBe(false);expect(f.controller.protectedPaths()).toContain(wav);expect(()=>f.quota(()=>f.controller.protectedPaths()).preview(1048576)).toThrow('protected');await expect(cached.list(null,10)).resolves.toMatchObject({commits:[],complete:true});expect(f.manager.settingsIntent()).toBeNull();}finally{f.cleanup();}
});
