import {test,expect} from 'bun:test';import {randomUUID} from 'node:crypto';import {join} from 'node:path';import {mkdirSync} from 'node:fs';
import {GoogleDriveProvider} from './google-drive-provider';import {driveFixture} from './google-drive-fixtures';import {encode,makeBundle,sha256} from '../portable-schema';import {PortableLibrary} from '../portable-library';import {SessionTags} from '../session-tags';import type {Session} from '@heed/shared';import {LibraryChatService} from '../library-chat';
function bundle(){const meetingId=randomUUID();return makeBundle(randomUUID(),randomUUID(),{schemaVersion:1,meetingId,title:'English Portuguese meeting',createdAt:'2026-10-05T10:00:00.000Z',duration:3,language:'pt',transcript:'English decision.\nConfirmamos a entrega.',segments:[{speaker:'Ana',text:'English decision.',start:0,end:1},{speaker:'Ana',text:'Confirmamos a entrega.',start:1,end:3}],speakers:['Ana'],tags:['Entrega'],aiNotes:'Grounded notes',summary:'Delivery confirmed',pinned:false,transcriptFinalized:true,transcriptionModel:'synthetic:local'},[]);}
test('validates referenced artifacts before publishing a marker and confirms immutable content',async()=>{const f=driveFixture();try{
 const provider=new GoogleDriveProvider({id:randomUUID(),name:'Google Drive',store:f.store()}),b=bundle(),prefix=`meetings/${b.marker.meetingId}/revisions/${b.marker.revisionId}`,markerPath=`commits/${b.marker.deviceId}/${b.marker.revisionId}.json`;
 await expect(provider.writeImmutable(markerPath,encode(b.marker))).rejects.toThrow();expect([...f.files.values()].some(file=>file.properties?.heedPath===markerPath)).toBe(false);
 await provider.writeImmutable(`${prefix}/meeting.json`,encode(b.payload));await provider.writeImmutable(b.marker.manifestPath,encode(b.manifest));await provider.writeImmutable(markerPath,encode(b.marker));expect(await provider.confirm(b.marker)).toBe('remote-confirmed');const page=await provider.list(null,1);expect(page.commits).toEqual([b.marker]);await provider.acknowledgeDiscovery();
 const meeting=[...f.files.values()].find(file=>file.properties?.heedPath===`${prefix}/meeting.json`)!;meeting.bytes=Buffer.from('corrupted');meeting.sha256Checksum=sha256(meeting.bytes);await expect(provider.confirm(b.marker)).rejects.toThrow();
}finally{f.cleanup();}});
test('portable import preserves final bilingual content and labels for offline any/all AI without fetching audio',async()=>{const f=driveFixture();try{
 const provider=new GoogleDriveProvider({id:randomUUID(),name:'Google Drive',store:f.store()}),b=bundle(),prefix=`meetings/${b.marker.meetingId}/revisions/${b.marker.revisionId}`;f.add(`${prefix}/meeting.json`,encode(b.payload));f.add(b.marker.manifestPath,encode(b.manifest));f.add(`commits/${b.marker.deviceId}/${b.marker.revisionId}.json`,encode(b.marker));
 mkdirSync(join(f.root,'sessions'));const sessions=new SessionTags(join(f.root,'sessions'));const library=new PortableLibrary({root:join(f.root,'local-library'),sessions,sessionsDir:join(f.root,'sessions'),quota:{reserve(){},release(){}},provider});await library.discover();expect(sessions.snapshot().sessions).toHaveLength(0);await library.importSelected([b.marker.revisionId]);const imported=sessions.snapshot().sessions[0]!;expect(imported.tags).toEqual(['Entrega']);expect(imported.speakers).toEqual(['Ana']);expect(imported.transcript).toContain('Confirmamos');expect(imported.transcriptFinalized).toBe(true);expect(imported.transcriptionModel).toBe('synthetic:local');
 library.selectProvider(undefined);const chat=new LibraryChatService({directory:join(f.root,'chat'),listSessions:()=>sessions.snapshot().sessions,isBusy:()=>false,generate:async()=>{throw new Error('Synthetic generation unused');}});for(const match of ['any','all'] as const)expect(chat.preview({mode:'labels',labels:['Entrega'],match}).snapshot.sources.map(source=>source.sessionId)).toEqual([imported.id]);expect(sessions.read(imported.id)?.transcript).toBe(b.payload.transcript);expect(f.requests.some(u=>u.searchParams.get('alt')==='media'&&u.pathname.includes('/objects/'))).toBe(false);
}finally{f.cleanup();}});
test('two-device immutable branches remain distinct and repeated discovery/import is idempotent',async()=>{const f=driveFixture();try{
 const provider=new GoogleDriveProvider({id:randomUUID(),name:'Google Drive',store:f.store()}),first=bundle(),second=makeBundle(first.marker.libraryId,randomUUID(),{...first.payload,transcript:'Other device branch'},[]);
 for(const b of [first,second]){const prefix=`meetings/${b.marker.meetingId}/revisions/${b.marker.revisionId}`;f.add(`${prefix}/meeting.json`,encode(b.payload));f.add(b.marker.manifestPath,encode(b.manifest));f.add(`commits/${b.marker.deviceId}/${b.marker.revisionId}.json`,encode(b.marker));}
 mkdirSync(join(f.root,'sessions'));const sessions=new SessionTags(join(f.root,'sessions')),library=new PortableLibrary({root:join(f.root,'local-library'),sessions,sessionsDir:join(f.root,'sessions'),quota:{reserve(){},release(){}},provider});await library.discover();await library.importSelected();await library.discover();await library.importSelected();expect(sessions.snapshot().sessions).toHaveLength(1);expect(library.snapshot().previews).toHaveLength(2);expect(library.snapshot().previews.some(item=>item.state==='conflict')).toBe(true);
}finally{f.cleanup();}});
test('recording preemption aborts an in-flight provider request and waits for its cleanup',async()=>{const f=driveFixture();try{
 let started!:()=>void;const waiting=new Promise<void>(resolve=>{started=resolve;});let cleaned=false;const auth={...f.auth,async request(url:string,init?:RequestInit,signal?:AbortSignal){started();return new Promise<Response>((resolve,reject)=>{signal!.addEventListener('abort',()=>{cleaned=true;reject(signal!.reason);},{once:true});});}};const {GoogleDriveStore}=await import('./google-drive-store');const provider=new GoogleDriveProvider({id:randomUUID(),name:'Google Drive',store:new GoogleDriveStore({path:f.path,auth,vault:f.vault,folder:f.folder,generation:1})});const job=provider.list(null,10);const failed=job.catch(error=>error);await waiting;await provider.preempt();expect(await failed).toBeDefined();expect(cleaned).toBe(true);
}finally{f.cleanup();}});
function wave(){const bytes=Buffer.alloc(48);bytes.write('RIFF');bytes.writeUInt32LE(40,4);bytes.write('WAVE',8);bytes.write('fmt ',12);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(16000,24);bytes.writeUInt32LE(32000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(4,40);return bytes;}
test('metadata import leaves remote audio untouched until requested and verified playback remains offline',async()=>{const f=driveFixture();try{
 const bytes=wave(),base=bundle(),audio={objectPath:`objects/${sha256(bytes)}`,sha256:sha256(bytes),bytes:bytes.length,format:'wav' as const,mode:'archived' as const};const b=makeBundle(base.marker.libraryId,base.marker.deviceId,{...base.payload,audio},[]),prefix=`meetings/${b.marker.meetingId}/revisions/${b.marker.revisionId}`;const remoteAudio=f.add(audio.objectPath,bytes);f.add(`${prefix}/meeting.json`,encode(b.payload));f.add(b.marker.manifestPath,encode(b.manifest));f.add(`commits/${b.marker.deviceId}/${b.marker.revisionId}.json`,encode(b.marker));mkdirSync(join(f.root,'sessions'));const sessions=new SessionTags(join(f.root,'sessions')),provider=new GoogleDriveProvider({id:randomUUID(),name:'Drive',store:f.store()}),library=new PortableLibrary({root:join(f.root,'local'),sessions,sessionsDir:join(f.root,'sessions'),quota:{reserve(){},release(){}},provider});await library.discover();await library.importSelected();const imported=sessions.snapshot().sessions[0]!;expect(f.requests.some(u=>u.pathname.endsWith('/'+remoteAudio.id)&&u.searchParams.get('alt')==='media')).toBe(false);expect(imported.files?.wav).toBeUndefined();const path=await library.requestAudio(imported.id);expect(await Bun.file(path).bytes()).toEqual(bytes);expect(f.requests.some(u=>u.pathname.endsWith('/'+remoteAudio.id)&&u.searchParams.get('alt')==='media')).toBe(true);library.selectProvider(undefined);expect(await library.requestAudio(imported.id)).toBe(path);
}finally{f.cleanup();}});
test('provider quota failure keeps queued local audio protected and no commit marker visible',async()=>{const f=driveFixture();try{
 mkdirSync(join(f.root,'sessions'));const sessions=new SessionTags(join(f.root,'sessions')),provider=new GoogleDriveProvider({id:randomUUID(),name:'Drive',store:f.store()}),library=new PortableLibrary({root:join(f.root,'local'),sessions,sessionsDir:join(f.root,'sessions'),quota:{reserve(){},release(){}},provider});const path=join(f.root,'local','media','recording.wav');await Bun.write(path,wave());const payload=bundle().payload;sessions.create({...payload,id:'synthetic-local',createdAt:payload.createdAt,files:{wav:path}} as Session);const queued=await library.queueLocal('synthetic-local');f.quota();const result=await library.publish(queued.revisionId);expect(result.previews.find(preview=>preview.revisionId===queued.revisionId)?.error).toContain('quota');expect(library.protectedPaths()).toContain(path);expect(library.snapshot().previews.find(preview=>preview.revisionId===queued.revisionId)?.state).toBe('unavailable');expect([...f.files.values()].some(file=>file.properties?.heedPath.startsWith('commits/'))).toBe(false);const restarted=new PortableLibrary({root:join(f.root,'local'),sessions,sessionsDir:join(f.root,'sessions'),quota:{reserve(){},release(){}},provider});expect(restarted.protectedPaths()).toContain(path);
}finally{f.cleanup();}});
