import {createHash,randomUUID} from 'node:crypto';import {existsSync,mkdirSync} from 'node:fs';import {join} from 'node:path';
import {readPrivateJson,privateRecord} from './private-json';
import {GoogleSettingsJournal,type GoogleSettingsIntent} from './google-settings-journal';
import {atomicWriteJson} from '../atomic-json';import {GoogleConnectionError,readGoogleJson,type GoogleAuth,type GoogleFolder} from './google-auth';import {GoogleDriveStore} from './google-drive-store';import type {SecretVault} from './keychain-vault';
const API='https://www.googleapis.com/drive/v3',UPLOAD='https://www.googleapis.com/upload/drive/v3/files',FOLDER='application/vnd.google-apps.folder';const ID=/^[-A-Za-z0-9_]{1,256}$/,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const FIELDS='id,name,mimeType,parents,size,sha256Checksum,capabilities,driveId,trashed';
interface File {id:string;name:string;mimeType:string;parents?:string[];size?:string;sha256Checksum?:string;driveId?:string;trashed?:boolean;capabilities?:{canDownload?:boolean;canAddChildren?:boolean}}
interface Creation {parentId:string;name:string;folderId:string;headerId:string;destinationId:string;generation:number}
interface Options {root:string;auth:Pick<GoogleAuth,'snapshot'|'request'|'selectFolder'>;vault:SecretVault;write?:typeof atomicWriteJson}
import type {DriveFolderPreview} from '@heed/shared';
export type {DriveFolderPreview} from '@heed/shared';
export class GoogleDriveLibraryManager {
 private state:{version:1;pending:Creation|null;providerIds?:Record<string,string>};private path:string;private active=false;private settings:GoogleSettingsJournal;
 constructor(private options:Options){this.settings=new GoogleSettingsJournal(join(options.root,'settings-intent.json'),options.write);mkdirSync(options.root,{recursive:true,mode:0o700});this.path=join(options.root,'creation.json');this.state=existsSync(this.path)?readPrivateJson<typeof this.state>(this.path,2097152):{version:1,pending:null};if(!this.state||Object.keys(this.state).some(key=>!['version','pending','providerIds'].includes(key))||this.state.version!==1||(this.state.providerIds&&(!privateRecord(this.state.providerIds,10000)||Object.entries(this.state.providerIds).some(([key,id])=>! /^[a-f0-9]{64}$/.test(key)||!UUID.test(id))))||(this.state.pending!==null&&(!this.state.pending||Object.keys(this.state.pending).sort().join(',')!=='destinationId,folderId,generation,headerId,name,parentId'||![this.state.pending.parentId,this.state.pending.folderId,this.state.pending.headerId].every(id=>typeof id==='string'&&ID.test(id))||!UUID.test(this.state.pending.destinationId)||typeof this.state.pending.name!=='string'||this.state.pending.name.length>80||!Number.isSafeInteger(this.state.pending.generation)||this.state.pending.generation<0)))throw new Error('Invalid Google creation state; preserve it for recovery');}
 settingsIntent(){return this.settings.intent();}
 beginSettings(intent:GoogleSettingsIntent){this.settings.begin(intent);}
 finishSettings(){this.settings.clear();}
 private persist(pending:Creation|null){const next={...this.state,version:1 as const,pending};(this.options.write||atomicWriteJson)(this.path,next);this.state=next;}
 private async operation<T>(run:()=>Promise<T>):Promise<T>{if(this.active)throw new Error('A Google library operation is already running');this.active=true;try{return await run();}finally{this.active=false;}}
 private async request(path:string,parameters:Record<string,string>={},init:RequestInit={},signal?:AbortSignal){const u=new URL(`${API}/${path}`);u.searchParams.set('supportsAllDrives','true');for(const [key,value] of Object.entries(parameters))u.searchParams.set(key,value);const response=await this.options.auth.request(u.toString(),init,signal);if(!response.ok){await response.body?.cancel();throw new GoogleConnectionError(response.status===403?'permission-denied':response.status===404?'remote-unavailable':'provider-response',response.status===403?'Google Drive permission denied':'Google Drive request failed');}return readGoogleJson(response,2097152);}
 private async file(id:string,signal?:AbortSignal):Promise<File>{if(!ID.test(id))throw new Error('Invalid Drive folder ID');const value=await this.request(`files/${id}`,{fields:FIELDS},{},signal) as unknown as File;if(value.id!==id||value.trashed||value.mimeType==='application/vnd.google-apps.shortcut'||typeof value.name!=='string')throw new Error('Invalid Drive folder metadata');return value;}
 private async header(file:File,signal?:AbortSignal){
  if(!file.size||!/^\d+$/.test(file.size)||Number(file.size)>4096||file.capabilities?.canDownload!==true)throw new Error('Heed library header permission is unavailable');
  const response=await this.options.auth.request(`${API}/files/${file.id}?alt=media&supportsAllDrives=true`,{},signal);if(!response.ok){await response.body?.cancel();throw new Error('Heed library header is unavailable');}
  const raw=await readGoogleJson(response,4096);if(Object.keys(raw).sort().join(',')!=='destinationId,format,schemaVersion'||raw.format!=='heed-portable-library'||raw.schemaVersion!==1||typeof raw.destinationId!=='string'||!UUID.test(raw.destinationId))throw new Error('Unsupported Heed library header');return raw.destinationId;
 }
 async folders(signal?:AbortSignal):Promise<DriveFolderPreview[]>{
  const folders:DriveFolderPreview[]=[];const seen=new Set<string>();let page:string|undefined;
  for(let index=0;index<10;index++){const result=await this.request('files',{q:`mimeType = '${FOLDER}' and trashed = false`,corpora:'user',includeItemsFromAllDrives:'true',pageSize:'100',fields:`nextPageToken,incompleteSearch,files(${FIELDS})`,...(page?{pageToken:page}:{})},{},signal);if(result.incompleteSearch===true||!Array.isArray(result.files)||result.files.length>100)throw new Error('Drive folder discovery is incomplete');
   for(const raw of result.files){const f=raw as File;if(!ID.test(f.id)||f.mimeType!==FOLDER||f.trashed||typeof f.name!=='string')throw new Error('Invalid Drive folder listing');folders.push({id:f.id,name:f.name,driveId:f.driveId,canCreate:f.capabilities?.canAddChildren===true&&this.options.auth.snapshot().accessMode!=='existing-readonly'});}
   if(!result.nextPageToken)return folders;if(typeof result.nextPageToken!=='string'||seen.has(result.nextPageToken))throw new Error('Invalid Drive folder pagination');page=result.nextPageToken;seen.add(page);
  }throw new Error('Drive folder list limit reached; enter the folder ID directly');
 }
 async select(folderId:string,signal?:AbortSignal):Promise<GoogleFolder>{return this.operation(async()=>{
  const generation=this.options.auth.snapshot().generation,folder=await this.file(folderId,signal);if(folder.mimeType!==FOLDER)throw new Error('Choose a Drive folder');
  const headers:File[]=[];let page:string|undefined;const seen=new Set<string>();
  for(let count=0;count<10;count++){const result=await this.request('files',{q:`'${folderId}' in parents and name = 'heed-library.json' and trashed = false`,includeItemsFromAllDrives:'true',corpora:folder.driveId?'drive':'user',...(folder.driveId?{driveId:folder.driveId}:{}),pageSize:'100',fields:`nextPageToken,incompleteSearch,files(${FIELDS})`,...(page?{pageToken:page}:{})},{},signal);
   if(result.incompleteSearch===true||!Array.isArray(result.files))throw new Error('Heed library discovery is incomplete');for(const raw of result.files){const item=raw as File;if(item.name!=='heed-library.json')continue;if(!ID.test(item.id)||!item.parents?.includes(folderId))throw new Error('Heed library header is outside the selected folder');headers.push(item);}if(!result.nextPageToken){page=undefined;break;}if(typeof result.nextPageToken!=='string'||seen.has(result.nextPageToken))throw new Error('Invalid Drive header pagination');page=result.nextPageToken;seen.add(page);
  }
  if(page)throw new Error('Heed library header page limit reached');if(!headers.length)throw new Error('The selected folder is not a Heed library');if(headers.length!==1)throw new Error('The selected Heed library header is ambiguous');const destinationId=await this.header(headers[0]!,signal);
  if(generation!==this.options.auth.snapshot().generation)throw new Error('Google connection changed during folder selection');const selected={id:folder.id,name:folder.name,destinationId,driveId:folder.driveId,canUpload:folder.capabilities?.canAddChildren===true&&this.options.auth.snapshot().accessMode!=='existing-readonly'};this.options.auth.selectFolder(selected);return selected;
 });}
 async capacity(signal?:AbortSignal):Promise<{limit?:number;usage?:number}>{const raw=await this.request('about',{fields:'storageQuota'},{},signal),quota=raw.storageQuota as {limit?:string;usage?:string}|undefined;const number=(value?:string)=>value&&/^\d+$/.test(value)&&Number.isSafeInteger(Number(value))?Number(value):undefined;return {limit:number(quota?.limit),usage:number(quota?.usage)};}
 isBusy():boolean{return this.active;}
 providerId():string{const folder=this.options.auth.snapshot().folder;if(!folder)throw new Error('Select a Google Heed library first');const key=createHash('sha256').update(`${folder.id}/${folder.destinationId}/${this.options.auth.snapshot().generation}`).digest('hex');const existing=this.state.providerIds?.[key];if(existing){if(!UUID.test(existing))throw new Error('Invalid Google provider identity');return existing;}if(Object.keys(this.state.providerIds||{}).length>=10000)throw new Error('Google provider identity limit reached');const id=randomUUID();const next={...this.state,providerIds:{...this.state.providerIds,[key]:id}};(this.options.write||atomicWriteJson)(this.path,next);this.state=next;return id;}
 pendingCreation():boolean{return !!this.state.pending;}
 async create(input:{parentId:string;name:string;confirmed:boolean},signal?:AbortSignal):Promise<GoogleFolder>{return this.operation(async()=>{
  if(input.confirmed!==true)throw new Error('Confirm creation of a new dedicated Heed library');if(!ID.test(input.parentId)||typeof input.name!=='string'||!input.name.trim()||input.name.length>80||/[\x00-\x1f\x7f]/.test(input.name))throw new Error('Invalid new Drive library');
  const snapshot=this.options.auth.snapshot();if(!snapshot.connected||snapshot.authorizing||snapshot.accessMode==='existing-readonly')throw new Error('Google Drive library creation requires write permission');const parent=await this.file(input.parentId,signal);if(parent.mimeType!==FOLDER||parent.capabilities?.canAddChildren!==true)throw new Error('Google Drive parent folder permission denied');let pending=this.state.pending;
  if(pending&&(pending.parentId!==input.parentId||pending.name!==input.name.trim()||(pending.generation!==snapshot.generation&&!(snapshot.generation===pending.generation+1&&snapshot.folder?.id===pending.folderId&&snapshot.folder.destinationId===pending.destinationId))))throw new Error('An incomplete library creation must be resumed or forgotten first');
  if(!pending){const raw=await this.request('files/generateIds',{count:'2',space:'drive',type:'files'},{},signal);if(!Array.isArray(raw.ids)||raw.ids.length!==2||raw.ids.some(id=>typeof id!=='string'||!ID.test(id)))throw new Error('Invalid generated Drive IDs');pending={parentId:parent.id,name:input.name.trim(),folderId:raw.ids[0],headerId:raw.ids[1],destinationId:randomUUID(),generation:snapshot.generation};this.persist(pending);}
  const ensureGeneration=()=>{if(this.options.auth.snapshot().generation!==snapshot.generation)throw new Error('Google connection changed during library creation');};ensureGeneration();
  let folder:File|undefined;try{folder=await this.file(pending.folderId,signal);}catch(error){if(error instanceof GoogleConnectionError&&error.code==='remote-unavailable'){ensureGeneration();folder=await this.request('files',{fields:FIELDS},{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:pending.folderId,name:pending.name,mimeType:FOLDER,parents:[pending.parentId]})},signal) as unknown as File;}else throw error;}
  if(folder?.id!==pending.folderId||folder.mimeType!==FOLDER||!folder.parents?.includes(pending.parentId)||folder.name!==pending.name)throw new Error('Reserved Drive folder identity changed');
  let header:File|undefined;try{header=await this.file(pending.headerId,signal);}catch(error){if(error instanceof GoogleConnectionError&&error.code==='remote-unavailable'){
   const boundary=`heed-${randomUUID()}`,metadata={id:pending.headerId,name:'heed-library.json',mimeType:'application/json',parents:[pending.folderId]},bytes=JSON.stringify({format:'heed-portable-library',schemaVersion:1,destinationId:pending.destinationId});const body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${bytes}\r\n--${boundary}--\r\n`;ensureGeneration();const response=await this.options.auth.request(`${UPLOAD}?uploadType=multipart&supportsAllDrives=true&fields=${encodeURIComponent(FIELDS)}`,{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body},signal);if(!response.ok){await response.body?.cancel();throw new Error('Google library header publication failed');}header=await readGoogleJson(response) as unknown as File;
  }else throw error;}
  if(header?.id!==pending.headerId||!header.parents?.includes(pending.folderId)||await this.header(header,signal)!==pending.destinationId)throw new Error('Reserved Drive library header changed');ensureGeneration();const selected={id:folder.id,name:folder.name,destinationId:pending.destinationId,driveId:folder.driveId,canUpload:folder.capabilities?.canAddChildren===true};if(snapshot.folder?.id!==selected.id||snapshot.folder.destinationId!==selected.destinationId)this.options.auth.selectFolder(selected);this.persist(null);return selected;
 });}
 forgetCreation():void{if(this.active)throw new Error('A Google library operation is running');this.persist(null);}
 store():GoogleDriveStore{const snapshot=this.options.auth.snapshot();if(!snapshot.connected||!snapshot.folder)throw new Error('Select a Google Heed library first');const key=createHash('sha256').update(`${snapshot.folder.id}/${snapshot.folder.destinationId}`).digest('hex');return new GoogleDriveStore({path:join(this.options.root,'providers',`${key}.json`),auth:this.options.auth,vault:this.options.vault,folder:snapshot.folder,generation:snapshot.generation});}
}
