import {test,expect} from 'bun:test';import {join} from 'node:path';import {GoogleDriveController,googleDriveResponse} from './google-drive-http';import {GoogleDriveLibraryManager} from './google-drive-library';import {driveFixture} from './google-drive-fixtures';
function fixture(){const f=driveFixture();let state={...f.auth.snapshot(),connectionId:'11111111-1111-4111-8111-111111111111',accessMode:'app-files' as const};let libraryBusy=false;const selected:string[]=[];const factories=new Map<string,()=>unknown>();const registry={async withMutation<T>(run:()=>Promise<T>){this.assertIdle();return run();},assertIdle(){if(libraryBusy)throw new Error('A library operation is already running');},register(id:string,factory:()=>unknown){factories.set(id,factory);},activate(id:string){this.assertIdle();selected.push(id);},deactivate(id:string){this.assertIdle();if(selected.at(-1)===id)selected.pop();},unregister(id:string){factories.delete(id);},currentId:()=>selected.at(-1),preferredId:()=>selected.at(-1)};
 const auth={...f.auth,snapshot:()=>state,selectionCheckpoint(){return {generation:state.generation,connectionId:state.connectionId,folder:structuredClone(state.folder)};},restoreSelection(previous:any){state={...state,generation:previous.generation,folder:previous.folder};},selectFolder(folder:any){state={...state,generation:state.generation+1,folder};},start(){throw new Error('Synthetic connect deliberately disabled');},async wait(){},async cancel(){return state;},async disconnect(){state={...state,connected:false};return state;}};
 const manager=new GoogleDriveLibraryManager({root:join(f.root,'libraries'),auth,vault:f.vault});const controller=new GoogleDriveController({auth,manager,registry,audioBusy:()=>false});const server:Bun.Server<unknown>=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request:Request){return googleDriveResponse(request,controller,server.port!);}});const post=(body:unknown,origin?:string)=>{const snapshot=auth.snapshot();const expected={expectedGeneration:snapshot.generation,expectedConnectionId:snapshot.connectionId??null,expectedFolderId:snapshot.folder?.id??null};return fetch(server.url,{method:'POST',headers:{'Content-Type':'application/json',...(origin?{Origin:origin}:{})},body:JSON.stringify(body===null?null:{...expected,...body as object})});};
 return {...f,controller,registry,selected,factories,server,post,setBusy(){libraryBusy=true;},cleanup(){server.stop(true);f.cleanup();}};
}
test('real local HTTP denies hostile origins and secret-bearing/oversized/unsupported commands',async()=>{const f=fixture();try{
 expect((await f.post({action:'select',folderId:f.folder.id},'https://evil.example')).status).toBe(403);for(const body of [{action:'connect',clientId:'client',accessMode:'app-files',clientSecret:'SECRET'},{action:'delete-remote'},null,{action:'create',name:'x'.repeat(70000)}])expect((await f.post(body)).status).toBe(400);expect(f.selected).toHaveLength(0);const status=await (await fetch(f.server.url)).json();expect(JSON.stringify(status)).not.toContain('SECRET');
}finally{f.cleanup();}});
test('restored registration does not select, explicit enable uses stable identity and busy mutations fail before disconnect',async()=>{const f=fixture();try{
 expect(f.selected).toHaveLength(0);expect(f.factories.size).toBe(1);expect((await f.post({action:'enable'})).status).toBe(200);expect(f.selected).toHaveLength(1);const id=f.selected[0];expect(id).toMatch(/^[a-f0-9-]{36}$/);expect((await f.post({action:'enable'})).status).toBe(200);expect(f.selected.at(-1)).toBe(id);f.setBusy();expect((await f.post({action:'disconnect',revoke:false})).status).toBe(409);expect(f.controller.snapshot().connected).toBe(true);
}finally{f.cleanup();}});
test('select/create/disconnect controls preserve local content and report protected failures',async()=>{const f=fixture();try{
 expect((await f.post({action:'select',folderId:f.folder.id})).status).toBe(200);expect((await f.post({action:'capacity'})).status).toBe(200);expect((await f.post({action:'disconnect',revoke:false})).status).toBe(200);expect(f.files.has('header')).toBe(true);expect(f.controller.snapshot().connected).toBe(false);
}finally{f.cleanup();}});

test('stale tab expectations cannot select, enable, disconnect or query a replacement library',async()=>{const f=fixture();try{const old=f.controller.snapshot();const expected={expectedConnectionId:old.connectionId??null,expectedGeneration:old.generation,expectedFolderId:old.folder!.id};expect((await f.post({action:'select',folderId:f.folder.id})).status).toBe(200);for(const action of ['disconnect','enable','select','capacity','folders']){const response=await f.post({action,revoke:false,folderId:f.folder.id,...expected});expect(response.status).toBe(400);}for(const body of [{action:'disconnect',revoke:false},{action:'enable'},{action:'select',folderId:f.folder.id},{action:'capacity'},{action:'folders'}]){const response=await f.post({...body,...expected});expect(response.status).toBe(409);expect((await response.json()).code).toBe('connection-changed');}expect(f.controller.snapshot().connected).toBe(true);}finally{f.cleanup();}});
