import {test,expect} from 'bun:test';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {GoogleAuth,GOOGLE_SCOPES} from './google-auth';import type {SecretVault} from './keychain-vault';
function fixture(){
 const root=mkdtempSync(join(tmpdir(),'heed-google-auth-'));const secrets=new Map<string,unknown>();let sequence=0,now=100000;let refreshDenied=false;let partial=false;let broader=false;const requests:Array<{path:string;body:string}>=[];
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request:Request){const url=new URL(request.url);return request.text().then(body=>{requests.push({path:url.pathname,body});const fields=new URLSearchParams(body);if(fields.get('grant_type')==='refresh_token'&&refreshDenied)return Response.json({error:'invalid_grant',error_description:'PRIVATE_PROVIDER_MESSAGE'},{status:400});if(url.pathname==='/token')return Response.json({access_token:'SECRET_ACCESS',refresh_token:'SECRET_REFRESH',expires_in:120,token_type:'Bearer',scope:partial?'wrong-scope':broader?`${GOOGLE_SCOPES['app-files']} ${GOOGLE_SCOPES['existing-readwrite']}`:GOOGLE_SCOPES['app-files']});if(url.pathname==='/revoke')return new Response(null,{status:200});return Response.json({ok:true});});}});
 const vault:SecretVault={async put(value,ref=`00000000-0000-0000-0000-${String(++sequence).padStart(12,'0')}`){secrets.set(ref,value);return ref;},async get<T>(ref:string){return (secrets.get(ref)??null) as T|null;},async remove(ref){secrets.delete(ref);}};
 const path=join(root,'google.json');const auth=new GoogleAuth({path,vault,now:()=>now,oauth:async()=>({code:'SECRET_CODE',codeVerifier:'SECRET_VERIFIER',redirectUri:'http://127.0.0.1:1234/oauth/callback'}),openBrowser:async()=>{},fetch:async(input,init)=>fetch(new URL(new URL(input.toString()).pathname,server.url),init)});
 return {auth,path,secrets,requests,setNow(value:number){now=value;},denyRefresh(){refreshDenied=true;},partial(){partial=true;},broader(){broader=true;},cleanup(){server.stop(true);rmSync(root,{recursive:true,force:true});},options:{path,vault,now:()=>now}};
}
const input={clientId:'registered.apps.googleusercontent.com',accessMode:'app-files' as const};
test('requires explicit broader-access consent before starting authorization',()=>{const f=fixture();try{expect(()=>f.auth.start({...input,accessMode:'existing-readwrite'})).toThrow('Explicit consent');expect(f.auth.snapshot().authorizing).toBe(false);expect(f.requests).toHaveLength(0);}finally{f.cleanup();}});
test('authorizes desktop client without an embedded secret, persists opaque references and refreshes after restart',async()=>{const f=fixture();try{
 f.auth.start(input);await f.auth.wait();expect(f.auth.snapshot().connected).toBe(true);expect(await f.auth.accessToken()).toBe('SECRET_ACCESS');const disk=readFileSync(f.path,'utf8');expect(disk).not.toContain('SECRET');expect(f.requests[0]!.body).toContain('code_verifier=SECRET_VERIFIER');expect(f.requests[0]!.body).not.toContain('client_secret');
 f.setNow(300000);const restored=new GoogleAuth({...f.options,openBrowser:async()=>{},fetch:async(input,init)=>{f.requests.push({path:'/refresh-after-restart',body:String(init?.body)});return Response.json({access_token:'SECRET_NEW_ACCESS',expires_in:120,token_type:'Bearer',scope:GOOGLE_SCOPES['app-files']});}});
 expect(await restored.accessToken()).toBe('SECRET_NEW_ACCESS');expect(f.requests.at(-1)!.body).toContain('refresh_token=SECRET_REFRESH');expect(readFileSync(f.path,'utf8')).not.toContain('SECRET_NEW_ACCESS');
}finally{f.cleanup();}});
test('partial grants never become connected and provider errors do not leak into status',async()=>{const f=fixture();try{f.partial();f.auth.start(input);await f.auth.wait();expect(f.auth.snapshot().connected).toBe(false);expect(f.auth.snapshot().error).toBe('missing-scopes');expect(f.secrets.size).toBe(0);}finally{f.cleanup();}});
test('revoked refresh credentials fail closed while local disconnect removes only this connection secret',async()=>{const f=fixture();try{
 f.auth.start(input);await f.auth.wait();f.setNow(300000);f.denyRefresh();await expect(f.auth.accessToken()).rejects.toThrow('Authorization is required');expect(f.auth.snapshot().connected).toBe(false);expect(JSON.stringify(f.auth.snapshot())).not.toContain('PRIVATE_PROVIDER_MESSAGE');
 f.secrets.set('OTHER_PROVIDER',{token:'unrelated'});await f.auth.disconnect(false);expect(f.secrets.has('OTHER_PROVIDER')).toBe(true);expect(f.auth.snapshot().connected).toBe(false);expect(f.requests.some(r=>r.path==='/revoke')).toBe(false);
}finally{f.cleanup();}});
test('authorization cancellation cannot replace a prior connection or retain a listener',async()=>{const f=fixture();try{
 const auth=new GoogleAuth({...f.options,openBrowser:async()=>{},oauth:async(options)=>new Promise((_,reject)=>options.signal!.addEventListener('abort',()=>reject(new Error('cancelled'))))});auth.start(input);await auth.cancel();expect(auth.snapshot().authorizing).toBe(false);expect(auth.snapshot().connected).toBe(false);expect(f.secrets.size).toBe(0);
}finally{f.cleanup();}});
test('authenticated transport rejects arbitrary secret destinations before sending any request',async()=>{const f=fixture();try{f.auth.start(input);await f.auth.wait();const before=f.requests.length;await expect(f.auth.request('https://evil.example/drive/v3/files')).rejects.toThrow('Invalid Google API destination');expect(f.requests.length).toBe(before);}finally{f.cleanup();}});
test('disconnect waits for an already-running refresh vault write and cannot resurrect its removed credential',async()=>{const f=fixture();try{
 f.auth.start(input);await f.auth.wait();f.setNow(300000);let started!:()=>void,release!:()=>void;const waiting=new Promise<void>(resolve=>{started=resolve;}),pause=new Promise<void>(resolve=>{release=resolve;});const vault:SecretVault={...f.options.vault,async put(value,reference){started();await pause;return f.options.vault.put(value,reference);}};const auth=new GoogleAuth({...f.options,vault,openBrowser:async()=>{},fetch:async()=>Response.json({access_token:'SECRET_REFRESHED',expires_in:120,token_type:'Bearer',scope:GOOGLE_SCOPES['app-files']})});const refresh=auth.accessToken();await waiting;let disconnected=false;const disconnect=auth.disconnect().then(()=>{disconnected=true;});await Bun.sleep(0);expect(disconnected).toBe(false);release();await refresh;await disconnect;expect(f.secrets.size).toBe(0);expect(auth.snapshot().connected).toBe(false);
}finally{f.cleanup();}});

test('a narrow request cannot silently accept an account-wide Drive grant',async()=>{const f=fixture();try{f.broader();f.auth.start(input);await f.auth.wait();expect(f.auth.snapshot().connected).toBe(false);expect(f.auth.snapshot().error).toBe('unexpected-scopes');expect(f.secrets.size).toBe(0);}finally{f.cleanup();}});

test('failed credential removal stays durable and retries after restart without authorizing the retired token',async()=>{const f=fixture();try{f.auth.start(input);await f.auth.wait();const ref=JSON.parse(readFileSync(f.path,'utf8')).credentialRef;let locked=true;const vault={...f.options.vault,async remove(reference:string){if(locked)throw new Error('locked');await f.options.vault.remove(reference);}};const auth=new GoogleAuth({...f.options,vault,openBrowser:async()=>{}});expect((await auth.disconnect()).error).toBe('storage-unavailable');const disk=JSON.parse(readFileSync(f.path,'utf8'));expect(disk.credentialRef).toBeUndefined();expect(disk.pendingRemovalRefs).toContain(ref);const restored=new GoogleAuth({...f.options,vault,openBrowser:async()=>{}});await expect(restored.accessToken()).rejects.toThrow('Authorization');locked=false;await restored.disconnect();expect(f.secrets.has(ref)).toBe(false);expect(JSON.parse(readFileSync(f.path,'utf8')).pendingRemovalRefs??[]).toHaveLength(0);}finally{f.cleanup();}});

test('credential rotation retains retired references until cleanup succeeds after restart',async()=>{const f=fixture();try{f.auth.start(input);await f.auth.wait();const old=JSON.parse(readFileSync(f.path,'utf8')).credentialRef;let locked=true;const vault={...f.options.vault,async remove(ref:string){if(locked&&ref===old)throw new Error('locked');await f.options.vault.remove(ref);}};const auth=new GoogleAuth({...f.options,vault,openBrowser:async()=>{},oauth:async()=>({code:'SYNTHETIC',codeVerifier:'SYNTHETIC',redirectUri:'http://127.0.0.1:1234/oauth/callback'}),fetch:async()=>Response.json({access_token:'SECRET_NEW',refresh_token:'SECRET_NEW_REFRESH',expires_in:120,token_type:'Bearer',scope:GOOGLE_SCOPES['app-files']})});auth.start(input);await auth.wait();expect(auth.snapshot().connected).toBe(true);const disk=JSON.parse(readFileSync(f.path,'utf8'));expect(disk.credentialRef).not.toBe(old);expect(disk.pendingRemovalRefs).toContain(old);locked=false;const restarted=new GoogleAuth({...f.options,vault,openBrowser:async()=>{}});await restarted.disconnect();expect(f.secrets.size).toBe(0);expect(JSON.parse(readFileSync(f.path,'utf8')).pendingRemovalRefs).toHaveLength(0);}finally{f.cleanup();}});
