import {randomUUID} from 'node:crypto';
import {test,expect} from 'bun:test';import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';
test('isolated application exposes optional local Google controls and corrupt connector state never prevents local sessions',async()=>{
 const root=mkdtempSync(join(tmpdir(),'heed-google-app-'));mkdirSync(join(root,'sessions'));writeFileSync(join(root,'sessions','local.json'),JSON.stringify({id:'local',title:'Synthetic offline meeting',createdAt:'2026-10-05T10:00:00Z',duration:1,language:'en',transcript:'SYNTHETIC_LOCAL_ONLY',segments:[],speakers:[],tags:[],pinned:false,transcriptFinalized:true}));const portLease=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response()});const port=portLease.port!;portLease.stop(true);const base=`http://127.0.0.1:${port}`;let app:Bun.Subprocess|undefined;
 async function start(){app=Bun.spawn([process.execPath,resolve(import.meta.dir,'../../server.ts')],{cwd:resolve(import.meta.dir,'../../../..'),env:{...process.env,PORT:String(port),HEED_APP_DIR:root,HEED_RECORDINGS_DIR:join(root,'media'),HEED_TRANSCRIPTION_URL:'http://127.0.0.1:1',OLLAMA_HOST:'http://127.0.0.1:1'},stdout:'ignore',stderr:'ignore'});const deadline=Date.now()+5000;while(Date.now()<deadline){try{if((await fetch(base+'/api/sessions')).ok)return;}catch{}await Bun.sleep(20);}throw new Error('Isolated local app failed to start');}
 const post=(body:unknown,origin?:string)=>fetch(base+'/api/google-drive',{method:'POST',headers:{'Content-Type':'application/json',...(origin?{Origin:origin}:{})},body:JSON.stringify(body)});
 try{await start();const response=await fetch(base+'/api/google-drive');expect(response.status).toBe(200);const snapshot=await response.json();expect(snapshot.connected).toBe(false);expect(response.headers.get('Cache-Control')).toBe('no-store');expect((await post({action:'connect'},'https://evil.example')).status).toBe(403);expect((await post({action:'connect',clientSecret:'SECRET'})).status).toBe(400);expect((await post({action:'enable',expectedConnectionId:null,expectedFolderId:null,expectedGeneration:0})).status).toBe(503);expect((await (await fetch(base+'/api/sessions')).json())[0].transcript).toBe('SYNTHETIC_LOCAL_ONLY');app!.kill('SIGTERM');await app!.exited;writeFileSync(join(root,'google-drive.json'),JSON.stringify({version:999,generation:0}));await start();expect((await fetch(base+'/api/google-drive')).status).toBe(503);expect((await (await fetch(base+'/api/sessions')).json())[0].transcript).toBe('SYNTHETIC_LOCAL_ONLY');}
 finally{app?.kill('SIGTERM');await app?.exited;rmSync(root,{recursive:true,force:true});}
});

test('restored authorization initializes protection after capture state and never probes private credentials',async()=>{
 const root=mkdtempSync(join(tmpdir(),'heed-google-restored-'));mkdirSync(join(root,'sessions'));mkdirSync(join(root,'media'));const wav=join(root,'media','source.wav');writeFileSync(wav,Buffer.alloc(1200000));writeFileSync(join(root,'config.json'),JSON.stringify({storage_limit_bytes:4000000}));writeFileSync(join(root,'sessions','local.json'),JSON.stringify({id:'local',title:'Synthetic',createdAt:'2026-10-05T00:00:00Z',duration:1,language:'en',transcript:'Local transcript',segments:[],speakers:[],tags:[],pinned:false,transcriptFinalized:true,files:{wav}}));writeFileSync(join(root,'google-drive.json'),JSON.stringify({version:1,generation:1,connectionId:randomUUID(),credentialRef:randomUUID(),clientId:'synthetic.apps.googleusercontent.com',accessMode:'app-files',folder:{id:'synthetic-root',name:'Synthetic',destinationId:randomUUID(),canUpload:true}}));
 const reserve=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response()}),base=`http://127.0.0.1:${reserve.port}`;reserve.stop(true);const child=Bun.spawn([process.execPath,resolve(import.meta.dir,'../../server.ts')],{cwd:resolve(import.meta.dir,'../../../..'),env:{...process.env,PORT:base.split(':').at(-1)!,HEED_APP_DIR:root,HEED_RECORDINGS_DIR:join(root,'media'),HEED_TRANSCRIPTION_URL:'http://127.0.0.1:1',OLLAMA_HOST:'http://127.0.0.1:1'},stdout:'ignore',stderr:'ignore'});
 try{const deadline=Date.now()+5000;while(Date.now()<deadline){try{if((await fetch(base+'/api/recording/status')).ok)break;}catch{}await Bun.sleep(20);}const response=await fetch(base+'/api/google-drive');expect(response.status).toBe(200);expect((await response.json()).connected).toBe(true);expect((await fetch(base+'/api/storage/preview',{method:'POST',body:JSON.stringify({limitBytes:1048576})})).status).toBe(409);expect((await (await fetch(base+'/api/recording/status')).json()).state).toBe('idle');}
 finally{child.kill('SIGTERM');await child.exited;rmSync(root,{recursive:true,force:true});}
},10000);
