import {existsSync,mkdirSync,statSync,createReadStream} from 'node:fs';import {dirname} from 'node:path';import {createHash} from 'node:crypto';import type {Session,PortableMeeting} from '@heed/shared';import {atomicWriteJson} from '../atomic-json';import {readPrivateJson,privateRecord} from './private-json';import {portableMeeting} from '../portable-schema';
interface Source {destination:string;sessionId:string;path:string;signature:string}
export interface GoogleProtectionCheckpoint {version:1;enabled?:string;pending:Record<string,Source>;acknowledged:Record<string,string>}
export function validGoogleProtectionCheckpoint(value:unknown):value is GoogleProtectionCheckpoint {const state=value as GoogleProtectionCheckpoint;return !(!state||Object.keys(state).some(key=>!['version','enabled','pending','acknowledged'].includes(key))||state.version!==1||(state.enabled!==undefined&&(typeof state.enabled!=='string'||state.enabled.length>64))||!privateRecord(state.pending,10000)||!privateRecord(state.acknowledged,10000)||Object.entries(state.pending).some(([key,source])=>!source||Object.keys(source).sort().join(',')!=='destination,path,sessionId,signature'||typeof source.destination!=='string'||source.destination.length>64||typeof source.sessionId!=='string'||source.sessionId.length>256||key!==`${source.destination}/${source.sessionId}`||typeof source.path!=='string'||source.path.length>4096||typeof source.signature!=='string'||(source.signature!=='unavailable'&&!/^[a-f0-9]{64}$/.test(source.signature)))||Object.entries(state.acknowledged).some(([key,value])=>key.length>322||typeof value!=='string'||!/^[a-f0-9]{64}$/.test(value)));}
interface Options {path:string;listSessions:()=>Session[];resolveSessionId?:(libraryId:string,meetingId:string)=>string|undefined;write?:typeof atomicWriteJson}
function normalized(value:unknown):unknown{if(Array.isArray(value))return value.map(normalized);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([,v])=>v!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,normalized(v)]));return value;}
function textHash(payload:PortableMeeting){return createHash('sha256').update(JSON.stringify(normalized({...payload,meetingId:'local-source',audio:undefined}))).digest('hex');}
/** Protection reads never initialize a library or write through quota callbacks. */
export class GoogleSourceProtection {
 private state:GoogleProtectionCheckpoint;private failed=false;
 constructor(private options:Options){mkdirSync(dirname(options.path),{recursive:true,mode:0o700});this.state=existsSync(options.path)?readPrivateJson<GoogleProtectionCheckpoint>(options.path,8388608):{version:1,pending:{},acknowledged:{}};if(!validGoogleProtectionCheckpoint(this.state))throw new Error('Invalid Google pending source journal; preserve it for recovery');}
 private persist(next:GoogleProtectionCheckpoint){try{(this.options.write||atomicWriteJson)(this.options.path,next);this.state=next;this.failed=false;}catch(error){this.failed=true;throw error;}}
 private source(session:Session,destination:string):Source|undefined{try{const path=session.files?.wav;if(!session.transcriptFinalized||!path||!existsSync(path))return;const info=statSync(path);if(!info.isFile())return;const signature=createHash('sha256').update(`${textHash(portableMeeting(session,'00000000-0000-4000-8000-000000000000'))}/${path}/${info.ino}/${info.size}/${info.mtimeMs}/${info.ctimeMs}`).digest('hex');return {destination,sessionId:session.id,path,signature};}catch{return session.transcriptFinalized&&session.files?.wav?{destination,sessionId:session.id,path:session.files.wav,signature:'unavailable'}:undefined;}}
 private retain(next:GoogleProtectionCheckpoint){if(next.enabled)for(const session of this.options.listSessions()){const source=this.source(session,next.enabled);if(source){const key=`${next.enabled}/${session.id}`;if(next.acknowledged[key]!==source.signature)next.pending[key]=source;}}if(Object.keys(next.pending).length>10000)throw new Error('Google pending source journal limit reached');}
 selectionCheckpoint():GoogleProtectionCheckpoint{const next=structuredClone(this.state);this.retain(next);return next;}
 restoreSelection(previous:GoogleProtectionCheckpoint):void{if(!validGoogleProtectionCheckpoint(previous))throw new Error('Invalid Google protection recovery');this.persist(structuredClone(previous));}
 allFinalizedPaths():string[]{return this.options.listSessions().flatMap(session=>session.transcriptFinalized&&session.files?.wav?[session.files.wav]:[]);}
 checkpoint(){try{const next=structuredClone(this.state);this.retain(next);this.persist(next);}catch(error){this.failed=true;throw error;}}
 enable(destination:string,writable:boolean){try{const next=structuredClone(this.state);this.retain(next);next.enabled=writable?destination:undefined;this.retain(next);this.persist(next);}catch(error){this.failed=true;throw error;}}
 disable(){try{const next=structuredClone(this.state);this.retain(next);delete next.enabled;this.persist(next);}catch(error){this.failed=true;throw error;}}
 protectedPaths():string[]{const sessions=this.options.listSessions();const next=structuredClone(this.state);try{if(this.failed)throw new Error('Protection state unavailable');this.retain(next);}catch{return [...new Set([...sessions.flatMap(session=>session.transcriptFinalized&&session.files?.wav?[session.files.wav]:[]),...Object.values(this.state.pending).map(source=>source.path)])];}return [...new Set(Object.values(next.pending).filter(source=>sessions.some(session=>session.id===source.sessionId&&session.files?.wav===source.path)).map(source=>source.path))];}
 async acknowledge(destination:string,marker:{libraryId:string;meetingId:string},payload:PortableMeeting,signal?:AbortSignal){
  const id=this.options.resolveSessionId?.(marker.libraryId,marker.meetingId),session=this.options.listSessions().find(session=>session.id===id);if(!session||!payload.audio)return;const before=this.source(session,destination);if(!before||before.signature==='unavailable'||textHash(portableMeeting(session,payload.meetingId))!==textHash(payload))return;
  const digest=createHash('sha256');let bytes=0;for await(const chunk of createReadStream(before.path)){signal?.throwIfAborted();bytes+=chunk.length;if(bytes>payload.audio.bytes)return;digest.update(chunk);}signal?.throwIfAborted();if(bytes!==payload.audio.bytes||digest.digest('hex')!==payload.audio.sha256||this.source(session,destination)?.signature!==before.signature)return;
  const next=structuredClone(this.state),key=`${destination}/${session.id}`;if(!Object.hasOwn(next.acknowledged,key)&&Object.keys(next.acknowledged).length>=10000)throw new Error('Google source acknowledgment limit reached');next.acknowledged[key]=before.signature;delete next.pending[key];this.persist(next);
 }
}
