import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';import {track} from '../process';
import type {LibraryProvider} from '../portable-provider';
import type {PortableCommit} from '@heed/shared';
export interface CloudBinding {bookmark:string;account:string;identity:string}
export interface CloudObservation {ubiquitous:boolean;uploaded?:boolean;uploading?:boolean;downloaded?:string;errorCode?:number;state:string;remoteChecksumVerified:false}
export interface CloudRequest {action:'pick'|'probe'|'create'|'list'|'read'|'write'|'status'|'hydrate'|'watch';binding?:CloudBinding;destinationId?:string;stagingId?:string;path?:string;bytes?:number;sha256?:string;maxBytes?:number}
export interface CloudNative {
 json(request:CloudRequest,signal?:AbortSignal):Promise<unknown>;
 stream(request:CloudRequest,max:number,signal?:AbortSignal):AsyncIterable<Uint8Array>;
 write(request:CloudRequest,source:AsyncIterable<Uint8Array>,signal?:AbortSignal):Promise<void>;
}
export const cloudUnavailable=()=>new Error('iCloud folder unavailable. Check sign-in, folder access, download status and library integrity.');
const hash=(value:Uint8Array)=>createHash('sha256').update(value).digest('hex');
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
function path(value:string){if(value.length>512||! /^(meetings|objects|commits)\/[A-Za-z0-9_./-]+$/.test(value)||value.split('/').some(p=>!p||p==='.'||p==='..'))throw cloudUnavailable();return value;}
function bound(value:number){if(!Number.isSafeInteger(value)||value<0||value>8_000_000_000_000)throw cloudUnavailable();return value;}
export function cloudHeader(value:unknown):{format:'heed-portable-library';schemaVersion:1;destinationId:string}|null {
 if(value===null)return null;const item=value as any;
 if(!item||Object.keys(item).sort().join(',')!=='destinationId,format,schemaVersion'||item.format!=='heed-portable-library'||item.schemaVersion!==1||!UUID.test(item.destinationId))throw cloudUnavailable();return item;
}
export function cloudBinding(value:unknown):CloudBinding {const b=value as CloudBinding;if(!b||Object.keys(b).sort().join(',')!=='account,bookmark,identity'||![b.account,b.bookmark].every(v=>typeof v==='string'&&v.length>0&&v.length<=65536&&/^[A-Za-z0-9+/]+=*$/.test(v))||typeof b.identity!=='string'||!/^\d+:\d+$/.test(b.identity))throw cloudUnavailable();return b;}
export class MacCloudNative implements CloudNative {
 constructor(private helper=fileURLToPath(new URL('../../../desktop/icloud-folder/.build/heed-icloud',import.meta.url))){}
 private async spawn(request:CloudRequest,signal?:AbortSignal){signal?.throwIfAborted();const process=track(Bun.spawn([this.helper],{stdin:'pipe',stdout:'pipe',stderr:'ignore'}));const abort=()=>process.kill('SIGKILL');const timer=setTimeout(abort,request.action==='pick'?120000:Math.min(3600000,30000+Math.ceil((request.bytes??request.maxBytes??0)/1_000_000)*1000));signal?.addEventListener('abort',abort,{once:true});try{process.stdin.write(JSON.stringify(request)+'\n');}catch{abort();await process.exited;clearTimeout(timer);signal?.removeEventListener('abort',abort);throw cloudUnavailable();}return {process,abort,clean(){clearTimeout(timer);signal?.removeEventListener('abort',abort);}};}
 async *stream(request:CloudRequest,max:number,signal?:AbortSignal){const {process,abort,clean}=await this.spawn(request,signal);let size=0;try{process.stdin.end();for await(const chunk of process.stdout){signal?.throwIfAborted();size+=chunk.length;if(size>max)throw cloudUnavailable();yield chunk;}if(await process.exited!==0)throw cloudUnavailable();signal?.throwIfAborted();}finally{abort();await process.exited;clean();}}
 async json(request:CloudRequest,signal?:AbortSignal){const chunks:Uint8Array[]=[];for await(const chunk of this.stream(request,request.action==='list'?2_000_000:150000,signal))chunks.push(chunk);try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw cloudUnavailable();}}
 async write(request:CloudRequest,source:AsyncIterable<Uint8Array>,signal?:AbortSignal){const {process,abort,clean}=await this.spawn(request,signal);const response=new Response(process.stdout).arrayBuffer();let size=0;try{for await(const chunk of source){signal?.throwIfAborted();size+=chunk.length;if(size>(request.bytes??0))throw cloudUnavailable();await process.stdin.write(chunk);await process.stdin.flush();}if(size!==request.bytes)throw cloudUnavailable();process.stdin.end();if(await process.exited!==0||(await response).byteLength>4096)throw cloudUnavailable();signal?.throwIfAborted();}finally{try{process.stdin.end();}catch{}abort();await process.exited;await response.catch(()=>{});clean();}}
}
/** macOS upload observations never release the sole private pending copy. */
export class ICloudFolderProvider implements LibraryProvider {
 readonly transport='os-managed-folder' as const;
 private observations=new Map<string,CloudObservation>();
 statusFor(revisionId:string){return this.observations.get(revisionId);}
 readonly capabilities={read:true,write:true,remoteDeletion:false,durability:'local-only' as const};
 constructor(readonly id:string,readonly name:string,private binding:CloudBinding,private destinationId:string,private native:CloudNative=new MacCloudNative(),private guard?:()=>void){}
 private request(action:CloudRequest['action'],extra:Partial<CloudRequest>={}):CloudRequest{return {action,binding:this.binding,destinationId:this.destinationId,stagingId:this.id,...extra};}
 private async access(signal?:AbortSignal){this.guard?.();const probe=await this.native.json(this.request('probe'),signal) as any;if(cloudHeader(probe?.header)?.destinationId!==this.destinationId||probe.remoteChecksumVerified!==false)throw cloudUnavailable();}
 async list(cursor:string|null,limit:number,signal?:AbortSignal){if(!Number.isInteger(limit)||limit<1||limit>100)throw cloudUnavailable();await this.access(signal);const paths=await this.native.json(this.request('list'),signal);if(!Array.isArray(paths)||paths.length>10000||paths.some(p=>typeof p!=='string'||!/^commits\/[a-f0-9-]{36}\/[a-f0-9-]{36}\.json$/i.test(p)))throw cloudUnavailable();const sorted=[...paths].sort();const identity=hash(Buffer.from(JSON.stringify(sorted)));let offset=0;if(cursor){const parts=cursor.split(':');if(parts.length!==2||parts[0]!==identity||!/^\d+$/.test(parts[1]!))throw cloudUnavailable();offset=Number(parts[1]);if(!Number.isSafeInteger(offset)||offset<0||offset>=sorted.length)throw cloudUnavailable();}const commits:PortableCommit[]=[];for(const file of sorted.slice(offset,offset+limit)){const marker=JSON.parse(Buffer.from(await this.read(file,16384,signal)).toString('utf8'));if(!marker||Object.keys(marker).sort().join(',')!=='deviceId,libraryId,manifestHash,manifestPath,meetingId,revisionId,schemaVersion'||marker.schemaVersion!==1||![marker.deviceId,marker.libraryId,marker.meetingId,marker.revisionId].every(v=>typeof v==='string'&&UUID.test(v))||file!==`commits/${marker.deviceId}/${marker.revisionId}.json`||marker.manifestPath!==`meetings/${marker.meetingId}/revisions/${marker.revisionId}/manifest.json`||! /^[a-f0-9]{64}$/.test(marker.manifestHash))throw cloudUnavailable();commits.push(marker);}return {commits,next:offset+limit<sorted.length?`${identity}:${offset+limit}`:null,complete:true};}
 async *stream(file:string,max:number,signal?:AbortSignal){path(file);bound(max);await this.access(signal);await this.native.json(this.request('hydrate',{path:file,maxBytes:max}),signal);let size=0;for await(const chunk of this.native.stream(this.request('read',{path:file,maxBytes:max}),max,signal)){signal?.throwIfAborted();size+=chunk.length;if(size>max)throw cloudUnavailable();yield chunk;}}
 async read(file:string,max:number,signal?:AbortSignal){if(max>16_000_000)throw cloudUnavailable();const chunks:Uint8Array[]=[];for await(const chunk of this.stream(file,max,signal))chunks.push(chunk);return Buffer.concat(chunks);}
 async writeImmutable(file:string,bytes:Uint8Array,signal?:AbortSignal){path(file);await this.access(signal);await this.native.write(this.request('write',{path:file,bytes:bytes.length,sha256:hash(bytes)}),(async function*(){yield bytes;})(),signal);}
 async writeObjectImmutable(file:string,bytes:number,digest:string,source:AsyncIterable<Uint8Array>,signal?:AbortSignal){path(file);bound(bytes);if(file!==`objects/${digest}`||! /^[a-f0-9]{64}$/.test(digest))throw cloudUnavailable();await this.access(signal);let size=0;const checksum=createHash('sha256');const verified=(async function*(){for await(const chunk of source){signal?.throwIfAborted();size+=chunk.length;if(size>bytes)throw cloudUnavailable();checksum.update(chunk);yield chunk;}if(size!==bytes||checksum.digest('hex')!==digest)throw cloudUnavailable();})();await this.native.write(this.request('write',{path:file,bytes,sha256:digest}),verified,signal);}
 async observation(marker:PortableCommit,signal?:AbortSignal){await this.access(signal);return await this.native.json(this.request('watch',{path:`commits/${marker.deviceId}/${marker.revisionId}.json`}),signal) as CloudObservation;}
 async confirm(marker:PortableCommit,signal?:AbortSignal):Promise<'local-only'>{await this.access(signal);const stored=await this.read(`commits/${marker.deviceId}/${marker.revisionId}.json`,16384,signal);if(hash(stored)!==hash(Buffer.from(JSON.stringify(marker))))throw cloudUnavailable();const observation=await this.observation(marker,signal);this.observations.set(marker.revisionId,observation);if(!observation.ubiquitous||observation.errorCode!==undefined)throw cloudUnavailable();return 'local-only';}
}
