import {test,expect} from 'bun:test';import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {ICloudConnections,icloudResponse} from './icloud-connections';
const dest=randomUUID();
function fixture(){const root=mkdtempSync(join(tmpdir(),'heed-cloud-config-'));let uploaded=true;let publishCount=0;let localCalls=0;const localId=randomUUID(),rev=randomUUID();const library:any={hasLocalRevision:()=>true,snapshot:()=>({localMeetings:[{id:localId,title:'Synthetic'}],previews:[{revisionId:rev,state:'pending',local:true}],complete:true,imported:1,skipped:0}),withProvider:async(_p:any,fn:any)=>fn(library),discover:async()=>{},importSelected:async()=>{},queueLocal:async()=>{localCalls++;return {revisionId:rev,state:'pending'};},publish:async()=>{publishCount++;}};const native:any={json:async(r:any)=>r.action==='pick'?{bookmark:'YQ==',account:'Yg==',identity:'1:2'}:r.action==='probe'?{header:{format:'heed-portable-library',schemaVersion:1,destinationId:dest},status:'pending-upload',remoteChecksumVerified:false}:r.action==='watch'?{ubiquitous:true,uploaded,state:uploaded?'system-reported-uploaded':'pending-upload',remoteChecksumVerified:false}:{} };const options={configPath:join(root,'icloud.json'),jobsPath:join(root,'jobs.json'),library,native,busy:()=>false};return {root,options,rev,localId,get publishCount(){return publishCount;},get localCalls(){return localCalls;},setUploaded(v:boolean){uploaded=v;},close(){rmSync(root,{recursive:true,force:true});}};}
test('reviewed binding stays private; system upload never acknowledges pending revision across restart',async()=>{const f=fixture();try{const c=new ICloudConnections(f.options);const selected=await c.select();await c.connect({name:'Fixture',receipt:selected.receipt,create:false});await c.sync();expect(c.protectedRevisionIds()).toEqual([f.rev]);expect(JSON.stringify(c.snapshot())).not.toContain('YQ==');const restarted=new ICloudConnections(f.options);expect(restarted.protectedRevisionIds()).toEqual([f.rev]);expect(restarted.snapshot().connection?.pending).toBe(1);await restarted.disconnect();expect(restarted.snapshot().connection).toBeNull();expect(restarted.protectedRevisionIds()).toEqual([f.rev]);expect(readFileSync(f.options.jobsPath,'utf8')).not.toContain('YQ==');}finally{f.close();}});
test('configuration write failure retains old binding and invalid receipt cannot initialize a folder',async()=>{const f=fixture();try{let fail=false;const c=new ICloudConnections({...f.options,write:(p:string,v:any)=>{if(fail)throw Error('disk');require('../atomic-json').atomicWriteJson(p,v);}});await expect(c.connect({name:'Fixture',receipt:randomUUID(),create:true})).rejects.toThrow();const selected=await c.select();fail=true;await expect(c.connect({name:'Fixture',receipt:selected.receipt,create:false})).rejects.toThrow();expect(c.snapshot().connection).toBeNull();}finally{f.close();}});
test('foreign origins cannot trigger native folder selection; read-only status never leaks bookmark',async()=>{const f=fixture();try{const c=new ICloudConnections(f.options);const response=await icloudResponse(new Request('http://localhost:5001/api/icloud',{method:'POST',headers:{origin:'https://untrusted.example'},body:JSON.stringify({action:'select'})}),c);expect(response.status).toBe(403);expect(f.localCalls).toBe(0);const invalid=await icloudResponse(new Request('http://localhost:5001/api/icloud',{method:'POST',body:JSON.stringify({action:'connect',receipt:'bad',name:'Fixture',create:true,bookmark:'private'})}),c);expect(invalid.status).toBe(400);}finally{f.close();}});
test('changed preview never imports a new remote selection and busy core prevents configuration mutation',async()=>{const f=fixture();try{let count=1;let imports=0;const library={...f.options.library,snapshot:()=>({localMeetings:[],previews:Array.from({length:count},(_,i)=>({revisionId:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,state:'pending',local:false,bytes:100,title:'Synthetic'})),complete:true,imported:0,skipped:0}),importSelected:async()=>{imports++;}};library.withProvider=async(_p:any,fn:any)=>fn(library);let busy=false;const c=new ICloudConnections({...f.options,library,busy:()=>busy});const selected=await c.select();await c.connect({name:'Fixture',receipt:selected.receipt,create:false});await c.previewLibrary();const token=c.snapshot().preview!.token;count=2;await expect(c.importReviewed(token)).rejects.toThrow('changed');expect(imports).toBe(0);busy=true;await expect(c.disconnect()).rejects.toThrow('Wait');expect(c.snapshot().connection?.name).toBe('Fixture');}finally{f.close();}});
test('stale tab cannot publish, preview, pause or disconnect a replacement library',async()=>{const f=fixture();try{const c=new ICloudConnections(f.options);let reviewed=await c.select();await c.connect({name:'First',receipt:reviewed.receipt,create:false});const old=c.snapshot().connection!.id;reviewed=await c.select();await c.connect({name:'Second',receipt:reviewed.receipt,create:false});const fresh=c.snapshot().connection!.id;for(const body of [{action:'sync',connectionId:old},{action:'preview',connectionId:old},{action:'disconnect',connectionId:old},{action:'enable',connectionId:old,enabled:false}]){const response=await icloudResponse(new Request('http://localhost:5001/api/icloud',{method:'POST',body:JSON.stringify(body)}),c);expect(response.status).toBe(409);}expect(c.snapshot().connection!.id).toBe(fresh);expect(f.publishCount).toBe(0);}finally{f.close();}});
test('preference activation failure restores the existing binding and previous selected provider',async()=>{const f=fixture();try{let selected:string|null=null;let fail=false;const factories=new Map<string,()=>any>();const providers={assertIdle(){},preferredId:()=>selected,currentId:()=>selected,register(id:string,factory:()=>any){factories.set(id,factory);},activate(id:string){if(fail){fail=false;throw Error('Preference disk failed');}selected=id;},deactivate(id:string){if(selected===id)selected=null;},unregister(id:string){if(selected===id)selected=null;factories.delete(id);},withMutation:async(fn:any)=>fn()};const c=new ICloudConnections({...f.options,providers});let reviewed=await c.select();await c.connect({name:'Original',receipt:reviewed.receipt,create:false});const original=c.snapshot().connection!.id;reviewed=await c.select();fail=true;await expect(c.connect({name:'Replacement',receipt:reviewed.receipt,create:false})).rejects.toThrow();expect(c.snapshot().connection!.name).toBe('Original');expect(selected).toBe(original);expect(JSON.parse(readFileSync(f.options.configPath,'utf8')).connection.id).toBe(original);}finally{f.close();}});

test('deleted old-folder jobs cannot block publication of a newer folder source',async()=>{
 const f=fixture();try{let oldDeleted=false;const fresh=randomUUID();const published:string[]=[];
 const library={...f.options.library,hasLocalRevision:(id:string)=>id===fresh||id===f.rev&&!oldDeleted,
 snapshot:()=>({localMeetings:[{id:oldDeleted?'new-source':f.localId,title:'Synthetic'}],previews:oldDeleted?[{revisionId:fresh,state:'pending',local:true}]:[{revisionId:f.rev,state:'pending',local:true}],complete:true,imported:0,skipped:0}),
 queueLocal:async()=>({revisionId:oldDeleted?fresh:f.rev}),publish:async(id:string)=>{if(oldDeleted&&id===f.rev)throw Error('Deleted local source');published.push(id);}};
 library.withProvider=async(_provider:any,run:any)=>run(library);const c=new ICloudConnections({...f.options,library});
 let selected=await c.select();await c.connect({name:'Old folder',receipt:selected.receipt,create:false});await c.sync();
 selected=await c.select();await c.connect({name:'New folder',receipt:selected.receipt,create:false});oldDeleted=true;
 await c.sync();expect(published).toEqual([f.rev,fresh]);expect(c.protectedRevisionIds()).toEqual([fresh]);
 }finally{f.close();}
});
