import {test,expect} from 'bun:test';
import {mkdtempSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {MacCloudNative} from './icloud-folder';import {ICloudConnections,icloudResponse} from './icloud-connections';
const sentinel='/private/sentinel-root SECRET_BOOKMARK localized diagnostic';
function fixture(stderr:string,stdout='',exit=1){const root=mkdtempSync(join(tmpdir(),'heed-cloud-failure-')),helper=join(root,'helper');writeFileSync(helper,`#!/bin/sh\nread request\ncat >/dev/null\ncat <<'OUT'\n${stdout}\nOUT\ncat >&2 <<'ERR'\n${stderr}\nERR\nexit ${exit}\n`,{mode:0o700});return {root,native:new MacCloudNative(helper),close(){rmSync(root,{recursive:true,force:true});}};}
for(const code of ['account-unavailable','bookmark-stale'])test(`nonzero native control failure retains ${code} through the public action API`,async()=>{const f=fixture(JSON.stringify({protocol:'heed-icloud-failure',version:1,code}));try{await expect(f.native.json({action:'probe'})).rejects.toMatchObject({code});const connections=new ICloudConnections({configPath:join(f.root,'config.json'),jobsPath:join(f.root,'jobs.json'),library:{} as any,native:f.native,busy:()=>false});const response=await icloudResponse(new Request('http://localhost:5001/api/icloud',{method:'POST',body:JSON.stringify({action:'select'})}),connections);expect(response.status).toBe(503);expect(await response.json()).toMatchObject({issue:code});}finally{f.close();}});
test('native failures expose only the closed failure envelope and never raw diagnostics',async()=>{for(const stderr of [sentinel,JSON.stringify({protocol:'heed-icloud-failure',version:1,code:'account-unavailable',detail:sentinel}),JSON.stringify({protocol:'heed-icloud-failure',version:1,code:sentinel}),'x'.repeat(100000)+JSON.stringify({protocol:'heed-icloud-failure',version:1,code:'bookmark-stale'})]){const f=fixture(stderr);try{await expect(f.native.json({action:'probe'})).rejects.toMatchObject({code:'unavailable'});try{await f.native.json({action:'probe'});}catch(error){expect(String(error)).not.toContain(sentinel);}}finally{f.close();}}});
test('successful artifact bytes are never interpreted as failure protocol and streamed failures remain generic',async()=>{const envelope=JSON.stringify({protocol:'heed-icloud-failure',version:1,code:'account-changed'});for(const exit of [0,1]){const f=fixture(envelope,envelope,exit);try{const read=async()=>{const chunks:Uint8Array[]=[];for await(const chunk of f.native.stream({action:'read'},1000))chunks.push(chunk);return Buffer.concat(chunks).toString().trim();};if(exit===0)expect(await read()).toBe(envelope);else await expect(read()).rejects.toMatchObject({code:'unavailable'});}finally{f.close();}}});
test('write failures retain an allowlisted issue without publishing stderr',async()=>{const f=fixture(JSON.stringify({protocol:'heed-icloud-failure',version:1,code:'permission-denied'}));try{await expect(f.native.write({action:'write',bytes:0},(async function*(){})())).rejects.toMatchObject({code:'permission-denied'});}finally{f.close();}});
test('raw native descriptions cannot bypass HTTP sanitization by matching a validation prefix',async()=>{const f=fixture('unused');try{const native={json:async()=>{throw Error('Invalid '+sentinel);},stream:f.native.stream.bind(f.native),write:f.native.write.bind(f.native)};const connections=new ICloudConnections({configPath:join(f.root,'config.json'),jobsPath:join(f.root,'jobs.json'),library:{} as any,native,busy:()=>false});const response=await icloudResponse(new Request('http://localhost:5001/api/icloud',{method:'POST',body:JSON.stringify({action:'select'})}),connections);const body=await response.text();expect(body).not.toContain(sentinel);expect(response.status).toBe(503);}finally{f.close();}});
function earlyRejectionFixture(){const f=fixture('unused');writeFileSync(join(f.root,'helper'),`#!/bin/sh\nread request\nprintf '%s\\n' '{"protocol":"heed-icloud-failure","version":1,"code":"permission-denied"}' >&2\nexit 1\n`,{mode:0o700});return f;}
test('early helper rejection retains its sanitized issue when a nonempty payload encounters a broken pipe',async()=>{const f=earlyRejectionFixture();try{const source=(async function*(){await Bun.sleep(50);yield Buffer.alloc(1_000_000);})();await expect(f.native.write({action:'write',bytes:1_000_000},source)).rejects.toMatchObject({code:'permission-denied'});}finally{f.close();}});
test('an early helper issue cannot replace the local source error even if it is named EPIPE',async()=>{const f=earlyRejectionFixture();try{const error=Object.assign(Error('Synthetic source failed'),{code:'EPIPE'}),source=(async function*(){await Bun.sleep(50);throw error;yield Buffer.alloc(1);})();await expect(f.native.write({action:'write',bytes:1},source)).rejects.toBe(error);}finally{f.close();}});
test('cancellation wins over an early helper issue before a delayed source chunk',async()=>{const f=earlyRejectionFixture(),controller=new AbortController();try{const reason=Error('Synthetic cancellation'),source=(async function*(){await Bun.sleep(50);controller.abort(reason);yield Buffer.alloc(1);})();await expect(f.native.write({action:'write',bytes:1},source,controller.signal)).rejects.toBe(reason);}finally{f.close();}});

test('a helper that closes payload input without exiting is bounded and reaped',async()=>{const f=fixture('unused'),pidFile=join(f.root,'pid');try{writeFileSync(join(f.root,'helper'),`#!/bin/sh\nread request\nprintf '%s' "$$" > '${pidFile}'\nexec 0<&-\ntrap '' TERM\nexec /bin/sleep 60\n`,{mode:0o700});const started=Date.now(),source=(async function*(){await Bun.sleep(50);yield Buffer.alloc(1_000_000);})();await expect(f.native.write({action:'write',bytes:1_000_000},source)).rejects.toMatchObject({code:'unavailable'});expect(Date.now()-started).toBeLessThan(4000);expect(()=>process.kill(Number(readFileSync(pidFile,'utf8')),0)).toThrow();}finally{f.close();}});
