import {expect,test} from 'bun:test';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve,dirname} from 'node:path';
async function fixture(corrupt?:string){
 const root=mkdtempSync(join(tmpdir(),'heed-icloud-router-'));if(corrupt){const file=join(root,corrupt);mkdirSync(dirname(file),{recursive:true});writeFileSync(file,'{corrupt');}
 mkdirSync(join(root,'sessions'),{recursive:true});mkdirSync(join(root,'recordings'));const wav=join(root,'recordings/source.wav');writeFileSync(wav,Buffer.alloc(1200000));writeFileSync(join(root,'sessions/fixture.json'),JSON.stringify({id:'fixture',title:'Retained local meeting',createdAt:'2026-10-05T00:00:00Z',duration:1,language:'en',transcript:'Complete local transcript',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true,files:{wav}}));writeFileSync(join(root,'config.json'),JSON.stringify({storage_limit_bytes:4000000}));
 const sidecar=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({whisper:true})}),reservation=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response()}),base=`http://127.0.0.1:${reservation.port}`;reservation.stop(true);const child=Bun.spawn([process.execPath,resolve(import.meta.dir,'../../server.ts')],{cwd:resolve(import.meta.dir,'../../../..'),env:{...process.env,PORT:base.split(':').at(-1)!,HEED_APP_DIR:root,HEED_RECORDINGS_DIR:join(root,'recordings'),HEED_TRANSCRIPTION_URL:`http://127.0.0.1:${sidecar.port}`},stdout:'ignore',stderr:'ignore'});
 return {root,wav,base,async ready(){const deadline=Date.now()+5000;while(Date.now()<deadline){try{if((await fetch(base+'/api/recording/status')).ok)return;}catch{}await Bun.sleep(30);}throw Error('Isolated server did not start');},async close(){child.kill();await child.exited;sidecar.stop(true);rmSync(root,{recursive:true,force:true});}};
}
test('production iCloud router is explicit and rejects foreign origins without launching native selection',async()=>{const f=await fixture();try{await f.ready();const status=await fetch(f.base+'/api/icloud');expect(status.status).toBe(200);expect((await status.json()).connection).toBeNull();for(const method of ['GET','POST'])expect((await fetch(f.base+'/api/icloud',{method,headers:{origin:'https://foreign.example'},body:method==='POST'?JSON.stringify({action:'select'}):undefined})).status).toBe(403);expect((await fetch(f.base+'/api/icloud',{method:'POST',body:JSON.stringify({action:'sync',connectionId:'not-a-destination'})})).status).toBe(400);expect((await (await fetch(f.base+'/api/recording/status')).json()).state).toBe('idle');}finally{await f.close();}},10000);
test.each(['icloud-folder.json','icloud-folder.json.transition.json','library/catalog/icloud-jobs.json'])('corrupt optional %s preserves local text and protects media without rewriting private configuration',async path=>{const f=await fixture(path);try{await f.ready();expect((await fetch(f.base+'/api/icloud')).status).toBe(503);expect((await fetch(f.base+'/api/icloud',{headers:{origin:'https://foreign.example'}})).status).toBe(403);expect((await (await fetch(f.base+'/api/sessions')).json())[0].transcript).toBe('Complete local transcript');expect((await fetch(f.base+'/api/storage/preview',{method:'POST',body:JSON.stringify({limitBytes:1048576})})).status).toBe(409);expect(readFileSync(join(f.root,path),'utf8')).toBe('{corrupt');expect(readFileSync(f.wav).length).toBe(1200000);}finally{await f.close();}},10000);
