import {test,expect} from 'bun:test';
import {createHash,randomUUID} from 'node:crypto';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {PortableLibrary} from '../portable-library';import {SessionTags} from '../session-tags';import {ManagedQuota,MIN_MANAGED_LIMIT} from '../managed-quota';
import {ICloudFolderProvider,cloudBinding,cloudHeader,type CloudNative,type CloudRequest} from './icloud-folder';
const id=randomUUID(), destinationId=randomUUID();
const sha=(value:Uint8Array)=>createHash('sha256').update(value).digest('hex');
function fixture(version:1|2=1){const files=new Map<string,Uint8Array>();const calls:CloudRequest[]=[];let status:any={ubiquitous:true,uploaded:true,state:'system-reported-uploaded',remoteChecksumVerified:false};const native:CloudNative={async json(request){calls.push(request);if(request.action==='probe')return {header:{format:'heed-portable-library',schemaVersion:version,destinationId},remoteChecksumVerified:false};if(request.action==='list')return [...files.keys()].filter(p=>p.startsWith('commits/'));if(request.action==='watch')return status;return {};},async *stream(request){calls.push(request);const bytes=files.get(request.path!);if(!bytes)throw Error('pending hydration');yield bytes;},async write(request,source){calls.push(request);const chunks:Uint8Array[]=[];for await(const chunk of source)chunks.push(chunk);const bytes=Buffer.concat(chunks);if(bytes.length!==request.bytes||sha(bytes)!==request.sha256)throw Error('integrity');const old=files.get(request.path!);if(old&&sha(old)!==sha(bytes))throw Error('conflict');files.set(request.path!,bytes);}};const provider=new ICloudFolderProvider(id,'Fixture',{bookmark:'YQ==',account:'Yg==',identity:'1:2'},destinationId,native,undefined,version,'fixture-generation');return {provider,native,files,calls,status,setStatus(value:any){status=value;}};}
test('system uploaded state is local-only and cannot release pending private data',async()=>{const f=fixture();const marker={schemaVersion:1,libraryId:randomUUID(),meetingId:randomUUID(),revisionId:randomUUID(),deviceId:randomUUID(),manifestPath:'',manifestHash:'0'.repeat(64)} as any;marker.manifestPath=`meetings/${marker.meetingId}/revisions/${marker.revisionId}/manifest.json`;await f.provider.writeImmutable(`commits/${marker.deviceId}/${marker.revisionId}.json`,Buffer.from(JSON.stringify(marker)));expect(await f.provider.confirm(marker)).toBe('local-only');expect(f.calls.some(c=>c.action==='watch')).toBe(true);f.setStatus({...f.status,errorCode:4354});await expect(f.provider.confirm(marker)).rejects.toThrow();});
test('bounded stream validates checksum before native publication and immutable writes reject conflicts',async()=>{const f=fixture(),bytes=Buffer.from('synthetic');await f.provider.writeObjectImmutable(`objects/${sha(bytes)}`,bytes.length,sha(bytes),(async function*(){yield bytes;})());expect(Buffer.from(await f.provider.read(`objects/${sha(bytes)}`,bytes.length)).toString()).toBe('synthetic');await expect(f.provider.writeObjectImmutable(`objects/${'0'.repeat(64)}`,bytes.length,'0'.repeat(64),(async function*(){yield bytes;})())).rejects.toThrow();expect(f.files.has(`objects/${'0'.repeat(64)}`)).toBe(false);await expect(f.provider.writeImmutable(`objects/${sha(bytes)}`,Buffer.from('changed'))).rejects.toThrow();expect(f.calls.find(c=>c.action==='hydrate')?.maxBytes).toBe(bytes.length);expect(f.calls.findIndex(c=>c.action==='hydrate')).toBeLessThan(f.calls.findIndex(c=>c.action==='read'));});
test('incomplete hydration, scoped traversal and invalid descriptors never complete discovery',async()=>{const f=fixture();await expect(f.provider.read('objects/missing',100)).rejects.toThrow();await expect(f.provider.read('objects/../escape',100)).rejects.toThrow();f.files.set(`commits/${randomUUID()}/${randomUUID()}.json`,Buffer.from('{}'));await expect(f.provider.list(null,100)).rejects.toThrow();expect(()=>cloudHeader({format:'other',schemaVersion:1,destinationId})).toThrow();expect(()=>cloudBinding({bookmark:'YQ==',account:'Yg==',identity:'1:2',token:'private'})).toThrow();});

test('two isolated catalogs import complete local-only publications while quota protects the first audio copy',async()=>{
 const f=fixture(),root=mkdtempSync(join(tmpdir(),'heed-icloud-roundtrip-'));
 try{
 const create=(device:string)=>{const base=join(root,device),sessionsDir=join(base,'sessions'),recordingsDir=join(base,'recordings'),libraryRoot=join(base,'library');mkdirSync(sessionsDir,{recursive:true});mkdirSync(recordingsDir);const sessions=new SessionTags(sessionsDir);let library:PortableLibrary;const quota=new ManagedQuota({ledgerPath:join(base,'quota.json'),roots:{text:[sessionsDir,join(libraryRoot,'catalog')],media:[recordingsDir,join(libraryRoot,'media')],staging:[join(libraryRoot,'staging')],indexes:[join(libraryRoot,'indexes')]},getLimit:()=>3_000_000,setLimit:()=>{},protectedPaths:()=>library?.protectedPaths()||[]});library=new PortableLibrary({root:libraryRoot,sessions,sessionsDir,recordingsDir,quota,provider:f.provider});return {sessions,library,quota,recordingsDir};};
 const a=create('a'),b=create('b');const audio=Buffer.alloc(1_200_000);audio.write('RIFF');audio.write('WAVE',8);const wav=join(a.recordingsDir,'synthetic.wav');writeFileSync(wav,audio);a.sessions.create({id:'synthetic',title:'Planning',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Approved synthetic review',segments:[],speakers:[],tags:['Review'],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true,files:{wav}});const queued=await a.library.queueLocal('synthetic');await a.library.publish(queued.revisionId);expect(a.library.snapshot().previews[0]?.state).toBe('pending');expect(()=>a.quota.preview(MIN_MANAGED_LIMIT)).toThrow();await b.library.discover();expect(b.sessions.snapshot().sessions).toHaveLength(0);const readAudioBefore=f.calls.filter(c=>c.action==='read'&&c.path?.startsWith('objects/')).length;await b.library.importSelected();expect(b.sessions.snapshot().sessions[0]?.transcript).toBe('Approved synthetic review');expect(f.calls.filter(c=>c.action==='read'&&c.path?.startsWith('objects/')).length).toBe(readAudioBefore);const imported=b.sessions.snapshot().sessions[0]!;const localAudio=await b.library.requestAudio(imported.id);expect(readFileSync(localAudio)).toEqual(audio);a.sessions.save({...a.sessions.read('synthetic')!,title:'Branch A'});const edited=await a.library.queueLocal('synthetic');await a.library.publish(edited.revisionId);b.sessions.save({...b.sessions.read(imported.id)!,title:'Branch B'});await b.library.discover();await b.library.importSelected();expect(b.sessions.read(imported.id)?.title).toBe('Branch B');expect(b.library.snapshot().previews.some(p=>p.state==='conflict')).toBe(true);expect(f.files.has(`objects/${sha(audio)}`)).toBe(true);
 const blocked=create('blocked');blocked.library.selectProvider(f.provider);await blocked.library.discover();const beforeBlocked=f.calls.filter(c=>c.action==='hydrate').length;const limited=new PortableLibrary({root:join(root,'blocked/library'),sessions:blocked.sessions,sessionsDir:join(root,'blocked/sessions'),recordingsDir:blocked.recordingsDir,quota:{reserve(){throw Error('quota-blocked');},release(){}},provider:f.provider});await limited.importSelected();expect(f.calls.filter(c=>c.action==='hydrate').length).toBe(beforeBlocked);expect(blocked.sessions.snapshot().sessions).toHaveLength(0);
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('v2 capability is local coordinated metadata only and escaped transaction calls cannot reach native',async()=>{const f=fixture();const provider=new ICloudFolderProvider(id,'Fixture',{bookmark:'YQ==',account:'Yg==',identity:'1:2'},destinationId,f.native,undefined,2,'generation');expect(provider.deletionCapabilities?.sharedAudioGC).toBe(false);expect(provider.deletionCapabilities?.confirmation).toBe('pending-propagation');const before=f.calls.length;await expect(provider.read('objects/a',1)).rejects.toThrow();expect(f.calls.length).toBe(before);});
test('v2 iCloud adapter and deletion engine accept exact sorted native fences and report pending propagation without shared media removal',async()=>{
 const {RemoteDeletion}=await import('../remote-deletion'),{makeBundle,portableMeeting,encode,revisionPath}=await import('../portable-schema'),{canonicalControl}=await import('../portable-deletion-schema');const f=fixture(2),root=mkdtempSync(join(tmpdir(),'heed-icloud-delete-adapter-'));try{
 const bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting({id:'synthetic',title:'Synthetic deletion',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Preserve local content',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true},randomUUID()),[]);const prefix=revisionPath(bundle.manifest.meetingId,bundle.manifest.revisionId),markerPath=`commits/${bundle.marker.deviceId}/${bundle.marker.revisionId}.json`;f.files.set(bundle.marker.manifestPath,encode(bundle.manifest));f.files.set(`${prefix}/meeting.json`,encode(bundle.payload));f.files.set(markerPath,encode(bundle.marker));f.files.set('objects/unselected',Buffer.from('shared synthetic media'));
 const json=f.native.json.bind(f.native);f.native.json=async request=>{if(request.action==='inventory')return {commits:[...f.files.keys()].filter(path=>path.startsWith('commits/')),deletions:[...f.files.keys()].filter(path=>path.startsWith('control/deletions/')),pending:[...f.files.keys()].filter(path=>path.startsWith('control/pending/'))};if(request.action==='remove-exact'){const record=JSON.parse(Buffer.from(f.files.get(`control/deletions/${request.jobId}.json`)!).toString()),artifact=record.artifacts.find((item:any)=>item.path===request.path);if(!artifact||artifact.bytes!==request.bytes||artifact.sha256!==request.sha256)throw Error('Native target mismatch');const current=f.files.get(request.path!);if(current&&(current.length!==artifact.bytes||sha(current)!==artifact.sha256))throw Error('Native expected hash changed');f.files.delete(request.path!);if(request.path!.endsWith('/manifest.json')){const fence={kind:'heed-deleted-revision',version:1,jobId:record.jobId,destinationId,revision:record.revisions[0],artifact};f.files.set(request.path!,Buffer.from(canonicalControl(fence)));}return {result:current?'removed':'already-removed',confirmation:'pending-propagation'};}return json(request);};
 const engine=new RemoteDeletion({path:join(root,'private.json')}),selection={providerId:id,destinationId,revisions:[{libraryId:bundle.manifest.libraryId,meetingId:bundle.manifest.meetingId,revisionId:bundle.manifest.revisionId}]};await f.provider.withTransaction({operationId:randomUUID(),deviceId:randomUUID(),kind:'delete'},async tx=>{const preview=await engine.preview(f.provider,tx,selection),job=await engine.confirm(f.provider,tx,preview.token,true);expect(job.state).toBe('pending-propagation');expect(f.files.has(`${prefix}/meeting.json`)).toBe(false);expect(f.files.has(markerPath)).toBe(false);expect(f.files.has('objects/unselected')).toBe(true);expect(JSON.parse(Buffer.from(f.files.get(bundle.marker.manifestPath)!).toString()).kind).toBe('heed-deleted-revision');});
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('equivalent iCloud fences require another exact confirmed intent and never overwrite its descriptor',async()=>{const {makeBundle,portableMeeting,encode}=await import('../portable-schema');const f=fixture(2),bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting({id:'synthetic',title:'Synthetic equivalent intent',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Confirmed exact metadata',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true},randomUUID()),[]),otherJob=randomUUID(),artifact={path:bundle.marker.manifestPath,bytes:encode(bundle.manifest).length,sha256:bundle.marker.manifestHash},revision={libraryId:bundle.manifest.libraryId,meetingId:bundle.manifest.meetingId,revisionId:bundle.manifest.revisionId,manifestHash:bundle.marker.manifestHash,parents:bundle.manifest.parents},fence={kind:'heed-deleted-revision' as const,version:1 as const,jobId:otherJob,destinationId,revision,artifact},record={version:1,jobId:otherJob,destinationId,revisions:[revision],artifacts:[artifact]};f.files.set(artifact.path,encode(fence));f.files.set(`control/deletions/${otherJob}.json`,encode(record));const expected={...fence,jobId:randomUUID()};await f.provider.withTransaction({operationId:expected.jobId,deviceId:randomUUID(),kind:'delete'},async tx=>{await tx.writeFence(expected);expect(f.files.get(artifact.path)).toEqual(encode(fence));f.files.set(`control/deletions/${otherJob}.json`,encode({...record,artifacts:[{...artifact,bytes:artifact.bytes+1}]}));await expect(tx.writeFence(expected)).rejects.toThrow();expect(f.files.get(artifact.path)).toEqual(encode(fence));});});

test('QA native observer is bounded before launch and cancellation waits for actual helper stop',async()=>{
 const {MacCloudNative}=await import('./icloud-folder');const {existsSync}=await import('node:fs');const root=mkdtempSync(join(tmpdir(),'heed-cloud-qa-protocol-')),helper=join(root,'helper'),started=join(root,'pid');const controller=new AbortController();let pending:Promise<unknown>|undefined;
 try{
  writeFileSync(helper,`#!${process.execPath}\nprocess.on('SIGTERM',()=>{});let input='';for await(const x of Bun.stdin.stream()){input+=Buffer.from(x);if(input.includes('\\n'))break;}const r=JSON.parse(input);if(r.action!=='qa-observe-parent')process.exit(2);await Bun.write(${JSON.stringify(started)},String(process.pid));setInterval(()=>{},1000);\n`,{mode:0o700});
  const native=new MacCloudNative(helper),binding={bookmark:'YQ==',account:'Yg==',identity:'1:2'};
  await expect(native.acceptance({action:'qa-create-child',binding,connectionGeneration:'fixture',spec:{oversize:'x'.repeat(150000)},workspace:{},selectedScope:'parent'})).rejects.toThrow();expect(existsSync(started)).toBe(false);
  pending=native.acceptance({action:'qa-observe-parent',binding},controller.signal);const deadline=Date.now()+3000;while(!existsSync(started)&&Date.now()<deadline)await Bun.sleep(10);expect(existsSync(started)).toBe(true);const pid=Number(readFileSync(started,'utf8'));controller.abort();let error:any;try{await pending;}catch(e){error=e;}expect(error?.guardianStopped).toBe(true);expect(()=>process.kill(pid,0)).toThrow();
 }finally{controller.abort();await pending?.catch(()=>{});rmSync(root,{recursive:true});}
});

test('original private root is private request input and invalid restrictions refuse before native calls',async()=>{
 const f=fixture(),expected={device:'1',inode:'2',birthMilliseconds:'3'},binding={bookmark:'YQ==',account:'Yg==',identity:'1:2'};
 const p=new ICloudFolderProvider(id,'Fixture',binding,destinationId,f.native,undefined,1,'generation','/private/owned-app',undefined,expected);
 const issued={...expected};expected.inode='99';await p.writeImmutable('objects/a',Buffer.from('synthetic'));expect(f.calls.length).toBeGreaterThan(0);for(const c of f.calls){expect(c.originalPrivateRoot).toEqual(issued);expect(c.privateRoot).toBe('/private/owned-app');}
 const before=f.calls.length;
 for(const invalid of [null,false,{}, {...expected,inode:'2\n'}, {...expected,device:'-1'}, {...expected,inode:2}, {...expected,extra:'4'}, {...expected,birthMilliseconds:'1'.repeat(31)}])expect(()=>new ICloudFolderProvider(id,'Fixture',binding,destinationId,f.native,undefined,1,'generation','/private/owned-app',undefined,invalid as any)).toThrow();
 expect(()=>new ICloudFolderProvider(id,'Fixture',binding,destinationId,f.native,undefined,1,'generation',undefined,undefined,expected)).toThrow();expect(f.calls).toHaveLength(before);
 const ordinary=fixture();await ordinary.provider.writeImmutable('objects/a',Buffer.from('synthetic'));for(const c of ordinary.calls)expect(Object.hasOwn(c,'originalPrivateRoot')).toBe(false);
});
