import {test,expect} from 'bun:test';
import {createHash,randomUUID} from 'node:crypto';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {PortableLibrary} from '../portable-library';import {SessionTags} from '../session-tags';import {ManagedQuota,MIN_MANAGED_LIMIT} from '../managed-quota';
import {ICloudFolderProvider,cloudBinding,cloudHeader,type CloudNative,type CloudRequest} from './icloud-folder';
const id=randomUUID(), destinationId=randomUUID();
const sha=(value:Uint8Array)=>createHash('sha256').update(value).digest('hex');
function fixture(){const files=new Map<string,Uint8Array>();const calls:CloudRequest[]=[];let status:any={ubiquitous:true,uploaded:true,state:'system-reported-uploaded',remoteChecksumVerified:false};const native:CloudNative={async json(request){calls.push(request);if(request.action==='probe')return {header:{format:'heed-portable-library',schemaVersion:1,destinationId},remoteChecksumVerified:false};if(request.action==='list')return [...files.keys()].filter(p=>p.startsWith('commits/'));if(request.action==='watch')return status;return {};},async *stream(request){calls.push(request);const bytes=files.get(request.path!);if(!bytes)throw Error('pending hydration');yield bytes;},async write(request,source){calls.push(request);const chunks:Uint8Array[]=[];for await(const chunk of source)chunks.push(chunk);const bytes=Buffer.concat(chunks);if(bytes.length!==request.bytes||sha(bytes)!==request.sha256)throw Error('integrity');const old=files.get(request.path!);if(old&&sha(old)!==sha(bytes))throw Error('conflict');files.set(request.path!,bytes);}};const provider=new ICloudFolderProvider(id,'Fixture',{bookmark:'YQ==',account:'Yg==',identity:'1:2'},destinationId,native);return {provider,native,files,calls,status,setStatus(value:any){status=value;}};}
test('system uploaded state is local-only and cannot release pending private data',async()=>{const f=fixture();const marker={schemaVersion:1,libraryId:randomUUID(),meetingId:randomUUID(),revisionId:randomUUID(),deviceId:randomUUID(),manifestPath:'',manifestHash:'0'.repeat(64)} as any;marker.manifestPath=`meetings/${marker.meetingId}/revisions/${marker.revisionId}/manifest.json`;await f.provider.writeImmutable(`commits/${marker.deviceId}/${marker.revisionId}.json`,Buffer.from(JSON.stringify(marker)));expect(await f.provider.confirm(marker)).toBe('local-only');expect(f.calls.some(c=>c.action==='watch')).toBe(true);f.setStatus({...f.status,errorCode:4354});await expect(f.provider.confirm(marker)).rejects.toThrow();});
test('bounded stream validates checksum before native publication and immutable writes reject conflicts',async()=>{const f=fixture(),bytes=Buffer.from('synthetic');await f.provider.writeObjectImmutable(`objects/${sha(bytes)}`,bytes.length,sha(bytes),(async function*(){yield bytes;})());expect(Buffer.from(await f.provider.read(`objects/${sha(bytes)}`,bytes.length)).toString()).toBe('synthetic');await expect(f.provider.writeObjectImmutable(`objects/${'0'.repeat(64)}`,bytes.length,'0'.repeat(64),(async function*(){yield bytes;})())).rejects.toThrow();expect(f.files.has(`objects/${'0'.repeat(64)}`)).toBe(false);await expect(f.provider.writeImmutable(`objects/${sha(bytes)}`,Buffer.from('changed'))).rejects.toThrow();expect(f.calls.find(c=>c.action==='hydrate')?.maxBytes).toBe(bytes.length);expect(f.calls.findIndex(c=>c.action==='hydrate')).toBeLessThan(f.calls.findIndex(c=>c.action==='read'));});
test('incomplete hydration, scoped traversal and invalid descriptors never complete discovery',async()=>{const f=fixture();await expect(f.provider.read('objects/missing',100)).rejects.toThrow();await expect(f.provider.read('objects/../escape',100)).rejects.toThrow();f.files.set(`commits/${randomUUID()}/${randomUUID()}.json`,Buffer.from('{}'));await expect(f.provider.list(null,100)).rejects.toThrow();expect(()=>cloudHeader({format:'other',schemaVersion:1,destinationId})).toThrow();expect(()=>cloudBinding({bookmark:'YQ==',account:'Yg==',identity:'1:2',token:'private'})).toThrow();});

test('two isolated catalogs import complete local-only publications while quota protects the first audio copy',async()=>{
 const f=fixture(),root=mkdtempSync(join(tmpdir(),'heed-icloud-roundtrip-'));
 try{
 const create=(device:string)=>{const base=join(root,device),sessionsDir=join(base,'sessions'),recordingsDir=join(base,'recordings'),libraryRoot=join(base,'library');mkdirSync(sessionsDir,{recursive:true});mkdirSync(recordingsDir);const sessions=new SessionTags(sessionsDir);let library:PortableLibrary;const quota=new ManagedQuota({ledgerPath:join(base,'quota.json'),roots:{text:[sessionsDir,join(libraryRoot,'catalog')],media:[recordingsDir,join(libraryRoot,'media')],staging:[join(libraryRoot,'staging')],indexes:[join(libraryRoot,'indexes')]},getLimit:()=>3_000_000,setLimit:()=>{},protectedPaths:()=>library?.protectedPaths()||[]});library=new PortableLibrary({root:libraryRoot,sessions,sessionsDir,recordingsDir,quota,provider:f.provider});return {sessions,library,quota,recordingsDir};};
 const a=create('a'),b=create('b');const audio=Buffer.alloc(1_200_000);audio.write('RIFF');audio.write('WAVE',8);const wav=join(a.recordingsDir,'synthetic.wav');writeFileSync(wav,audio);a.sessions.create({id:'synthetic',title:'Planning',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Approved synthetic review',segments:[],speakers:[],tags:['Review'],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true,files:{wav}});const queued=await a.library.queueLocal('synthetic');await a.library.publish(queued.revisionId);expect(a.library.snapshot().previews[0]?.state).toBe('pending');expect(()=>a.quota.preview(MIN_MANAGED_LIMIT)).toThrow();await b.library.discover();expect(b.sessions.snapshot().sessions).toHaveLength(0);const readAudioBefore=f.calls.filter(c=>c.action==='read'&&c.path?.startsWith('objects/')).length;await b.library.importSelected();expect(b.sessions.snapshot().sessions[0]?.transcript).toBe('Approved synthetic review');expect(f.calls.filter(c=>c.action==='read'&&c.path?.startsWith('objects/')).length).toBe(readAudioBefore);const imported=b.sessions.snapshot().sessions[0]!;const localAudio=await b.library.requestAudio(imported.id);expect(readFileSync(localAudio)).toEqual(audio);a.sessions.save({...a.sessions.read('synthetic')!,title:'Branch A'});const edited=await a.library.queueLocal('synthetic');await a.library.publish(edited.revisionId);b.sessions.save({...b.sessions.read(imported.id)!,title:'Branch B'});await b.library.discover();await b.library.importSelected();expect(b.sessions.read(imported.id)?.title).toBe('Branch B');expect(b.library.snapshot().previews.some(p=>p.state==='conflict')).toBe(true);expect(f.files.has(`objects/${sha(audio)}`)).toBe(true);
 const blocked=create('blocked');blocked.library.selectProvider(f.provider);await blocked.library.discover();const beforeBlocked=f.calls.filter(c=>c.action==='hydrate').length;const limited=new PortableLibrary({root:join(root,'blocked/library'),sessions:blocked.sessions,sessionsDir:join(root,'blocked/sessions'),recordingsDir:blocked.recordingsDir,quota:{reserve(){throw Error('quota-blocked');},release(){}},provider:f.provider});await limited.importSelected();expect(f.calls.filter(c=>c.action==='hydrate').length).toBe(beforeBlocked);expect(blocked.sessions.snapshot().sessions).toHaveLength(0);
 }finally{rmSync(root,{recursive:true,force:true});}
});
