import {test,expect} from 'bun:test';
import {createHash,randomUUID} from 'node:crypto';
import {ICloudFolderProvider,cloudBinding,cloudHeader,type CloudNative,type CloudRequest} from './icloud-folder';
const id=randomUUID(), destinationId=randomUUID();
const sha=(value:Uint8Array)=>createHash('sha256').update(value).digest('hex');
function fixture(){const files=new Map<string,Uint8Array>();const calls:CloudRequest[]=[];let status:any={ubiquitous:true,uploaded:true,state:'system-reported-uploaded',remoteChecksumVerified:false};const native:CloudNative={async json(request){calls.push(request);if(request.action==='probe')return {header:{format:'heed-portable-library',schemaVersion:1,destinationId},remoteChecksumVerified:false};if(request.action==='list')return [...files.keys()].filter(p=>p.startsWith('commits/'));if(request.action==='watch')return status;return {};},async *stream(request){calls.push(request);const bytes=files.get(request.path!);if(!bytes)throw Error('pending hydration');yield bytes;},async write(request,source){calls.push(request);const chunks:Uint8Array[]=[];for await(const chunk of source)chunks.push(chunk);const bytes=Buffer.concat(chunks);if(bytes.length!==request.bytes||sha(bytes)!==request.sha256)throw Error('integrity');const old=files.get(request.path!);if(old&&sha(old)!==sha(bytes))throw Error('conflict');files.set(request.path!,bytes);}};const provider=new ICloudFolderProvider(id,'Fixture',{bookmark:'YQ==',account:'Yg==',identity:'1:2'},destinationId,native);return {provider,files,calls,status,setStatus(value:any){status=value;}};}
test('system uploaded state is local-only and cannot release pending private data',async()=>{const f=fixture();const marker={schemaVersion:1,libraryId:randomUUID(),meetingId:randomUUID(),revisionId:randomUUID(),deviceId:randomUUID(),manifestPath:'',manifestHash:'0'.repeat(64)} as any;marker.manifestPath=`meetings/${marker.meetingId}/revisions/${marker.revisionId}/manifest.json`;await f.provider.writeImmutable(`commits/${marker.deviceId}/${marker.revisionId}.json`,Buffer.from(JSON.stringify(marker)));expect(await f.provider.confirm(marker)).toBe('local-only');expect(f.calls.some(c=>c.action==='watch')).toBe(true);f.setStatus({...f.status,errorCode:4354});await expect(f.provider.confirm(marker)).rejects.toThrow();});
test('bounded stream validates checksum before native publication and immutable writes reject conflicts',async()=>{const f=fixture(),bytes=Buffer.from('synthetic');await f.provider.writeObjectImmutable(`objects/${sha(bytes)}`,bytes.length,sha(bytes),(async function*(){yield bytes;})());expect(Buffer.from(await f.provider.read(`objects/${sha(bytes)}`,bytes.length)).toString()).toBe('synthetic');await expect(f.provider.writeObjectImmutable(`objects/${'0'.repeat(64)}`,bytes.length,'0'.repeat(64),(async function*(){yield bytes;})())).rejects.toThrow();expect(f.files.has(`objects/${'0'.repeat(64)}`)).toBe(false);await expect(f.provider.writeImmutable(`objects/${sha(bytes)}`,Buffer.from('changed'))).rejects.toThrow();expect(f.calls.findIndex(c=>c.action==='hydrate')).toBeLessThan(f.calls.findIndex(c=>c.action==='read'));});
test('incomplete hydration, scoped traversal and invalid descriptors never complete discovery',async()=>{const f=fixture();await expect(f.provider.read('objects/missing',100)).rejects.toThrow();await expect(f.provider.read('objects/../escape',100)).rejects.toThrow();f.files.set(`commits/${randomUUID()}/${randomUUID()}.json`,Buffer.from('{}'));await expect(f.provider.list(null,100)).rejects.toThrow();expect(()=>cloudHeader({format:'other',schemaVersion:1,destinationId})).toThrow();expect(()=>cloudBinding({bookmark:'YQ==',account:'Yg==',identity:'1:2',token:'private'})).toThrow();});
