import {test,expect} from 'bun:test';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {ICloudConnections,icloudResponse} from './icloud-connections';import {cloudUnavailable,type CloudNative,type CloudIssue,type CloudRequest} from './icloud-folder';import {PortableLibrary} from '../portable-library';import {SessionTags} from '../session-tags';import {atomicWriteJson} from '../atomic-json';
const hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
function fixture(){
 const root=mkdtempSync(join(tmpdir(),'heed-cloud-recovery-')),destinationId=randomUUID(),files=new Map<string,Uint8Array>(),calls:CloudRequest[]=[];let fault:{action:string;issue:CloudIssue;pathSuffix?:string}|undefined;const binding={bookmark:'YQ==',account:'Yg==',identity:'1:2'};
 const native:CloudNative={async json(request){calls.push(request);if(fault?.action===request.action&&(!fault.pathSuffix||request.path?.endsWith(fault.pathSuffix)))throw cloudUnavailable(fault.issue);if(request.action==='pick')return binding;if(request.action==='probe')return {header:{format:'heed-portable-library',schemaVersion:1,destinationId},remoteChecksumVerified:false};if(request.action==='list')return [...files.keys()].filter(path=>path.startsWith('commits/'));if(request.action==='watch')return {ubiquitous:true,state:'pending-upload',remoteChecksumVerified:false};return {};},async *stream(request){calls.push(request);if(fault?.action==='read')throw cloudUnavailable(fault.issue);const bytes=files.get(request.path!);if(!bytes)throw cloudUnavailable();yield bytes;},async write(request,source){calls.push(request);if(fault?.action==='write')throw cloudUnavailable(fault.issue);const chunks:Uint8Array[]=[];for await(const chunk of source)chunks.push(chunk);const bytes=Buffer.concat(chunks);if(bytes.length!==request.bytes||hash(bytes)!==request.sha256)throw cloudUnavailable();const old=files.get(request.path!);if(old&&hash(old)!==hash(bytes))throw cloudUnavailable();files.set(request.path!,bytes);}};
 const create=(device:string)=>{const base=join(root,device),sessionsDir=join(base,'sessions'),recordingsDir=join(base,'recordings');mkdirSync(sessionsDir,{recursive:true});mkdirSync(recordingsDir,{recursive:true});const sessions=new SessionTags(sessionsDir),library=new PortableLibrary({root:join(base,'library'),sessions,sessionsDir,recordingsDir,quota:{reserve(){},release(){}}});const options={configPath:join(base,'icloud.json'),jobsPath:join(base,'jobs.json'),library:library as any,native,busy:()=>false,sessions:()=>sessions.snapshot().sessions};return {base,sessions,library,recordingsDir,options,connections:new ICloudConnections(options)};};
 const connect=async(c:ICloudConnections)=>{const selected=await c.select();await c.connect({name:'Synthetic recovery',receipt:selected.receipt,create:false});};
 return {root,files,calls,create,connect,setFault(value:typeof fault){fault=value;},close(){rmSync(root,{recursive:true,force:true});}};
}
for(const [scenario,issue] of [['signed-out','account-unavailable'],['disabled-account','account-unavailable'],['changed-account','account-changed'],['stale-bookmark','bookmark-stale'],['denied-bookmark','permission-denied'],['missing-folder','folder-unavailable']] as const)test(`${scenario} fault preserves the reviewed private binding and pending source across restart`,async()=>{
 const f=fixture();try{let a=f.create('a');await f.connect(a.connections);const wav=join(a.recordingsDir,'synthetic.wav'),audio=Buffer.alloc(1000);audio.write('RIFF');audio.write('WAVE',8);writeFileSync(wav,audio);a.sessions.create({id:'synthetic',title:'Synthetic retained source',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Retained source',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true,files:{wav}});await a.connections.sync();const revision=a.connections.protectedRevisionIds()[0]!,binding=readFileSync(a.options.configPath),journal=readFileSync(a.options.jobsPath);const checkpoint=readFileSync(join(a.base,'library','catalog','state.json'));const commits=[...f.files.keys()].filter(path=>path.startsWith('commits/'));
 f.setFault({action:'probe',issue});const before=f.calls.length;const response=await icloudResponse(new Request('http://localhost:5001/api/icloud',{method:'POST',body:JSON.stringify({action:'preview',connectionId:a.connections.snapshot().connection!.id})}),a.connections);expect(response.status).toBe(503);expect(await response.json()).toMatchObject({issue});expect(a.connections.snapshot().issue).toBe(issue);expect(f.calls.slice(before).some(r=>['write','create'].includes(r.action))).toBe(false);
 a=f.create('a');expect(a.connections.protectedRevisionIds()).toEqual([revision]);expect(a.connections.protectedLocalPaths()).toContain(wav);expect(readFileSync(a.options.configPath)).toEqual(binding);expect(readFileSync(a.options.jobsPath)).toEqual(journal);const beforeState=JSON.parse(checkpoint.toString()),afterState=JSON.parse(readFileSync(join(a.base,'library','catalog','state.json'),'utf8'));expect(afterState.entries).toEqual(beforeState.entries);expect(afterState.heads).toEqual(beforeState.heads);expect(afterState.deviceId).toBe(beforeState.deviceId);expect(existsSync(a.options.configPath+'.transition.json')).toBe(false);expect(hash(readFileSync(wav))).toBe(hash(audio));expect(a.sessions.read('synthetic')?.transcript).toBe('Retained source');f.setFault(undefined);await a.connections.sync();expect(a.connections.protectedRevisionIds()).toEqual([revision]);expect(a.sessions.snapshot().sessions).toHaveLength(1);expect([...f.files.keys()].filter(path=>path.startsWith('commits/'))).toEqual(commits);
 }finally{f.close();}
});
test('delayed payload hydration never exposes a partial meeting and the same reviewed revision imports once after restart',async()=>{
 const f=fixture();try{const a=f.create('a');await f.connect(a.connections);a.sessions.create({id:'synthetic',title:'Synthetic remote',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'pt-BR',transcript:'Texto sintético preservado',segments:[],speakers:[],tags:['QA'],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true});await a.connections.sync();let b=f.create('b');await f.connect(b.connections);const binding=readFileSync(b.options.configPath);f.setFault({action:'hydrate',issue:'hydration-pending',pathSuffix:'/meeting.json'});const before=f.calls.length;await expect(b.connections.previewLibrary()).rejects.toMatchObject({code:'hydration-pending'});expect(b.sessions.snapshot().sessions).toHaveLength(0);expect(b.library.snapshot().complete).toBe(false);expect(f.calls.slice(before).some(r=>['write','create'].includes(r.action))).toBe(false);b=f.create('b');expect(b.sessions.snapshot().sessions).toHaveLength(0);expect(readFileSync(b.options.configPath)).toEqual(binding);f.setFault(undefined);await b.connections.previewLibrary();await b.connections.importReviewed(b.connections.snapshot().preview!.token);expect(b.sessions.snapshot().sessions).toHaveLength(1);expect(b.sessions.snapshot().sessions[0]?.transcript).toBe('Texto sintético preservado');await b.connections.previewLibrary();expect(b.connections.snapshot().preview?.count).toBe(0);expect(b.connections.protectedRevisionIds()).toEqual([]);
 }finally{f.close();}
});
