import {existsSync,readFileSync,lstatSync} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';
import {atomicWriteJson} from '../atomic-json';import {desktopRequestAllowed} from '../desktop-permissions';
import {MacCloudNative,ICloudFolderProvider,cloudBinding,cloudHeader,cloudUnavailable,type CloudBinding,type CloudNative} from './icloud-folder';
interface Connection {id:string;name:string;destinationId:string;binding:CloudBinding;enabled:boolean}
interface Library {hasLocalRevision(revisionId:string):boolean;withMutation?<T>(run:()=>Promise<T>):Promise<T>;withProvider<T>(provider:ICloudFolderProvider,run:(library:Library)=>Promise<T>,signal?:AbortSignal):Promise<T>;snapshot():{localMeetings:{id:string;title:string}[];previews:Array<{revisionId:string;state:string;local:boolean;bytes:number;title:string}>;complete:boolean;error?:string;imported:number;skipped:number};discover(signal?:AbortSignal):Promise<unknown>;importSelected(ids?:string[],signal?:AbortSignal):Promise<unknown>;queueLocal(id:string,signal?:AbortSignal):Promise<{revisionId:string}>;publish(id:string,signal?:AbortSignal):Promise<unknown>}
interface Options {configPath:string;jobsPath:string;library:Library|(()=>Library);native?:CloudNative;busy:()=>boolean;write?:typeof atomicWriteJson;now?:()=>number;providers?:{withMutation?<T>(run:()=>Promise<T>):Promise<T>;preferredId?():string|null;currentId?():string|undefined|null;assertIdle():void;register(id:string,factory:()=>ICloudFolderProvider):void;activate(id:string):void;deactivate(id:string):void;unregister(id:string):void}}
interface Job {revisionId:string;attempts:number;next:number;state:string}
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
function read(path:string,max:number){if(!existsSync(path))return null;if(!lstatSync(path).isFile()||lstatSync(path).size>max)throw cloudUnavailable();return JSON.parse(readFileSync(path,'utf8'));}
function name(value:string){if(typeof value!=='string'||!value.trim()||value.length>80||/[\x00-\x1f\x7f]/.test(value))throw Error('Invalid iCloud library name');return value.trim();}
/** Connections are explicit. Observation and retries cannot connect a private account by themselves. */
export class ICloudConnections {
 private connection:Connection|null=null;private jobs:Job[]=[];private native:CloudNative;private running=false;private controller?:AbortController;
 private receipts=new Map<string,{binding:CloudBinding;destinationId:string|null;time:number}>();private preview:{token:string;ids:string[];bytes:number;count:number;time:number}|null=null;private error:string|null=null;private factories=new Map<string,()=>ICloudFolderProvider>();private mutating=false;
 constructor(private options:Options){this.native=options.native||new MacCloudNative();const config=read(options.configPath,150000);if(config){if(config.version!==1||!('connection' in config))throw cloudUnavailable();const c=config.connection;if(c){if(Object.keys(c).sort().join(',')!=='binding,destinationId,enabled,id,name'||!UUID.test(c.id)||!UUID.test(c.destinationId)||typeof c.enabled!=='boolean'||name(c.name)!==c.name)throw cloudUnavailable();cloudBinding(c.binding);this.connection=c;}}
  const ledger=read(options.jobsPath,4_000_000);if(ledger){if(ledger.version!==1||!Array.isArray(ledger.jobs)||ledger.jobs.length>10000||ledger.jobs.some((j:Job)=>!UUID.test(j.revisionId)||!Number.isSafeInteger(j.attempts)||j.attempts<0||j.attempts>30||!Number.isFinite(j.next)||j.next<0||!['pending-upload','system-reported-uploaded','cloud-full','provider-offline','provider-error'].includes(j.state)))throw cloudUnavailable();this.jobs=ledger.jobs;}if(this.connection?.enabled)this.register(this.connection); }
 private owner(){const value=this.options.library;return typeof value==='function'?value():value;}
 assertConnection(id:string){if(this.connection?.id!==id)throw Error('iCloud library changed; review the current folder before continuing');}
 private async mutate<T>(run:()=>Promise<T>):Promise<T>{if(this.mutating)throw Error('Wait for iCloud settings to finish');this.mutating=true;try{return this.options.providers?.withMutation?await this.options.providers.withMutation(run):this.owner().withMutation?await this.owner().withMutation!(run):await run();}finally{this.mutating=false;}}
 private control(value:Connection|null,activate:()=>void){
  const previous=this.connection?structuredClone(this.connection):null,preview=this.preview,preferred=this.options.providers?.preferredId?.()??null;
  this.saveConnection(value);
  try{activate();}catch(error){
   try{this.saveConnection(previous);this.preview=preview;if(previous)this.register(previous);if(preferred)this.options.providers?.activate(preferred);else if(value)this.options.providers?.deactivate(value.id);if(value&&value.id!==previous?.id){this.options.providers?.unregister(value.id);this.factories.delete(value.id);}}
   catch{this.connection=null;this.error='iCloud settings recovery is required. Retain the private configuration and pending jobs.';throw Error('iCloud settings could not be restored; preserve configuration for recovery');}
   throw error;
  }
 }
 private register(connection:Connection){if(!this.options.providers)return;let factory=this.factories.get(connection.id);if(!factory){factory=()=>{const current=this.connection;if(!current||current.id!==connection.id||!current.enabled)throw cloudUnavailable();return new ICloudFolderProvider(current.id,current.name,current.binding,current.destinationId,this.native);};this.factories.set(connection.id,factory);}this.options.providers.register(connection.id,factory);}
 private idle(){if(this.running||this.options.busy())throw Error('Wait for the active meeting or library operation to finish');this.options.providers?.assertIdle();}
 private now(){return this.options.now?.()??Date.now();}
 private saveConnection(value:Connection|null){(this.options.write||atomicWriteJson)(this.options.configPath,{version:1,connection:value});this.connection=value;this.preview=null;}
 private editJobs(run:(jobs:Job[])=>void){const next=structuredClone(this.jobs);run(next);if(next.length>10000)throw Error('iCloud pending queue limit reached');(this.options.write||atomicWriteJson)(this.options.jobsPath,{version:1,jobs:next});this.jobs=next;}
 protectedRevisionIds(){return this.jobs.map(job=>job.revisionId);}
 snapshot(){const c=this.connection;return {connection:c?{id:c.id,name:c.name,destinationId:c.destinationId,enabled:c.enabled,pending:this.jobs.length,status:this.jobs.some(j=>j.state==='cloud-full')?'cloud-full':this.jobs.some(j=>j.state==='provider-offline')?'provider-offline':this.jobs.length?'pending-upload':'connected',observations:this.jobs.reduce((counts,j)=>({...counts,[j.state]:(counts[j.state]||0)+1}),{} as Record<string,number>)}:null,syncing:this.running,error:this.error,preview:this.preview?{token:this.preview.token,count:this.preview.count,bytes:this.preview.bytes}:null,remoteChecksumVerified:false as const,confirmation:'local-only' as const};}
 async select(){this.idle();const binding=cloudBinding(await this.native.json({action:'pick'}));const probe=await this.native.json({action:'probe',binding}) as any;const header=cloudHeader(probe?.header);if(probe.remoteChecksumVerified!==false)throw cloudUnavailable();for(const [id,r] of this.receipts)if(this.now()-r.time>600000)this.receipts.delete(id);if(this.receipts.size>=16)this.receipts.delete(this.receipts.keys().next().value!);const receipt=randomUUID();this.receipts.set(receipt,{binding,destinationId:header?.destinationId??null,time:this.now()});return {receipt,needsCreation:!header,status:probe.status,confirmation:'local-only'};}
 async connect(input:{name:string;receipt:string;create:boolean}){return this.mutate(()=>this.connectOwned(input));}
 private async connectOwned(input:{name:string;receipt:string;create:boolean}){this.idle();const title=name(input.name),receipt=this.receipts.get(input.receipt);if(!receipt||this.now()-receipt.time>600000)throw Error('Invalid or expired iCloud folder review');if(!receipt.destinationId&&!input.create)throw Error('Confirm creation of an empty iCloud library');const probe=await this.native.json({action:'probe',binding:receipt.binding}) as any;let header=cloudHeader(probe?.header);if((header?.destinationId??null)!==receipt.destinationId)throw Error('iCloud destination changed after review');this.idle();if(!header){const destinationId=randomUUID();header=cloudHeader(await this.native.json({action:'create',binding:receipt.binding,destinationId}));if(header?.destinationId!==destinationId)throw cloudUnavailable();}this.idle();const old=this.connection;this.control({id:randomUUID(),name:title,destinationId:header!.destinationId,binding:receipt.binding,enabled:true},()=>{if(old)this.options.providers?.unregister(old.id);this.register(this.connection!);this.options.providers?.activate(this.connection!.id);});this.receipts.delete(input.receipt);this.error=null;return this.snapshot();}
 async rename(value:string,id?:string){return this.mutate(async()=>{this.idle();if(id)this.assertConnection(id);if(!this.connection)throw Error('iCloud library not connected');const previous=this.connection;this.control({...previous,name:name(value)},()=>{if(this.options.providers?.currentId?.()===previous.id)this.options.providers.activate(previous.id);});return this.snapshot();});}
 async enable(enabled:boolean,id?:string){return this.mutate(async()=>{this.idle();if(id)this.assertConnection(id);if(!this.connection)throw Error('iCloud library not connected');const current=this.connection;this.control({...current,enabled},()=>{if(enabled){this.register(this.connection!);this.options.providers?.activate(current.id);}else this.options.providers?.deactivate(current.id);});return this.snapshot();});}
 async disconnect(id?:string){return this.mutate(async()=>{this.idle();if(id)this.assertConnection(id);const old=this.connection;this.control(null,()=>{if(old)this.options.providers?.unregister(old.id);});this.receipts.clear();this.error=null;return this.snapshot();});}
 private provider(){const c=this.connection;if(!c?.enabled)throw Error('iCloud library is disabled or disconnected');return new ICloudFolderProvider(c.id,c.name,c.binding,c.destinationId,this.native);}
 private review(library:Library){const snapshot=library.snapshot();if(!snapshot.complete||snapshot.error)throw cloudUnavailable();const eligible=snapshot.previews.filter(p=>!p.local&&p.state!=='conflict');const ids=eligible.map(p=>p.revisionId).sort(),bytes=eligible.reduce((sum,p)=>sum+p.bytes,0);const token=createHash('sha256').update(JSON.stringify({destination:this.connection?.destinationId,ids,bytes})).digest('hex');return {token,ids,bytes,count:ids.length,time:this.now()};}
 private async operation(run:(library:Library,provider:ICloudFolderProvider,signal:AbortSignal)=>Promise<void>,expectedId?:string,requestSignal?:AbortSignal){if(expectedId)this.assertConnection(expectedId);requestSignal?.throwIfAborted();if(this.running||this.options.busy())throw Error('Wait for the active meeting or library operation to finish');const provider=this.provider();this.running=true;const controller=this.controller=new AbortController();const abort=()=>controller.abort();requestSignal?.addEventListener('abort',abort,{once:true});try{await this.owner().withProvider(provider,library=>run(library,provider,controller.signal),controller.signal);this.error=null;}catch(error){this.error='iCloud operation pending. Check sign-in, folder permissions, downloads, cloud space and the local quota; then retry.';throw error;}finally{requestSignal?.removeEventListener('abort',abort);this.running=false;this.controller=undefined;}return this.snapshot();}
 previewLibrary(id?:string,signal?:AbortSignal){return this.operation(async(library,_p,signal)=>{await library.discover(signal);this.preview=this.review(library);},id,signal);}
 importReviewed(token:string,id?:string,signal?:AbortSignal){return this.operation(async(library,_p,signal)=>{const previous=this.preview;if(!previous||previous.token!==token||this.now()-previous.time>600000)throw Error('iCloud import preview expired');await library.discover(signal);const current=this.review(library);if(current.token!==token)throw Error('iCloud import preview changed; review it again');await library.importSelected(current.ids,signal);this.preview=this.review(library);},id,signal);}
 sync(id?:string,force=true,signal?:AbortSignal){return this.operation(async(library,provider,signal)=>{const snapshot=library.snapshot();for(const local of snapshot.localMeetings.slice(0,10000)){signal.throwIfAborted();if(this.options.busy())break;const revision=await library.queueLocal(local.id,signal);this.editJobs(jobs=>{if(!jobs.some(j=>j.revisionId===revision.revisionId))jobs.push({revisionId:revision.revisionId,attempts:0,next:0,state:'pending-upload'});});}for(const job of [...this.jobs]){signal.throwIfAborted();if(!library.hasLocalRevision(job.revisionId)){this.editJobs(jobs=>{const index=jobs.findIndex(j=>j.revisionId===job.revisionId);if(index>=0)jobs.splice(index,1);});continue;}if(this.options.busy())break;if(!force&&job.next>this.now())continue;await library.publish(job.revisionId,signal);const observation=provider.statusFor(job.revisionId);const failed=library.snapshot().previews.find(p=>p.revisionId===job.revisionId)?.state==='unavailable';const state=observation&&['system-reported-uploaded','cloud-full','provider-offline','provider-error'].includes(observation.state)?observation.state:failed?'provider-error':'pending-upload';this.editJobs(jobs=>{const saved=jobs.find(j=>j.revisionId===job.revisionId)!;saved.attempts=Math.min(30,saved.attempts+1);saved.next=this.now()+Math.min(86_400_000,30000*2**Math.min(saved.attempts,12));saved.state=state;});}},id,signal);}
 close(){this.controller?.abort();}
}
export async function icloudResponse(request:Request,connections:ICloudConnections):Promise<Response>{
 if(!desktopRequestAllowed(request,new URL(request.url).port))return Response.json({error:'iCloud controls are only available from this Mac'},{status:403});if(request.method==='GET')return Response.json(connections.snapshot());if(request.method!=='POST')return new Response(null,{status:405});
 try{if(Number(request.headers.get('content-length'))>16384)throw Error('Invalid iCloud request');const text=await request.text();if(text.length>16384)throw Error('Invalid iCloud request');const body=JSON.parse(text);const fields:Record<string,string[]>={select:['action'],connect:['action','name','receipt','create'],rename:['action','name','connectionId'],enable:['action','enabled','connectionId'],disconnect:['action','connectionId'],preview:['action','connectionId'],import:['action','token','connectionId'],sync:['action','connectionId']};if(!body||typeof body!=='object'||Array.isArray(body)||!fields[body.action]||Object.keys(body).some(key=>!fields[body.action]!.includes(key)))throw Error('Invalid iCloud request');if(['rename','enable','disconnect','preview','import','sync'].includes(body.action)){if(typeof body.connectionId!=='string'||!UUID.test(body.connectionId))throw Error('Invalid iCloud request');connections.assertConnection(body.connectionId);}switch(body.action){case 'select':return Response.json(await connections.select());case 'connect':if(typeof body.name!=='string'||typeof body.receipt!=='string'||!UUID.test(body.receipt)||typeof body.create!=='boolean')throw Error('Invalid iCloud request');return Response.json(await connections.connect(body));case 'rename':if(typeof body.name!=='string')throw Error('Invalid iCloud request');return Response.json(await connections.rename(body.name,body.connectionId));case 'enable':if(typeof body.enabled!=='boolean')throw Error('Invalid iCloud request');return Response.json(await connections.enable(body.enabled,body.connectionId));case 'disconnect':return Response.json(await connections.disconnect(body.connectionId));case 'preview':return Response.json(await connections.previewLibrary(body.connectionId,request.signal));case 'import':if(typeof body.token!=='string'||! /^[a-f0-9]{64}$/.test(body.token))throw Error('Invalid iCloud request');return Response.json(await connections.importReviewed(body.token,body.connectionId,request.signal));case 'sync':return Response.json(await connections.sync(body.connectionId,true,request.signal));}}catch(error){const message=error instanceof Error?error.message:'';const safe=/^Invalid|^Wait for|^Confirm creation|^iCloud (library|pending queue|import preview|destination changed)/.test(message);return Response.json({error:safe?message:'iCloud operation unavailable. Check sign-in, access, downloads, cloud space and the local quota.'},{status:/^Invalid/.test(message)?400:/Wait for|expired|changed|Confirm creation/.test(message)?409:503});}return new Response(null,{status:400});
}
