import {symlinkSync,truncateSync} from 'node:fs';
import {afterEach,expect,test} from 'bun:test';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';import {OneDriveStore} from './onedrive-store';import {atomicWriteJson} from '../atomic-json';
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});const binding={connectionId:randomUUID(),driveId:'drive-fixture',appRootId:'approot-fixture',rootId:'library-fixture',destinationId:randomUUID(),name:'Synthetic library',accountType:'personal' as const};
function fixture(write=atomicWriteJson){const root=mkdtempSync(join(tmpdir(),'heed-ms-store-'));roots.push(root);const options={path:join(root,'state.json'),binding,write};return {options,store:new OneDriveStore(options)};}
const item=(id:string,name:string)=>({id,name,parentId:'library-fixture',driveId:'drive-fixture',size:12,etag:'"one"',folder:false,deleted:false});
test('delta candidate is durable but checkpoint remains old until complete local acknowledgment',()=>{const f=fixture(),generation=f.store.begin(true);f.store.stage(generation,{one:item('one','first')},'https://graph.microsoft.com/v1.0/drives/drive-fixture/items/library-fixture/delta?next=2',undefined);expect(new OneDriveStore(f.options).pending()?.next).toContain('next=2');expect(f.store.checkpoint()).toBeUndefined();expect(()=>f.store.acknowledge(generation)).toThrow('incomplete');f.store.stage(generation,{one:item('one','last')},undefined,'https://graph.microsoft.com/v1.0/drives/drive-fixture/items/library-fixture/delta?token=last');f.store.acknowledge(generation);const restart=new OneDriveStore(f.options);expect(restart.items().one?.name).toBe('last');expect(restart.checkpoint()).toContain('token=last');expect(restart.pending()).toBeUndefined();});
test('failed checkpoint persistence preserves candidate for idempotent replay',()=>{let fail=false;const f=fixture((path,value)=>{if(fail)throw new Error('Quota full');atomicWriteJson(path,value);});const generation=f.store.begin(true);f.store.stage(generation,{one:item('one','data')},undefined,'https://graph.microsoft.com/v1.0/drives/drive-fixture/items/library-fixture/delta?token=last');fail=true;expect(()=>f.store.acknowledge(generation)).toThrow('Quota');expect(new OneDriveStore({...f.options,write:atomicWriteJson}).pending()?.id).toBe(generation);fail=false;f.store.acknowledge(generation);expect(f.store.items().one?.name).toBe('data');});
test('drive/root/destination identity replacement and unbounded indexes fail closed',()=>{const f=fixture();f.store.begin(true);expect(()=>new OneDriveStore({...f.options,binding:{...binding,rootId:'replacement'}})).toThrow('changed');expect(()=>f.store.record(item('x','../escape'))).toThrow('Invalid');expect(()=>f.store.record({...item('x','x'),driveId:'other-drive'})).toThrow('Invalid');const generation=f.store.pending()!.id;const enormous=Object.fromEntries(Array.from({length:20001},(_,i)=>[String(i),item(String(i),'item')]));expect(()=>f.store.stage(generation,enormous,undefined,'https://graph.microsoft.com/v1.0/drives/drive-fixture/items/library-fixture/delta?token=last')).toThrow('limit');});
test('upload journal persists only opaque URL references, fixed identity and progress',()=>{const f=fixture(),path='objects/'+'a'.repeat(64),secretRef=randomUUID();f.store.upload(path,{bytes:20,hash:'a'.repeat(64),offset:0,secretRef,expiresAt:12345,parentId:'parent',name:'a'.repeat(64),state:'uploading'});const restart=new OneDriveStore(f.options);expect(restart.uploadJob(path)?.secretRef).toBe(secretRef);expect(readFileSync(f.options.path,'utf8')).not.toContain('https://upload');expect(()=>f.store.upload(path,{...restart.uploadJob(path)!,hash:'b'.repeat(64)})).toThrow('changed');});

test('completed upload history stays bounded without pruning active jobs or credential cleanup references',()=>{const f=fixture((()=>{}) as typeof atomicWriteJson),active='objects/'+'f'.repeat(64),secret='objects/'+'e'.repeat(64);const job={bytes:20,hash:'a'.repeat(64),offset:20,parentId:'parent',name:'data',state:'verified' as const};f.store.upload(active,{...job,state:'uploading',offset:0});f.store.upload(secret,{...job,secretRef:randomUUID()});for(let i=0;i<1100;i++)f.store.upload('objects/'+i.toString(16).padStart(64,'0'),job);expect(f.store.uploadJob(active)?.state).toBe('uploading');expect(f.store.uploadJob(secret)?.secretRef).toBeDefined();expect(f.store.uploadJob('objects/'+(1099).toString(16).padStart(64,'0'))?.state).toBe('verified');});

test('private transfer state rejects actual symlinks and oversized files',()=>{const f=fixture();f.store.begin();const alias=join(require('node:path').dirname(f.options.path),'alias.json');symlinkSync(f.options.path,alias);expect(()=>new OneDriveStore({...f.options,path:alias})).toThrow('Invalid private');truncateSync(f.options.path,32000001);expect(()=>new OneDriveStore(f.options)).toThrow('Invalid private');});
