import {readPrivateJson} from './private-json';
import {randomUUID} from 'node:crypto';import {existsSync,mkdirSync} from 'node:fs';import {dirname} from 'node:path';import {atomicWriteJson} from '../atomic-json';import {providerPath} from '../portable-provider';import {UUID} from '../portable-schema';
export const GRAPH='https://graph.microsoft.com/v1.0';export const GRAPH_ID=/^[A-Za-z0-9!_-]{1,256}$/;
import type {OneDriveBinding} from '@heed/shared';export type {OneDriveBinding} from '@heed/shared';
export interface OneDriveItem {id:string;name:string;parentId?:string;driveId:string;size:number;etag?:string;folder:boolean;deleted:boolean}
export interface OneDriveUpload {bytes:number;hash:string;offset:number;secretRef?:string;expiresAt?:number;parentId:string;name:string;state:'uploading'|'provider-confirmed'|'verified';itemId?:string}
interface Candidate {id:string;items:Record<string,OneDriveItem>;next?:string;delta?:string}
interface State {version:1;binding:OneDriveBinding;items:Record<string,OneDriveItem>;checkpoint?:string;candidate?:Candidate;uploads:Record<string,OneDriveUpload>}
interface Options {path:string;binding:OneDriveBinding;write?:typeof atomicWriteJson}
const safeName=(name:unknown):name is string=>typeof name==='string'&&name.length>0&&name.length<=256&&name!=='.'&&name!=='..'&&!/[\/\\\u0000]/.test(name);
export function deltaUrl(binding:OneDriveBinding,value:string):string{const url=new URL(value),expected=`/v1.0/drives/${binding.driveId}/items/${binding.rootId}/delta`;if(value.length>16384||url.protocol!=='https:'||url.hostname!=='graph.microsoft.com'||url.port||url.username||url.password||url.hash||url.pathname!==expected)throw new Error('Invalid scoped OneDrive continuation');return url.toString();}
function validItem(item:OneDriveItem,binding:OneDriveBinding){if(!item||!GRAPH_ID.test(item.id)||item.driveId!==binding.driveId||!safeName(item.name)||(item.parentId!==undefined&&!GRAPH_ID.test(item.parentId))||!Number.isSafeInteger(item.size)||item.size<0||item.size>8_000_000_000_000||typeof item.folder!=='boolean'||typeof item.deleted!=='boolean'||(item.etag!==undefined&&(typeof item.etag!=='string'||item.etag.length>1024)))throw new Error('Invalid OneDrive item metadata');}
/** Indexes and transfer journals are quota-managed; preauthenticated URLs remain opaque vault refs. */
export class OneDriveStore {
 private state:State;
 constructor(private options:Options){if(!UUID.test(options.binding.connectionId)||!UUID.test(options.binding.destinationId)||![options.binding.driveId,options.binding.appRootId,options.binding.rootId].every(id=>GRAPH_ID.test(id)))throw new Error('Invalid OneDrive library binding');mkdirSync(dirname(options.path),{recursive:true,mode:0o700});this.state=existsSync(options.path)?readPrivateJson<State>(options.path,32000000):{version:1,binding:options.binding,items:{},uploads:{}};if(this.state.version!==1||!this.state.binding||['connectionId','driveId','appRootId','rootId','destinationId'].some(key=>this.state.binding[key as keyof OneDriveBinding]!==options.binding[key as keyof OneDriveBinding]))throw new Error('OneDrive destination identity changed; preserve pending jobs');this.validate(this.state);}
 private validate(next:State){const check=(items:Record<string,OneDriveItem>)=>{if(!items||typeof items!=='object'||Array.isArray(items)||Object.keys(items).length>20000)throw new Error('OneDrive metadata limit reached');for(const [id,item] of Object.entries(items)){validItem(item,this.options.binding);if(id!==item.id)throw new Error('Invalid OneDrive item identity');}};check(next.items);if(next.checkpoint)deltaUrl(this.options.binding,next.checkpoint);if(next.candidate){if(!UUID.test(next.candidate.id))throw new Error('Invalid OneDrive candidate');check(next.candidate.items);if(next.candidate.next)deltaUrl(this.options.binding,next.candidate.next);if(next.candidate.delta)deltaUrl(this.options.binding,next.candidate.delta);if(next.candidate.next&&next.candidate.delta)throw new Error('Invalid OneDrive checkpoint');}if(!next.uploads||typeof next.uploads!=='object'||Array.isArray(next.uploads)||Object.keys(next.uploads).length>1024)throw new Error('OneDrive upload journal limit reached');for(const [path,job] of Object.entries(next.uploads)){providerPath(path);if(!job||!Number.isSafeInteger(job.bytes)||job.bytes<1||job.bytes>8_000_000_000_000||!/^[a-f0-9]{64}$/.test(job.hash)||!Number.isSafeInteger(job.offset)||job.offset<0||job.offset>job.bytes||!GRAPH_ID.test(job.parentId)||!safeName(job.name)||(job.secretRef!==undefined&&!UUID.test(job.secretRef))||(job.expiresAt!==undefined&&(!Number.isSafeInteger(job.expiresAt)||job.expiresAt<0))||!['uploading','provider-confirmed','verified'].includes(job.state)||(job.itemId!==undefined&&!GRAPH_ID.test(job.itemId)))throw new Error('Invalid OneDrive upload journal');}if(Buffer.byteLength(JSON.stringify(next))>32_000_000)throw new Error('OneDrive metadata limit reached');}
 private edit(run:(state:State)=>void){const next=structuredClone(this.state);run(next);this.validate(next);(this.options.write||atomicWriteJson)(this.options.path,next);this.state=next;}
 binding():OneDriveBinding{return structuredClone(this.state.binding);}
 checkpoint():string|undefined{return this.state.checkpoint;}
 pending():Candidate|undefined{return this.state.candidate?structuredClone(this.state.candidate):undefined;}
 items():Record<string,OneDriveItem>{return structuredClone(this.state.candidate?.items||this.state.items);}
 begin(full=false):string{const id=randomUUID();this.edit(next=>{next.candidate={id,items:full?{}:structuredClone(next.items)};});return id;}
 stage(id:string,items:Record<string,OneDriveItem>,nextUrl?:string,delta?:string):void{if(this.state.candidate?.id!==id)throw new Error('OneDrive candidate changed');this.edit(next=>{next.candidate={id,items:structuredClone(items),next:nextUrl,delta};});}
 acknowledge(id:string):void{if(this.state.candidate?.id!==id||!this.state.candidate.delta||this.state.candidate.next)throw new Error('OneDrive discovery is incomplete');this.edit(next=>{next.items=next.candidate!.items;next.checkpoint=next.candidate!.delta;delete next.candidate;});}
 record(item:OneDriveItem):void{this.edit(next=>{next.items[item.id]=item;if(next.candidate)next.candidate.items[item.id]=item;});}
 uploadJob(path:string):OneDriveUpload|undefined{const job=this.state.uploads[providerPath(path)];return job?structuredClone(job):undefined;}
 upload(path:string,job:OneDriveUpload):void{providerPath(path);const old=this.state.uploads[path];if(old&&(old.hash!==job.hash||old.bytes!==job.bytes||old.parentId!==job.parentId||old.name!==job.name))throw new Error('Immutable OneDrive upload identity changed');this.edit(next=>{next.uploads[path]=job;const completed=Object.keys(next.uploads).filter(key=>key!==path&&next.uploads[key]!.state==='verified'&&!next.uploads[key]!.secretRef);while(Object.keys(next.uploads).length>512&&completed.length)delete next.uploads[completed.shift()!];});}
 removeUpload(path:string):void{this.edit(next=>{delete next.uploads[providerPath(path)];});}
 uploadRefs():string[]{return Object.values(this.state.uploads).flatMap(job=>job.secretRef?[job.secretRef]:[]);}
}
