import {randomUUID} from 'node:crypto';import type {SecretVault} from './keychain-vault';import {GRAPH,type OneDriveBinding} from './onedrive-store';
/** Synthetic Graph semantics only; no real account, URL or credential is used. */
export class OneDriveFixture {
 binding:OneDriveBinding={connectionId:randomUUID(),driveId:'drive',appRootId:'app',rootId:'root',destinationId:randomUUID(),name:'Synthetic library',accountType:'personal'};
 items=new Map<string,any>();contents=new Map<string,Buffer>();secrets=new Map<string,any>();sessions=new Map<string,{parent:string;name:string;bytes?:number;data:Buffer}>();ranges:string[]=[];methods:string[]=[];lostFinal=false;force416=false;expired=false;corruptDownload=false;denyDelta=false;denyUpload=false;etagConflict=false;
 vault:SecretVault={put:async(value,reference=randomUUID())=>{this.secrets.set(reference,value);return reference;},get:async<T>(ref:string)=>this.secrets.get(ref) as T||null,remove:async(ref)=>{this.secrets.delete(ref);}};
 constructor(){this.items.set('app',{id:'app',name:'Heed',folder:{},size:0,parentReference:{driveId:'drive',id:'outside'},eTag:'"app"'});this.items.set('root',{id:'root',name:'Library',folder:{},size:0,parentReference:{driveId:'drive',id:'app'},eTag:'"root"'});this.file('root','library.json',Buffer.from(JSON.stringify({format:'heed-portable-library',schemaVersion:1,destinationId:this.binding.destinationId})));}
 file(parent:string,name:string,bytes:Buffer){const id=randomUUID(),item={id,name,file:{},size:bytes.length,parentReference:{driveId:'drive',id:parent},eTag:`"${id}"`};this.items.set(id,item);this.contents.set(id,bytes);return item;}
 folder(parent:string,name:string){const existing=[...this.items.values()].find(i=>i.parentReference?.id===parent&&i.name===name);if(existing)return existing;const id=randomUUID(),item={id,name,folder:{},size:0,parentReference:{driveId:'drive',id:parent},eTag:`"${id}"`};this.items.set(id,item);return item;}
 put(path:string,bytes:Buffer){const parts=path.split('/');let parent='root';for(const name of parts.slice(0,-1))parent=this.folder(parent,name).id;return this.file(parent,parts.at(-1)!,bytes);}
 lookup(parent:string,path:string){let result=this.items.get(parent);for(const name of path.split('/')){result=[...this.items.values()].find(i=>i.parentReference?.id===result?.id&&i.name===name);if(!result)return;}return result;}
 private metadata(item:any){return {...item,...(item.file?{'@microsoft.graph.downloadUrl':`https://synthetic.files.1drv.com/content/${item.id}?opaque=synthetic-private-url`}:{})};}
 request=async(url:string,init:RequestInit={})=>{const target=new URL(url),path=decodeURIComponent(target.pathname);this.methods.push(`${init.method||'GET'} ${path}`);if(path==='/v1.0/me/drive/special/approot')return Response.json(this.metadata(this.items.get('app')));if(path==='/v1.0/me/drive')return Response.json({id:'drive',driveType:'personal',quota:{total:1000000000,remaining:900000000}});if(path.endsWith('/delta')){if(this.denyDelta)return Response.json({}, {status:403});return Response.json({value:[...this.items.values()].filter(item=>item.id!=='app'),'@odata.deltaLink':`${GRAPH}/drives/drive/items/root/delta?token=complete`});}const byPath=/\/items\/([^/]+):\/(.+)$/.exec(path);if(byPath&&path.endsWith(':/content')&&init.method==='PUT'){const name=byPath[2]!.replace(/:\/content$/,''),parent=byPath[1]!;if(this.lookup(parent,name))return new Response('{}',{status:412});return Response.json(this.file(parent,name,Buffer.from(init.body as Uint8Array)),{status:201});}if(byPath&&path.endsWith(':/createUploadSession')){if(this.denyUpload)return Response.json({}, {status:403});const name=byPath[2]!.replace(/:\/createUploadSession$/,''),parent=byPath[1]!;if(this.lookup(parent,name))return Response.json({}, {status:409});const id=randomUUID();this.sessions.set(id,{parent,name,data:Buffer.alloc(0)});return Response.json({uploadUrl:`https://synthetic.up.1drv.com/session/${id}?opaque=synthetic-private-upload`,expirationDateTime:'2045-01-01T00:00:00Z',nextExpectedRanges:['0-']});}if(byPath){const item=this.lookup(byPath[1]!,byPath[2]!);return item?Response.json(this.metadata(item)):new Response('{}',{status:404});}const match=/\/items\/([^/]+)(?:\/(children))?$/.exec(path);if(match){const id=match[1]!,item=this.items.get(id);if(!item)return new Response('{}',{status:404});if(match[2]&&init.method==='POST'){const body=JSON.parse(String(init.body));if(this.lookup(id,body.name))return Response.json({}, {status:409});return Response.json(this.folder(id,body.name),{status:201});}if(match[2])return Response.json({value:[...this.items.values()].filter(i=>i.parentReference?.id===id)});return Response.json(this.metadata(item));}return new Response('{}',{status:404});};
 fetch=async(url:string|URL,init:RequestInit={})=>{const target=new URL(url);if(new Headers(init.headers).has('Authorization'))throw new Error('Bearer token leaked to a preauthenticated transfer');const id=target.pathname.split('/').at(-1)!;if(target.hostname==='synthetic.files.1drv.com'){const bytes=this.contents.get(id);return bytes?new Response(new Uint8Array(this.corruptDownload&&this.items.get(id)?.name!=='library.json'?Buffer.alloc(bytes.length,1):bytes)):new Response('{}',{status:404});}if(target.hostname!=='synthetic.up.1drv.com')throw new Error('Invalid synthetic URL');const session=this.sessions.get(id);if(!session||this.expired)return new Response('{}',{status:404});if(!init.method||init.method==='GET')return Response.json({expirationDateTime:'2045-01-01T00:00:00Z',nextExpectedRanges:[`${session.data.length}-`]});const headers=new Headers(init.headers),range=headers.get('Content-Range')!,match=/^bytes (\d+)-(\d+)\/(\d+)$/.exec(range);if(!match)throw new Error('Missing upload range');const start=Number(match[1]),end=Number(match[2]),total=Number(match[3]),data=Buffer.from(init.body as Uint8Array);this.ranges.push(range);if(headers.get('Content-Length')!==String(data.length)||end-start+1!==data.length||session.bytes!==undefined&&session.bytes!==total)throw new Error('Inconsistent upload size');if(this.force416){this.force416=false;return new Response('{}',{status:416});}if(start!==session.data.length)return new Response('{}',{status:416});session.bytes=total;session.data=Buffer.concat([session.data,data]);if(session.data.length<total)return Response.json({expirationDateTime:'2045-01-01T00:00:00Z',nextExpectedRanges:[`${session.data.length}-`]}, {status:202});if(this.etagConflict)return new Response('{}',{status:412});const item=this.file(session.parent,session.name,session.data);this.sessions.delete(id);if(this.lostFinal){this.lostFinal=false;throw new Error('Synthetic lost acceptance response');}return Response.json(item,{status:201});};
}
