import {randomUUID} from 'node:crypto';
import {readPrivateJson} from './private-json';
import {existsSync,mkdirSync} from 'node:fs';import {dirname} from 'node:path';
import {atomicWriteJson} from '../atomic-json';import {beginDesktopOAuth,type DesktopOAuthOptions} from './oauth-pkce';import type {SecretVault} from './keychain-vault';
export const MICROSOFT_SCOPES=['openid','offline_access','https://graph.microsoft.com/Files.ReadWrite.AppFolder'];
const GUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
export interface OneDriveRegistration {clientId:string;tenant:string}
export interface OneDriveAuthSnapshot {connected:boolean;authorizing:boolean;generation:number;clientId?:string;tenant?:string;error?:string}
interface State {version:1;generation:number;clientId?:string;tenant?:string;credentialRef?:string;requiresAuthorization?:boolean;pendingRemovalRefs?:string[]}
interface Tokens {accessToken:string;refreshToken:string;expiresAt:number;scopes:string[]}
export interface OneDriveAuthOptions {path:string;vault:SecretVault;openBrowser:(url:string)=>Promise<void>;oauth?:typeof beginDesktopOAuth;fetch?:(input:string|URL,init?:RequestInit)=>Promise<Response>;now?:()=>number;write?:typeof atomicWriteJson}
export class OneDriveError extends Error {retryAfterMs?:number;constructor(readonly code:string,message:string){super(message);}}
/** All externally supplied provider responses are bounded; errors never include OAuth payloads. */
export async function readMicrosoftJson(response:Response,maxBytes=131072):Promise<Record<string,any>> {
 if(!response.body)throw new OneDriveError('provider-response','Invalid Microsoft response');const reader=response.body.getReader();let bytes=0;const chunks:Uint8Array[]=[];
 try{while(true){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.length;if(bytes>maxBytes)throw new Error();chunks.push(chunk.value);}const value=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!value||typeof value!=='object'||Array.isArray(value))throw new Error();return value;}catch{await reader.cancel().catch(()=>{});throw new OneDriveError('provider-response','Invalid Microsoft response');}finally{reader.releaseLock();}
}
const registration=(input:OneDriveRegistration)=>typeof input?.clientId==='string'&&GUID.test(input.clientId)&&typeof input.tenant==='string'&&(['common','consumers','organizations'].includes(input.tenant)||GUID.test(input.tenant));
const grantedFolder=(scope:string)=>scope.toLowerCase().replace(/^https:\/\/graph\.microsoft\.com\//,'')==='files.readwrite.appfolder';
/** Public registration and opaque references are device preferences; tokens remain in Keychain. */
export class OneDriveAuth {
 private state:State;private active?:AbortController;private job?:Promise<void>;private refresh?:Promise<Tokens>;private error?:string;private requests=new Set<AbortController>();
 constructor(private options:OneDriveAuthOptions){mkdirSync(dirname(options.path),{recursive:true,mode:0o700});this.state=existsSync(options.path)?readPrivateJson<State>(options.path,65536):{version:1,generation:0};if(this.state.version!==1||!Number.isSafeInteger(this.state.generation)||this.state.generation<0||(this.state.clientId&&!registration(this.state as OneDriveRegistration))||(this.state.credentialRef&&!GUID.test(this.state.credentialRef))||(this.state.pendingRemovalRefs&&(!Array.isArray(this.state.pendingRemovalRefs)||this.state.pendingRemovalRefs.length>64||this.state.pendingRemovalRefs.some(ref=>!GUID.test(ref)))))throw new Error('Invalid OneDrive connection state; preserve it for recovery');}
 private now(){return (this.options.now||Date.now)();}
 private persist(next:State){(this.options.write||atomicWriteJson)(this.options.path,next);this.state=next;}
 snapshot():OneDriveAuthSnapshot{return {connected:!!this.state.credentialRef&&!this.state.requiresAuthorization,authorizing:!!this.active,generation:this.state.generation,clientId:this.state.clientId,tenant:this.state.tenant,error:this.error};}
 start(input:OneDriveRegistration):OneDriveAuthSnapshot {if(this.active)throw new OneDriveError('busy','Authorization is already running');if(!registration(input))throw new Error('Invalid Microsoft public desktop registration');const controller=new AbortController();this.active=controller;this.error=undefined;this.job=this.authorize(input,controller).catch(error=>{this.error=controller.signal.aborted?'authorization-cancelled':error instanceof OneDriveError?error.code:'authorization-failed';}).finally(()=>{if(this.active===controller)this.active=undefined;});return this.snapshot();}
 private async authorize(input:OneDriveRegistration,controller:AbortController){await this.removeRetired();if(this.state.pendingRemovalRefs?.length)throw new OneDriveError('storage-unavailable','Credential cleanup is unavailable');controller.signal.throwIfAborted();const generation=this.state.generation,old=this.state.credentialRef;let reference:string|undefined;
  try{const result=await (this.options.oauth||beginDesktopOAuth)({authorizationEndpoint:`https://login.microsoftonline.com/${input.tenant}/oauth2/v2.0/authorize`,clientId:input.clientId,scopes:[...MICROSOFT_SCOPES],parameters:{prompt:'select_account'},loopbackHost:'localhost',openBrowser:this.options.openBrowser,signal:controller.signal} satisfies DesktopOAuthOptions);controller.signal.throwIfAborted();const raw=await this.tokenRequest(input.tenant,{client_id:input.clientId,grant_type:'authorization_code',code:result.code,redirect_uri:result.redirectUri,code_verifier:result.codeVerifier,scope:MICROSOFT_SCOPES.join(' ')},controller.signal);const tokens=this.parseTokens(raw);controller.signal.throwIfAborted();reference=randomUUID();this.persist({...this.state,pendingRemovalRefs:this.retired(reference)});await this.options.vault.put(tokens,reference);controller.signal.throwIfAborted();if(this.state.generation!==generation)throw new OneDriveError('connection-changed','Microsoft connection changed');this.persist({version:1,generation:generation+1,...input,credentialRef:reference,pendingRemovalRefs:this.retired(old).filter(ref=>ref!==reference)});}
  finally{await this.removeRetired();}
 }
 async wait(){await this.job;}
 async cancel():Promise<OneDriveAuthSnapshot>{this.active?.abort();await this.job;return this.snapshot();}
 private async tokenRequest(tenant:string,fields:Record<string,string>,signal?:AbortSignal){const response=await this.fetchControlled(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields)},signal,30000);const raw=await readMicrosoftJson(response);if(!response.ok){if(raw.error==='invalid_grant'||raw.error==='interaction_required')throw new OneDriveError('auth-required','Authorization is required');if(response.status===429)throw new OneDriveError('rate-limited','Microsoft authorization is temporarily limited');throw new OneDriveError('authorization-failed','Microsoft authorization failed');}return raw;}
 private parseTokens(raw:Record<string,any>,previous?:Tokens):Tokens {const scopes=typeof raw.scope==='string'?raw.scope.split(/\s+/).filter(Boolean):previous?.scopes;const broader=scopes?.some(scope=>{const short=scope.toLowerCase().replace(/^https:\/\/graph\.microsoft\.com\//,'');return /^(files\.|sites\.)/.test(short)&&!grantedFolder(scope);});if(!scopes?.some(grantedFolder)||broader)throw new OneDriveError('missing-scopes','The app-folder permission was not granted; broader access is not enabled');const refresh=raw.refresh_token??previous?.refreshToken;if(typeof raw.access_token!=='string'||!raw.access_token||raw.access_token.length>16384||typeof refresh!=='string'||!refresh||refresh.length>16384||typeof raw.expires_in!=='number'||!Number.isFinite(raw.expires_in)||raw.expires_in<1||raw.expires_in>86400||typeof raw.token_type!=='string'||raw.token_type.toLowerCase()!=='bearer')throw new OneDriveError('provider-response','Invalid Microsoft token response');return {accessToken:raw.access_token,refreshToken:refresh,expiresAt:this.now()+raw.expires_in*1000,scopes};}
 private async tokens(force=false,signal?:AbortSignal):Promise<Tokens>{signal?.throwIfAborted();if(this.active||!this.state.credentialRef||this.state.requiresAuthorization||!this.state.clientId||!this.state.tenant)throw new OneDriveError('auth-required','Authorization is required');const reference=this.state.credentialRef,generation=this.state.generation;const current=await this.options.vault.get<Tokens>(reference);if(this.state.generation!==generation)throw new OneDriveError('connection-changed','Microsoft connection changed');if(!current||typeof current.refreshToken!=='string'||!current.refreshToken||!Array.isArray(current.scopes)||!current.scopes.some(grantedFolder))throw new OneDriveError('auth-required','Authorization is required');if(!force&&typeof current.accessToken==='string'&&current.accessToken&&current.expiresAt>this.now()+60000)return current;
  if(!this.refresh){const clientId=this.state.clientId,tenant=this.state.tenant;this.refresh=(async()=>{try{const raw=await this.tokenRequest(tenant,{client_id:clientId,grant_type:'refresh_token',refresh_token:current.refreshToken,scope:MICROSOFT_SCOPES.join(' ')},signal),next=this.parseTokens(raw,current);if(generation!==this.state.generation||reference!==this.state.credentialRef)throw new OneDriveError('connection-changed','Microsoft connection changed');await this.options.vault.put(next,reference);if(generation!==this.state.generation)throw new OneDriveError('connection-changed','Microsoft connection changed');return next;}catch(error){if(error instanceof OneDriveError&&error.code==='auth-required'&&generation===this.state.generation){this.persist({...this.state,requiresAuthorization:true});this.error='auth-required';}throw error;}finally{this.refresh=undefined;}})();}return this.refresh;
 }
 async accessToken(signal?:AbortSignal):Promise<string>{return (await this.tokens(false,signal)).accessToken;}
 private async fetchControlled(url:string|URL,init:RequestInit,signal?:AbortSignal,timeout=60000):Promise<Response>{const controller=new AbortController();this.requests.add(controller);try{return await (this.options.fetch||fetch)(url,{...init,redirect:'error',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(timeout),...(signal?[signal]:[])])});}catch{throw new OneDriveError('offline','Microsoft OneDrive is unavailable');}finally{this.requests.delete(controller);}}
 async request(url:string,init:RequestInit={},signal?:AbortSignal):Promise<Response>{const target=new URL(url);if(target.protocol!=='https:'||target.hostname!=='graph.microsoft.com'||target.port||target.username||target.password||target.hash||!target.pathname.startsWith('/v1.0/'))throw new Error('Invalid Microsoft Graph destination');const generation=this.state.generation;for(let attempt=0;attempt<2;attempt++){const tokens=await this.tokens(attempt>0,signal);if(generation!==this.state.generation)throw new OneDriveError('connection-changed','Microsoft connection changed');const headers=new Headers(init.headers);headers.set('Authorization',`Bearer ${tokens.accessToken}`);const response=await this.fetchControlled(target,{...init,headers},signal);if(generation!==this.state.generation){await response.body?.cancel();throw new OneDriveError('connection-changed','Microsoft connection changed');}if(response.status!==401||attempt===1)return response;await response.body?.cancel();}throw new OneDriveError('auth-required','Authorization is required');}
 private retired(reference?:string):string[]{const refs=[...new Set([...(this.state.pendingRemovalRefs||[]),...(reference?[reference]:[])])];if(refs.length>64)throw new OneDriveError('storage-unavailable','Credential cleanup limit reached');return refs;}
 private async removeRetired(){const remaining:string[]=[];for(const ref of this.state.pendingRemovalRefs||[])try{await this.options.vault.remove(ref);}catch{remaining.push(ref);}if(remaining.length!==this.state.pendingRemovalRefs?.length)this.persist({...this.state,pendingRemovalRefs:remaining});if(remaining.length)this.error='storage-unavailable';}
 async disconnect():Promise<OneDriveAuthSnapshot>{const reference=this.state.credentialRef;this.persist({version:1,generation:this.state.generation+1,clientId:this.state.clientId,tenant:this.state.tenant,pendingRemovalRefs:this.retired(reference)});this.active?.abort();for(const controller of this.requests)controller.abort();await this.job;await this.refresh?.catch(()=>{});await this.removeRetired();return this.snapshot();}
}
