import {expect,test} from 'bun:test';
import {oneDriveResponse} from './onedrive-http';
import {OneDriveError} from './onedrive-auth';
const expected={connectionId:null,folderGeneration:0,authGeneration:0};
const req=(body:unknown,origin='http://localhost:4000')=>new Request('http://localhost:4000/api/connectors/onedrive',{method:'POST',headers:{Origin:origin},body:JSON.stringify(body)});
function fixture(){const calls:unknown[]=[];const manager:any={snapshot:()=>({connected:false,...expected}),expectation:()=>expected,start:(input:unknown,proof:unknown)=>{calls.push([input,proof]);return {authorizing:true};},sync:async()=>{throw new OneDriveError('stale-state','private synthetic details');}};return {calls,manager};}
test('local-only controls require strict identity proof and bounded commands before authorization',async()=>{const f=fixture();expect((await oneDriveResponse(req({action:'connect',expected,clientId:'x',tenant:'common'},'https://outside.example'),f.manager)).status).toBe(403);expect((await oneDriveResponse(req({action:'connect',clientId:'x',tenant:'common'}),f.manager)).status).toBe(400);expect((await oneDriveResponse(req({action:'connect',expected,clientId:'x',tenant:'common',secret:'excluded'}),f.manager)).status).toBe(400);expect((await oneDriveResponse(req({action:'connect',expected,clientId:'x',tenant:'common'}),f.manager)).status).toBe(200);expect(f.calls).toEqual([[{clientId:'x',tenant:'common'},expected]]);expect((await oneDriveResponse(req({action:'create',expected,name:'x'.repeat(7000)}),f.manager)).status).toBe(400);});
test('stale destination responses are conflicts and never expose arbitrary provider messages',async()=>{const f=fixture(),response=await oneDriveResponse(req({action:'sync',expected}),f.manager);expect(response.status).toBe(409);expect(await response.json()).toEqual({code:'stale-state',error:'OneDrive settings changed. Refresh before continuing.'});f.manager.sync=async()=>{throw new Error('https://private-token.example?secret=private');};const failure=await oneDriveResponse(req({action:'sync',expected}),f.manager);expect(failure.status).toBe(503);expect(await failure.text()).not.toContain('private');});
test('status is local-only, never cacheable and unsupported methods are rejected',async()=>{const f=fixture(),response=await oneDriveResponse(new Request('http://localhost:4000/api/connectors/onedrive'),f.manager);expect(response.status).toBe(200);expect(response.headers.get('Cache-Control')).toBe('no-store');expect((await oneDriveResponse(new Request('http://localhost:4000/api/connectors/onedrive',{method:'DELETE'}),f.manager)).status).toBe(405);});
