import {randomUUID,createHash} from 'node:crypto';import type {PortableCommit} from '@heed/shared';import type {LibraryProvider} from '../portable-provider';import {providerPath} from '../portable-provider';import {encode,revisionPath,sha256,UUID,validateBundle,validateCommit,validateManifest} from '../portable-schema';import {OneDriveError,readMicrosoftJson} from './onedrive-auth';import {OneDriveStore,GRAPH,GRAPH_ID,deltaUrl,type OneDriveItem} from './onedrive-store';import type {SecretVault} from './keychain-vault';
interface GraphAuth {request(url:string,init?:RequestInit,signal?:AbortSignal):Promise<Response>}
export interface OneDriveProviderOptions {assertAvailable?:()=>void;auth:GraphAuth;store:OneDriveStore;vault:SecretVault;fetch?:(input:string|URL,init?:RequestInit)=>Promise<Response>;now?:()=>number}
const safeName=(name:unknown):name is string=>typeof name==='string'&&!!name&&name.length<=256&&!/[\/\\\u0000]/.test(name)&&!['.','..'].includes(name);
export function oneDrivePath(path:string):string{providerPath(path);const parts=path.split('/');const valid=parts[0]==='objects'?parts.length===2&&/^[a-f0-9]{64}$/.test(parts[1]!):parts[0]==='commits'?parts.length===3&&UUID.test(parts[1]!)&&UUID.test(parts[2]!.replace(/\.json$/,''))&&parts[2]!.endsWith('.json'):parts.length===5&&UUID.test(parts[1]!)&&parts[2]==='revisions'&&UUID.test(parts[3]!)&&['meeting.json','manifest.json'].includes(parts[4]!);if(!valid)throw new Error('Invalid portable OneDrive path');return path;}
export function microsoftTransferUrl(value:unknown,upload=false):string{if(typeof value!=='string'||value.length>16384)throw new Error('Invalid Microsoft transfer destination');const url=new URL(value),host=url.hostname.toLowerCase();const allowed=upload?(host.endsWith('.up.1drv.com')||host.endsWith('.sharepoint.com')):(host.endsWith('.files.1drv.com')||host.endsWith('.sharepoint.com')||host.endsWith('.storage.live.com'));if(url.protocol!=='https:'||url.port||url.username||url.password||url.hash||!allowed)throw new Error('Invalid Microsoft transfer destination');return url.toString();}
/** Graph completion and streamed SHA-256 verification are distinct durable publication states. */
export class OneDriveProvider implements LibraryProvider {
 readonly id:string;readonly name:string;readonly transport='authenticated-network' as const;readonly capabilities={read:true,write:true,transportSecurity:'encrypted' as const,remoteDeletion:false,durability:'provider-receipt' as const};private failure?:OneDriveError;lastFailure(){return this.failure;}private discovery?:{id:string;commits:PortableCommit[];complete:boolean};
 constructor(private options:OneDriveProviderOptions){const binding=options.store.binding();this.id=`onedrive-${binding.connectionId}`;this.name=binding.name;}
 private binding(){return this.options.store.binding();}
 private endpoint(path:string){return `${GRAPH}/drives/${this.binding().driveId}/${path}`;}
 private now(){return (this.options.now||Date.now)();}
 private async checked(response:Response):Promise<Response>{if(response.ok)return response;const status=response.status;await response.body?.cancel();if(status===429){const error=new OneDriveError('rate-limited','Microsoft OneDrive is temporarily limited');const value=response.headers.get('retry-after')||'60',seconds=Number(value),delay=Number.isFinite(seconds)?seconds*1000:Date.parse(value)-this.now();error.retryAfterMs=Math.min(86400000,Math.max(1000,Number.isFinite(delay)?delay:60000));this.failure=error;throw error;}if(status===507)throw new OneDriveError('remote-quota','The OneDrive destination is full');if(status===401)throw new OneDriveError('auth-required','Authorization is required');if(status===403)throw new OneDriveError('access-denied','OneDrive denied this library operation');if(status===409||status===412)throw new OneDriveError('conflict','OneDrive has a conflicting immutable item');if(status===404)throw new OneDriveError('unavailable','The OneDrive item is unavailable');throw new OneDriveError('offline','Microsoft OneDrive is unavailable');}
 private normalize(raw:Record<string,any>,old?:OneDriveItem):OneDriveItem{const binding=this.binding();if(!raw||typeof raw!=='object'||!GRAPH_ID.test(raw.id)||raw.remoteItem||raw.parentReference?.driveId&&raw.parentReference.driveId!==binding.driveId)throw new Error('Invalid OneDrive item scope or shortcut');const deleted=raw.deleted!==undefined;const name=raw.name??(deleted?old?.name||`deleted-${raw.id}`:undefined);if(!safeName(name)||(!deleted&&!raw.folder&&!raw.file))throw new Error('Invalid OneDrive item metadata');const size=raw.size??(deleted?old?.size||0:undefined);if(!Number.isSafeInteger(size)||size<0||size>8_000_000_000_000)throw new Error('Invalid OneDrive item size');const parentId=raw.parentReference?.id??old?.parentId;if(parentId!==undefined&&!GRAPH_ID.test(parentId))throw new Error('Invalid OneDrive parent identity');const etag=raw.eTag??old?.etag;if(etag!==undefined&&(typeof etag!=='string'||etag.length>1024))throw new Error('Invalid OneDrive item ETag');return {id:raw.id,name,parentId,driveId:binding.driveId,size,etag,folder:!!raw.folder,deleted};}
 private paths():Map<string,OneDriveItem>{const items=this.options.store.items(),root=this.binding().rootId,paths=new Map<string,OneDriveItem>(),done=new Map<string,string|null>(),visiting=new Set<string>();const resolve=(id:string,depth=0):string|null=>{if(id===root)return '';if(done.has(id))return done.get(id)!;if(depth>64||visiting.has(id))throw new Error('Invalid OneDrive parent cycle');const item=items[id];if(!item||item.deleted||!item.parentId)return null;visiting.add(id);const parent=resolve(item.parentId,depth+1);visiting.delete(id);const path=parent===null?null:parent?`${parent}/${item.name}`:item.name;done.set(id,path);return path;};const names=new Set<string>();for(const item of Object.values(items)){const path=resolve(item.id);if(!path)continue;if(names.has(path.toLowerCase()))throw new Error('Conflicting OneDrive path identities');names.add(path.toLowerCase());paths.set(path,item);}return paths;}
 private async assertBinding(signal?:AbortSignal):Promise<void>{this.options.assertAvailable?.();const binding=this.binding(),appRaw=await readMicrosoftJson(await this.checked(await this.options.auth.request(`${GRAPH}/me/drive/special/approot`,{},signal)));if(appRaw.parentReference?.driveId!==binding.driveId)throw new Error('OneDrive account identity changed');const app=this.normalize(appRaw);if(app.id!==binding.appRootId||!app.folder||app.deleted)throw new Error('OneDrive account identity changed');const root=this.normalize(await this.metadata(binding.rootId,signal));if(root.id!==binding.rootId||root.parentId!==binding.appRootId||!root.folder||root.deleted)throw new Error('OneDrive library identity changed');const raw=await readMicrosoftJson(await this.checked(await this.options.auth.request(this.endpoint(`items/${binding.rootId}:/library.json`),{},signal))),item=this.normalize(raw);if(item.folder||item.deleted||item.name!=='library.json'||item.parentId!==binding.rootId||item.size>4096)throw new Error('OneDrive destination identity changed');let response:Response;try{response=await (this.options.fetch||fetch)(microsoftTransferUrl(raw['@microsoft.graph.downloadUrl']),{redirect:'error',signal:AbortSignal.any([AbortSignal.timeout(30000),...(signal?[signal]:[])])});}catch{throw new OneDriveError('offline','Microsoft OneDrive is unavailable');}const header=await readMicrosoftJson(await this.checked(response),4096);if(Object.keys(header).sort().join(',')!=='destinationId,format,schemaVersion'||header.format!=='heed-portable-library'||header.schemaVersion!==1||header.destinationId!==binding.destinationId)throw new Error('OneDrive destination identity changed');}
 private async scan(signal?:AbortSignal):Promise<{id:string;complete:boolean}>{let pending=this.options.store.pending();if(pending?.delta)return {id:pending.id,complete:true};let id=pending?.id||this.options.store.begin(!this.options.store.checkpoint()),items=pending?.items||this.options.store.items(),url=pending?.next||this.options.store.checkpoint()||this.endpoint(`items/${this.binding().rootId}/delta`);const seen=new Set<string>();let reset=false;
  for(let page=0;page<100;page++){signal?.throwIfAborted();url=deltaUrl(this.binding(),url);if(seen.has(url))throw new Error('Invalid repeated OneDrive continuation');seen.add(url);let response:Response;try{response=await this.options.auth.request(url,{},signal);}catch(error){if(signal?.aborted)throw error;return {id,complete:false};}if(response.status===410&&!reset){await response.body?.cancel();reset=true;id=this.options.store.begin(true);items={};url=this.endpoint(`items/${this.binding().rootId}/delta`);seen.clear();continue;}if(!response.ok){try{await this.checked(response);}catch(error){if(error instanceof OneDriveError&&['offline','rate-limited'].includes(error.code))return {id,complete:false};throw error;}}
   const data=await readMicrosoftJson(response,2_000_000);if(!Array.isArray(data.value)||data.value.length>2000||data['@odata.nextLink']&&data['@odata.deltaLink'])throw new Error('Invalid OneDrive delta page');for(const raw of data.value){const normalized=this.normalize(raw,items[raw.id]);items[normalized.id]=normalized;}const next=data['@odata.nextLink'],delta=data['@odata.deltaLink'];if(next!==undefined&&typeof next!=='string'||delta!==undefined&&typeof delta!=='string'||!next&&!delta)throw new Error('Invalid OneDrive delta checkpoint');if(next)deltaUrl(this.binding(),next);if(delta)deltaUrl(this.binding(),delta);this.options.store.stage(id,items,next,delta);this.paths();if(delta)return {id,complete:true};url=next;
  }return {id,complete:false};
 }
 async list(cursor:string|null,limit:number,signal?:AbortSignal){await this.assertBinding(signal);if(!Number.isSafeInteger(limit)||limit<1||limit>100)throw new Error('Invalid OneDrive page limit');let offset=0;if(cursor===null){const scan=await this.scan(signal),commits:PortableCommit[]=[];for(const [path,item] of this.paths()){if(!path.startsWith('commits/')||item.folder)continue;try{oneDrivePath(path);}catch{continue;}const marker=validateCommit(JSON.parse(Buffer.from(await this.read(path,65536,signal)).toString('utf8')));if(path!==`commits/${marker.deviceId}/${marker.revisionId}.json`)throw new Error('Invalid OneDrive commit identity');commits.push(marker);if(commits.length>10000)throw new Error('OneDrive commit limit reached');}commits.sort((a,b)=>a.deviceId.localeCompare(b.deviceId)||a.revisionId.localeCompare(b.revisionId));this.discovery={...scan,commits};}else{const [id,start]=cursor.split(':');if(!this.discovery||id!==this.discovery.id||!/^\d+$/.test(start||''))throw new Error('OneDrive discovery changed');offset=Number(start);}if(!this.discovery||offset>this.discovery.commits.length)throw new Error('Invalid OneDrive cursor');const next=offset+limit<this.discovery.commits.length?`${this.discovery.id}:${offset+limit}`:null;return {commits:this.discovery.commits.slice(offset,offset+limit),next,complete:this.discovery.complete};}
 async acknowledgeDiscovery(signal?:AbortSignal){signal?.throwIfAborted();await this.assertBinding(signal);if(!this.discovery?.complete)throw new Error('OneDrive discovery is incomplete');this.options.store.acknowledge(this.discovery.id);this.discovery=undefined;}
 private async metadata(id:string,signal?:AbortSignal):Promise<Record<string,any>>{if(!GRAPH_ID.test(id))throw new Error('Invalid OneDrive item identity');return readMicrosoftJson(await this.checked(await this.options.auth.request(this.endpoint(`items/${id}`),{},signal)));}
 private async validatePath(item:OneDriveItem,path:string,signal?:AbortSignal):Promise<OneDriveItem>{
  const binding=this.binding(),parts=path.split('/'),raw=await this.metadata(item.id,signal);
  if(raw.id!==item.id||raw.parentReference?.driveId!==binding.driveId)throw new Error('OneDrive path identity changed');
  const fresh=this.normalize(raw,item);if(fresh.deleted||fresh.folder!==item.folder||fresh.name!==parts.at(-1)||!fresh.parentId||(!fresh.folder&&item.etag&&fresh.etag!==item.etag))throw new OneDriveError('conflict','OneDrive path identity changed');
  const records=[fresh],seen=new Set([fresh.id]);let parent=fresh.parentId;
  for(let index=parts.length-2;index>=0;index--){if(parent===binding.rootId||seen.has(parent))throw new Error('Invalid OneDrive library ancestry');seen.add(parent);const parentRaw=await this.metadata(parent,signal);if(parentRaw.id!==parent||parentRaw.parentReference?.driveId!==binding.driveId)throw new Error('Invalid OneDrive library ancestry');const folder=this.normalize(parentRaw);if(!folder.folder||folder.deleted||folder.name!==parts[index]||!folder.parentId)throw new Error('OneDrive path identity changed');records.push(folder);parent=folder.parentId;}
  if(parent!==binding.rootId)throw new Error('Invalid OneDrive library ancestry');const rootRaw=await this.metadata(parent,signal);if(rootRaw.id!==binding.rootId||rootRaw.parentReference?.driveId!==binding.driveId||rootRaw.parentReference?.id!==binding.appRootId||!rootRaw.folder||rootRaw.remoteItem||rootRaw.deleted)throw new Error('Invalid OneDrive library ancestry');
  for(const record of records)this.options.store.record(record);return fresh;
 }
 private async lookup(path:string,signal?:AbortSignal):Promise<OneDriveItem|null>{const indexed=this.paths().get(path);if(indexed)return this.validatePath(indexed,path,signal);const response=await this.options.auth.request(this.endpoint(`items/${this.binding().rootId}:/${path.split('/').map(encodeURIComponent).join('/')}`),{},signal);if(response.status===404){await response.body?.cancel();return null;}const raw=await readMicrosoftJson(await this.checked(response));if(raw.parentReference?.driveId!==this.binding().driveId)throw new Error('Invalid OneDrive library ancestry');return this.validatePath(this.normalize(raw),path,signal);}

 async *stream(path:string,maxBytes:number,signal?:AbortSignal):AsyncIterable<Uint8Array>{oneDrivePath(path);await this.assertBinding(signal);if(!Number.isSafeInteger(maxBytes)||maxBytes<1||maxBytes>8_000_000_000_000)throw new Error('Invalid OneDrive transfer bound');const item=await this.lookup(path,signal);if(!item||item.folder||item.deleted||item.size>maxBytes)throw new OneDriveError('unavailable','The archived OneDrive object is unavailable');const raw=await this.metadata(item.id,signal),fresh=this.normalize(raw,item);if(fresh.id!==item.id||fresh.parentId!==item.parentId||fresh.name!==item.name||fresh.size!==item.size||item.etag&&fresh.etag!==item.etag)throw new OneDriveError('conflict','OneDrive item changed during verification');const url=microsoftTransferUrl(raw['@microsoft.graph.downloadUrl']);let response:Response;try{response=await (this.options.fetch||fetch)(url,{redirect:'error',signal:AbortSignal.any([AbortSignal.timeout(300000),...(signal?[signal]:[])])});}catch{throw new OneDriveError('offline','Microsoft OneDrive is unavailable');}await this.checked(response);if(!response.body)throw new OneDriveError('provider-response','Invalid OneDrive transfer');const reader=response.body.getReader();let received=0;try{while(true){signal?.throwIfAborted();const chunk=await reader.read();if(chunk.done)break;received+=chunk.value.length;if(received>maxBytes||received>item.size)throw new Error('OneDrive transfer exceeded declared size');yield chunk.value;}if(received!==item.size)throw new Error('OneDrive transfer was truncated');}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}}
 async read(path:string,maxBytes:number,signal?:AbortSignal){if(maxBytes>16_000_000)throw new Error('OneDrive metadata read limit reached');const chunks=[];for await(const chunk of this.stream(path,maxBytes,signal))chunks.push(Buffer.from(chunk));return Buffer.concat(chunks);}
 private async parentFor(path:string,signal?:AbortSignal):Promise<{id:string;name:string}>{const parts=path.split('/');let parent=this.binding().rootId;for(let index=0;index<parts.length-1;index++){const prefix=parts.slice(0,index+1).join('/');let item=await this.lookup(prefix,signal);if(!item){const response=await this.options.auth.request(this.endpoint(`items/${parent}/children`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:parts[index],folder:{},'@microsoft.graph.conflictBehavior':'fail'})},signal);if(response.status===409){await response.body?.cancel();item=await this.lookup(prefix,signal);}else{const raw=await readMicrosoftJson(await this.checked(response));item=await this.validatePath(this.normalize(raw),prefix,signal);}}if(!item||!item.folder||item.deleted||item.parentId!==parent||item.name!==parts[index])throw new Error('Invalid OneDrive publication ancestry');parent=item.id;}return {id:parent,name:parts.at(-1)!};}
 private async transfer(url:string,init:RequestInit,signal?:AbortSignal):Promise<Response>{microsoftTransferUrl(url,true);try{return await (this.options.fetch||fetch)(url,{...init,redirect:'error',signal:AbortSignal.any([AbortSignal.timeout(300000),...(signal?[signal]:[])])});}catch{if(signal?.aborted)signal.throwIfAborted();throw new OneDriveError('offline','Microsoft OneDrive is unavailable');}}
 private progress(raw:Record<string,any>,bytes:number):{offset:number;expiresAt:number}{const expiresAt=Date.parse(raw.expirationDateTime);if(!Number.isFinite(expiresAt)||!Array.isArray(raw.nextExpectedRanges)||!raw.nextExpectedRanges.length||raw.nextExpectedRanges.length>32)throw new Error('Invalid OneDrive upload status');const positions=raw.nextExpectedRanges.map((range:unknown)=>{if(typeof range!=='string'||!/^\d+-(?:\d+)?$/.test(range))throw new Error('Invalid OneDrive upload range');return Number(range.split('-')[0]);}),offset=Math.min(...positions);if(!Number.isSafeInteger(offset)||offset<0||offset>bytes||(offset!==bytes&&offset%327680!==0))throw new Error('Invalid OneDrive upload offset');return {offset,expiresAt};}
 private async verifyObject(path:string,bytes:number,hash:string,signal?:AbortSignal){const digest=createHash('sha256');let received=0;for await(const chunk of this.stream(path,bytes,signal)){received+=chunk.length;digest.update(chunk);}if(received!==bytes||digest.digest('hex')!==hash)throw new Error('OneDrive remote integrity verification failed');}
 private async cleanupRetiredUploads(){for(const reference of this.options.store.retiredUploadRefs())try{await this.options.vault.remove(reference);this.options.store.forgetRetiredUploadRef(reference);}catch{/* Durable opaque references remain retryable after restart and on disconnect. */}}
 async writeImmutable(path:string,bytes:Uint8Array,signal?:AbortSignal):Promise<void>{oneDrivePath(path);if(bytes.length<1||bytes.length>16_000_000)throw new Error('Invalid OneDrive metadata size');await this.writeObjectImmutable(path,bytes.length,sha256(bytes),(async function*(){yield bytes;})(),signal);}
 async writeObjectImmutable(path:string,bytes:number,hash:string,source:AsyncIterable<Uint8Array>,signal?:AbortSignal):Promise<void>{oneDrivePath(path);await this.assertBinding(signal);await this.cleanupRetiredUploads();if(!Number.isSafeInteger(bytes)||bytes<1||bytes>8_000_000_000_000||!/^[a-f0-9]{64}$/.test(hash)||(path.startsWith('objects/')&&path!==`objects/${hash}`))throw new Error('Invalid OneDrive immutable object identity');signal?.throwIfAborted();const parent=await this.parentFor(path,signal),old=this.options.store.uploadJob(path);if(old&&(old.hash!==hash||old.bytes!==bytes))throw new OneDriveError('conflict','OneDrive has a conflicting immutable upload');let existing=await this.lookup(path,signal);
  const finish=async(item:OneDriveItem)=>{if(item.parentId!==parent.id||item.name!==parent.name||item.size!==bytes||item.folder||item.deleted)throw new OneDriveError('conflict','OneDrive has a conflicting immutable item');this.options.store.record(item);const job=this.options.store.uploadJob(path);this.options.store.upload(path,{...job,bytes,hash,offset:bytes,parentId:parent.id,name:parent.name,state:'provider-confirmed',itemId:item.id});await this.verifyObject(path,bytes,hash,signal);let secretRef=job?.secretRef;if(secretRef){try{await this.options.vault.remove(secretRef);secretRef=undefined;}catch{/* Keep its opaque reference for explicit disconnect cleanup. */}}this.options.store.upload(path,{...this.options.store.uploadJob(path)!,state:'verified',secretRef});await this.cleanupRetiredUploads();};
  if(existing){await finish(existing);return;}let job=old,url:string|undefined;
  if(job?.secretRef&&job.expiresAt&&job.expiresAt>this.now()){url=await this.options.vault.get<string>(job.secretRef)||undefined;if(url){microsoftTransferUrl(url,true);const status=await this.transfer(url,{},signal);if(status.status===404||status.status===410){await status.body?.cancel();url=undefined;}else{const progress=this.progress(await readMicrosoftJson(await this.checked(status)),bytes);job={...job,...progress};this.options.store.upload(path,job);if(progress.expiresAt<=this.now())url=undefined;}}}
  if(!url){const response=await this.options.auth.request(this.endpoint(`items/${parent.id}:/${encodeURIComponent(parent.name)}:/createUploadSession`),{method:'POST',headers:{'Content-Type':'application/json','If-None-Match':'*'},body:JSON.stringify({item:{name:parent.name,'@microsoft.graph.conflictBehavior':'fail'}})},signal);if(response.status===409||response.status===412){await response.body?.cancel();existing=await this.lookup(path,signal);if(existing){await finish(existing);return;}throw new OneDriveError('conflict','OneDrive has a conflicting immutable item');}const raw=await readMicrosoftJson(await this.checked(response));url=microsoftTransferUrl(raw.uploadUrl,true);const progress=this.progress({...raw,nextExpectedRanges:raw.nextExpectedRanges||['0-']},bytes);if(progress.offset!==0||progress.expiresAt<=this.now())throw new Error('Invalid new OneDrive upload session');const reference=randomUUID();job={bytes,hash,parentId:parent.id,name:parent.name,secretRef:reference,...progress,state:'uploading'};this.options.store.upload(path,job);await this.options.vault.put(url,reference);await this.cleanupRetiredUploads();}
  if(job!.offset===bytes)throw new OneDriveError('resume-required','OneDrive upload completion must be checked before resuming');
  let offset=job!.offset,received=0,filled=0;const chunkSize=10*1024*1024,buffer=Buffer.alloc(Math.min(chunkSize,bytes-offset)),digest=createHash('sha256');
  const send=async(length:number,final:boolean)=>{const start=offset,end=offset+length-1;for(let attempt=0;attempt<2;attempt++){let response:Response;try{response=await this.transfer(url!,{method:'PUT',headers:{'Content-Length':String(length),'Content-Range':`bytes ${start}-${end}/${bytes}`},body:buffer.subarray(0,length)},signal);}catch(error){if(final&&!signal?.aborted){const accepted=await this.lookup(path,signal);if(accepted){await finish(accepted);offset=bytes;return;}}throw error;}if(response.status===416){await response.body?.cancel();const status=await this.transfer(url!,{},signal);if(status.status===404){await status.body?.cancel();const accepted=await this.lookup(path,signal);if(accepted&&final){await finish(accepted);offset=bytes;return;}throw new OneDriveError('resume-required','OneDrive upload must resume from a fresh source');}const progress=this.progress(await readMicrosoftJson(await this.checked(status)),bytes);this.options.store.upload(path,{...this.options.store.uploadJob(path)!,...progress});if(progress.offset===end+1&&!final){offset=progress.offset;return;}if(progress.offset!==start||attempt===1)throw new OneDriveError('resume-required','OneDrive upload must resume from a fresh source');continue;}await this.checked(response);const raw=await readMicrosoftJson(response);if(response.status===200||response.status===201){if(!final)throw new Error('OneDrive completed an incomplete upload');await finish(this.normalize(raw));offset=bytes;return;}if(response.status!==202||final)throw new Error('Invalid OneDrive upload completion');const progress=this.progress(raw,bytes);if(progress.offset!==end+1)throw new OneDriveError('resume-required','OneDrive upload must resume from a fresh source');offset=progress.offset;this.options.store.upload(path,{...this.options.store.uploadJob(path)!,...progress});return;}throw new OneDriveError('resume-required','OneDrive upload must resume from a fresh source');};
  const skipped=offset;for await(const value of source){signal?.throwIfAborted();const chunk=Buffer.from(value.buffer,value.byteOffset,value.byteLength),before=received;received+=chunk.length;if(received>bytes)throw new Error('OneDrive source integrity verification failed');digest.update(chunk);let position=Math.max(0,skipped-before);while(position<chunk.length){const copied=Math.min(buffer.length-filled,chunk.length-position);chunk.copy(buffer,filled,position,position+copied);filled+=copied;position+=copied;if(filled===buffer.length&&offset+filled<bytes){await send(filled,false);filled=0;}}}if(received!==bytes||digest.digest('hex')!==hash)throw new Error('OneDrive source integrity verification failed');if(offset<bytes){if(filled!==bytes-offset)throw new Error('OneDrive source integrity verification failed');await send(filled,true);}
 }
 async confirm(commit:PortableCommit,signal?:AbortSignal):Promise<'remote-confirmed'>{const marker=validateCommit(JSON.parse(Buffer.from(await this.read(`commits/${commit.deviceId}/${commit.revisionId}.json`,65536,signal)).toString('utf8')));if(sha256(encode(marker))!==sha256(encode(commit)))throw new Error('OneDrive commit integrity verification failed');const manifest=validateManifest(JSON.parse(Buffer.from(await this.read(marker.manifestPath,65536,signal)).toString('utf8'))),payload=validateBundle(marker,manifest,await this.read(`${revisionPath(marker.meetingId,marker.revisionId)}/meeting.json`,manifest.artifacts[0]!.bytes,signal));if(payload.audio)await this.verifyObject(payload.audio.objectPath,payload.audio.bytes,payload.audio.sha256,signal);return 'remote-confirmed';}
}
