import {useEffect,useRef,useState} from 'react';
import type {MediaImportConfig,MediaImportJob,MediaImportPhase,MediaImportSnapshot} from '@heed/shared';
import {mediaImportApi} from '@/api/media-import';
import {tr,useLocale} from '@/lib/i18n';
import {useSessionsStore} from '@/stores/sessions';
import {Dialog} from '../layout/Dialog';
import styles from './ImportRecordingDialog.module.css';
const phaseLabels:Record<MediaImportPhase,string>={copy:'Copying recording',normalization:'Preparing audio',transcription:'Transcribing recording',diarization:'Identifying speakers',saving:'Saving meeting'};
export function ImportRecordingDialog({onClose}:{onClose:()=>void}){
 useLocale();const [file,setFile]=useState<File|null>(null),[config,setConfig]=useState<MediaImportConfig>({model:'parakeet-v3',language:'auto',meetingMode:'audio-transcript'}),[snapshot,setSnapshot]=useState<MediaImportSnapshot|null>(null),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[commanding,setCommanding]=useState(false);
 const request=useRef(crypto.randomUUID()),input=useRef<HTMLInputElement>(null),mounted=useRef(true),completed=useRef(new Set<string>());
 const refresh=async()=>{try{const next=await mediaImportApi.list();if(!mounted.current)return;setSnapshot(next);for(const job of next.jobs)if(job.state==='completed'&&!completed.current.has(job.id)){completed.current.add(job.id);void useSessionsStore.getState().load(true);}}catch(e){if(mounted.current)setError((e as Error).message);}};
 useEffect(()=>{mounted.current=true;void refresh();const timer=window.setInterval(()=>void refresh(),1000);return()=>{mounted.current=false;clearInterval(timer);};},[]);
 const select=(files:FileList|null)=>{if(uploading||snapshot?.busy)return;if(!files?.length)return;if(files.length!==1){setError(tr('Choose one recording at a time.'));return;}if(files[0].size<=0||files[0].size>(snapshot?.maxFileBytes??256_000_000)){setError(tr('This recording exceeds the available import storage. Choose a smaller file or increase the storage limit in Settings.'));return;}setFile(files[0]);request.current=crypto.randomUUID();setError('');};
 const start=async()=>{if(!file||uploading||snapshot?.busy)return;setUploading(true);setError('');try{const job=await mediaImportApi.submit(request.current,file,config);if(mounted.current){setFile(null);setSnapshot(previous=>previous?{...previous,busy:['queued','running','cancelling'].includes(job.state),jobs:[job,...previous.jobs.filter(entry=>entry.id!==job.id)]}:null);await refresh();}}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setUploading(false);}};
 const command=async(job:MediaImportJob,action:'cancel'|'retry'|'discard')=>{if(commanding)return;if(action==='discard'&&!window.confirm(tr('Discard the managed working copies? Your original file is kept.')))return;setCommanding(true);setError('');try{await mediaImportApi.command(job.id,action);await refresh();}catch(e){setError((e as Error).message);}finally{setCommanding(false);}};
 const disabled=uploading||!!snapshot?.busy;
 return <Dialog label={tr('Import recording')} onClose={onClose}><section className={styles.content}><h2>{tr('Import recording')}</h2><p>{tr('Choose local audio or video. Only audio is kept; the original file is never changed.')}</p>
  <button type="button" className={styles.drop} disabled={disabled} onClick={()=>input.current?.click()} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();select(event.dataTransfer.files);}}>{tr('Choose a recording or drop it here')}</button>
  <label>{tr('Choose recording file')}<input ref={input} type="file" disabled={disabled} accept=".wav,.mp3,.m4a,.aac,.flac,.ogg,.aiff,.aif,.mp4,.mov,.webm,.mkv,audio/*,video/*" onChange={event=>select(event.target.files)}/></label>
  <p className={styles.hint}>{tr('WAV, MP3, M4A, AAC, FLAC, OGG, AIFF, MP4, MOV and WebM. Maximum 256 MB; available storage may reduce this limit.')}</p>
  {file&&<p><strong>{file.name}</strong> · {(file.size/1_000_000).toFixed(1)} MB</p>}
  <label>{tr('Transcription model')}<select disabled={disabled} value={config.model} onChange={event=>setConfig({...config,model:event.target.value as MediaImportConfig['model']})}><option value="parakeet-v3">{tr('Parakeet v3 · native and fast')}</option><option value="base">{tr('Whisper base · lighter')}</option><option value="small">{tr('Whisper small')}</option><option value="medium">{tr('Whisper medium')}</option><option value="large-v3">{tr('Whisper large-v3 · highest Whisper accuracy')}</option></select></label>
  <label>{tr('Meeting language')}<select disabled={disabled} value={config.language} onChange={event=>setConfig({...config,language:event.target.value as MediaImportConfig['language']})}><option value="auto">{tr('Detect English or Portuguese')}</option><option value="en">{tr('English')}</option><option value="pt">{tr('Portuguese (Brazil)')}</option></select></label>
  <label>{tr('Meeting storage')}<select disabled={disabled} value={config.meetingMode} onChange={event=>setConfig({...config,meetingMode:event.target.value as MediaImportConfig['meetingMode']})}><option value="audio-transcript">{tr('Audio + transcript')}</option><option value="transcript-only">{tr('Transcript only')}</option></select></label>
  {config.meetingMode==='transcript-only'&&<p className={styles.hint}>{tr('Temporary local audio is used during processing and removed after the meeting is saved. Playback and future retranscription will be unavailable.')}</p>}
  <p className={styles.hint}>{tr('Models may need to download on first use. Larger models use more memory and take longer.')}</p>
  {uploading&&<p role="status">{tr('Uploading recording')}</p>}{error&&<p role="alert" className={styles.error}>{tr(error)}</p>}
  <div className={styles.actions}><button type="button" disabled={!file||disabled||!snapshot} onClick={()=>void start()}>{tr('Start import')}</button><button type="button" onClick={onClose}>{tr('Close')}</button></div>
  {snapshot?.jobs.length? <section aria-label={tr('Import activity')} className={styles.jobs}><h3>{tr('Import activity')}</h3>{snapshot.jobs.map(job=><article key={job.id}><strong>{job.filename}</strong><p role="status">{tr(job.state==='completed'?'Import saved':job.state==='cancelled'?'Import cancelled':job.state==='failed'?'Import needs attention':job.state==='cancelling'?'Cancellation requested; waiting for the current processing step to finish.':phaseLabels[job.phase])}</p>{job.error&&<p className={styles.error}>{tr(job.error)}</p>}{['queued','running'].includes(job.state)&&<button type="button" disabled={commanding||job.phase==='saving'} onClick={()=>void command(job,'cancel')}>{tr('Cancel import')}</button>}{job.state==='failed'&&<div className={styles.actions}><button type="button" disabled={commanding||(snapshot.busy&&!job.workerUnconfirmed)} onClick={()=>void command(job,'retry')}>{tr('Retry import')}</button>{!job.sessionId&&!job.workerUnconfirmed&&<button type="button" disabled={commanding} onClick={()=>void command(job,'discard')}>{tr('Discard working copies')}</button>}</div>}</article>)}</section>:null}
  <p className={styles.hint}>{tr('You can close this window. Submitted imports continue locally and their status is restored when you return.')}</p>
 </section></Dialog>;
}
