import {beforeEach,expect,test,vi} from 'vitest';
import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {ImportRecordingDialog} from './ImportRecordingDialog';
import {useLocaleStore} from '@/stores/locale';
const mocks=vi.hoisted(()=>({list:vi.fn(),submit:vi.fn(),command:vi.fn()}));
vi.mock('@/api/media-import',()=>({mediaImportApi:mocks}));
beforeEach(()=>{vi.clearAllMocks();useLocaleStore.setState({locale:'en'});mocks.list.mockResolvedValue({jobs:[],busy:false,maxFileBytes:256_000_000,availableBytes:2_000_000_000});mocks.submit.mockResolvedValue({id:'job',state:'queued',filename:'meeting.mp4',phase:'copy',config:{model:'base',language:'en',meetingMode:'transcript-only'}});});
test('keyboard file selection previews media and freezes model language and storage on import',async()=>{render(<ImportRecordingDialog onClose={vi.fn()}/>);await waitFor(()=>expect(mocks.list).toHaveBeenCalled());const file=new File(['media'],'meeting.mp4',{type:'video/mp4'});fireEvent.change(screen.getByLabelText('Choose recording file'),{target:{files:[file]}});expect(screen.getByText('meeting.mp4')).toBeVisible();fireEvent.change(screen.getByRole('combobox',{name:'Transcription model'}),{target:{value:'base'}});fireEvent.change(screen.getByRole('combobox',{name:'Meeting language'}),{target:{value:'en'}});fireEvent.change(screen.getByRole('combobox',{name:'Meeting storage'}),{target:{value:'transcript-only'}});expect(screen.getByText(/Temporary local audio/)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Start import'}));await waitFor(()=>expect(mocks.submit).toHaveBeenCalledWith(expect.any(String),file,{model:'base',language:'en',meetingMode:'transcript-only'}));});
test('refresh recovers pending imports and offers cancellation with honest worker cleanup',async()=>{mocks.list.mockResolvedValue({jobs:[{id:'job',filename:'pending.wav',state:'running',phase:'diarization',config:{model:'base',language:'en',meetingMode:'audio-transcript'}}],busy:true,maxFileBytes:1000,availableBytes:1000});mocks.command.mockResolvedValue({id:'job',state:'cancelling'});render(<ImportRecordingDialog onClose={vi.fn()}/>);expect(await screen.findByText('pending.wav')).toBeVisible();expect(screen.getByText('Identifying speakers')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Cancel import'}));await waitFor(()=>expect(mocks.command).toHaveBeenCalledWith('job','cancel'));expect(screen.getByRole('button',{name:'Start import'})).toBeDisabled();});
test.each(['pt-BR','fr','de'] as const)('import dialog has translated title in %s',async(locale)=>{useLocaleStore.setState({locale});render(<ImportRecordingDialog onClose={vi.fn()}/>);expect(screen.queryByRole('dialog',{name:'Import recording'})).not.toBeInTheDocument();expect(screen.getByRole('dialog')).toBeVisible();await waitFor(()=>expect(mocks.list).toHaveBeenCalled());});

test('uncertain worker recovery stays available while new imports are blocked',async()=>{mocks.list.mockResolvedValue({jobs:[{id:'job',filename:'protected.wav',state:'failed',phase:'transcription',workerUnconfirmed:true,config:{model:'base',language:'en',meetingMode:'audio-transcript'}}],busy:true,maxFileBytes:1000,availableBytes:1000});render(<ImportRecordingDialog onClose={vi.fn()}/>);const retry=await screen.findByRole('button',{name:'Retry import'});expect(retry).toBeEnabled();expect(screen.getByRole('button',{name:'Start import'})).toBeDisabled();fireEvent.click(retry);await waitFor(()=>expect(mocks.command).toHaveBeenCalledWith('job','retry'));});
