import {useEffect,useRef,useState} from 'react';import type {GoogleDriveSnapshot,GoogleAccessMode,DriveFolderPreview,GoogleDriveCapacity} from '@heed/shared';
import {googleDriveApi} from '@/api/google-drive';import {useLocale} from '@/lib/i18n';import styles from './PermissionsPage.module.css';
export function GoogleDriveSettings({onProviderChanged}:{onProviderChanged?:()=>void}={}){
 const {tr}=useLocale();const [snapshot,setSnapshot]=useState<GoogleDriveSnapshot|null>(null),[clientId,setClientId]=useState(''),[mode,setMode]=useState<GoogleAccessMode>('app-files'),[consent,setConsent]=useState(false),[folderId,setFolderId]=useState(''),[name,setName]=useState('Heed Library'),[folders,setFolders]=useState<DriveFolderPreview[]>([]),[capacity,setCapacity]=useState<GoogleDriveCapacity|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const sequence=useRef(0),mutation=useRef(false),initialized=useRef(false);
 useEffect(()=>{let active=true;const refresh=async()=>{if(mutation.current)return;const seq=++sequence.current;try{const value=await googleDriveApi.snapshot();if(active&&sequence.current===seq){setSnapshot(value);if(!initialized.current){initialized.current=true;setClientId(value.clientId||'');setMode(value.accessMode||'app-files');setFolderId(value.folder?.id||'');}}}catch{if(active&&sequence.current===seq&&!mutation.current)setError('Google Drive is unavailable. Local transcripts are preserved.');}};void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>{active=false;++sequence.current;clearInterval(timer);};},[]);
 useEffect(()=>{setFolders([]);setCapacity(null);if(snapshot)setFolderId(snapshot.folder?.id||'');},[snapshot?.connectionId,snapshot?.generation]);
 const run=async(operation:()=>Promise<void>)=>{mutation.current=true;++sequence.current;setBusy(true);setError('');try{await operation();}catch{setError('Google Drive is unavailable. Check permissions, connection and storage, then retry. Local transcripts are preserved.');}finally{mutation.current=false;setBusy(false);}};
 const adopt=(value:GoogleDriveSnapshot,changed=false)=>{setSnapshot(value);if(changed)onProviderChanged?.();};
 const blocked=busy||snapshot?.busy||snapshot?.authorizing;const format=(bytes?:number)=>bytes===undefined?tr('Unknown'):`${(bytes/1e9).toFixed(2)} GB`;
 return <article className={styles.card} aria-labelledby="google-drive-title"><h2 id="google-drive-title">{tr('Google Drive')}</h2><p>{tr('Connect an optional library. Only explicitly published meeting revisions are uploaded; imported transcripts remain available offline.')}</p>
  {error&&<p role="alert">{tr(error)}</p>}{snapshot?.error&&<p role="status">{tr('Authorization or provider access needs attention. Check Google consent, Keychain and network access, then reconnect or retry.')}</p>}
  {!snapshot?<p>{tr('Loading Google Drive…')}</p>:<>
   <label htmlFor="google-client-id">{tr('Desktop OAuth client ID')}</label><input id="google-client-id" value={clientId} disabled={blocked} onChange={event=>setClientId(event.target.value)}/><p>{tr('Use a registered Google Desktop OAuth client with Drive API enabled. Register the same application on both Macs; no client secret is embedded.')}</p>
   <label htmlFor="google-access">{tr('Drive access')}</label><select id="google-access" value={mode} disabled={blocked} onChange={event=>{setMode(event.target.value as GoogleAccessMode);setConsent(false);}}><option value="app-files">{tr('App-authorized libraries (per-file access)')}</option><option value="existing-readonly">{tr('Existing libraries (read-only Drive access)')}</option><option value="existing-readwrite">{tr('Existing libraries (read and write Drive access)')}</option></select>
   <p>{tr('Per-file access only sees files authorized for this OAuth application. Choosing an existing folder does not grant access to every child. Broader access requires your explicit consent.')}</p>
   {mode!=='app-files'&&<label><input type="checkbox" checked={consent} disabled={blocked} onChange={event=>setConsent(event.target.checked)}/>{tr('I understand that this permission covers Drive files outside this library.')}</label>}
   {snapshot.authorizing?<><p role="status">{tr('Finish authorization in your system browser. Heed never asks for your account password.')}</p><button disabled={busy} onClick={()=>void run(async()=>adopt(await googleDriveApi.cancel(snapshot)))}>{tr('Cancel authorization')}</button></>:<button disabled={blocked||!clientId.trim()||(mode!=='app-files'&&!consent)} onClick={()=>void run(async()=>adopt(await googleDriveApi.connect({clientId:clientId.trim(),accessMode:mode,broaderAccessConfirmed:consent},snapshot)))}>{tr('Connect Google Drive')}</button>}
   {snapshot.connected&&<>
    <p role="status">{tr('Account connected')}</p><p>{tr('While this library is enabled, finalized local audio is protected until publication is verified for this destination. Disconnect preserves pending protection.')}</p>{snapshot.folder&&<><p>{snapshot.folder.name}</p><p>{tr('Library identity')}: {snapshot.folder.destinationId}</p><p>{tr(snapshot.folder.canUpload?'Library supports publication':'Library is read-only')}</p><button disabled={blocked} onClick={()=>void run(async()=>adopt(await googleDriveApi.enable(snapshot),true))}>{tr('Enable this library')}</button></>}
    <button disabled={blocked} onClick={()=>void run(async()=>setFolders(await googleDriveApi.folders(snapshot)))}>{tr('Browse accessible folders')}</button>{folders.length>0&&<select aria-label={tr('Accessible folders')} value={folderId} disabled={blocked} onChange={event=>setFolderId(event.target.value)}><option value="">{tr('Choose a folder')}</option>{folders.map(folder=><option key={folder.id} value={folder.id}>{folder.name}</option>)}</select>}
    <label htmlFor="google-library-folder">{tr('Library folder ID')}</label><input id="google-library-folder" value={folderId} disabled={blocked} onChange={event=>setFolderId(event.target.value)}/><button disabled={blocked||!folderId.trim()} onClick={()=>void run(async()=>adopt(await googleDriveApi.select(folderId.trim(),snapshot),true))}>{tr('Use existing library')}</button>
    <label htmlFor="google-new-library">{tr('New library name')}</label><input id="google-new-library" value={name} disabled={blocked} onChange={event=>setName(event.target.value)}/><button disabled={blocked||!folderId.trim()||!name.trim()||snapshot.accessMode==='existing-readonly'} onClick={()=>{if(window.confirm(tr('Create a dedicated Heed library inside the chosen folder? Existing files are preserved.')))void run(async()=>adopt(await googleDriveApi.create({parentId:folderId.trim(),name:name.trim(),confirmed:true},snapshot),true));}}>{tr('Create dedicated library')}</button>
    <button disabled={blocked} onClick={()=>void run(async()=>setCapacity(await googleDriveApi.capacity(snapshot)))}>{tr('Check Drive capacity')}</button>{capacity&&<p>{tr('Drive usage')}: {format(capacity.usage)} / {format(capacity.limit)}</p>}<p>{tr('Managed local usage appears in Storage. Drive for desktop caches are outside Heed’s quota.')}</p>
    <button disabled={blocked} onClick={()=>{if(window.confirm(tr('Disconnect this Mac? Local transcripts and pending copies are preserved.')))void run(async()=>adopt(await googleDriveApi.disconnect(false,snapshot),true));}}>{tr('Disconnect Google Drive')}</button><button disabled={blocked} onClick={()=>{if(window.confirm(tr('Revoke this OAuth application’s account access and disconnect? Other installations using this grant may need to reconnect. Local transcripts are preserved.')))void run(async()=>adopt(await googleDriveApi.disconnect(true,snapshot),true));}}>{tr('Revoke access and disconnect')}</button>
   </>}
   {snapshot.pendingCreation&&<button disabled={blocked} onClick={()=>{if(window.confirm(tr('Forget the incomplete creation job? A partially created remote folder may remain. No remote files will be deleted.')))void run(async()=>adopt(await googleDriveApi.forgetCreation(snapshot)));}}>{tr('Forget incomplete library creation')}</button>}
  </>}
 </article>;
}
