import {describe,it,expect,vi,beforeEach} from 'vitest';import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {GoogleDriveSettings} from './GoogleDriveSettings';import {useLocaleStore} from '@/stores/locale';
const api=vi.hoisted(()=>({snapshot:vi.fn(),connect:vi.fn(),cancel:vi.fn(),disconnect:vi.fn(),folders:vi.fn(),select:vi.fn(),create:vi.fn(),capacity:vi.fn(),enable:vi.fn(),forgetCreation:vi.fn()}));vi.mock('@/api/google-drive',()=>({googleDriveApi:api}));
const initial={connected:false,authorizing:false,pendingCreation:false,busy:false,generation:0};
// Preserve enabled-form coverage without a production runtime opt-in.
vi.mock('@heed/shared',async()=>({...await vi.importActual<any>('@heed/shared'),CLOUD_CONNECTIONS_ENABLED:{googleDrive:true,oneDrive:true}}));
beforeEach(()=>{cleanup();vi.clearAllMocks();useLocaleStore.getState().sync('en');api.snapshot.mockResolvedValue(initial);api.connect.mockResolvedValue({...initial,authorizing:true});api.capacity.mockResolvedValue({limit:2000000000,usage:1000});});
describe('Google Drive settings',()=>{
 it('requires public desktop client registration and fresh explicit consent for broader access',async()=>{render(<GoogleDriveSettings/>);const client=await screen.findByLabelText('Desktop OAuth client ID');fireEvent.change(client,{target:{value:'registered.apps.googleusercontent.com'}});fireEvent.change(screen.getByLabelText('Drive access'),{target:{value:'existing-readwrite'}});expect(screen.getByRole('button',{name:'Connect Google Drive'})).toBeDisabled();fireEvent.click(screen.getByLabelText('I understand that this permission covers Drive files outside this library.'));fireEvent.click(screen.getByRole('button',{name:'Connect Google Drive'}));await waitFor(()=>expect(api.connect).toHaveBeenCalledWith({clientId:'registered.apps.googleusercontent.com',accessMode:'existing-readwrite',broaderAccessConfirmed:true},initial));});
 it('previews identity, selects existing libraries and distinguishes Drive capacity from managed storage',async()=>{api.snapshot.mockResolvedValue({...initial,connected:true,clientId:'registered.apps.googleusercontent.com',accessMode:'app-files',folder:{id:'folder-one',name:'Existing library',destinationId:'synthetic-identity',canUpload:true}});api.select.mockResolvedValue({...initial,connected:true,generation:1,folder:{id:'folder-two',name:'Shared library',destinationId:'second-identity',canUpload:false}});render(<GoogleDriveSettings/>);await screen.findByText('Existing library');expect(screen.getByText(/synthetic-identity/)).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Library folder ID'),{target:{value:'folder-two'}});fireEvent.click(screen.getByRole('button',{name:'Use existing library'}));await waitFor(()=>expect(api.select).toHaveBeenCalledWith('folder-two',expect.objectContaining({generation:0,folder:expect.objectContaining({id:'folder-one'})})));expect(await screen.findByText('Shared library')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Check Drive capacity'}));expect(await screen.findByText(/2.00 GB/)).toBeInTheDocument();expect(screen.getByText('Managed local usage appears in Storage. Drive for desktop caches are outside Heed’s quota.')).toBeInTheDocument();});
 it('creation and revocation require reviewable confirmation while disconnect preserves local transcripts',async()=>{api.snapshot.mockResolvedValue({...initial,connected:true});api.create.mockResolvedValue({...initial,connected:true});api.disconnect.mockResolvedValue(initial);const confirmation=vi.spyOn(window,'confirm').mockReturnValueOnce(false).mockReturnValueOnce(true).mockReturnValueOnce(true);render(<GoogleDriveSettings/>);fireEvent.change(await screen.findByLabelText('Library folder ID'),{target:{value:'parent'}});fireEvent.change(screen.getByLabelText('New library name'),{target:{value:'Heed library'}});fireEvent.click(screen.getByRole('button',{name:'Create dedicated library'}));expect(api.create).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Create dedicated library'}));await waitFor(()=>expect(api.create).toHaveBeenCalledWith({parentId:'parent',name:'Heed library',confirmed:true},expect.objectContaining({generation:0,connected:true})));fireEvent.click(screen.getByRole('button',{name:'Revoke access and disconnect'}));await waitFor(()=>expect(api.disconnect).toHaveBeenCalledWith(true,expect.objectContaining({generation:0,connected:true})));confirmation.mockRestore();});
 it('offers cancellation while browser authorization is pending',async()=>{api.snapshot.mockResolvedValue({...initial,authorizing:true});api.cancel.mockResolvedValue(initial);render(<GoogleDriveSettings/>);fireEvent.click(await screen.findByRole('button',{name:'Cancel authorization'}));await waitFor(()=>expect(api.cancel).toHaveBeenCalled());});
});

it('blocks settings mutations while unresolved recovery protects local audio',async()=>{api.snapshot.mockResolvedValue({...initial,connected:true,recoveryRequired:true,clientId:'registered.apps.googleusercontent.com',folder:{id:'old',name:'Unresolved library',destinationId:'synthetic',canUpload:true}});render(<GoogleDriveSettings/>);expect(await screen.findByRole('alert')).toHaveTextContent('Google settings recovery is required. Local audio is protected. Preserve the connection configuration before recovery.');for(const button of screen.getAllByRole('button'))expect(button).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Enable this library'}));expect(api.enable).not.toHaveBeenCalled();});
