import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';import {afterEach,test,expect,vi} from 'vitest';
import {ICloudFolderSettings} from './ICloudFolderSettings';import {tr} from '@/lib/i18n';import {useLocaleStore} from '@/stores/locale';
const calls=vi.hoisted(()=>({request:vi.fn()}));vi.mock('@/api/icloud',()=>({icloudApi:{request:calls.request}}));afterEach(()=>{cleanup();vi.resetAllMocks();useLocaleStore.getState().sync("en");localStorage.clear();});
test.each(['en','pt-BR','fr','de'] as const)('folder connection and import use reviewed counts with honest confirmation in %s',async(locale)=>{useLocaleStore.getState().sync(locale);calls.request.mockResolvedValueOnce({connection:null,syncing:false,error:null,preview:null});const changed=vi.fn();render(<ICloudFolderSettings onProviderChanged={changed}/>);await waitFor(()=>expect(calls.request).toHaveBeenCalledWith());const choose=screen.getByTestId('icloud-select');calls.request.mockResolvedValueOnce({receipt:'reviewed',needsCreation:false});fireEvent.click(choose);await waitFor(()=>expect(screen.getByTestId('icloud-connect')).toBeEnabled());calls.request.mockResolvedValueOnce({connection:{id:'connection',name:'Library',enabled:true,pending:1,status:'pending-upload',observations:{}},syncing:false,error:null,preview:null});fireEvent.click(screen.getByTestId('icloud-connect'));await waitFor(()=>expect(calls.request).toHaveBeenCalledWith({action:'connect',name:'iCloud Drive',receipt:'reviewed',create:false}));await waitFor(()=>expect(changed).toHaveBeenCalledTimes(1));expect(screen.getByTestId('icloud-limitation')).toHaveTextContent(tr('iCloud upload status is not a server checksum receipt. Pending private copies stay protected; verify a second-device import before relying on remote recovery.'));calls.request.mockResolvedValueOnce({connection:{id:'connection',name:'Library',enabled:true,pending:1,status:'pending-upload',observations:{}},preview:{token:'review-token',count:2,bytes:2048},syncing:false,error:null});fireEvent.click(screen.getByTestId('icloud-preview'));await waitFor(()=>expect(screen.getByTestId('icloud-import')).toBeEnabled());calls.request.mockResolvedValueOnce({connection:{id:'connection',name:'Library',enabled:true,pending:1,status:'pending-upload',observations:{}},preview:{token:'new-token',count:0,bytes:0},syncing:false,error:null});fireEvent.click(screen.getByTestId('icloud-import'));await waitFor(()=>expect(calls.request).toHaveBeenCalledWith({action:'import',connectionId:'connection',token:'review-token'}));await waitFor(()=>expect(changed).toHaveBeenCalledTimes(3));});

test.each(['en','pt-BR','fr','de'] as const)('failed configuration refresh exposes recovery protection and disables future access in %s',async locale=>{
 useLocaleStore.getState().sync(locale);const connected={connection:{id:'connection',name:'Library',enabled:true,pending:0,status:'connected',observations:{}},syncing:false,error:null,preview:null};calls.request.mockResolvedValueOnce(connected);render(<ICloudFolderSettings/>);await waitFor(()=>expect(screen.getByTestId('icloud-preview')).toBeEnabled());
 calls.request.mockRejectedValueOnce(Error('Disk failure'));calls.request.mockResolvedValueOnce({...connected,recoveryRequired:true,error:'Recovery is required'});fireEvent.click(screen.getByTestId('icloud-preview'));
 await waitFor(()=>expect(screen.getByTestId('icloud-preview')).toBeDisabled());expect(screen.getByRole('alert')).toHaveTextContent(tr('iCloud settings recovery is required. Preserve private configuration and pending copies.'));expect(screen.getByTestId('icloud-select')).toBeDisabled();
});
