import {useEffect,useRef,useState} from 'react';import {icloudApi,type ICloudSnapshot,type ICloudSelection} from '@/api/icloud';import {useLocale} from '@/lib/i18n';import styles from './PermissionsPage.module.css';
export function ICloudFolderSettings(){const {tr}=useLocale();const [snapshot,setSnapshot]=useState<ICloudSnapshot|null>(null),[selection,setSelection]=useState<ICloudSelection|null>(null),[name,setName]=useState('iCloud Drive'),[create,setCreate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(false);const active=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;icloudApi.request().then(value=>{if(mounted.current)setSnapshot(value);}).catch(()=>{if(mounted.current)setError(true);});return()=>{mounted.current=false;};},[]);
 const run=async(action:()=>Promise<void>)=>{if(active.current)return;active.current=true;setBusy(true);setError(false);try{await action();}catch{if(mounted.current)setError(true);try{const current=await icloudApi.request();if(mounted.current)setSnapshot(current);}catch{ /* Keep the last reviewed state when recovery status is unavailable. */ }}finally{active.current=false;if(mounted.current)setBusy(false);}};
 const update=async(body:Record<string,unknown>)=>{const value=await icloudApi.request(body);if(mounted.current)setSnapshot(value);};
 const connection=snapshot?.connection;const state=snapshot?.recoveryRequired?'Recovery required':connection?.status==='cloud-full'?'iCloud space is full':connection?.status==='provider-offline'?'iCloud is offline':connection?.pending?'Upload pending — private copy protected':'Connected';
 return <article className={styles.card} aria-labelledby="icloud-settings-title"><h2 id="icloud-settings-title">iCloud Drive</h2><p>{tr('Choose a document library folder using macOS. No account is connected automatically.')}</p><p data-testid="icloud-limitation">{tr('iCloud upload status is not a server checksum receipt. Pending private copies stay protected; verify a second-device import before relying on remote recovery.')}</p><p>{tr('The local quota covers Heed copies and staging. macOS and iCloud caches outside Heed are excluded.')}</p>
 {snapshot?.recoveryRequired&&<p role="alert">{tr('iCloud settings recovery is required. Preserve private configuration and pending copies.')}</p>}
 {error&&!snapshot?.recoveryRequired&&<p role="alert">{tr('Check iCloud sign-in, folder permissions, download status, cloud space and the local storage limit; then retry.')}</p>}
 {!snapshot&&!error&&<p>{tr('Loading library…')}</p>}
 <button data-testid="icloud-select" disabled={busy||!snapshot||snapshot.recoveryRequired} onClick={()=>void run(async()=>{const selected=await icloudApi.request<ICloudSelection>({action:'select'});if(mounted.current){setSelection(selected);setCreate(false);}})}>{tr('Choose iCloud folder')}</button>
 {selection&&<><label htmlFor="icloud-library-name">{tr('Library name')}</label><input id="icloud-library-name" maxLength={80} disabled={busy||snapshot?.recoveryRequired} value={name} onChange={event=>setName(event.target.value)}/>{selection.needsCreation&&<label><input type="checkbox" disabled={busy||snapshot?.recoveryRequired} checked={create} onChange={event=>setCreate(event.target.checked)}/>{tr('Create a library in the selected empty folder')}</label>}<button data-testid="icloud-connect" disabled={busy||snapshot?.recoveryRequired||!name.trim()||selection.needsCreation&&!create} onClick={()=>void run(async()=>{await update({action:'connect',name,receipt:selection.receipt,create});if(mounted.current)setSelection(null);})}>{tr('Connect reviewed folder')}</button></>}
 {connection&&<><p>{connection.name}</p><p role="status">{tr(state)} · {tr('Pending')}: {connection.pending}</p>{Object.entries(connection.observations).map(([state,count])=><p key={state}>{tr(state==='system-reported-uploaded'?'macOS reports uploaded — remote integrity unverified':state==='cloud-full'?'iCloud space is full':state==='provider-offline'?'iCloud is offline':'Upload pending — private copy protected')}: {count}</p>)}
 <button disabled={busy||snapshot?.recoveryRequired} onClick={()=>void run(()=>update({action:'enable',connectionId:connection.id,enabled:!connection.enabled}))}>{tr(connection.enabled?'Pause iCloud access':'Resume iCloud access')}</button><button data-testid="icloud-preview" disabled={busy||snapshot?.recoveryRequired||!connection.enabled} onClick={()=>void run(()=>update({action:'preview',connectionId:connection.id}))}>{tr('Preview remote transcripts')}</button><button disabled={busy||snapshot?.recoveryRequired||!connection.enabled} onClick={()=>void run(()=>update({action:'sync',connectionId:connection.id}))}>{tr('Publish finalized meetings')}</button>
 {snapshot?.preview&&<><p>{tr('Eligible transcripts')}: {snapshot.preview.count} · {Math.ceil(snapshot.preview.bytes/1024)} KB</p><button data-testid="icloud-import" disabled={busy||snapshot?.recoveryRequired||!connection.enabled||!snapshot.preview.count} onClick={()=>void run(()=>update({action:'import',connectionId:connection.id,token:snapshot.preview!.token}))}>{tr('Import reviewed transcripts')}</button></>}
 <p>{tr('If protected pending files fill the quota, increase the limit or pause optional transfers. Retained transcripts are preserved.')}</p><button disabled={busy||snapshot?.recoveryRequired} onClick={()=>void run(()=>update({action:'disconnect',connectionId:connection.id}))}>{tr('Disconnect iCloud folder')}</button><p>{tr('Disconnect removes future folder access and keeps imported local transcripts and recoverable pending copies.')}</p></>}
 </article>;
}
