import {useEffect,useRef,useState} from 'react';
import type {DeletionJob,DeletionPreview,LibrarySnapshot,RevisionKey} from '@heed/shared';
import {libraryApi} from '@/api/library';import {useLocale} from '@/lib/i18n';
const key=(revision:RevisionKey)=>`${revision.libraryId}/${revision.meetingId}/${revision.revisionId}`;
export function RemoteDeletionSettings({snapshot,onChanged,parentBusy=false,onBusyChange}:{snapshot:LibrarySnapshot;onChanged:()=>void;parentBusy?:boolean;onBusyChange?:(busy:boolean)=>void}){
 const {tr}=useLocale(),caps=snapshot.deletionCapabilities;
 const supported=!!caps?.revisionMetadata&&caps.destinationVersion===2&&!snapshot.readOnly;
 const binding=`${snapshot.providerId}/${caps?.destinationId}/${caps?.connectionGeneration}`;
 const currentBinding=useRef(binding),mounted=useRef(true);currentBinding.current=binding;
 const [selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<DeletionPreview|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[jobs,setJobs]=useState<DeletionJob[]>([]);
 useEffect(()=>{mounted.current=true;setBusy(false);onBusyChange?.(false);setError('');setSelected([]);setPreview(null);setConfirmed(false);setJobs([]);if(!supported)return()=>{mounted.current=false;};let active=true;libraryApi.deletionJobs().then(value=>{if(active)setJobs(value);}).catch(()=>{if(active)setError('Deletion status is unavailable. Preserve existing jobs for recovery.');});return()=>{active=false;mounted.current=false;};},[binding,supported]);
 const run=async(work:(valid:()=>boolean)=>Promise<void>)=>{const requestBinding=binding;const valid=()=>mounted.current&&currentBinding.current===requestBinding;if(!valid())return;setBusy(true);onBusyChange?.(true);setError('');try{await work(valid);}catch{if(valid()){setPreview(null);setConfirmed(false);setError('Deletion could not complete. Refresh and review the destination, or retry the existing exact job.');}}finally{if(valid()){setBusy(false);onBusyChange?.(false);}}};
 const status=(job:DeletionJob)=>tr(job.state==='pending-verification'?'Metadata removed; cross-device verification is pending.':job.state==='pending-propagation'?'Metadata removed locally; iCloud propagation is pending.':'Deletion is incomplete. Retry the same job; do not create a replacement library.');
 if(!supported)return <section><h3>{tr('Physical remote deletion')}</h3><p>{tr('Physical deletion requires a new writable v2 library. Existing libraries are preserved.')}</p></section>;
 return <section aria-labelledby="remote-deletion-title"><h3 id="remote-deletion-title">{tr('Physical remote deletion')}</h3><p>{tr('Shared audio is retained. Local meetings and AI content are preserved.')}</p>{error&&<p role="alert">{tr(error)}</p>}
 <ul>{snapshot.previews.filter(item=>!item.remoteDeleted&&item.remoteAvailable!==false).slice(0,100).map(item=><li key={key(item)}><label><input type="checkbox" disabled={busy||parentBusy||!!preview} checked={selected.includes(key(item))} onChange={event=>setSelected(ids=>event.target.checked?[...ids,key(item)]:ids.filter(id=>id!==key(item)))}/>{item.title}</label><small> {item.libraryId} / {item.meetingId} / {item.revisionId}</small></li>)}</ul>
 <button disabled={busy||parentBusy||!selected.length||!snapshot.complete||!!preview} onClick={()=>void run(async valid=>{const revisions=snapshot.previews.filter(item=>selected.includes(key(item))).map(({libraryId,meetingId,revisionId})=>({libraryId,meetingId,revisionId}));const value=await libraryApi.deletionPreview(revisions,snapshot.providerId!,caps!.destinationId!);if(!valid())return;setPreview(value);setConfirmed(false);})}>{tr('Review physical deletion')}</button>
 {preview&&<div role="group" aria-label={tr('Confirm remote deletion')}><p>{snapshot.providerName} · {preview.versions} {tr('Selected versions')} · {tr('Metadata bytes to remove')}: {preview.eligibleBytes} · {tr('Audio bytes retained')}: {preview.retainedBytes}</p><p>{tr('This removes the selected remote metadata contents. A small deletion descriptor prevents old copies from republishing the same versions.')}</p><label><input type="checkbox" disabled={busy||parentBusy} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{tr('I confirm physical deletion of these remote versions.')}</label><button disabled={busy||parentBusy||!confirmed||Date.parse(preview.expiresAt)<=Date.now()} onClick={()=>void run(async valid=>{const result=await libraryApi.deletionConfirm(preview.token,preview.selection.providerId,preview.selection.destinationId);if(!valid())return;setJobs(old=>[result,...old.filter(job=>job.id!==result.id)]);setPreview(null);setSelected([]);setConfirmed(false);onChanged();})}>{tr('Delete selected remote metadata')}</button><button disabled={busy||parentBusy} onClick={()=>{setPreview(null);setConfirmed(false);}}>{tr('Cancel deletion review')}</button></div>}
 {jobs.filter(job=>(job.selection.providerId===snapshot.providerId&&job.selection.destinationId===caps!.destinationId)||!!job.blockedReason).map(job=><div key={job.id}><p role="status">{status(job)} {job.removed}/{job.total}</p>{job.blockedReason&&<p>{tr(job.blockedReason)} · {job.selection.destinationId}</p>}{job.state!=='pending-verification'&&<button disabled={busy||parentBusy||!!job.blockedReason} onClick={()=>void run(async valid=>{const result=await libraryApi.deletionRetry(job.id,job.selection.providerId,job.selection.destinationId);if(!valid())return;setJobs(old=>old.map(item=>item.id===job.id?result:item));onChanged();})}>{tr(job.state==='pending-propagation'?'Reconcile iCloud deletion':'Retry exact deletion job')}</button>}</div>)}
 </section>;
}
