import {useEffect,useRef,useState} from 'react';import type {LibrarySnapshot,RecoveryTransaction} from '@heed/shared';import {libraryApi} from '@/api/library';import {useLocale} from '@/lib/i18n';
export function RemoteRecoverySettings({snapshot,busy,onBusyChange,onChanged}:{snapshot:LibrarySnapshot;busy:boolean;onBusyChange:(value:boolean)=>void;onChanged:()=>void}){
 const {tr}=useLocale(),binding=`${snapshot.providerId}/${snapshot.deletionCapabilities?.destinationId}/${snapshot.deletionCapabilities?.connectionGeneration}`,current=useRef(binding);current.current=binding;
 const [jobs,setJobs]=useState<RecoveryTransaction[]>([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;setJobs([]);setError('');if(snapshot.deletionCapabilities?.destinationVersion!==2)return;libraryApi.recoveryJobs().then(value=>{if(active)setJobs(value);}).catch(()=>{if(active)setError('Remote recovery status is unavailable. Preserve the private journal.');});return()=>{active=false;};},[binding,snapshot]);
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 if(!jobs.length&&!error)return null;
 const recover=(job:RecoveryTransaction,release=false)=>{const initial=binding;onBusyChange(true);setError('');void (release?libraryApi.releaseOperation(job.operationId,snapshot.providerId!):libraryApi.reconcile(job.operationId,snapshot.providerId!)).then(()=>{if(mounted.current&&current.current===initial){setJobs(old=>old.filter(item=>item.operationId!==job.operationId));onChanged();}}).catch(()=>{if(mounted.current&&current.current===initial)setError('Original operation recovery is incomplete. Preserve its journal and retry the same operation.');}).finally(()=>{if(mounted.current&&current.current===initial)onBusyChange(false);});};
 return <section><h3>{tr('Interrupted remote operations')}</h3><p>{tr('An interrupted transaction can block this destination on other Macs. Preserve its journal. Local recording is still available.')}</p>{error&&<p role="alert">{tr(error)}</p>}{jobs.map(job=><div key={job.operationId}><p>{tr(job.kind==='delete'?'Interrupted deletion review':job.kind==='read'?'Interrupted remote read':'Interrupted publication')} · {job.operationId}</p>{job.blockedReason&&<p>{tr(job.blockedReason)}</p>}{!job.recoverable&&<p>{tr('Recovery cannot be proven. Preserve this destination and its private journal; use a new empty destination for future synchronization.')}</p>}<button disabled={busy||!job.recoverable} onClick={()=>recover(job)}>{tr(job.releaseOnly?'Release original interrupted operation':'Reconcile original operation')}</button>{job.releaseAvailable&&!job.releaseOnly&&<><p>{tr('Release stops this original publication without deleting its pending remote contents. Local meetings are preserved.')}</p><button disabled={busy||!job.recoverable} onClick={()=>recover(job,true)}>{tr('Release original interrupted operation')}</button></>}</div>)}</section>;
}
