import {beforeEach,describe,expect,it,vi} from 'vitest';import {fireEvent,render,screen,waitFor,cleanup} from '@testing-library/react';import {SmbSettings} from './SmbSettings';import {smbApi} from '@/api/smb';
vi.mock('@/api/smb',()=>({smbApi:{status:vi.fn(),test:vi.fn(),connect:vi.fn(),rename:vi.fn(),enable:vi.fn(),disconnect:vi.fn(),sync:vi.fn(),folder:vi.fn(),mount:vi.fn()}}));
vi.mock('@/lib/i18n',()=>({useLocale:()=>({locale:'en',tr:(s:string)=>s})}));
const empty={connections:[],syncing:false,selectedFolder:null,desktopPending:false,desktopError:null};
beforeEach(()=>{cleanup();vi.resetAllMocks();vi.mocked(smbApi.status).mockResolvedValue(empty);});
describe('SMB Settings',()=>{
 it('requires access test and explicit new-library confirmation before connecting',async()=>{vi.mocked(smbApi.test).mockResolvedValue({receipt:'r',destinationId:null,needsCreation:true,readOnly:false,security:'signed',dialect:'SMB_3.1.1',authentication:'macOS-session',folder:'/fixture/share'});vi.mocked(smbApi.connect).mockResolvedValue(empty);render(<SmbSettings/>);await screen.findByText('SMB/Samba');fireEvent.change(screen.getByLabelText('Destination name'),{target:{value:'Office'}});fireEvent.change(screen.getByLabelText('Mounted share folder'),{target:{value:'/fixture/share'}});fireEvent.click(screen.getByRole('button',{name:'Test access'}));await screen.findByLabelText('Create a dedicated Heed Library subfolder');expect(screen.getByRole('button',{name:'Connect and synchronize'})).toBeDisabled();fireEvent.click(screen.getByLabelText('Create a dedicated Heed Library subfolder'));fireEvent.click(screen.getByRole('button',{name:'Connect and synchronize'}));await waitFor(()=>expect(smbApi.connect).toHaveBeenCalledWith('Office','r',true,undefined));});
 it('surface readonly imports, pending uploads and actionable tests without claiming server durability',async()=>{vi.mocked(smbApi.status).mockResolvedValue({...empty,connections:[{id:'c',name:'Office',root:'/fixture/share/Heed Library',destinationId:'destination',enabled:true,readOnly:true,security:'signed',pending:2,lastSync:null,error:null,imported:3,skipped:1,bytes:1024}]});render(<SmbSettings/>);await screen.findByText(/Read-only — imports available/);expect(screen.getByText('Share acknowledgment does not prove survival of server power loss.')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Disable'}));await waitFor(()=>expect(smbApi.enable).toHaveBeenCalledWith('c',false));expect(smbApi.sync).not.toHaveBeenCalled();});
 it('failed test keeps connection action unavailable and clears confirmation after folder edits',async()=>{vi.mocked(smbApi.test).mockRejectedValue(new Error('offline'));render(<SmbSettings/>);await screen.findByText('SMB/Samba');fireEvent.change(screen.getByLabelText('Mounted share folder'),{target:{value:'/fixture/share'}});fireEvent.click(screen.getByRole('button',{name:'Test access'}));await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'Connect and synchronize'})).toBeNull();});
 it('publishes only to the displayed destination and reports a stale-tab rejection',async()=>{vi.mocked(smbApi.status).mockResolvedValue({...empty,connections:[{id:'old-displayed',name:'Office',root:'/fixture/share/Heed Library',destinationId:'destination',enabled:true,readOnly:false,security:'signed',pending:1,lastSync:null,error:null,imported:0,skipped:0,bytes:1024}]});vi.mocked(smbApi.sync).mockRejectedValue(new Error('Destination changed in another tab'));render(<SmbSettings/>);const sync=await screen.findByRole('button',{name:'Synchronize now'});fireEvent.click(sync);await waitFor(()=>expect(smbApi.sync).toHaveBeenCalledWith('old-displayed'));expect(await screen.findByRole('alert')).toHaveTextContent('Could not complete the SMB operation.');});

});
