import {render,screen,waitFor,cleanup,fireEvent} from '@testing-library/react';import {beforeEach,it,expect,vi} from 'vitest';import {SmbSettings} from './SmbSettings';import {smbApi} from '@/api/smb';import {useLocaleStore} from '@/stores/locale';
vi.mock('@/api/smb',()=>({smbApi:{status:vi.fn(),test:vi.fn(),disconnect:vi.fn()}}));
beforeEach(()=>{cleanup();vi.resetAllMocks();vi.mocked(smbApi.status).mockRejectedValue(new Error('Synchronization settings recovery is required. Preserve configuration and pending copies.'));});
it.each([['pt-BR','É necessário recuperar as configurações de sincronização. Preserve a configuração e as cópias pendentes.'],['fr','La récupération des paramètres de synchronisation est nécessaire. Conservez la configuration et les copies en attente.'],['de','Die Synchronisierungseinstellungen müssen wiederhergestellt werden. Bewahren Sie die Konfiguration und ausstehenden Kopien auf.']] as const)('explains retained pending work and blocks destination edits in %s',async(locale,message)=>{useLocaleStore.setState({locale});const {container}=render(<SmbSettings/>);expect(await screen.findByRole('alert')).toHaveTextContent(message);await waitFor(()=>expect(container.querySelector('#smb-folder')).toBeDisabled());expect(smbApi.status).toHaveBeenCalled();});

it.each([
 ['en','Test access','SMB filesystem does not support the required atomic operations. Use a compatible destination; existing files are preserved.'],
 ['pt-BR','Testar acesso','O sistema de arquivos SMB não oferece as operações atômicas necessárias. Use um destino compatível; os arquivos existentes são preservados.'],
 ['fr','Tester l’accès','Le système de fichiers SMB ne prend pas en charge les opérations atomiques requises. Utilisez une destination compatible ; les fichiers existants sont conservés.'],
 ['de','Zugriff testen','Das SMB-Dateisystem unterstützt die erforderlichen atomaren Vorgänge nicht. Verwenden Sie ein kompatibles Ziel; vorhandene Dateien bleiben erhalten.'],
] as const)('explains unsupported filesystem capability without offering creation or leaking native messages in %s',async(locale,button,message)=>{vi.mocked(smbApi.status).mockResolvedValue({connections:[],syncing:false,selectedFolder:null,desktopPending:false,desktopError:null});vi.mocked(smbApi.test).mockRejectedValue(new Error('SMB filesystem does not support the required atomic operations. Use a compatible destination; existing files are preserved.'));useLocaleStore.setState({locale});const {container}=render(<SmbSettings/>);await waitFor(()=>expect(smbApi.status).toHaveBeenCalled());fireEvent.change(container.querySelector('#smb-folder')!,{target:{value:'/synthetic-share'}});fireEvent.click(screen.getByRole('button',{name:button}));expect(await screen.findByRole('alert')).toHaveTextContent(message);expect(container.querySelector('input[type=checkbox]')).toBeNull();expect(smbApi.test).toHaveBeenCalledWith('/synthetic-share');});

it.each([
 ['en','Disconnect destination','Recover the original SMB operation before reconnecting or disconnecting this destination. Its configuration is preserved.'],
 ['pt-BR','Desconectar destino','Recupere a operação SMB original antes de reconectar ou desconectar este destino. A configuração é preservada.'],
 ['fr','Déconnecter la destination','Récupérez l’opération SMB d’origine avant de reconnecter ou de déconnecter cette destination. Sa configuration est conservée.'],
 ['de','Ziel trennen','Stellen Sie den ursprünglichen SMB-Vorgang wieder her, bevor Sie dieses Ziel erneut verbinden oder trennen. Die Konfiguration bleibt erhalten.'],
] as const)('keeps original-operation recovery distinct from permanent settings faults in %s',async(locale,button,message)=>{vi.mocked(smbApi.status).mockResolvedValue({connections:[{id:'original',name:'Synthetic library',root:'/synthetic-share/Heed Library',destinationId:'synthetic-destination',enabled:true,readOnly:false,security:'signed',pending:1,lastSync:null,error:null,imported:0,skipped:0,bytes:1}],syncing:false,selectedFolder:null,desktopPending:false,desktopError:null});vi.mocked(smbApi.disconnect).mockRejectedValue(new Error('Recover the original SMB operation before reconnecting or disconnecting this destination. Its configuration is preserved.'));useLocaleStore.setState({locale});render(<SmbSettings/>);fireEvent.click(await screen.findByRole('button',{name:button}));expect(await screen.findByRole('alert')).toHaveTextContent(message);await waitFor(()=>expect(screen.getByRole('button',{name:button})).toBeEnabled());expect(smbApi.disconnect).toHaveBeenCalledWith('original');});
