import {useEffect,useRef,useState} from 'react';
import type {VocabularyEntry,VocabularyLibrary} from '@heed/shared';
import {vocabularyApi} from '@/api/vocabulary';
import {useLocale} from '@/lib/i18n';
import styles from './PermissionsPage.module.css';
const blank=():VocabularyLibrary=>({schemaVersion:1,version:0,defaultGlossaryId:null,glossaries:[]});
export function VocabularySettings(){
 const {tr}=useLocale();const [library,setLibrary]=useState<VocabularyLibrary>(blank),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[name,setName]=useState(''),[term,setTerm]=useState(''),[hint,setHint]=useState(''),[language,setLanguage]=useState(''),[editing,setEditing]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const file=useRef<HTMLInputElement>(null);
 const refresh=async()=>{try{const next=await vocabularyApi.read();if(next){setLibrary(next);setLoaded(true);setSelected(current=>next.glossaries.some(g=>g.id===current)?current:next.glossaries[0]?.id||'');setError('');}}catch{setError('Could not load vocabulary. Retry by reopening this page.');}};
 useEffect(()=>{void refresh();},[]);
 const glossary=library.glossaries.find(g=>g.id===selected);
 const reset=()=>{setEditing(null);setTerm('');setHint('');setLanguage('');};
 const save=async(next:VocabularyLibrary)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const saved=await vocabularyApi.save(next);setLibrary(saved);setSelected(current=>saved.glossaries.some(g=>g.id===current)?current:saved.glossaries[0]?.id||'');setNotice('Vocabulary saved locally. Existing meetings are unchanged.');reset();}catch{setError('Could not save vocabulary. Check duplicates, lengths and language, or reload after a conflict.');}finally{setBusy(false);}};
 const updateEntries=(entries:VocabularyEntry[])=>save({...library,glossaries:library.glossaries.map(g=>g.id===selected?{...g,entries}:g)});
 const add=()=>{if(!glossary)return;const entry:VocabularyEntry={term,...(hint?{hint}:{}),...(language?{language:language as 'en'|'pt'}:{})};void updateEntries(editing===null?[...glossary.entries,entry]:glossary.entries.map((e,i)=>i===editing?entry:e));};
 const importFile=async(input:File)=>{setBusy(true);setError('');setNotice('');try{if(input.size>1_000_000)throw Error('large');const next=await vocabularyApi.import(await input.text(),library.version);setLibrary(next);setSelected(next.glossaries[0]?.id||'');reset();setNotice('Vocabulary saved locally. Existing meetings are unchanged.');}catch{setError('Could not import vocabulary. Use the documented JSON format and reload after a conflict.');}finally{setBusy(false);if(file.current)file.current.value='';}};
 return <article className={styles.card} aria-labelledby="vocabulary-title"><h2 id="vocabulary-title">{tr('Local vocabulary')}</h2><p>{tr('Vocabulary stays on this Mac. Import replaces the local glossary library; export downloads its JSON file explicitly.')}</p>
 <p>{tr('Whisper uses vocabulary as first-window recognition context. Native Parakeet in Heed does not apply it. Recognition is not guaranteed; hints never rename speakers or replace text.')}</p>
 <fieldset disabled={!loaded||busy}><label>{tr('Glossary')} <select aria-label={tr('Manage glossary')} value={selected} onChange={event=>{setSelected(event.target.value);setName('');reset();}}>{!library.glossaries.length&&<option value="">{tr('No glossary')}</option>}{library.glossaries.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>
 <label>{tr('Glossary name')}<input aria-label={tr('Glossary name')} value={name} maxLength={100} onChange={event=>setName(event.target.value)}/></label><button disabled={!name.trim()||library.glossaries.length>=20} onClick={()=>{const id=crypto.randomUUID();setSelected(id);void save({...library,glossaries:[...library.glossaries,{id,name,version:1,entries:[]}]});setName('');}}>{tr('Add glossary')}</button>
 <button disabled={!glossary||!name.trim()} onClick={()=>{void save({...library,glossaries:library.glossaries.map(g=>g.id===selected?{...g,name}:g)});setName('');}}>{tr('Rename glossary')}</button>
 <button disabled={!glossary} onClick={()=>{if(window.confirm(tr('Delete this glossary? Existing meetings remain unchanged.')))void save({...library,defaultGlossaryId:library.defaultGlossaryId===selected?null:library.defaultGlossaryId,glossaries:library.glossaries.filter(g=>g.id!==selected)});}}>{tr('Delete glossary')}</button>
 <label>{tr('Default glossary')} <select aria-label={tr('Default glossary')} value={library.defaultGlossaryId||''} onChange={event=>void save({...library,defaultGlossaryId:event.target.value||null})}><option value="">{tr('No glossary')}</option>{library.glossaries.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>
 <label>{tr('Search vocabulary')}<input aria-label={tr('Search vocabulary')} value={search} onChange={event=>setSearch(event.target.value)}/></label>
 <ul>{glossary?.entries.map((entry,index)=>({entry,index})).filter(({entry})=>`${entry.term} ${entry.hint||''}`.normalize('NFC').toLowerCase().includes(search.normalize('NFC').toLowerCase())).map(({entry,index})=><li key={index}>{entry.term}{entry.hint?` (${entry.hint})`:''}{entry.language?` · ${entry.language}`:''} <button onClick={()=>{setEditing(index);setTerm(entry.term);setHint(entry.hint||'');setLanguage(entry.language||'');}}>{tr('Edit term')}</button> <button onClick={()=>void updateEntries(glossary!.entries.filter((_,i)=>i!==index))}>{tr('Remove term')}</button></li>)}</ul>
 <label>{tr('Term')}<input aria-label={tr('Term')} value={term} maxLength={120} onChange={event=>setTerm(event.target.value)}/></label><label>{tr('Pronunciation or alias hint')}<input aria-label={tr('Pronunciation or alias hint')} value={hint} maxLength={120} onChange={event=>setHint(event.target.value)}/></label>
 <label>{tr('Language scope')}<select aria-label={tr('Language scope')} value={language} onChange={event=>setLanguage(event.target.value)}><option value="">{tr('Any language')}</option><option value="en">{tr('English')}</option><option value="pt">{tr('Portuguese (Brazil)')}</option></select></label>
 <button disabled={!glossary||!term.trim()} onClick={add}>{tr(editing===null?'Add term':'Save term')}</button>{editing!==null&&<button onClick={reset}>{tr('Cancel')}</button>}
 <input ref={file} type="file" accept="application/json,.json" aria-label={tr('Import vocabulary JSON')} onChange={event=>{if(event.target.files?.[0]&&window.confirm(tr('Replace the local vocabulary library with this file?')))void importFile(event.target.files[0]);}}/>
 </fieldset><a href={vocabularyApi.exportUrl()} download="heed-vocabulary.json">{tr('Export vocabulary JSON')}</a><button disabled={busy} onClick={()=>void refresh()}>{tr('Reload')}</button>
 {notice&&<p role="status">{tr(notice)}</p>}{error&&<p role="alert" className={styles.error}>{tr(error)}</p>}</article>;
}
