import Foundation

struct MenuLocalization {
    static let locales = ["en", "pt-BR", "fr", "de"]
    static func normalize(_ locale: String?) -> String { locales.contains(locale ?? "") ? locale! : "en" }
    private static let translations: [String: [String: String]] = [
        "pt-BR": [
            "Recording • live text off; transcript after stop": "Gravando • texto ao vivo desativado; transcrição após parar",
            "Recover system audio permission?": "Recuperar a permissão de áudio do sistema?",
            "Heed will clear only its screen and system audio permission, then restart. macOS will ask you to authorize it again. Meetings, settings and other permissions are preserved.": "O Heed redefinirá apenas sua permissão de tela e áudio do sistema e reiniciará. O macOS solicitará uma nova autorização. Reuniões, configurações e outras permissões serão preservadas.",
            "Recover and restart": "Recuperar e reiniciar",
            "System audio permission recovery could not finish. Reopen Heed and try again after active work or updates finish.": "Não foi possível concluir a recuperação da permissão de áudio do sistema. Reabra o Heed e tente novamente após o processamento ou as atualizações terminarem.",
            "Updates": "Atualizações",
            "Installed version: %@": "Versão instalada: %@",
            "Available version: %@": "Versão disponível: %@",
            "Unknown": "Desconhecida",
            "development": "desenvolvimento",
            "Updates not checked": "Atualizações não verificadas",
            "Check for updates…": "Verificar atualizações…",
            "Checking for updates…": "Verificando atualizações…",
            "Update available": "Atualização disponível",
            "Heed is up to date": "O Heed está atualizado",
            "Release notes": "Notas da versão",
            "Update…": "Atualizar…",
            "Update": "Atualizar",
            "Cancel": "Cancelar",
            "Retry update": "Tentar atualização novamente",
            "Retry recovery": "Tentar recuperação novamente",
            "View update log…": "Ver log da atualização…",
            "Downloading update…": "Baixando atualização…",
            "Verifying update…": "Verificando atualização…",
            "Preparing update…": "Preparando atualização…",
            "Restarting Heed…": "Reiniciando o Heed…",
            "Verifying installed services…": "Verificando serviços instalados…",
            "Checking capture permissions…": "Verificando permissões de captura…",
            "Update installed": "Atualização instalada",
            "Finish processing, then retry the update.": "Aguarde o processamento terminar e tente atualizar novamente.",
            "Update interrupted. Retry recovery or view the update log.": "Atualização interrompida. Tente recuperar ou veja o log da atualização.",
            "Release verification failed. Check again or view the update log.": "A verificação da versão falhou. Verifique novamente ou veja o log da atualização.",
            "Upgrade the installed API with the release installer before using menu updates.": "Atualize a API instalada com o instalador de versões antes de atualizar pelo menu.",
            "This release requires a newer macOS or a compatible Mac.": "Esta versão exige um macOS mais recente ou um Mac compatível.",
            "GitHub is limiting requests. Try again later.": "O GitHub está limitando as solicitações. Tente novamente mais tarde.",
            "Update helper unavailable. Reinstall Heed or view the service status.": "O auxiliar de atualização está indisponível. Reinstale o Heed ou veja o estado dos serviços.",
            "Update failed. View the log and verify the retained version.": "A atualização falhou. Veja o log e verifique a versão mantida.",
            "Could not check or update Heed. Check the network and retry.": "Não foi possível verificar ou atualizar o Heed. Verifique a rede e tente novamente.",
            "Capture permissions allowed": "Permissões de captura autorizadas",
            "Permissions need attention": "Permissões precisam de atenção",
            "Microphone restricted by device policy": "Microfone restrito pela política do dispositivo",
            "Could not verify permissions": "Não foi possível verificar as permissões",
            "Microphone permission needed": "Permissão de microfone necessária",
            "Screen & System Audio Recording permission needed": "Permissão de gravação de tela e áudio do sistema necessária",
            "Slack log access may need renewal": "O acesso aos logs do Slack pode precisar de nova autorização",
            "Check permissions again": "Verificar permissões novamente",
            "Permission help after updating…": "Ajuda com permissões após atualizar…",
            "Permissions after updating": "Permissões após atualizar",
            "Install Heed %@?": "Instalar o Heed %@?",
            "Heed will restart. Meeting data and settings are preserved. macOS permissions may need renewal after the update.": "O Heed será reiniciado. Os dados das reuniões e as configurações serão preservados. As permissões do macOS podem precisar de nova autorização após a atualização.",
            "Enable Heed under System Settings > Privacy & Security > Microphone and Screen & System Audio Recording. If capture still fails after updating, turn the affected permission off and on, then quit and reopen Heed. A restricted microphone requires your device administrator. Reauthorize Slack or shared folders only if their access no longer works. Heed never resets permissions automatically.": "Ative o Heed em Ajustes do Sistema > Privacidade e Segurança > Microfone e Gravação de Tela e Áudio do Sistema. Se a captura ainda falhar após atualizar, desative e reative a permissão afetada, depois encerre e reabra o Heed. Um microfone restrito exige ajuda do administrador do dispositivo. Autorize o Slack ou pastas compartilhadas novamente apenas se o acesso deixar de funcionar. O Heed nunca redefine permissões automaticamente.",
            "Services responded.": "Os serviços responderam.",
            "Retry Heed startup after checking the service and its configured port.": "Tente iniciar o Heed novamente após verificar o serviço e sua porta configurada.",
            "Heed API": "API do Heed",
            "Heed interface": "Interface do Heed",
            "Transcription engine": "Motor de transcrição",
            "Another application is using %@ port %@.": "Outro aplicativo está usando %@ na porta %@.",
            "%@ is stopped on port %@.": "%@ está parado na porta %@.",
            "%@ is starting on port %@.": "%@ está iniciando na porta %@.",
            "%@ is not healthy on port %@.": "%@ não está funcionando corretamente na porta %@.",
            "Could not diagnose %@ on port %@.": "Não foi possível diagnosticar %@ na porta %@.",
            "Application: %@": "Aplicativo: %@",
            "Check again": "Verificar novamente",
            "Close": "Fechar",
            "Service status…": "Estado dos serviços…",
            "Retry service startup": "Tentar iniciar os serviços novamente",
            "Heed preserved the other application. Stop it yourself, or configure a free allowed Heed port and retry startup. Installed app and LaunchAgent port settings must match; rerun the idle installer with those settings if necessary.": "O Heed preservou o outro aplicativo. Pare-o manualmente ou configure uma porta permitida livre para o Heed e tente iniciar novamente. As portas do aplicativo instalado e do LaunchAgent devem coincidir; se necessário, execute novamente o instalador sem reunião ativa com essas configurações.",
            "Local meeting storage": "Armazenamento local de reuniões",
            "Select mounted SMB share": "Selecionar compartilhamento SMB montado",
            "Select a folder on the mounted share. Heed uses a dedicated Heed Library subfolder.": "Selecione uma pasta no compartilhamento montado. O Heed usa uma subpasta dedicada Heed Library.",
            "Select share folder": "Selecionar pasta compartilhada",

            "Meeting detection could not save its state. Automation is disabled; stop the recording manually and reconfigure detection after fixing storage.": "Não foi possível salvar o estado da detecção. A automação está desativada; pare a gravação manualmente e reconfigure a detecção após corrigir o armazenamento.",
            "Meeting detection settings could not be read. Reconfigure detection before using it.": "Não foi possível ler as configurações da detecção. Reconfigure a detecção antes de usá-la.",
            "Waiting for reconnect — %@s": "Aguardando reconexão — %@s",
            "Automatically record Zoom meetings": "Gravar reuniões do Zoom automaticamente",
            "Automatically record Teams meetings": "Gravar reuniões do Teams automaticamente",
            "Automatically record Google Meet meetings": "Gravar reuniões do Google Meet automaticamente",
            "Authorize Accessibility": "Autorizar Acessibilidade",
            "Paused for this call": "Pausado para esta chamada",
            "Accessibility permission needed": "Permissão de Acessibilidade necessária",
            "Detection unavailable — use manual recording": "Detecção indisponível — use a gravação manual",
            "Not checked": "Não verificado",
            "Could not save meeting detection settings.": "Não foi possível salvar as configurações de detecção de reuniões.",
            "Automatic recording is waiting for capture permissions and a ready transcription model.": "A gravação automática aguarda permissões de captura e um modelo de transcrição pronto.",
            "Finish the active meeting before quitting Heed.": "Finalize a reunião ativa antes de sair do Heed.",
            "Could not check recording status. Try again before quitting.": "Não foi possível verificar a gravação. Tente novamente antes de sair.",
            "Preparing services…": "Preparando serviços…",
            "Start recording": "Iniciar gravação",
            "Stop recording": "Parar gravação",
            "Open interface": "Abrir interface",
            "Settings and permissions…": "Configurações e permissões…",
            "Automatically record Slack meetings": "Gravar reuniões do Slack automaticamente",
            "Allow Slack log access…": "Autorizar acesso aos logs do Slack…",
            "Quit menu app": "Sair do aplicativo da barra",
            "Interface language": "Idioma da interface",
            "Recording": "Gravando",
            "Processing meeting…": "Processando reunião…",
            "Waiting for the interface…": "Aguardando a interface…",
            "Ready to record": "Pronto para gravar",
            "Service unavailable — open the interface": "Serviço indisponível — abra a interface",
            "Heed recording": "Heed gravando",
            "disabled": "desativado",
            "closed": "fechado",
            "unavailable": "indisponível",
            "meeting detected": "reunião detectada",
            "waiting for the next meeting": "aguardando a próxima reunião",
            "Allow microphone access for Heed in System Settings.": "Autorize o acesso ao microfone para o Heed nos Ajustes do Sistema.",
            "Unknown authorization request.": "Solicitação de autorização desconhecida.",
            "The Slack log authorization dialog is already open.": "A janela de autorização dos logs do Slack já está aberta.",
            "Allow Slack meeting detection": "Autorizar detecção de reuniões do Slack",
            "Select the Slack logs folder. Heed only reads logs to detect when a meeting starts or ends.": "Selecione a pasta de logs do Slack. O Heed só lê os logs para detectar quando uma reunião começa ou termina.",
            "Allow log access": "Autorizar acesso aos logs",
            "Slack log authorization was canceled.": "A autorização dos logs do Slack foi cancelada.",
            "Select the exact Slack logs folder; access to other folders will not be granted.": "Selecione a pasta exata de logs do Slack; o acesso a outras pastas não será autorizado.",
            "The saved authorization does not match the Slack log folder.": "A autorização salva não corresponde à pasta de logs do Slack.",
            "Could not save the interface language. Try again.": "Não foi possível salvar o idioma da interface. Tente novamente.",
            "Communication failed (HTTP %@)": "Falha na comunicação (HTTP %@)",
            "Could not restore Slack log authorization (code %@).": "Não foi possível restaurar a autorização dos logs do Slack (código %@).",
            "Access is allowed for this launch; could not save the authorization (code %@).": "O acesso está autorizado nesta execução; não foi possível salvar a autorização (código %@).",
            "Recording controller disconnected. Open the interface and check the capture before retrying.": "O controle da gravação foi desconectado. Abra a interface e verifique a captura antes de tentar novamente.",
            "Recording command expired. Open the interface and try again.": "O comando de gravação expirou. Abra a interface e tente novamente.",
            "Heed is already recording": "O Heed já está gravando",
            "Heed is not recording": "O Heed não está gravando",
            "Heed is still processing the previous recording": "O Heed ainda está processando a gravação anterior",
            "A recording command is already pending": "Já há um comando de gravação pendente"
        ],
        "fr": [
            "Recording • live text off; transcript after stop": "Enregistrement • texte en direct désactivé ; transcription après l’arrêt",
            "Recover system audio permission?": "Rétablir l’autorisation audio système ?",
            "Heed will clear only its screen and system audio permission, then restart. macOS will ask you to authorize it again. Meetings, settings and other permissions are preserved.": "Heed réinitialisera uniquement son autorisation d’écran et d’audio système, puis redémarrera. macOS vous demandera de l’autoriser à nouveau. Les réunions, les réglages et les autres autorisations seront conservés.",
            "Recover and restart": "Rétablir et redémarrer",
            "System audio permission recovery could not finish. Reopen Heed and try again after active work or updates finish.": "Le rétablissement de l’autorisation audio système n’a pas pu aboutir. Rouvrez Heed et réessayez après la fin du traitement ou des mises à jour.",
            "Updates": "Mises à jour",
            "Installed version: %@": "Version installée : %@",
            "Available version: %@": "Version disponible : %@",
            "Unknown": "Inconnue",
            "development": "développement",
            "Updates not checked": "Mises à jour non vérifiées",
            "Check for updates…": "Rechercher des mises à jour…",
            "Checking for updates…": "Recherche de mises à jour…",
            "Update available": "Mise à jour disponible",
            "Heed is up to date": "Heed est à jour",
            "Release notes": "Notes de version",
            "Update…": "Mettre à jour…",
            "Update": "Mettre à jour",
            "Cancel": "Annuler",
            "Retry update": "Réessayer la mise à jour",
            "Retry recovery": "Réessayer la récupération",
            "View update log…": "Afficher le journal de mise à jour…",
            "Downloading update…": "Téléchargement de la mise à jour…",
            "Verifying update…": "Vérification de la mise à jour…",
            "Preparing update…": "Préparation de la mise à jour…",
            "Restarting Heed…": "Redémarrage de Heed…",
            "Verifying installed services…": "Vérification des services installés…",
            "Checking capture permissions…": "Vérification des autorisations de capture…",
            "Update installed": "Mise à jour installée",
            "Finish processing, then retry the update.": "Attendez la fin du traitement puis réessayez la mise à jour.",
            "Update interrupted. Retry recovery or view the update log.": "Mise à jour interrompue. Réessayez la récupération ou consultez le journal.",
            "Release verification failed. Check again or view the update log.": "La vérification de la version a échoué. Réessayez ou consultez le journal.",
            "Upgrade the installed API with the release installer before using menu updates.": "Mettez à niveau l’API installée avec l’installateur avant d’utiliser les mises à jour du menu.",
            "This release requires a newer macOS or a compatible Mac.": "Cette version nécessite un macOS plus récent ou un Mac compatible.",
            "GitHub is limiting requests. Try again later.": "GitHub limite les requêtes. Réessayez plus tard.",
            "Update helper unavailable. Reinstall Heed or view the service status.": "L’assistant de mise à jour est indisponible. Réinstallez Heed ou consultez l’état des services.",
            "Update failed. View the log and verify the retained version.": "La mise à jour a échoué. Consultez le journal et vérifiez la version conservée.",
            "Could not check or update Heed. Check the network and retry.": "Impossible de vérifier ou mettre à jour Heed. Vérifiez le réseau et réessayez.",
            "Capture permissions allowed": "Autorisations de capture accordées",
            "Permissions need attention": "Autorisations à vérifier",
            "Microphone restricted by device policy": "Microphone restreint par la politique de l’appareil",
            "Could not verify permissions": "Impossible de vérifier les autorisations",
            "Microphone permission needed": "Autorisation du microphone nécessaire",
            "Screen & System Audio Recording permission needed": "Autorisation d’enregistrement de l’écran et de l’audio système nécessaire",
            "Slack log access may need renewal": "L’accès aux journaux Slack peut nécessiter une nouvelle autorisation",
            "Check permissions again": "Vérifier à nouveau les autorisations",
            "Permission help after updating…": "Aide sur les autorisations après la mise à jour…",
            "Permissions after updating": "Autorisations après la mise à jour",
            "Install Heed %@?": "Installer Heed %@ ?",
            "Heed will restart. Meeting data and settings are preserved. macOS permissions may need renewal after the update.": "Heed va redémarrer. Les données des réunions et les paramètres sont conservés. Les autorisations macOS peuvent devoir être renouvelées après la mise à jour.",
            "Enable Heed under System Settings > Privacy & Security > Microphone and Screen & System Audio Recording. If capture still fails after updating, turn the affected permission off and on, then quit and reopen Heed. A restricted microphone requires your device administrator. Reauthorize Slack or shared folders only if their access no longer works. Heed never resets permissions automatically.": "Activez Heed dans Réglages Système > Confidentialité et sécurité > Microphone et Enregistrement de l’écran et de l’audio système. Si la capture échoue encore après la mise à jour, désactivez puis réactivez l’autorisation concernée et redémarrez Heed. Un microphone restreint nécessite l’administrateur de l’appareil. Réautorisez Slack ou les dossiers partagés uniquement si leur accès ne fonctionne plus. Heed ne réinitialise jamais les autorisations automatiquement.",
            "Services responded.": "Les services ont répondu.",
            "Retry Heed startup after checking the service and its configured port.": "Réessayez le démarrage de Heed après avoir vérifié le service et son port configuré.",
            "Heed API": "API Heed",
            "Heed interface": "Interface Heed",
            "Transcription engine": "Moteur de transcription",
            "Another application is using %@ port %@.": "Une autre application utilise %@ sur le port %@.",
            "%@ is stopped on port %@.": "%@ est arrêté sur le port %@.",
            "%@ is starting on port %@.": "%@ démarre sur le port %@.",
            "%@ is not healthy on port %@.": "%@ ne fonctionne pas correctement sur le port %@.",
            "Could not diagnose %@ on port %@.": "Impossible de diagnostiquer %@ sur le port %@.",
            "Application: %@": "Application : %@",
            "Check again": "Vérifier à nouveau",
            "Close": "Fermer",
            "Service status…": "État des services…",
            "Retry service startup": "Réessayer le démarrage des services",
            "Heed preserved the other application. Stop it yourself, or configure a free allowed Heed port and retry startup. Installed app and LaunchAgent port settings must match; rerun the idle installer with those settings if necessary.": "Heed a préservé l’autre application. Arrêtez-la vous-même ou configurez un port autorisé libre pour Heed et réessayez le démarrage. Les ports de l’application installée et du LaunchAgent doivent correspondre ; si nécessaire, réexécutez l’installateur sans réunion active avec ces paramètres.",
            "Local meeting storage": "Stockage local des réunions",
            "Select mounted SMB share": "Sélectionner le partage SMB monté",
            "Select a folder on the mounted share. Heed uses a dedicated Heed Library subfolder.": "Sélectionnez un dossier sur le partage monté. Heed utilise un sous-dossier dédié Heed Library.",
            "Select share folder": "Sélectionner le dossier partagé",

            "Meeting detection could not save its state. Automation is disabled; stop the recording manually and reconfigure detection after fixing storage.": "Impossible d’enregistrer l’état de détection. L’automatisation est désactivée ; arrêtez manuellement l’enregistrement et reconfigurez la détection après avoir corrigé le stockage.",
            "Meeting detection settings could not be read. Reconfigure detection before using it.": "Impossible de lire les paramètres de détection. Reconfigurez la détection avant de l’utiliser.",
            "Waiting for reconnect — %@s": "En attente de reconnexion — %@s",
            "Automatically record Zoom meetings": "Enregistrer automatiquement les réunions Zoom",
            "Automatically record Teams meetings": "Enregistrer automatiquement les réunions Teams",
            "Automatically record Google Meet meetings": "Enregistrer automatiquement les réunions Google Meet",
            "Authorize Accessibility": "Autoriser l’accessibilité",
            "Paused for this call": "En pause pour cet appel",
            "Accessibility permission needed": "Autorisation d’accessibilité nécessaire",
            "Detection unavailable — use manual recording": "Détection indisponible — utilisez l’enregistrement manuel",
            "Not checked": "Non vérifié",
            "Could not save meeting detection settings.": "Impossible d’enregistrer les paramètres de détection des réunions.",
            "Automatic recording is waiting for capture permissions and a ready transcription model.": "L’enregistrement automatique attend les autorisations de capture et un modèle de transcription prêt.",
            "Finish the active meeting before quitting Heed.": "Terminez la réunion active avant de quitter Heed.",
            "Could not check recording status. Try again before quitting.": "Impossible de vérifier l’enregistrement. Réessayez avant de quitter.",
            "Preparing services…": "Préparation des services…",
            "Start recording": "Démarrer l’enregistrement",
            "Stop recording": "Arrêter l’enregistrement",
            "Open interface": "Ouvrir l’interface",
            "Settings and permissions…": "Paramètres et autorisations…",
            "Automatically record Slack meetings": "Enregistrer automatiquement les réunions Slack",
            "Allow Slack log access…": "Autoriser l’accès aux journaux Slack…",
            "Quit menu app": "Quitter l’application de la barre",
            "Interface language": "Langue de l’interface",
            "Recording": "Enregistrement",
            "Processing meeting…": "Traitement de la réunion…",
            "Waiting for the interface…": "En attente de l’interface…",
            "Ready to record": "Prêt à enregistrer",
            "Service unavailable — open the interface": "Service indisponible — ouvrez l’interface",
            "Heed recording": "Heed enregistre",
            "disabled": "désactivé",
            "closed": "fermé",
            "unavailable": "indisponible",
            "meeting detected": "réunion détectée",
            "waiting for the next meeting": "en attente de la prochaine réunion",
            "Allow microphone access for Heed in System Settings.": "Autorisez l’accès au microphone pour Heed dans les Réglages Système.",
            "Unknown authorization request.": "Demande d’autorisation inconnue.",
            "The Slack log authorization dialog is already open.": "La fenêtre d’autorisation des journaux Slack est déjà ouverte.",
            "Allow Slack meeting detection": "Autoriser la détection des réunions Slack",
            "Select the Slack logs folder. Heed only reads logs to detect when a meeting starts or ends.": "Sélectionnez le dossier des journaux Slack. Heed les lit uniquement pour détecter le début ou la fin d’une réunion.",
            "Allow log access": "Autoriser l’accès aux journaux",
            "Slack log authorization was canceled.": "L’autorisation des journaux Slack a été annulée.",
            "Select the exact Slack logs folder; access to other folders will not be granted.": "Sélectionnez le dossier exact des journaux Slack ; l’accès aux autres dossiers ne sera pas autorisé.",
            "The saved authorization does not match the Slack log folder.": "L’autorisation enregistrée ne correspond pas au dossier des journaux Slack.",
            "Could not save the interface language. Try again.": "Impossible d’enregistrer la langue de l’interface. Réessayez.",
            "Communication failed (HTTP %@)": "Échec de la communication (HTTP %@)",
            "Could not restore Slack log authorization (code %@).": "Impossible de restaurer l’autorisation des journaux Slack (code %@).",
            "Access is allowed for this launch; could not save the authorization (code %@).": "L’accès est autorisé pour cette exécution ; impossible d’enregistrer l’autorisation (code %@).",
            "Recording controller disconnected. Open the interface and check the capture before retrying.": "Le contrôleur d’enregistrement est déconnecté. Ouvrez l’interface et vérifiez la capture avant de réessayer.",
            "Recording command expired. Open the interface and try again.": "La commande d’enregistrement a expiré. Ouvrez l’interface et réessayez.",
            "Heed is already recording": "Heed enregistre déjà",
            "Heed is not recording": "Heed n’enregistre pas",
            "Heed is still processing the previous recording": "Heed traite encore l’enregistrement précédent",
            "A recording command is already pending": "Une commande d’enregistrement est déjà en attente"
        ],
        "de": [
            "Recording • live text off; transcript after stop": "Aufnahme • Live-Text aus; Transkript nach dem Stoppen",
            "Recover system audio permission?": "Systemaudio-Berechtigung wiederherstellen?",
            "Heed will clear only its screen and system audio permission, then restart. macOS will ask you to authorize it again. Meetings, settings and other permissions are preserved.": "Heed setzt nur seine Bildschirm- und Systemaudio-Berechtigung zurück und startet neu. macOS bittet Sie erneut um Erlaubnis. Besprechungen, Einstellungen und andere Berechtigungen bleiben erhalten.",
            "Recover and restart": "Wiederherstellen und neu starten",
            "System audio permission recovery could not finish. Reopen Heed and try again after active work or updates finish.": "Die Systemaudio-Berechtigung konnte nicht wiederhergestellt werden. Öffnen Sie Heed erneut und versuchen Sie es nach Abschluss der Verarbeitung oder der Updates noch einmal.",
            "Updates": "Updates",
            "Installed version: %@": "Installierte Version: %@",
            "Available version: %@": "Verfügbare Version: %@",
            "Unknown": "Unbekannt",
            "development": "Entwicklung",
            "Updates not checked": "Updates nicht geprüft",
            "Check for updates…": "Nach Updates suchen…",
            "Checking for updates…": "Updates werden gesucht…",
            "Update available": "Update verfügbar",
            "Heed is up to date": "Heed ist aktuell",
            "Release notes": "Versionshinweise",
            "Update…": "Aktualisieren…",
            "Update": "Aktualisieren",
            "Cancel": "Abbrechen",
            "Retry update": "Update erneut versuchen",
            "Retry recovery": "Wiederherstellung erneut versuchen",
            "View update log…": "Update-Protokoll anzeigen…",
            "Downloading update…": "Update wird heruntergeladen…",
            "Verifying update…": "Update wird geprüft…",
            "Preparing update…": "Update wird vorbereitet…",
            "Restarting Heed…": "Heed wird neu gestartet…",
            "Verifying installed services…": "Installierte Dienste werden geprüft…",
            "Checking capture permissions…": "Aufnahmeberechtigungen werden geprüft…",
            "Update installed": "Update installiert",
            "Finish processing, then retry the update.": "Warten Sie auf das Ende der Verarbeitung und versuchen Sie das Update erneut.",
            "Update interrupted. Retry recovery or view the update log.": "Update unterbrochen. Versuchen Sie die Wiederherstellung oder öffnen Sie das Protokoll.",
            "Release verification failed. Check again or view the update log.": "Versionsprüfung fehlgeschlagen. Prüfen Sie erneut oder öffnen Sie das Protokoll.",
            "Upgrade the installed API with the release installer before using menu updates.": "Aktualisieren Sie die installierte API mit dem Installationsprogramm, bevor Sie Menü-Updates verwenden.",
            "This release requires a newer macOS or a compatible Mac.": "Diese Version benötigt ein neueres macOS oder einen kompatiblen Mac.",
            "GitHub is limiting requests. Try again later.": "GitHub begrenzt Anfragen. Versuchen Sie es später erneut.",
            "Update helper unavailable. Reinstall Heed or view the service status.": "Update-Helfer nicht verfügbar. Installieren Sie Heed erneut oder prüfen Sie den Dienststatus.",
            "Update failed. View the log and verify the retained version.": "Update fehlgeschlagen. Prüfen Sie das Protokoll und die beibehaltene Version.",
            "Could not check or update Heed. Check the network and retry.": "Heed konnte nicht geprüft oder aktualisiert werden. Prüfen Sie das Netzwerk und versuchen Sie es erneut.",
            "Capture permissions allowed": "Aufnahmeberechtigungen erteilt",
            "Permissions need attention": "Berechtigungen müssen geprüft werden",
            "Microphone restricted by device policy": "Mikrofon durch Geräterichtlinie eingeschränkt",
            "Could not verify permissions": "Berechtigungen konnten nicht geprüft werden",
            "Microphone permission needed": "Mikrofonberechtigung erforderlich",
            "Screen & System Audio Recording permission needed": "Berechtigung für Bildschirm- und Systemaudioaufnahme erforderlich",
            "Slack log access may need renewal": "Zugriff auf Slack-Protokolle muss eventuell erneut erlaubt werden",
            "Check permissions again": "Berechtigungen erneut prüfen",
            "Permission help after updating…": "Hilfe zu Berechtigungen nach dem Update…",
            "Permissions after updating": "Berechtigungen nach dem Update",
            "Install Heed %@?": "Heed %@ installieren?",
            "Heed will restart. Meeting data and settings are preserved. macOS permissions may need renewal after the update.": "Heed wird neu gestartet. Besprechungsdaten und Einstellungen bleiben erhalten. macOS-Berechtigungen müssen nach dem Update eventuell erneut erteilt werden.",
            "Enable Heed under System Settings > Privacy & Security > Microphone and Screen & System Audio Recording. If capture still fails after updating, turn the affected permission off and on, then quit and reopen Heed. A restricted microphone requires your device administrator. Reauthorize Slack or shared folders only if their access no longer works. Heed never resets permissions automatically.": "Aktivieren Sie Heed unter Systemeinstellungen > Datenschutz und Sicherheit > Mikrofon und Bildschirm- und Systemaudioaufnahme. Falls die Aufnahme nach dem Update weiter fehlschlägt, schalten Sie die betroffene Berechtigung aus und wieder ein und starten Sie Heed neu. Ein eingeschränktes Mikrofon erfordert den Geräteadministrator. Erlauben Sie Slack oder freigegebene Ordner erneut nur, wenn der Zugriff nicht mehr funktioniert. Heed setzt Berechtigungen niemals automatisch zurück.",
            "Services responded.": "Die Dienste haben geantwortet.",
            "Retry Heed startup after checking the service and its configured port.": "Prüfen Sie den Dienst und seinen konfigurierten Port und versuchen Sie anschließend erneut, Heed zu starten.",
            "Heed API": "Heed-API",
            "Heed interface": "Heed-Oberfläche",
            "Transcription engine": "Transkriptionsengine",
            "Another application is using %@ port %@.": "Eine andere Anwendung verwendet %@ auf Port %@.",
            "%@ is stopped on port %@.": "%@ ist auf Port %@ angehalten.",
            "%@ is starting on port %@.": "%@ startet auf Port %@.",
            "%@ is not healthy on port %@.": "%@ funktioniert auf Port %@ nicht ordnungsgemäß.",
            "Could not diagnose %@ on port %@.": "%@ auf Port %@ konnte nicht diagnostiziert werden.",
            "Application: %@": "Anwendung: %@",
            "Check again": "Erneut prüfen",
            "Close": "Schließen",
            "Service status…": "Dienststatus…",
            "Retry service startup": "Dienststart erneut versuchen",
            "Heed preserved the other application. Stop it yourself, or configure a free allowed Heed port and retry startup. Installed app and LaunchAgent port settings must match; rerun the idle installer with those settings if necessary.": "Heed hat die andere Anwendung unverändert gelassen. Beenden Sie sie selbst oder konfigurieren Sie einen freien zulässigen Heed-Port und versuchen Sie den Start erneut. Die Port-Einstellungen der installierten App und des LaunchAgent müssen übereinstimmen; führen Sie bei Bedarf das Installationsprogramm ohne aktive Besprechung mit diesen Einstellungen erneut aus.",
            "Local meeting storage": "Lokaler Besprechungsspeicher",
            "Select mounted SMB share": "Eingebundene SMB-Freigabe auswählen",
            "Select a folder on the mounted share. Heed uses a dedicated Heed Library subfolder.": "Wählen Sie einen Ordner auf der eingebundenen Freigabe aus. Heed verwendet einen eigenen Unterordner Heed Library.",
            "Select share folder": "Freigabeordner auswählen",

            "Meeting detection could not save its state. Automation is disabled; stop the recording manually and reconfigure detection after fixing storage.": "Der Erkennungsstatus konnte nicht gespeichert werden. Die Automatisierung ist deaktiviert; beenden Sie die Aufnahme manuell und konfigurieren Sie die Erkennung nach Beheben des Speicherproblems erneut.",
            "Meeting detection settings could not be read. Reconfigure detection before using it.": "Die Erkennungseinstellungen konnten nicht gelesen werden. Konfigurieren Sie die Erkennung vor der Nutzung erneut.",
            "Waiting for reconnect — %@s": "Warten auf Wiederverbindung — %@s",
            "Automatically record Zoom meetings": "Zoom-Besprechungen automatisch aufnehmen",
            "Automatically record Teams meetings": "Teams-Besprechungen automatisch aufnehmen",
            "Automatically record Google Meet meetings": "Google-Meet-Besprechungen automatisch aufnehmen",
            "Authorize Accessibility": "Bedienungshilfen erlauben",
            "Paused for this call": "Für diesen Anruf pausiert",
            "Accessibility permission needed": "Berechtigung für Bedienungshilfen erforderlich",
            "Detection unavailable — use manual recording": "Erkennung nicht verfügbar — manuell aufnehmen",
            "Not checked": "Nicht geprüft",
            "Could not save meeting detection settings.": "Die Einstellungen der Besprechungserkennung konnten nicht gespeichert werden.",
            "Automatic recording is waiting for capture permissions and a ready transcription model.": "Die automatische Aufnahme wartet auf Aufnahmeberechtigungen und ein bereites Transkriptionsmodell.",
            "Finish the active meeting before quitting Heed.": "Beenden Sie die aktive Besprechung, bevor Sie Heed schließen.",
            "Could not check recording status. Try again before quitting.": "Der Aufnahmestatus konnte nicht geprüft werden. Versuchen Sie es vor dem Beenden erneut.",
            "Preparing services…": "Dienste werden vorbereitet…",
            "Start recording": "Aufnahme starten",
            "Stop recording": "Aufnahme beenden",
            "Open interface": "Oberfläche öffnen",
            "Settings and permissions…": "Einstellungen und Berechtigungen…",
            "Automatically record Slack meetings": "Slack-Besprechungen automatisch aufnehmen",
            "Allow Slack log access…": "Zugriff auf Slack-Protokolle erlauben…",
            "Quit menu app": "Menüleisten-App beenden",
            "Interface language": "Sprache der Oberfläche",
            "Recording": "Aufnahme läuft",
            "Processing meeting…": "Besprechung wird verarbeitet…",
            "Waiting for the interface…": "Warten auf die Oberfläche…",
            "Ready to record": "Bereit zur Aufnahme",
            "Service unavailable — open the interface": "Dienst nicht verfügbar — Oberfläche öffnen",
            "Heed recording": "Heed nimmt auf",
            "disabled": "deaktiviert",
            "closed": "geschlossen",
            "unavailable": "nicht verfügbar",
            "meeting detected": "Besprechung erkannt",
            "waiting for the next meeting": "Warten auf die nächste Besprechung",
            "Allow microphone access for Heed in System Settings.": "Erlauben Sie Heed den Mikrofonzugriff in den Systemeinstellungen.",
            "Unknown authorization request.": "Unbekannte Berechtigungsanfrage.",
            "The Slack log authorization dialog is already open.": "Das Fenster zur Autorisierung der Slack-Protokolle ist bereits geöffnet.",
            "Allow Slack meeting detection": "Erkennung von Slack-Besprechungen erlauben",
            "Select the Slack logs folder. Heed only reads logs to detect when a meeting starts or ends.": "Wählen Sie den Slack-Protokollordner. Heed liest die Protokolle nur, um Beginn und Ende einer Besprechung zu erkennen.",
            "Allow log access": "Protokollzugriff erlauben",
            "Slack log authorization was canceled.": "Die Autorisierung der Slack-Protokolle wurde abgebrochen.",
            "Select the exact Slack logs folder; access to other folders will not be granted.": "Wählen Sie den genauen Slack-Protokollordner; Zugriff auf andere Ordner wird nicht gewährt.",
            "The saved authorization does not match the Slack log folder.": "Die gespeicherte Autorisierung entspricht nicht dem Slack-Protokollordner.",
            "Could not save the interface language. Try again.": "Die Sprache der Oberfläche konnte nicht gespeichert werden. Versuchen Sie es erneut.",
            "Communication failed (HTTP %@)": "Kommunikation fehlgeschlagen (HTTP %@)",
            "Could not restore Slack log authorization (code %@).": "Die Autorisierung der Slack-Protokolle konnte nicht wiederhergestellt werden (Code %@).",
            "Access is allowed for this launch; could not save the authorization (code %@).": "Der Zugriff ist für diesen Start erlaubt; die Autorisierung konnte nicht gespeichert werden (Code %@).",
            "Recording controller disconnected. Open the interface and check the capture before retrying.": "Die Aufnahmesteuerung wurde getrennt. Öffnen Sie die Oberfläche und prüfen Sie die Aufnahme, bevor Sie es erneut versuchen.",
            "Recording command expired. Open the interface and try again.": "Der Aufnahmebefehl ist abgelaufen. Öffnen Sie die Oberfläche und versuchen Sie es erneut.",
            "Heed is already recording": "Heed nimmt bereits auf",
            "Heed is not recording": "Heed nimmt nicht auf",
            "Heed is still processing the previous recording": "Heed verarbeitet noch die vorherige Aufnahme",
            "A recording command is already pending": "Ein Aufnahmebefehl wartet bereits auf Ausführung"
        ]
    ]
    static func text(_ key: String, locale: String) -> String { translations[normalize(locale)]?[key] ?? LiveLanguageLocalization.translations[key]?[normalize(locale)] ?? key }
    static func format(_ key: String, locale: String, value: String) -> String {
        String(format: text(key, locale: locale), value)
    }
    static func message(_ message: String, locale: String) -> String {
        if message.hasPrefix("Communication failed (HTTP "),
           let range = message.range(of: #"(?<=HTTP )[0-9]+"#, options: .regularExpression) {
            return format("Communication failed (HTTP %@)", locale: locale, value: String(message[range]))
        }
        for prefix in ["Could not restore Slack log authorization", "Access is allowed for this launch; could not save the authorization"] {
            if message.hasPrefix(prefix), let range = message.range(of: #"(?<=code )-?[0-9]+"#, options: .regularExpression) {
                return format(prefix + " (code %@).", locale: locale, value: String(message[range]))
            }
        }
        return text(message, locale: locale)
    }
    static func selfTestCoverage() {
        let keys = Set(translations["pt-BR"]!.keys)
        for locale in ["fr", "de"] { precondition(Set(translations[locale]!.keys) == keys) }
    }
}

func menuLocalizationSelfTests() {
    MenuLocalization.selfTestCoverage()
    precondition(MenuLocalization.text("Start recording", locale: "fr") == "Démarrer l’enregistrement")
    precondition(MenuLocalization.text("Stop recording", locale: "pt-BR") == "Parar gravação")
    precondition(MenuLocalization.text("Ready to record", locale: "de") == "Bereit zur Aufnahme")
    precondition(MenuLocalization.text("Start recording", locale: "en") == "Start recording")
    precondition(MenuLocalization.normalize("es") == "en")
    precondition(MenuLocalization.normalize(nil) == "en")
    precondition(MenuLocalization.message("Communication failed (HTTP 500)", locale: "de") == "Kommunikation fehlgeschlagen (HTTP 500)")
    precondition(MenuLocalization.message("Could not restore Slack log authorization (code -1).", locale: "pt-BR").contains("código -1"))
    precondition(MenuLocalization.text("Unknown technical detail", locale: "fr") == "Unknown technical detail")
}

struct LiveLanguageLocalization {
    static let translations: [String:[String:String]] = [
        "Live speech language": ["pt-BR": "Idioma da fala ao vivo", "fr": "Langue de la parole en direct", "de": "Sprache der Live-Spracherkennung"],
        "English": ["pt-BR": "Inglês", "fr": "Anglais", "de": "Englisch"],
        "Brazilian Portuguese": ["pt-BR": "Português brasileiro", "fr": "Portugais brésilien", "de": "Brasilianisches Portugiesisch"],
        "This changes live speech recognition, independently of the interface language. It does not turn real-time transcription on.": ["pt-BR": "Altera o reconhecimento da fala ao vivo, independentemente do idioma da interface. Não ativa a transcrição em tempo real.", "fr": "Modifie la reconnaissance vocale en direct, indépendamment de la langue de l’interface. N’active pas la transcription en temps réel.", "de": "Ändert die Live-Spracherkennung unabhängig von der Oberflächensprache. Aktiviert keine Echtzeittranskription."],
        "Live engine: {engine} • model: {model}": ["pt-BR": "Motor ao vivo: {engine} • modelo: {model}", "fr": "Moteur en direct : {engine} • modèle : {model}", "de": "Live-Engine: {engine} • Modell: {model}"],
        "Final engine: {engine} • model: {model}": ["pt-BR": "Motor final: {engine} • modelo: {model}", "fr": "Moteur final : {engine} • modèle : {model}", "de": "Finale Engine: {engine} • Modell: {model}"],
        "English-only models (.en) cannot preview Portuguese.": ["pt-BR": "Modelos exclusivos para inglês (.en) não transcrevem português ao vivo.", "fr": "Les modèles uniquement anglais (.en) ne transcrivent pas le portugais en direct.", "de": "Nur englische Modelle (.en) können Portugiesisch nicht live transkribieren."],
        "The final transcript automatically detects English or Portuguese. Mixed-language accuracy has not been verified.": ["pt-BR": "A transcrição final detecta inglês ou português automaticamente. A precisão com idiomas mistos não foi verificada.", "fr": "La transcription finale détecte automatiquement l’anglais ou le portugais. La précision multilingue n’a pas été vérifiée.", "de": "Die finale Transkription erkennt Englisch oder Portugiesisch automatisch. Die Genauigkeit bei gemischten Sprachen wurde nicht geprüft."],
        "Active recording: {language}. Changes apply to the next recording.": ["pt-BR": "Gravação ativa: {language}. As alterações valem para a próxima gravação.", "fr": "Enregistrement actif : {language}. Les modifications s’appliquent au prochain enregistrement.", "de": "Aktive Aufnahme: {language}. Änderungen gelten für die nächste Aufnahme."],
        "Saved. Live speech language applies to the next recording.": ["pt-BR": "Salvo. O idioma da fala ao vivo vale para a próxima gravação.", "fr": "Enregistré. La langue de la parole en direct s’applique au prochain enregistrement.", "de": "Gespeichert. Die Live-Sprache gilt für die nächste Aufnahme."],
        "The live model does not support this language. Choose a compatible model or record final-only.": ["pt-BR": "O modelo ao vivo não suporta este idioma. Escolha um modelo compatível ou grave apenas para transcrição final.", "fr": "Le modèle en direct ne prend pas en charge cette langue. Choisissez un modèle compatible ou enregistrez pour la transcription finale uniquement.", "de": "Das Live-Modell unterstützt diese Sprache nicht. Wählen Sie ein kompatibles Modell oder nehmen Sie nur für die finale Transkription auf."],
        "Live language capabilities are unavailable. Retry when the service is ready or record final-only.": ["pt-BR": "Os recursos de idioma ao vivo estão indisponíveis. Tente novamente quando o serviço estiver pronto ou grave apenas para transcrição final.", "fr": "Les capacités linguistiques en direct sont indisponibles. Réessayez lorsque le service est prêt ou enregistrez pour la transcription finale uniquement.", "de": "Die Live-Sprachfunktionen sind nicht verfügbar. Versuchen Sie es erneut, wenn der Dienst bereit ist, oder nehmen Sie nur für die finale Transkription auf."],
        "Could not load live speech language. Reopen Settings and try again.": ["pt-BR": "Não foi possível carregar o idioma da fala ao vivo. Reabra Configurações e tente novamente.", "fr": "Impossible de charger la langue de la parole en direct. Rouvrez les paramètres et réessayez.", "de": "Die Live-Sprache konnte nicht geladen werden. Öffnen Sie die Einstellungen erneut."],
        "Could not save live speech language. Try again.": ["pt-BR": "Não foi possível salvar o idioma da fala ao vivo. Tente novamente.", "fr": "Impossible d’enregistrer la langue de la parole en direct. Réessayez.", "de": "Die Live-Sprache konnte nicht gespeichert werden. Versuchen Sie es erneut."],
        "Record final-only (keeps real-time off)": ["pt-BR": "Gravar apenas para transcrição final (mantém o tempo real desativado)", "fr": "Enregistrer pour la transcription finale uniquement (garde le temps réel désactivé)", "de": "Nur final aufnehmen (Echtzeit bleibt ausgeschaltet)"],
        "Real-time transcription is now off for future recordings. Change it in Settings to turn it on again.": ["pt-BR": "A transcrição em tempo real está desativada para as próximas gravações. Altere em Configurações para ativá-la novamente.", "fr": "La transcription en temps réel est désactivée pour les prochains enregistrements. Réactivez-la dans les paramètres.", "de": "Die Echtzeittranskription ist für zukünftige Aufnahmen ausgeschaltet. Aktivieren Sie sie wieder in den Einstellungen."],
        "Live speech language is configured in Settings. The final transcript automatically detects English or Portuguese.": ["pt-BR": "O idioma da fala ao vivo é configurado em Configurações. A transcrição final detecta inglês ou português automaticamente.", "fr": "La langue de la parole en direct se configure dans les paramètres. La transcription finale détecte automatiquement l’anglais ou le portugais.", "de": "Die Live-Sprache wird in den Einstellungen gewählt. Die finale Transkription erkennt Englisch oder Portugiesisch automatisch."],
        "Provisional live text: {language} • {engine} / {model}": ["pt-BR": "Texto ao vivo provisório: {language} • {engine} / {model}", "fr": "Texte provisoire en direct : {language} • {engine} / {model}", "de": "Vorläufiger Live-Text: {language} • {engine} / {model}"],
        "Initial model: {model}": ["pt-BR": "Modelo inicial: {model}", "fr": "Modèle initial : {model}", "de": "Anfängliches Modell: {model}"]
    ]
}
