import {afterEach,expect,test} from 'bun:test';
import {mkdtempSync,mkdirSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {ManagedQuota} from './managed-quota';import {atomicWriteJson,setAtomicWriteBudget} from './atomic-json';import {reserveCapture,releaseCapture} from './capture-quota';
const directories:string[]=[];afterEach(()=>{setAtomicWriteBudget(undefined);for(const dir of directories.splice(0))rmSync(dir,{recursive:true,force:true});});
function fixture(limit=2_000_000){const dir=mkdtempSync(join(tmpdir(),'heed-capture-quota-'));directories.push(dir);const media=join(dir,'media'),staging=join(dir,'staging');mkdirSync(media);mkdirSync(staging);const text=join(dir,'text');mkdirSync(text);const quota=new ManagedQuota({ledgerPath:join(dir,'quota.json'),roots:{media:[media],staging:[staging],text:[text]},getLimit:()=>limit,setLimit:()=>{},protectedPaths:()=>[]});return {quota,path:join(media,'capture.wav'),work:join(staging,'capture'),metadataPaths:[join(text,'session.json'),join(text,'manifest.json'),join(text,'recovery.json')]};}
test('capture allowance derives from available device quota and includes finalization copies',()=>{const f=fixture();const allocation=reserveCapture(f.quota,'meeting',f.path,f.work,f.metadataPaths);expect(allocation.maxCaptureBytes).toBeGreaterThan(44);expect(allocation.reservedBytes).toBe(allocation.maxCaptureBytes*4+allocation.metadataHeadroom);expect(f.quota.snapshot().reservedBytes).toBe(allocation.reservedBytes);expect(f.quota.snapshot().availableBytes).toBeLessThan(4);expect(()=>f.quota.reserve('download',2_000_000,[])).toThrow('quota');});
test('pending capture reservations resume idempotently across restart and release after durable saving',()=>{const f=fixture();const first=reserveCapture(f.quota,'meeting',f.path,f.work,f.metadataPaths);writeFileSync(f.path,'x'.repeat(100));expect(reserveCapture(f.quota,'meeting',f.path,f.work,f.metadataPaths)).toEqual(first);releaseCapture(f.quota,'meeting');expect(f.quota.snapshot().reservedBytes).toBe(0);expect(f.quota.snapshot().usedBytes).toBe(100);});
test('protected work exhausting quota prevents capture before an audio writer starts',()=>{const f=fixture(100);expect(()=>reserveCapture(f.quota,'meeting',f.path,f.work,f.metadataPaths)).toThrow('quota');expect(f.quota.snapshot().reservedBytes).toBe(0);});

test('capture final metadata keeps its own claimed allowance while unrelated jobs cannot consume it',()=>{const f=fixture();const allocation=reserveCapture(f.quota,'meeting',f.path,f.work,f.metadataPaths);expect(()=>f.quota.reserve('other',allocation.metadataHeadroom,[])).toThrow('quota');setAtomicWriteBudget((path,bytes,tmp)=>f.quota.atomicWriteBudget(path,bytes,tmp));atomicWriteJson(f.metadataPaths[0],{transcript:'Durably finalized'});expect(f.quota.snapshot().usedBytes).toBeGreaterThan(0);expect(f.quota.snapshot().usedBytes+f.quota.snapshot().reservedBytes).toBeLessThanOrEqual(2_000_000);});
