import {expect,test} from 'bun:test';
import {existsSync,mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {createHash,randomUUID} from 'node:crypto';
const repository=resolve(import.meta.dir,'../../..');
test('real local upload persists metadata, seekable audio and transcript-only cleanup without modifying the original',async()=>{
 const temporary=mkdtempSync(join(tmpdir(),'heed-import-workflow-')),appRoot=join(temporary,'app');mkdirSync(appRoot);writeFileSync(join(appRoot,'config.json'),JSON.stringify({storage_limit_bytes:20_000_000}));
 const original=join(temporary,'original-misleading.mp4'),wav=Buffer.alloc(128044);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);writeFileSync(original,wav);
 const digest=()=>createHash('sha256').update(readFileSync(original)).digest('hex'),before=digest();let pipelineCalls=0;let releaseSpeech:()=>void=()=>{};const speechGate=new Promise<void>(resolve=>{releaseSpeech=resolve;});
 const sidecar=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){if(new URL(request.url).pathname==='/finalize-import'){pipelineCalls++;const body=await request.json();if(pipelineCalls===1)await speechGate;return new Response(`event: phase\ndata: ${JSON.stringify({phase:'diarization'})}\n\nevent: phase\ndata: ${JSON.stringify({phase:'transcription'})}\n\nevent: result\ndata: ${JSON.stringify({finalized:true,duration:4,language:body.language==='pt'?'pt':'en',model:body.final_model,turns:[{start:1,end:3,text:'Synthetic test only',speaker:'Speaker 1',channel:'mic'}],embeddings:{}})}\n\n`,{headers:{'Content-Type':'text/event-stream'}});}return Response.json({});}});
 const portLease=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response()});const base=`http://127.0.0.1:${portLease.port}`;portLease.stop(true);
 const env={...process.env,PORT:base.split(':').at(-1)!,HEED_APP_DIR:appRoot,HEED_RECORDINGS_DIR:join(appRoot,'media'),HEED_TRANSCRIPTION_URL:String(sidecar.url).replace(/\/$/,''),OLLAMA_HOST:String(sidecar.url).replace(/\/$/,'')};for(const key of ['HEED_API_PORT','HEED_UI_PORT','HEED_TRANSCRIPTION_PORT','HEED_SERVICE_CONFIG_ROOT'])delete env[key];
 const app=Bun.spawn([process.execPath,join(repository,'packages/server/server.ts')],{cwd:repository,env,stdout:'ignore',stderr:'pipe'}),diagnostics=new Response(app.stderr).text();
 try{
  let ready=false;for(let i=0;i<200&&app.exitCode===null;i++){try{if((await fetch(`${base}/api/sessions`)).ok){ready=true;break;}}catch{}await Bun.sleep(25);}if(!ready)throw Error(`Import fixture startup failed: ${await diagnostics}`);
  for(const meetingMode of ['audio-transcript','transcript-only']){
   const requestId=randomUUID(),form=new FormData();form.append('requestId',requestId);form.append('file',new File([wav],'original-misleading.mp4'));form.append('model','base');form.append('language',meetingMode==='transcript-only'?'pt':'en');form.append('meetingMode',meetingMode);
   const response=await fetch(`${base}/api/media/imports`,{method:'POST',headers:{'X-Heed-Import-Id':requestId,'X-Heed-Import-Size':String(wav.length)},body:form});expect(response.status).toBe(202);const job=await response.json();if(meetingMode==='audio-transcript'){for(let i=0;i<100&&pipelineCalls===0;i++)await Bun.sleep(10);const managedPath=join(appRoot,'media',`import-${job.id}.wav`);const recovery=await (await fetch(`${base}/api/recovery/list`)).json();expect(recovery.recordings.some((entry:any)=>entry.path===managedPath)).toBe(false);expect((await fetch(`${base}/api/recovery/discard?path=${encodeURIComponent(managedPath)}`,{method:'DELETE'})).status).toBe(409);expect(existsSync(managedPath)).toBe(true);releaseSpeech();}let state:any;
   for(let i=0;i<200;i++){state=await (await fetch(`${base}/api/media/imports/${job.id}`)).json();if(['completed','failed','cancelled'].includes(state.state))break;await Bun.sleep(25);}expect(state.state).toBe('completed');
   const sessions=await (await fetch(`${base}/api/sessions`)).json();const saved=sessions.find((session:any)=>session.id===state.sessionId);expect(saved).toMatchObject({duration:4,transcriptionModel:'base',meetingMode,transcriptFinalized:true});expect(saved.segments[0]).toMatchObject({start:1,end:3});
   const audio=await fetch(`${base}/api/sessions/${saved.id}/audio`,{headers:{Range:'bytes=44-63'}});
   if(meetingMode==='audio-transcript'){expect(existsSync(saved.files.wav)).toBe(true);expect(audio.status).toBe(206);expect((await audio.arrayBuffer()).byteLength).toBe(20);}else{expect(saved.audioCleanup.status).toBe('completed');expect(saved.audioUnavailableReason).toBe('transcript-only');expect(saved.files.wav).toBe('');expect(audio.status).toBe(410);expect(audio.headers.get("X-Heed-Audio-Unavailable-Reason")).toBe("transcript-only");}
   expect(existsSync(join(appRoot,'library/staging',`media-import-${job.id}`))).toBe(false);expect(digest()).toBe(before);
  }
  expect(pipelineCalls).toBe(2);expect((await (await fetch(`${base}/api/storage`)).json()).reservedBytes).toBe(0);
 }finally{releaseSpeech();app.kill();await app.exited;await diagnostics;sidecar.stop(true);rmSync(temporary,{recursive:true,force:true});}
},15000);
