import {afterEach, expect, test} from 'bun:test';
import {existsSync,mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {ManagedQuota} from './managed-quota';
import {MediaImportController} from './media-import';
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
function fixture(overrides:any={}) {const root=mkdtempSync(join(tmpdir(),'heed-import-'));roots.push(root);const recordings=join(root,'recordings'),staging=join(root,'staging'),jobs=join(root,'catalog','imports');for(const path of [recordings,staging,jobs])mkdirSync(path,{recursive:true});const quota=new ManagedQuota({ledgerPath:join(root,'quota.json'),roots:{media:[recordings],staging:[staging],text:[join(root,'catalog')]},getLimit:()=>20_000_000,setLimit(){},protectedPaths:()=>[]});const sessions=new Map<string,any>();let runs=0;const options={jobsDirectory:jobs,recordingsDirectory:recordings,stagingDirectory:staging,quota,isBusy:()=>false,probe:async()=>({duration:2,normalizedBytes:64044}),normalize:async (_source:string,wav:string)=>{await Bun.write(wav,Buffer.alloc(64044));},transcribe:async(_wav:string,_work:string,_config:any,onPhase:any)=>{runs++;onPhase('diarization');return {success:true,finalized:true,duration:2,text:'Synthetic',segments:[{speaker:'Speaker 1',text:'Synthetic',start:0,end:2}],speakers:['Speaker 1'],metadata:{language:'en',model:'base'},files:{wav:_wav,srt:'',txt:''},wordCount:1};},save:(session:any)=>{sessions.set(session.id,session);return session;},readSession:(id:string)=>sessions.get(id),cleanup:(session:any)=>session,...overrides};return {root,quota,sessions,options,controller:new MediaImportController(options),runs:()=>runs};}
const config={model:'base',language:'en',meetingMode:'audio-transcript'} as const;
const id='11111111-1111-4111-8111-111111111111';
async function finish(controller:any){for(let i=0;i<100&&(controller as any).active;i++)await Bun.sleep(5);expect((controller as any).active).toBeUndefined();expect(controller.busy).toBe(controller.list().some((job:any)=>job.workerUnconfirmed));}
test('a retry uses its durable submission identity and saves one normal meeting',async()=>{const f=fixture();const file=new File(['synthetic'],'misleading.mp4');const first=await f.controller.submit(id,file,config);await finish(f.controller);const retry=await f.controller.submit(id,file,config);expect(retry.id).toBe(first.id);expect(f.sessions.size).toBe(1);expect(f.runs()).toBe(1);expect(f.controller.get(first.id).state).toBe('completed');expect([...f.sessions.values()][0].duration).toBe(2);expect(f.quota.snapshot().reservedBytes).toBe(0);});
test('active recording rejects import before managed copies or claims',async()=>{const f=fixture({isBusy:()=>true});await expect(f.controller.submit(id,new File(['synthetic'],'audio.wav'),config)).rejects.toThrow('recording');expect(f.controller.list()).toHaveLength(0);expect(f.quota.snapshot().reservedBytes).toBe(0);});
test('cancellation waits for processing completion before deleting owned copies',async()=>{let done!:()=>void;const pending=new Promise<void>(resolve=>{done=resolve;});const f=fixture({transcribe:async(wav:string)=>{await pending;return {success:true,finalized:true,duration:2,text:'Synthetic',metadata:{language:'en',model:'base'},speakers:[],segments:[],files:{wav,srt:'',txt:''},wordCount:1};}});const job=await f.controller.submit(id,new File(['synthetic'],'audio.wav'),config);for(let i=0;i<100&&f.controller.get(job.id).phase!=='transcription';i++)await Bun.sleep(5);await expect(f.controller.submit('22222222-2222-4222-8222-222222222222',new File(['other'],'other.wav'),config)).rejects.toThrow('recording');f.controller.cancel(job.id);expect(f.controller.get(job.id).state).toBe('cancelling');expect(f.quota.snapshot().reservedBytes).toBeGreaterThan(0);done();await finish(f.controller);expect(f.controller.get(job.id).state).toBe('cancelled');expect(f.sessions.size).toBe(0);expect(existsSync(join(f.options.recordingsDirectory,`import-${job.id}.wav`))).toBe(false);expect(f.quota.snapshot().reservedBytes).toBe(0);});
test('failed saving retains bounded audio and retries without redoing recognition',async()=>{let fail=true;const f=fixture({save:(session:any)=>{if(fail)throw Error('Synthetic save failed');f.sessions.set(session.id,session);return session;}});const job=await f.controller.submit(id,new File(['synthetic'],'audio.wav'),config);await finish(f.controller);expect(f.controller.get(job.id).state).toBe('failed');expect(f.quota.snapshot().reservedBytes).toBeGreaterThan(0);fail=false;f.controller.retry(job.id);await finish(f.controller);expect(f.runs()).toBe(1);expect(f.sessions.size).toBe(1);});

test('restart retains protected source and completed recognition for idempotent saving recovery',async()=>{const f=fixture({save:()=>{throw Error('Synthetic save failure');}});const job=await f.controller.submit(id,new File(['synthetic'],'original.wav'),config);await finish(f.controller);const recovered=new MediaImportController({...f.options,save:(session:any)=>{f.sessions.set(session.id,session);return session;}});expect(recovered.get(job.id).state).toBe('failed');expect(f.quota.snapshot().reservedBytes).toBeGreaterThan(0);recovered.retry(job.id);await finish(recovered);expect(f.runs()).toBe(1);expect(f.sessions.size).toBe(1);expect(recovered.get(job.id).state).toBe('completed');});
test('quota pressure protects pending imports and duplicate new submissions share a meeting',async()=>{const f=fixture({save:()=>{throw Error('Synthetic save failure');}});const file=new File(['synthetic'],'original.wav');const job=await f.controller.submit(id,file,config);await finish(f.controller);expect(()=>f.quota.preview(1_000_000)).toThrow('protected');expect(existsSync(join(f.options.recordingsDirectory,`import-${job.id}.wav`))).toBe(true);const duplicate=await f.controller.submit('22222222-2222-4222-8222-222222222222',file,config);expect(duplicate.id).toBe(job.id);expect(f.runs()).toBe(1);f.controller.discard(job.id);expect(f.quota.snapshot().reservedBytes).toBe(0);});
test('a shortened normalized timeline is rejected before ASR',async()=>{let probes=0;const f=fixture({probe:async()=>({duration:++probes===1?4:2,normalizedBytes:128044})});const job=await f.controller.submit(id,new File(['synthetic'],'original.wav'),config);await finish(f.controller);expect(f.controller.get(job.id).state).toBe('failed');expect(f.controller.get(job.id).error).toContain('timeline');expect(f.runs()).toBe(0);});
test('an unconfirmed worker disconnect preserves cancelled media for recovery',async()=>{let done!:()=>void;const pending=new Promise<void>(resolve=>{done=resolve;});const f=fixture({transcribe:async()=>{await pending;throw Object.assign(Error('Worker connection lost; retain protected audio.'),{workerStillRunning:true});}});const job=await f.controller.submit(id,new File(['synthetic'],'audio.wav'),config);for(let i=0;i<100&&f.controller.get(job.id).phase!=='transcription';i++)await Bun.sleep(5);f.controller.cancel(job.id);done();await finish(f.controller);expect(f.controller.get(job.id).state).toBe('failed');expect(existsSync(join(f.options.recordingsDirectory,`import-${job.id}.wav`))).toBe(true);expect(f.quota.snapshot().reservedBytes).toBeGreaterThan(0);});
test('out-of-range segment timestamps cannot become a saved meeting',async()=>{const f=fixture({transcribe:async(wav:string)=>({success:true,finalized:true,duration:2,text:'Synthetic',segments:[{speaker:'Speaker 1',text:'Synthetic',start:1,end:20}],speakers:['Speaker 1'],metadata:{language:'en',model:'base'},files:{wav,srt:'',txt:''},wordCount:1})});const job=await f.controller.submit(id,new File(['synthetic'],'audio.wav'),config);await finish(f.controller);expect(f.controller.get(job.id).state).toBe('failed');expect(f.sessions.size).toBe(0);});
test('imports freeze the effective vocabulary through retries after default changes',async()=>{let snapshot={glossaryId:'first',entries:[{term:'Heed'}]};let first=true;const seen:any[]=[];const f=fixture({vocabularySnapshot:()=>snapshot,validateVocabularySnapshot:(value:any)=>value,transcribe:async(wav:string,_work:string,_config:any,_phase:any,vocabulary:any)=>{seen.push(vocabulary);if(first){first=false;throw Error('Synthetic recognition failure');}return {success:true,finalized:true,duration:2,text:'Heed',segments:[{speaker:'Speaker 1',text:'Heed',start:0,end:2}],speakers:['Speaker 1'],metadata:{language:'en',model:'base'},files:{wav,srt:'',txt:''},wordCount:1};}});const job=await f.controller.submit(id,new File(['synthetic'],'audio.wav'),config);await finish(f.controller);snapshot={glossaryId:'second',entries:[{term:'Changed'}]};f.controller.retry(job.id);await finish(f.controller);expect(seen).toEqual([{glossaryId:'first',entries:[{term:'Heed'}]},{glossaryId:'first',entries:[{term:'Heed'}]}]);});
for(const mode of ['audio-transcript','transcript-only'] as const)test(`terminal journal failure recovers the canonical ${mode} meeting after restart`,async()=>{
 const f=fixture({cleanup:(session:any,wav:string,work:string)=>{rmSync(wav,{force:true});rmSync(work,{recursive:true,force:true});const cleaned={...session,files:{wav:''},audioCleanup:{status:'completed',requestedAt:session.audioCleanup.requestedAt,completedAt:new Date().toISOString()}};f.sessions.set(session.id,cleaned);return cleaned;}});
 const originalPersist=(f.controller as any).persist.bind(f.controller);let fail=true;(f.controller as any).persist=(job:any)=>{if(job.state==='completed'&&fail){fail=false;throw Error('Synthetic terminal receipt failure');}originalPersist(job);};
 const job=await f.controller.submit(id,new File(['synthetic'],'audio.wav'),{...config,meetingMode:mode});await finish(f.controller);
 expect(f.controller.get(job.id).state).toBe('failed');expect(f.sessions.size).toBe(1);expect(existsSync(join(f.options.stagingDirectory,`media-import-${id}`))).toBe(false);expect(f.quota.snapshot().reservedBytes).toBeGreaterThan(0);
 const recovered=new MediaImportController(f.options);recovered.retry(id);await finish(recovered);expect(recovered.get(id).state).toBe('completed');expect(f.sessions.size).toBe(1);expect(f.runs()).toBe(1);expect(f.quota.snapshot().reservedBytes).toBe(0);
});
test('interrupted normalization rebuilds its partial managed WAV on restart before ASR',async()=>{
 let normalizations=0;const f=fixture({probe:async(path:string)=>({duration:path.endsWith('.wav')&&existsSync(path)&&Bun.file(path).size===100?1:2,normalizedBytes:64044}),normalize:async(_source:string,wav:string)=>{normalizations++;await Bun.write(wav,Buffer.alloc(normalizations===1?100:64044));if(normalizations===1)throw Error('Synthetic normalization interrupted');}});
 await f.controller.submit(id,new File(['synthetic'],'source.mp4'),config);await finish(f.controller);expect(f.controller.get(id).state).toBe('failed');const recovered=new MediaImportController(f.options);recovered.retry(id);await finish(recovered);expect(recovered.get(id).state).toBe('completed');expect(normalizations).toBe(2);expect(f.runs()).toBe(1);
});
test('an uncertain worker blocks new audio admission across restart but permits its own recovery',async()=>{
 let first=true;let normalizations=0;const f=fixture({normalize:async(_source:string,wav:string)=>{normalizations++;await Bun.write(wav,Buffer.alloc(64044));},transcribe:async(wav:string)=>{if(first){first=false;throw Object.assign(Error('Synthetic worker disconnect'),{workerStillRunning:true});}return {success:true,finalized:true,duration:2,text:'Synthetic',segments:[{speaker:'Speaker 1',text:'Synthetic',start:0,end:2}],speakers:['Speaker 1'],metadata:{language:'en',model:'base'},files:{wav,srt:'',txt:''},wordCount:1};}});
 await f.controller.submit(id,new File(['synthetic'],'source.wav'),config);for(let i=0;i<100&&f.controller.get(id).state!=='failed';i++)await Bun.sleep(5);expect(f.controller.busy).toBe(true);
 const recovered=new MediaImportController(f.options);expect(recovered.busy).toBe(true);expect(()=>recovered.beginUpload('22222222-2222-4222-8222-222222222222',10)).toThrow('recording');await expect(recovered.submit('22222222-2222-4222-8222-222222222222',new File(['other'],'other.wav'),config)).rejects.toThrow('recording');recovered.retry(id);await finish(recovered);expect(recovered.get(id).state).toBe('completed');expect(normalizations).toBe(1);
});

test('persistent journal failure retains the failed owner without an unhandled background rejection',async()=>{const f=fixture();const original=(f.controller as any).persist.bind(f.controller);(f.controller as any).persist=(job:any)=>{if(job.state==='running'||job.state==='failed')throw Error('Synthetic disk unavailable');original(job);};await f.controller.submit(id,new File(['synthetic'],'audio.wav'),config);await finish(f.controller);expect(f.controller.get(id).state).toBe('failed');expect(f.controller.get(id).error).toContain('disk');expect(f.quota.snapshot().reservedBytes).toBeGreaterThan(0);});
