import {expect,test,afterEach} from 'bun:test';import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {runManagedMedia} from './media';
const dirs:string[]=[];afterEach(()=>{for(const dir of dirs.splice(0))rmSync(dir,{recursive:true,force:true});});
test('a media writer crossing its reserved source cap is reaped and cannot silently return truncated success',async()=>{const dir=mkdtempSync(join(tmpdir(),'heed-bounded-media-'));dirs.push(dir);const target=join(dir,'oversized.bin');const child=Bun.spawn([process.execPath,'-e',`require('fs').writeFileSync(${JSON.stringify(target)},Buffer.alloc(4096));setInterval(()=>{},1000)`],{stdout:'pipe',stderr:'pipe'});await expect(runManagedMedia(child,{directory:dir,maxBytes:1024})).rejects.toThrow('quota');expect(()=>process.kill(child.pid,0)).toThrow();});
test('completed bounded media preserves output and observes cancellation before accepting it',async()=>{const dir=mkdtempSync(join(tmpdir(),'heed-bounded-media-'));dirs.push(dir);writeFileSync(join(dir,'ok.bin'),'audio');const child=Bun.spawn([process.execPath,'-e','process.exit(0)'],{stdout:'pipe',stderr:'pipe'});expect((await runManagedMedia(child,{directory:dir,maxBytes:1024})).code).toBe(0);const abort=new AbortController();abort.abort();const canceled=Bun.spawn([process.execPath,'-e','setInterval(()=>{},1000)'],{stdout:'pipe',stderr:'pipe'});await expect(runManagedMedia(canceled,{directory:dir,maxBytes:1024,signal:abort.signal})).rejects.toThrow();expect(()=>process.kill(canceled.pid,0)).toThrow();});

import {probeImportMedia,normalizeAudio} from './media';

test('content probing rejects video without audio and accepts audio with a misleading extension',async()=>{if(!Bun.which('ffmpeg')||!Bun.which('ffprobe'))throw Error('FFmpeg and FFprobe are required for import media regression tests');const dir=mkdtempSync(join(tmpdir(),'heed-import-media-'));dirs.push(dir);const audio=join(dir,'misleading.mp4'),video=join(dir,'video.mp4');await Bun.spawn(['ffmpeg','-v','error','-f','lavfi','-i','sine=frequency=500:duration=2','-f','wav',audio],{stdout:'ignore',stderr:'pipe'}).exited;await Bun.spawn(['ffmpeg','-v','error','-f','lavfi','-i','color=size=32x32:duration=1','-an',video],{stdout:'ignore',stderr:'pipe'}).exited;expect((await probeImportMedia(audio,1_000_000)).duration).toBeCloseTo(2);await expect(probeImportMedia(video,1_000_000)).rejects.toThrow('audio');writeFileSync(join(dir,'corrupt.wav'),'synthetic corrupt media');await expect(probeImportMedia(join(dir,'corrupt.wav'),1_000_000)).rejects.toThrow('media');});
test('import normalization retains long silence and the source timeline',async()=>{const dir=mkdtempSync(join(tmpdir(),'heed-import-timeline-'));dirs.push(dir);const input=join(dir,'source.wav'),output=join(dir,'normalized.wav');await Bun.spawn(['ffmpeg','-v','error','-f','lavfi','-i','aevalsrc=if(lt(t\\,1)\\,0.2*sin(440*2*PI*t)\\,0):s=44100:d=4','-ac','2',input],{stdout:'ignore',stderr:'pipe'}).exited;await normalizeAudio(input,output,{directory:output,maxBytes:1_000_000},true);expect((await probeImportMedia(output,1_000_000)).duration).toBeCloseTo(4,1);expect((await probeImportMedia(input,1_000_000)).duration).toBeCloseTo(4,1);});
test('mono and stereo WAV, compressed audio and video audio normalize with preserved duration',async()=>{const dir=mkdtempSync(join(tmpdir(),'heed-import-formats-'));dirs.push(dir);for(const [name,extra]of [['mono.wav',['-ac','1']],['stereo.wav',['-ac','2']],['audio.mp3',['-c:a','libmp3lame']],['audio.m4a',['-c:a','aac']],['video.mp4',['-f','lavfi','-i','color=size=32x32:duration=2','-shortest','-c:v','libx264','-c:a','aac']],['audio.flac',[]]] as Array<[string,string[]]>){const source=join(dir,name);const writer=Bun.spawn(['ffmpeg','-v','error','-f','lavfi','-i','sine=frequency=440:duration=2',...extra,source],{stdout:'ignore',stderr:'pipe'});expect(await writer.exited).toBe(0);const probe=await probeImportMedia(source,1_000_000);expect(probe.duration).toBeGreaterThanOrEqual(1.9);const target=join(dir,`normalized-${name}.wav`);await normalizeAudio(source,target,{directory:target,maxBytes:1_000_000},true);expect((await probeImportMedia(target,1_000_000)).duration).toBeCloseTo(2,1);}});
test('missing media dependencies fail with an installation action before any processing starts',async()=>{const dir=mkdtempSync(join(tmpdir(),'heed-import-no-dependency-'));dirs.push(dir);const source=join(dir,'source.wav');writeFileSync(source,'synthetic');const child=Bun.spawn([process.execPath,'-e',`import {probeImportMedia} from ${JSON.stringify(join(import.meta.dir,'media.ts'))};try{await probeImportMedia(${JSON.stringify(source)},1000);process.exit(1);}catch(error){console.error(error.message);process.exit(error.message.includes('Install FFmpeg')?0:2);}`],{env:{...process.env,PATH:dir},stdout:'ignore',stderr:'pipe'});const message=await new Response(child.stderr).text();expect(await child.exited).toBe(0);expect(message).toContain('Install FFmpeg');});
