import {expect,test} from 'bun:test';
import {existsSync,mkdirSync,mkdtempSync,readFileSync,rmSync,symlinkSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import type {Session} from '@heed/shared';
import {cleanupMeetingAudio,discardOwnedMeetingAudio} from './meeting-audio-cleanup';
import {atomicWriteJson} from './atomic-json';
function fixture(){const root=mkdtempSync(join(tmpdir(),'heed-transcript-cleanup-')),media=join(root,'media'),staging=join(root,'staging'),work=join(staging,'capture-owned'),audioPath=join(media,'capture.wav');mkdirSync(media);mkdirSync(work,{recursive:true});for(const path of [audioPath,audioPath.replace('.wav','-mic.wav'),audioPath.replace('.wav','-sys.wav'),join(work,'derived.wav')])writeFileSync(path,'Synthetic audio');const file=join(root,'session.json');const session={id:'owned',meetingMode:'transcript-only',transcriptFinalized:true,transcript:'Synthetic authoritative transcript',files:{wav:audioPath},audioCleanup:{status:'pending',requestedAt:'2026-10-07'}} as Session;atomicWriteJson(file,session);const readSession=()=>JSON.parse(readFileSync(file,'utf8')) as Session;return {root,work,audioPath,file,readSession,options:{sessionId:'owned',readSession,saveSession:(session:Session)=>{atomicWriteJson(file,session);return session;},audioPath,workDirectory:work,recordingsRoots:[media],stagingRoot:staging}};}
test('cleanup deletes original and every owned derivative only after durable finalized pending meeting',()=>{const f=fixture();try{const result=cleanupMeetingAudio(f.options);expect(existsSync(f.audioPath)).toBe(false);expect(existsSync(f.work)).toBe(false);expect(result).toMatchObject({audioUnavailableReason:'transcript-only',audioCleanup:{status:'completed'},files:{wav:''},transcript:'Synthetic authoritative transcript'});expect(f.readSession()).toEqual(result);}finally{rmSync(f.root,{recursive:true,force:true});}});
test('missing final save never deletes audio; symlink audio/staging is rejected before any mutation',()=>{const f=fixture();try{expect(()=>cleanupMeetingAudio({...f.options,readSession:()=>null})).toThrow('saved');expect(existsSync(f.audioPath)).toBe(true);const outside=join(f.root,'private.wav');writeFileSync(outside,'Private original');rmSync(f.audioPath);symlinkSync(outside,f.audioPath);expect(()=>cleanupMeetingAudio(f.options)).toThrow('symbolic');expect(readFileSync(outside,'utf8')).toBe('Private original');expect(existsSync(f.work)).toBe(true);}finally{rmSync(f.root,{recursive:true,force:true});}});
test('post-deletion metadata fault stays pending and retry confirms already absent files without changing transcript',()=>{const f=fixture();try{expect(()=>cleanupMeetingAudio({...f.options,saveSession:()=>{throw Error('Synthetic metadata fault');}})).toThrow('metadata');expect(f.readSession().audioCleanup?.status).toBe('pending');const result=cleanupMeetingAudio(f.options);expect(result.audioCleanup?.status).toBe('completed');expect(result.transcript).toBe('Synthetic authoritative transcript');expect(cleanupMeetingAudio(f.options)).toEqual(result);}finally{rmSync(f.root,{recursive:true,force:true});}});
test('discard refuses a path outside managed roots and preserves user source',()=>{const f=fixture();try{const outside=join(f.root,'user-original.wav');writeFileSync(outside,'User audio');expect(()=>discardOwnedMeetingAudio({...f.options,audioPath:outside})).toThrow('managed');expect(readFileSync(outside,'utf8')).toBe('User audio');expect(existsSync(f.work)).toBe(true);}finally{rmSync(f.root,{recursive:true,force:true});}});
