import {test,expect,afterEach} from 'bun:test';import {mkdtempSync,mkdirSync,writeFileSync,existsSync,readFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {SessionTags} from './session-tags';import {migrateLegacyAudio,migrationProtectedPaths} from './portable-migration';import type {Session,TranscribeResult} from '@heed/shared';
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));
function fixture(){const root=mkdtempSync(join(tmpdir(),'heed-migration-'));roots.push(root);const recordings=join(root,'recordings'),sessionsDir=join(root,'sessions'),libraryRoot=join(root,'library');mkdirSync(recordings);mkdirSync(sessionsDir);const source=join(recordings,'legacy.wav');writeFileSync(source,Buffer.from([0,255,1,254,2,253]));const sessions=new SessionTags(sessionsDir);for(const id of ['session-old','session-other'])sessions.create({id,title:'Legacy',createdAt:'2026-01-01T00:00:00Z',tags:[],files:{wav:source}} as unknown as Session);const claims=new Set<string>();const quota={reserve:(id:string)=>{claims.add(id);},release:(id:string)=>{claims.delete(id);}};return {root,source,sessions,claims,options:{libraryRoot,recordingsDir:recordings,sessionsDir,sessions,quota,protectedPaths:()=>[] as string[]}};}
test('verified binary migration changes every reference before deleting legacy source',async()=>{const f=fixture(),bytes=readFileSync(f.source);const result=await migrateLegacyAudio(f.options);expect(result.migrated).toBe(2);expect(existsSync(f.source)).toBe(false);const paths=f.sessions.snapshot().sessions.map(s=>s.files!.wav!);expect(new Set(paths).size).toBe(1);expect(readFileSync(paths[0]!)).toEqual(bytes);expect(f.claims.size).toBe(0);expect((await migrateLegacyAudio(f.options)).migrated).toBe(0);});
test('quota/final reference failures preserve source and durable recoverable target until retry',async()=>{const f=fixture(),save=f.sessions.save.bind(f.sessions);let count=0;f.sessions.save=session=>{if(++count===2)throw new Error('Rejected write');return save(session);};const result=await migrateLegacyAudio(f.options);expect(result.pending).toBe(1);expect(existsSync(f.source)).toBe(true);expect(migrationProtectedPaths(f.options.libraryRoot)).toContain(f.source);f.sessions.save=save;await migrateLegacyAudio(f.options);expect(existsSync(f.source)).toBe(false);expect(f.claims.size).toBe(0);});
test('active capture and paths outside legacy root remain untouched',async()=>{const f=fixture();f.options.protectedPaths=()=>[f.source];expect((await migrateLegacyAudio(f.options)).migrated).toBe(0);expect(existsSync(f.source)).toBe(true);});
test('completed migration history is pruned and oversized pending journals fail closed',async()=>{const f=fixture();mkdirSync(join(f.options.libraryRoot,'catalog'),{recursive:true});const ledger=join(f.options.libraryRoot,'catalog/migrations.json');writeFileSync(ledger,JSON.stringify({version:1,plans:Array.from({length:10001},()=>({source:f.source,target:join(f.options.libraryRoot,'media/old.wav'),hash:'a'.repeat(64),bytes:6,complete:true}))}));await migrateLegacyAudio(f.options);expect(JSON.parse(readFileSync(ledger,'utf8')).plans).toHaveLength(0);writeFileSync(ledger,JSON.stringify({version:1,plans:Array.from({length:10001},()=>({source:f.source,target:join(f.options.libraryRoot,'media/old.wav'),hash:'a'.repeat(64),bytes:6,complete:false}))}));expect(()=>migrationProtectedPaths(f.options.libraryRoot)).toThrow('journal');});
test('audio migration preserves local accepted history, guard, pending candidates and terminal receipts',async()=>{
 const f=fixture();const {AutomaticNotesService}=await import('./automatic-notes'),{TranscriptService}=await import('./transcript-service'),{transcriptGuard}=await import('./session-tags');const prior=f.sessions.read('session-old')!;
 const initial=f.sessions.commitSource(prior.id,transcriptGuard(prior),current=>({...current!,duration:1,language:'en',transcript:'Original',segments:[],speakers:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true}));
 const notes=new AutomaticNotesService({sessionsDir:f.options.sessionsDir,sessionStore:f.sessions,getSettings:()=>({enabled:false,templateId:'none',model:null,language:'meeting'}),loadTemplate:()=>undefined,generate:async()=>'',isBusy:()=>false}),service=new TranscriptService({notes,store:f.sessions});
 const corrected=notes.commitTranscript(initial.id,{...transcriptGuard(initial),requestId:'migration-edit',action:'edit',target:{kind:'document'},text:'Corrected'}),result:TranscribeResult={success:true,finalized:true,text:'Candidate',segments:[],speakers:[],duration:1,wordCount:1,metadata:{language:'en',model:'new'},files:{wav:'',txt:'',srt:''}};
 const staged=service.stage(initial.id,{requestId:'migration-stage',base:transcriptGuard(corrected),result});service.discard(initial.id,staged.transcriptEditing!.candidates[0]!.id,'migration-discard');service.stage(initial.id,{requestId:'migration-pending',base:transcriptGuard(corrected),result});const before=f.sessions.read(initial.id)!;
 expect((await migrateLegacyAudio(f.options)).migrated).toBe(2);const after=f.sessions.read(initial.id)!;expect(after.transcriptEditing).toEqual(before.transcriptEditing);expect(transcriptGuard(after)).toEqual(transcriptGuard(before));expect(after.transcript).toBe('Corrected');expect(after.files!.wav).not.toBe(f.source);expect(readFileSync(after.files!.wav!)).toEqual(Buffer.from([0,255,1,254,2,253]));
});
