import {test,expect,afterEach} from 'bun:test';
import {mkdtempSync,mkdirSync,rmSync,readdirSync,existsSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {PortableLibrary} from './portable-library';import {atomicWriteJson} from './atomic-json';import {AutomaticNotesService} from './automatic-notes';import {TranscriptService} from './transcript-service';import {transcriptGuard} from './session-tags';import {sourceRevision} from '../../shared/lib/transcript-source';import type {TranscribeResult} from '@heed/shared';import {SessionTags} from './session-tags';
import {encode,makeBundle,portableMeeting,revisionPath,sha256} from './portable-schema';
import type {LibraryProvider,QuotaBudget} from './portable-provider';import type {PortableCommit,Session} from '@heed/shared';
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const meeting=(title='Planning',createdAt='2026-01-01T00:00:00Z')=>({id:'session-1',title,createdAt,duration:12,language:'pt',transcript:'Ana delivers review',speakers:['Ana'],segments:[{speaker:'Ana',start:0,end:12,text:'delivers review'}],aiNotes:'Notes',summary:'Summary',tags:['Product'],pinned:false,transcriptFinalized:true,transcriptionModel:'model'} as Session);
class Provider implements LibraryProvider {
 id='fixture';name='Synthetic library';transport='os-managed-folder' as const;objects=new Map<string,Uint8Array>();commits:PortableCommit[]=[];reads:string[]=[];writes:string[]=[];confirmation:'remote-confirmed'|'local-only'='remote-confirmed';partial=false;failRead='';acknowledgments=0;failAcknowledgment=false;
 async list(cursor:string|null,limit:number){const start=Number(cursor||0);return {commits:this.commits.slice(start,start+limit),next:start+limit<this.commits.length?String(start+limit):null,complete:!this.partial};}
 async read(path:string,maxBytes:number,signal?:AbortSignal){signal?.throwIfAborted();this.reads.push(path);if(path===this.failRead)throw new Error('Provider offline');const bytes=this.objects.get(path);if(!bytes||bytes.length>maxBytes)throw new Error('Invalid provider read');return bytes;}
 async *stream(path:string,maxBytes:number,signal?:AbortSignal){yield await this.read(path,maxBytes,signal);}
 async writeImmutable(path:string,bytes:Uint8Array){this.writes.push(path);const previous=this.objects.get(path);if(previous&&sha256(previous)!==sha256(bytes))throw new Error('Immutable collision');this.objects.set(path,bytes);}
 async writeObjectImmutable(path:string,bytes:number,hash:string,source:AsyncIterable<Uint8Array>){const chunks=[];for await(const chunk of source)chunks.push(Buffer.from(chunk));const data=Buffer.concat(chunks);if(data.length!==bytes||sha256(data)!==hash)throw new Error('Object integrity mismatch');await this.writeImmutable(path,data);}
 async confirm(){return this.confirmation;}
 async acknowledgeDiscovery(){this.acknowledgments++;if(this.failAcknowledgment)throw new Error('Checkpoint acknowledgment failed');}
 add(bundle:ReturnType<typeof makeBundle>){this.commits.push(bundle.marker);this.objects.set(bundle.marker.manifestPath,encode(bundle.manifest));this.objects.set(`${revisionPath(bundle.manifest.meetingId,bundle.manifest.revisionId)}/meeting.json`,encode(bundle.payload));}
}
function fixture(provider=new Provider(),quota?:QuotaBudget,write?:any){const root=mkdtempSync(join(tmpdir(),'heed-portable-'));roots.push(root);const sessionsDir=join(root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir);const reservations=new Map<string,number>();const budget=quota||{reserve:(id:string,bytes:number)=>{reservations.set(id,bytes);},release:(id:string)=>{reservations.delete(id);}};const options={root:join(root,'library'),sessions,sessionsDir,quota:budget,provider,write};return {root,sessions,provider,reservations,options,library:new PortableLibrary(options)};}
test('discovery is metadata-only; validated import is complete, idempotent and restart resumable',async()=>{
 const f=fixture();const payload=portableMeeting(meeting(),randomUUID());const bundle=makeBundle(randomUUID(),randomUUID(),payload,[]);f.provider.add(bundle);
 const preview=await f.library.discover();expect(preview.previews[0]?.local).toBe(false);expect(f.sessions.snapshot().sessions).toHaveLength(0);expect(f.provider.reads.some(path=>path.startsWith('objects/'))).toBe(false);
 const result=await f.library.importSelected();expect(result.imported).toBe(1);const saved=f.sessions.snapshot().sessions[0]!;expect(saved.transcript).toBe('delivers review');expect(saved.tags).toEqual(payload.tags);expect(saved.files?.wav).toBeUndefined();
 const restarted=new PortableLibrary(f.options);await restarted.importSelected();expect(f.sessions.snapshot().sessions).toHaveLength(1);expect(restarted.snapshot().previews[0]?.local).toBe(true);expect(f.reservations.size).toBe(0);
});
test('provider checkpoints acknowledge only complete validated durable discovery',async()=>{const f=fixture(),bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]);f.provider.add(bundle);await f.library.discover();expect(f.provider.acknowledgments).toBe(1);f.provider.partial=true;await f.library.discover();expect(f.provider.acknowledgments).toBe(1);f.provider.partial=false;f.provider.failRead=bundle.marker.manifestPath;await f.library.discover();expect(f.provider.acknowledgments).toBe(1);});
test('catalog acknowledgment failure never advances a provider checkpoint',async()=>{const f=fixture();f.provider.add(makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]));let interrupted=false;f.options.write=(path:string,value:any)=>{if(!interrupted&&value.entries&&Object.keys(value.entries).length){interrupted=true;throw new Error('Catalog commit unavailable');}atomicWriteJson(path,value);};const snapshot=await f.library.discover();expect(snapshot.complete).toBe(false);expect(snapshot.previews).toHaveLength(1);expect(f.provider.acknowledgments).toBe(0);});
test('provider checkpoint failure preserves discovered records for idempotent restart replay',async()=>{const f=fixture();f.provider.add(makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]));f.provider.failAcknowledgment=true;const failed=await f.library.discover();expect(failed.complete).toBe(false);expect(failed.previews).toHaveLength(1);expect(failed.error).toContain('Checkpoint');f.provider.failAcknowledgment=false;const restarted=new PortableLibrary(f.options);const result=await restarted.discover();expect(result.complete).toBe(true);expect(result.previews).toHaveLength(1);expect(f.provider.acknowledgments).toBe(2);await restarted.importSelected();expect(f.sessions.snapshot().sessions).toHaveLength(1);});
test('quota pressure imports newest eligible text and reports skipped without evicting transcripts',async()=>{
 let calls=0;const f=fixture(new Provider(),{reserve(){if(++calls>1)throw new Error('Managed meeting quota has insufficient available space');},release(){}});const libraryId=randomUUID();
 f.provider.add(makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Older','2025-01-01T00:00:00Z'),randomUUID()),[]));f.provider.add(makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Newer'),randomUUID()),[]));
 await f.library.discover();const result=await f.library.importSelected();expect(result.imported).toBe(1);expect(result.skipped).toBe(1);expect(result.pending).toBe(1);expect(f.sessions.snapshot().sessions[0]?.title).toBe('Newer');
});
test('corrupt/canceled/unavailable transfer never exposes a partial meeting and bounded staging cleans up',async()=>{
 const f=fixture();const bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]);f.provider.add(bundle);await f.library.discover();const path=`${revisionPath(bundle.manifest.meetingId,bundle.manifest.revisionId)}/meeting.json`;f.provider.objects.set(path,encode({bad:true}));
 await f.library.importSelected();expect(f.sessions.snapshot().sessions).toHaveLength(0);expect(readdirSync(join(f.root,'library/staging'))).toHaveLength(0);expect(f.reservations.size).toBe(0);
 const canceled=new AbortController();canceled.abort();expect(()=>f.library.importSelected(undefined,canceled.signal)).toThrow();
});
test('partial listing/outage retains previous discovery; clock-skew divergence stays conflict and local edits survive',async()=>{
 const f=fixture();const libraryId=randomUUID(),meetingId=randomUUID(),device=randomUUID();const first=makeBundle(libraryId,device,portableMeeting(meeting(),meetingId),[]);f.provider.add(first);await f.library.discover();await f.library.importSelected();
 const saved=f.sessions.snapshot().sessions[0]!;f.sessions.save({...saved,title:'Local correction'});
 const other=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Remote correction','2020-01-01T00:00:00Z'),meetingId),[first.manifest.revisionId]);f.provider.add(other);f.provider.partial=true;const snapshot=await f.library.discover();expect(snapshot.complete).toBe(false);await f.library.importSelected();expect(f.sessions.read(saved.id)?.title).toBe('Local correction');expect(f.library.snapshot().previews.find(p=>p.revisionId===other.manifest.revisionId)?.state).toBe('conflict');
 f.provider.commits=[];f.provider.partial=false;await f.library.discover();expect(f.library.snapshot().previews).toHaveLength(2);
});
test('stable legacy aliases preserve IDs and private fields; publish marker last and local write stays pending',async()=>{
 const f=fixture();f.sessions.create({...meeting(),id:'session-legacy',files:{txt:'/private/local.txt'},embeddings:{Ana:[1]}});const local=await f.library.queueLocal('session-legacy');const restart=new PortableLibrary(f.options);const again=await restart.queueLocal('session-legacy');expect(again.meetingId).toBe(local.meetingId);expect(again.revisionId).toBe(local.revisionId);expect(f.sessions.read('session-legacy')?.id).toBe('session-legacy');
 f.provider.confirmation='local-only';await restart.publish(local.revisionId);expect(f.provider.writes.at(-1)).toMatch(/^commits\//);expect(restart.snapshot().previews[0]?.state).toBe('pending');expect(JSON.stringify([...f.provider.objects.values()].map(v=>Buffer.from(v).toString()))).not.toContain('/private');
 f.provider.confirmation='remote-confirmed';await restart.publish(local.revisionId);expect(restart.snapshot().previews[0]?.state).toBe('verified');
});
test('lazy audio requests only selected object and verifies before exposing local playback',async()=>{
 const f=fixture();const audio=Buffer.from('RIFFsynthetic audio');const hash=sha256(audio);const payload=portableMeeting(meeting(),randomUUID(),{sha256:hash,bytes:audio.length,format:'wav',mode:'archived',objectPath:`objects/${hash}`});const bundle=makeBundle(randomUUID(),randomUUID(),payload,[]);f.provider.add(bundle);f.provider.objects.set(payload.audio!.objectPath,audio);
 await f.library.discover();await f.library.importSelected();expect(f.provider.reads).not.toContain(payload.audio!.objectPath);const saved=f.sessions.snapshot().sessions[0]!;const path=await f.library.requestAudio(saved.id);expect(readFileSync(path)).toEqual(audio);expect(f.sessions.read(saved.id)?.files?.wav).toBe(path);expect(await f.library.requestAudio(saved.id)).toBe(path);expect(f.provider.reads.filter(p=>p===payload.audio!.objectPath)).toHaveLength(1);
});
test('descendant imported before ancestor stays current; explicit conflict resolution produces a merge revision',async()=>{
 const f=fixture();const libraryId=randomUUID(),meetingId=randomUUID();const first=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Base'),meetingId),[]);const newer=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Latest','2026-02-01T00:00:00Z'),meetingId),[first.manifest.revisionId]);f.provider.add(first);f.provider.add(newer);await f.library.discover();await f.library.importSelected();expect(f.sessions.snapshot().sessions[0]?.title).toBe('Latest');expect(f.library.snapshot().previews.every(p=>p.state!=='conflict')).toBe(true);
 const branch=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Alternative','2026-03-01T00:00:00Z'),meetingId),[first.manifest.revisionId]);f.provider.add(branch);await f.library.discover();await f.library.importSelected();expect(f.library.snapshot().previews.find(p=>p.revisionId===branch.manifest.revisionId)?.state).toBe('conflict');const merged=await f.library.resolveConflict(branch.manifest.revisionId);expect(f.sessions.snapshot().sessions[0]?.title).toBe('Alternative');expect(merged.revisionId).not.toBe(branch.manifest.revisionId);await f.library.publish(merged.revisionId);const manifest=JSON.parse(Buffer.from(f.provider.objects.get(`meetings/${meetingId}/revisions/${merged.revisionId}/manifest.json`)!).toString());expect(manifest.parents).toContain(branch.manifest.revisionId);expect(manifest.parents).toHaveLength(2);const preserved=JSON.parse(readFileSync(join(f.options.root,'catalog/revisions',libraryId,meetingId,manifest.parents.find((id:string)=>id!==branch.manifest.revisionId),'manifest.json'),'utf8'));expect(preserved.parents).toContain(newer.manifest.revisionId);
});
test('complete-session commit retry recovers after catalog failure, preserving complete local data',async()=>{
 const f=fixture();const bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]);f.provider.add(bundle);await f.library.discover();const original=f.sessions.commitSource.bind(f.sessions);let fail=true;f.sessions.commitSource=(...args)=>{const saved=original(...args);if(fail){fail=false;throw new Error('Simulated ack failure');}return saved;};await f.library.importSelected();expect(f.sessions.snapshot().sessions).toHaveLength(1);await new PortableLibrary(f.options).importSelected();expect(f.sessions.snapshot().sessions).toHaveLength(1);expect(f.library.snapshot().previews[0]?.state).toBe('unavailable');
});
test('same portable UUID from separate libraries cannot overwrite another local meeting',async()=>{
 const f=fixture(),meetingId=randomUUID();f.provider.add(makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting('First'),meetingId),[]));f.provider.add(makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting('Second'),meetingId),[]));await f.library.discover();await f.library.importSelected();expect(f.sessions.snapshot().sessions.map(s=>s.title).sort()).toEqual(['First','Second']);
});
test('restart after session acknowledgment failure preserves subsequent user corrections',async()=>{
 const f=fixture(),bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]);f.provider.add(bundle);await f.library.discover();const original=f.sessions.commitSource.bind(f.sessions);f.sessions.commitSource=(...args)=>{const saved=original(...args);throw new Error('Ack interrupted');};await f.library.importSelected();f.sessions.commitSource=original;const saved=f.sessions.snapshot().sessions[0]!;f.sessions.save({...saved,title:'User correction after retryable failure'});const restart=new PortableLibrary(f.options);await restart.importSelected();expect(f.sessions.read(saved.id)?.title).toBe('User correction after retryable failure');expect(restart.snapshot().previews[0]?.state).toBe('conflict');
});
test('immutable revision replacement and multi-revision parent cycles fail closed without losing local state',async()=>{
 const f=fixture(),libraryId=randomUUID(),meetingId=randomUUID(),deviceId=randomUUID(),a=randomUUID(),b=randomUUID();const first=makeBundle(libraryId,deviceId,portableMeeting(meeting(),meetingId),[],a);f.provider.add(first);await f.library.discover();await f.library.importSelected();f.provider.commits=[];f.provider.add(makeBundle(libraryId,deviceId,portableMeeting(meeting('Tampered'),meetingId),[],a));const changed=await f.library.discover();expect(changed.complete).toBe(false);expect(changed.error).toContain('Immutable');expect(f.sessions.snapshot().sessions[0]?.title).toBe('Planning');
 const clean=fixture();clean.provider.add(makeBundle(libraryId,deviceId,portableMeeting(meeting(),meetingId),[b],a));clean.provider.add(makeBundle(libraryId,deviceId,portableMeeting(meeting('Cycle'),meetingId),[a],b));const cycle=await clean.library.discover();expect(cycle.complete).toBe(false);expect(cycle.error).toContain('cycle');expect(clean.library.snapshot().previews).toHaveLength(0);
});
function validWav(){const bytes=Buffer.alloc(48);bytes.write('RIFF');bytes.writeUInt32LE(40,4);bytes.write('WAVE',8);bytes.write('fmt ',12);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(16000,24);bytes.writeUInt32LE(32000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(4,40);return bytes;}
test('local RF64 recordings retain their content-addressed archive reference',async()=>{const f=fixture(),base=validWav(),ds64=Buffer.alloc(36);ds64.write('ds64');ds64.writeUInt32LE(28,4);ds64.writeBigUInt64LE(76n,8);ds64.writeBigUInt64LE(4n,16);ds64.writeBigUInt64LE(2n,24);const bytes=Buffer.concat([base.subarray(0,12),ds64,base.subarray(12)]);bytes.write('RF64');bytes.writeUInt32LE(0xffffffff,4);bytes.writeUInt32LE(0xffffffff,76);const path=join(f.root,'library/media/rf64.wav');require('node:fs').writeFileSync(path,bytes);f.sessions.create({...meeting(),files:{wav:path}});const preview=await f.library.queueLocal('session-1');expect(preview.audio).toBe(true);await f.library.publish(preview.revisionId);expect(f.provider.objects.get(`objects/${sha256(bytes)}`)).toEqual(bytes);});
test('local WAV publication round-trips to second device text first and requested verified media',async()=>{
 const first=fixture(),bytes=validWav(),path=join(first.root,'library/media/local-capture.wav');require('node:fs').writeFileSync(path,bytes);first.sessions.create({...meeting(),id:'recording-legacy',files:{wav:path}});const local=await first.library.queueLocal('recording-legacy');expect(local.audio).toBe(true);expect(first.library.protectedPaths()).toContain(path);await first.library.publish(local.revisionId);const markerPath=first.provider.writes.at(-1)!;const marker=JSON.parse(Buffer.from(first.provider.objects.get(markerPath)!).toString());first.provider.commits.push(marker);
 const second=fixture(first.provider);await second.library.discover();await second.library.importSelected();const imported=second.sessions.snapshot().sessions[0]!;expect(imported.files?.wav).toBeUndefined();expect(imported.transcript).toBe('delivers review');const downloaded=await second.library.requestAudio(imported.id);expect(readFileSync(downloaded)).toEqual(bytes);expect(first.provider.writes[0]).toMatch(/^objects\//);
});
test('another destination can protect an already verified revision source until its acknowledgment',async()=>{const f=fixture(),path=join(f.root,'library/media/local.wav');require('node:fs').writeFileSync(path,validWav());f.sessions.create({...meeting(),files:{wav:path}});const preview=await f.library.queueLocal('session-1');await f.library.publish(preview.revisionId);expect(f.library.protectedPaths()).not.toContain(path);expect(f.library.protectedPaths([preview.revisionId])).toContain(path);f.sessions.save({...f.sessions.read('session-1')!,title:'Unpublished correction'});await f.library.queueLocal('session-1');expect(f.library.protectedPaths([])).toContain(path);});
test('cached audio integrity verifies without another provider transfer',async()=>{
 const f=fixture(),bytes=validWav(),hash=sha256(bytes),payload=portableMeeting(meeting(),randomUUID(),{sha256:hash,bytes:bytes.length,format:'wav',mode:'archived',objectPath:`objects/${hash}`});f.provider.add(makeBundle(randomUUID(),randomUUID(),payload,[]));f.provider.objects.set(payload.audio!.objectPath,bytes);await f.library.discover();await f.library.importSelected();const session=f.sessions.snapshot().sessions[0]!;const path=await f.library.requestAudio(session.id);const reads=f.provider.reads.length;expect(await f.library.requestAudio(session.id)).toBe(path);expect(f.provider.reads).toHaveLength(reads);
});
test('a descendant with a different archived object cannot expose the preceding revision audio',async()=>{
 const f=fixture(),libraryId=randomUUID(),meetingId=randomUUID(),old=validWav(),fresh=validWav();fresh[44]=1;const audio=(bytes:Buffer)=>({sha256:sha256(bytes),bytes:bytes.length,format:'wav' as const,mode:'archived' as const,objectPath:`objects/${sha256(bytes)}`});
 const first=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Original'),meetingId,audio(old)),[]);f.provider.add(first);f.provider.objects.set(audio(old).objectPath,old);await f.library.discover();await f.library.importSelected();const id=f.sessions.snapshot().sessions[0]!.id;const oldPath=await f.library.requestAudio(id);
 const next=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Updated','2026-02-01T00:00:00Z'),meetingId,audio(fresh)),[first.manifest.revisionId]);f.provider.add(next);f.provider.objects.set(audio(fresh).objectPath,fresh);await f.library.discover();await f.library.importSelected();expect(f.sessions.read(id)?.title).toBe('Updated');expect(f.sessions.read(id)?.files?.wav).toBeUndefined();expect(existsSync(oldPath)).toBe(true);const path=await f.library.requestAudio(id);expect(path).not.toBe(oldPath);expect(readFileSync(path)).toEqual(fresh);
});
test('conflict selection intent reconciles after catalog acknowledgment failure and keeps later correction',async()=>{
 const f=fixture(),libraryId=randomUUID(),meetingId=randomUUID();const base=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Base'),meetingId),[]);f.provider.add(base);await f.library.discover();await f.library.importSelected();const alternative=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Chosen'),meetingId),[]);f.provider.add(alternative);await f.library.discover();await f.library.importSelected();const original=f.sessions.commitSource.bind(f.sessions);let failCatalog=false;f.options.write=(path:string,value:any)=>{if(failCatalog&&!Object.values(value.entries||{}).some((entry:any)=>entry.commitIntent)){failCatalog=false;throw new Error('Catalog ack failed after session commit');}atomicWriteJson(path,value);};f.sessions.commitSource=(...args)=>{const saved=original(...args);failCatalog=true;return saved;};await expect(f.library.resolveConflict(alternative.manifest.revisionId)).rejects.toThrow();f.sessions.commitSource=original;const saved=f.sessions.snapshot().sessions[0]!;f.sessions.save({...saved,title:'Correction after chosen revision'});const restart=new PortableLibrary(f.options);expect(restart.snapshot().previews.some(p=>p.state==='conflict'&&p.local)).toBe(true);expect(f.sessions.read(saved.id)?.title).toBe('Correction after chosen revision');const queued=await restart.queueLocal(saved.id);expect(queued.title).toBe('Correction after chosen revision');
});
test('restart after interrupted local conflict selection never claims remote publication verification',async()=>{const f=fixture(),libraryId=randomUUID(),meetingId=randomUUID();f.provider.add(makeBundle(libraryId,randomUUID(),portableMeeting(meeting('First'),meetingId),[]));await f.library.discover();await f.library.importSelected();const branch=makeBundle(libraryId,randomUUID(),portableMeeting(meeting('Selected'),meetingId),[]);f.provider.add(branch);await f.library.discover();await f.library.importSelected();const save=f.sessions.commitSource.bind(f.sessions);f.sessions.commitSource=(...args)=>{save(...args);throw new Error('Lost ack');};await expect(f.library.resolveConflict(branch.manifest.revisionId)).rejects.toThrow();f.sessions.commitSource=save;const restart=new PortableLibrary(f.options);const selected=restart.snapshot().previews.find(p=>p.local&&p.title==='Selected');expect(selected?.state).toBe('pending');});
test('a local archive remains downloadable after media eviction and clears expired flags',async()=>{
 const f=fixture(),bytes=validWav(),path=join(f.root,'library/media/capture.wav');require('node:fs').writeFileSync(path,bytes);f.sessions.create({...meeting(),files:{wav:path}});const queued=await f.library.queueLocal('session-1');expect(f.sessions.read('session-1')?.audioArchived).toBe(true);await f.library.publish(queued.revisionId);rmSync(path);f.sessions.save({...f.sessions.read('session-1')!,files:{wav:''},audioExpired:true,audioRemovedAt:'2026-01-01'} as Session);const downloaded=await f.library.requestAudio('session-1');expect(readFileSync(downloaded)).toEqual(bytes);expect((f.sessions.read('session-1') as any).audioExpired).toBeUndefined();expect((f.sessions.read('session-1') as any).audioRemovedAt).toBeUndefined();
});
test('deleted queued sources cannot publish; private tombstones suppress automatic restart imports',async()=>{
 const f=fixture();f.sessions.create(meeting());const preview=await f.library.queueLocal('session-1');const state=JSON.parse(readFileSync(join(f.options.root,'catalog/state.json'),'utf8')),entry=Object.values(state.entries)[0] as any;f.provider.add({marker:entry.marker,manifest:entry.manifest,payload:JSON.parse(readFileSync(join(f.options.root,'catalog/revisions',entry.manifest.libraryId,preview.meetingId,preview.revisionId,'meeting.json'),'utf8'))} as any);rmSync(join(f.options.sessionsDir,'session-1.json'));await expect(f.library.publish(preview.revisionId)).rejects.toThrow('deleted');expect(f.provider.writes).toHaveLength(0);const restarted=new PortableLibrary(f.options);await restarted.discover();await restarted.importSelected();expect(f.sessions.snapshot().sessions).toHaveLength(0);await restarted.importSelected([preview.revisionId]);expect(f.sessions.snapshot().sessions).toHaveLength(1);expect(JSON.stringify([...f.provider.objects.values()].map(v=>Buffer.from(v).toString()))).not.toContain('tombstone');
});
test('deletion during an upload suppresses its remote commit marker',async()=>{
 const f=fixture();f.sessions.create(meeting());const queued=await f.library.queueLocal('session-1');const write=f.provider.writeImmutable.bind(f.provider);f.provider.writeImmutable=async(path,bytes)=>{await write(path,bytes);if(path.endsWith('meeting.json'))rmSync(join(f.options.sessionsDir,'session-1.json'));};await f.library.publish(queued.revisionId);expect(f.provider.writes.some(path=>path.startsWith('commits/'))).toBe(false);expect(f.library.snapshot().previews[0]?.local).toBe(false);
});
test('whole provider leases prevent competing ticks or manual mutations from switching destinations',async()=>{
 const f=fixture(),other=new Provider();other.id='second';let release!:()=>void;const paused=new Promise<void>(resolve=>{release=resolve;});f.sessions.create(meeting());const leased=f.library.withProvider(f.provider,async library=>{const queued=await library.queueLocal('session-1');await paused;await library.publish(queued.revisionId);return queued;});await Bun.sleep(0);expect(f.library.isBusy()).toBe(true);expect(()=>f.library.selectProvider(other)).toThrow('already running');await expect(f.library.withProvider(other,async library=>library.discover())).rejects.toThrow('already running');await expect(f.library.queueLocal('session-1')).rejects.toThrow('already running');release();await leased;expect(f.library.isBusy()).toBe(false);expect(other.writes).toHaveLength(0);expect(f.provider.writes.at(-1)).toMatch(/^commits\//);f.library.selectProvider(other);expect(f.library.snapshot().providerName).toBe(other.name);
});
test('a validated duplicate on a healthy destination remains importable after first destination goes offline',async()=>{const a=new Provider(),f=fixture(a),bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]);a.id='destination-a';a.add(bundle);await f.library.discover();const b=new Provider();b.id='destination-b';b.add(bundle);f.library.selectProvider(b);await f.library.discover();const imported=await f.library.importSelected();expect(imported.imported).toBe(1);expect(f.sessions.snapshot().sessions[0]?.title).toBe('Planning');});
test('provider-scoped snapshots exclude unavailable remote-only leftovers while preserving local meetings',async()=>{const a=new Provider(),f=fixture(a);a.id='a';a.add(makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting('Only A'),randomUUID()),[]));await f.library.discover();const b=new Provider();b.id='b';b.add(makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting('Only B'),randomUUID()),[]));const scoped=await f.library.withProvider(b,async library=>library.discover());expect(scoped.previews.map(p=>p.title)).toEqual(['Only B']);expect(f.library.snapshot().previews.map(p=>p.title)).toEqual(['Only A']);});

test('local source eligibility remains independent of the selected destination after deletion',async()=>{
 const f=fixture();f.sessions.create(meeting());const queued=await f.library.queueLocal('session-1');await f.library.publish(queued.revisionId);
 const markerPath=f.provider.writes.find(p=>p.startsWith('commits/'))!;f.provider.commits.push(JSON.parse(Buffer.from(f.provider.objects.get(markerPath)!).toString()));await f.library.discover();
 const alternate=new Provider();alternate.id='second-destination';f.library.selectProvider(alternate);
 expect(f.library.hasLocalRevision(queued.revisionId)).toBe(true);rmSync(join(f.options.sessionsDir,'session-1.json'));
 expect(f.library.snapshot().previews.some(p=>p.revisionId===queued.revisionId)).toBe(false);
 expect(f.library.hasLocalRevision(queued.revisionId)).toBe(false);expect(f.library.hasLocalRevision(randomUUID())).toBe(false);
});

function withNotes(f:ReturnType<typeof fixture>,generate:ConstructorParameters<typeof AutomaticNotesService>[0]['generate']=async()=> 'Generated') {
 const settings={enabled:false,templateId:'meeting',model:'local',language:'meeting' as const};
 const notes=new AutomaticNotesService({sessionsDir:f.options.sessionsDir,sessionStore:f.sessions,getSettings:()=>settings,loadTemplate:()=>({id:'meeting',name:'Meeting',description:'',prompt:'Use evidence'}),generate,isBusy:()=>false});
 Object.assign(f.options,{replaceAccepted:(id:string,guard:ReturnType<typeof transcriptGuard>,build:(current:Session,now:string)=>Session)=>notes.replaceAccepted(id,guard,build)});
 return {notes,settings,service:new TranscriptService({notes,store:f.sessions})};
}
function finalResult():TranscribeResult{return {success:true,finalized:true,text:'Candidate',segments:[],speakers:[],metadata:{language:'pt',model:'new'},duration:12,wordCount:1,files:{wav:'/private/candidate.wav',txt:'',srt:''}};}
function deferred(){let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return {promise,resolve};}
for(const aba of [false,true])test(`remote read admission rejects concurrent ${aba?'edit/revert ABA':'correction'} without writing accepted bytes`,async()=>{
 const f=fixture(),n=withNotes(f),libraryId=randomUUID(),meetingId=randomUUID(),base=makeBundle(libraryId,randomUUID(),portableMeeting(meeting(),meetingId),[]);f.provider.add(base);await f.library.discover();await f.library.importSelected();const current=f.sessions.snapshot().sessions[0]!;
 const remote=makeBundle(libraryId,randomUUID(),portableMeeting({...meeting(),transcript:'Remote',segments:[{speaker:'Ana',text:'Remote',start:0,end:12}]},meetingId),[base.manifest.revisionId]);f.provider.add(remote);await f.library.discover();const entered=deferred(),release=deferred(),read=f.provider.read.bind(f.provider);f.provider.read=async(...args)=>{if(args[0].endsWith(`${remote.manifest.revisionId}/meeting.json`)){entered.resolve();await release.promise;}return read(...args);};
 const importing=f.library.importSelected([remote.manifest.revisionId]);await entered.promise;const changed=n.notes.commitTranscript(current.id,{...transcriptGuard(current),requestId:'edit-during-read',action:'edit',target:{kind:'segment',index:0},text:'Local correction'});
 if(aba)n.notes.commitTranscript(current.id,{...transcriptGuard(changed),requestId:'revert-during-read',action:'revert',editId:changed.transcriptEditing!.edits[0]!.id});
 const bytes=readFileSync(join(f.options.sessionsDir,`${current.id}.json`),'utf8');release.resolve();const result=await importing;expect(result.imported).toBe(0);expect(result.previews.find(p=>p.revisionId===remote.manifest.revisionId)?.state).toBe('conflict');expect(readFileSync(join(f.options.sessionsDir,`${current.id}.json`),'utf8')).toBe(bytes);expect(f.sessions.read(current.id)?.transcriptVersion).toBe(aba?3:2);
});
test('failed accepted write is never acknowledged or advanced as current on restart',async()=>{
 const f=fixture(),bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]);f.provider.add(bundle);await f.library.discover();const commit=f.sessions.commitSource.bind(f.sessions);f.sessions.commitSource=(id,guard,build)=>commit(id,guard,current=>{build(current);throw new Error('Synthetic source disk full');});await f.library.importSelected();expect(f.sessions.snapshot().sessions).toHaveLength(0);
 const restarted=new PortableLibrary(f.options),catalog=JSON.parse(readFileSync(join(f.options.root,'catalog/state.json'),'utf8'));expect(catalog.heads).toEqual({});expect(restarted.snapshot().previews[0]?.state).not.toBe('verified');f.sessions.commitSource=commit;await restarted.importSelected();expect(f.sessions.snapshot().sessions).toHaveLength(1);expect(restarted.snapshot().previews[0]?.state).toBe('verified');
});
test('lost accepted acknowledgment uses exact canonical projection and guard on restart',async()=>{
 const f=fixture(),bundle=makeBundle(randomUUID(),randomUUID(),portableMeeting(meeting(),randomUUID()),[]);f.provider.add(bundle);await f.library.discover();const commit=f.sessions.commitSource.bind(f.sessions);f.sessions.commitSource=(...args)=>{const saved=commit(...args);throw new Error('Lost source ack');};await f.library.importSelected();const durable=f.sessions.snapshot().sessions[0]!,bytes=readFileSync(join(f.options.sessionsDir,`${durable.id}.json`),'utf8');f.sessions.commitSource=commit;
 const restarted=new PortableLibrary(f.options);expect(restarted.snapshot().previews[0]?.state).toBe('verified');expect(readFileSync(join(f.options.sessionsDir,`${durable.id}.json`),'utf8')).toBe(bytes);const catalog=JSON.parse(readFileSync(join(f.options.root,'catalog/state.json'),'utf8')),entry=Object.values(catalog.entries)[0] as any;expect(entry.payloadHash).toBe(sha256(encode(bundle.payload)));expect(entry.acceptedPayloadHash).not.toBe(entry.payloadHash);expect(entry.acceptedTranscriptVersion).toBe(durable.transcriptVersion);expect(durable.transcriptRevision).toBe(sourceRevision(durable));
});
test('two device notes services roundtrip correction and explicit selection retains local candidates/history',async()=>{
 const a=fixture(),an=withNotes(a),initial=an.notes.create({...meeting(),aiNotes:''}),changed=an.notes.commitTranscript(initial.id,{...transcriptGuard(initial),requestId:'device-a-edit',action:'edit',target:{kind:'segment',index:0},text:'Corrected on A'});const local=await a.library.queueLocal(changed.id);await a.library.publish(local.revisionId);const marker=JSON.parse(Buffer.from(a.provider.objects.get(a.provider.writes.at(-1)!)!).toString());a.provider.commits.push(marker);
 const b=fixture(a.provider),bn=withNotes(b);await b.library.discover();await b.library.importSelected();const imported=b.sessions.snapshot().sessions[0]!;expect(imported.transcript).toBe('Corrected on A');expect(imported.transcriptEditing!.generations[0]!.transcript).toBe('delivers review');expect(imported.transcriptEditing!.edits[0]!.requestId).toBeUndefined();expect(imported.transcriptVersion).toBe(1);
 const edited=bn.notes.commitTranscript(imported.id,{...transcriptGuard(imported),requestId:'device-b-edit',action:'edit',target:{kind:'segment',index:0},text:'Local correction on B'});const staged=bn.service.stage(edited.id,{requestId:'local-stage',base:transcriptGuard(edited),result:finalResult()});bn.service.discard(staged.id,staged.transcriptEditing!.candidates[0]!.id,'local-discard');const pending=bn.service.stage(edited.id,{requestId:'pending-stage',base:transcriptGuard(edited),result:finalResult()});
 const alternative=makeBundle(marker.libraryId,randomUUID(),portableMeeting({...meeting(),transcript:'Selected remote',segments:[{speaker:'Ana',text:'Selected remote',start:0,end:12}]},local.meetingId),[local.revisionId]);a.provider.add(alternative);await b.library.discover();await b.library.importSelected([alternative.manifest.revisionId]);const prior=b.sessions.read(edited.id)!;await b.library.resolveConflict(alternative.manifest.revisionId);const accepted=b.sessions.read(edited.id)!;
 expect(accepted.transcript).toBe('Selected remote');expect(accepted.transcriptVersion).toBe(prior.transcriptVersion!+1);expect(accepted.createdAt).toBe(imported.createdAt);expect(accepted.transcriptEditing!.edits).toEqual(prior.transcriptEditing!.edits);expect(accepted.transcriptEditing!.candidates).toEqual(pending.transcriptEditing!.candidates);expect(accepted.transcriptEditing!.candidateRequestReceipts).toEqual(prior.transcriptEditing!.candidateRequestReceipts);expect(accepted.transcriptEditing!.generations[0]).toEqual(imported.transcriptEditing!.generations[0]);
});
for(const acceptedEdit of [false,true])test(`deferred audio inspection ${acceptedEdit?'rejects accepted drift':'preserves latest candidate and metadata writes'}`,async()=>{
 const f=fixture(),n=withNotes(f),path=join(f.root,'library/media/race.wav');require('node:fs').writeFileSync(path,validWav());const initial=n.notes.create({...meeting(),files:{wav:path}}),entered=deferred(),release=deferred(),inspect=(f.library as any).inspectAudio.bind(f.library);(f.library as any).inspectAudio=async(...args:any[])=>{entered.resolve();await release.promise;return inspect(...args);};const queuing=f.library.queueLocal(initial.id);await entered.promise;
 n.notes.patch(initial.id,{title:'Latest title',pinned:true});const staged=n.service.stage(initial.id,{requestId:'audio-stage',base:transcriptGuard(initial),result:finalResult()});n.service.discard(initial.id,staged.transcriptEditing!.candidates[0]!.id,'audio-discard');n.service.stage(initial.id,{requestId:'audio-pending',base:transcriptGuard(initial),result:finalResult()});
 if(acceptedEdit)n.notes.commitTranscript(initial.id,{...transcriptGuard(initial),requestId:'audio-edit',action:'edit',target:{kind:'segment',index:0},text:'Edited during audio inspection'});const before=f.sessions.read(initial.id)!;release.resolve();if(acceptedEdit)await expect(queuing).rejects.toThrow('changed');else{await queuing;const after=f.sessions.read(initial.id)!;expect(after).toEqual({...before,audioArchived:true});}
 expect(f.sessions.read(initial.id)!.transcriptEditing).toEqual(before.transcriptEditing);expect(f.reservations.size).toBe(0);
});
test('candidate-only lazy baseline does not mark an unchanged queued v2 source as local drift',async()=>{
 const f=fixture(),n=withNotes(f),initial=n.notes.create(meeting()),queued=await f.library.queueLocal(initial.id);const staged=n.service.stage(initial.id,{requestId:'stage-after-queue',base:transcriptGuard(initial),result:finalResult()});
 const catalog=JSON.parse(readFileSync(join(f.options.root,'catalog/state.json'),'utf8')),entry=Object.values(catalog.entries)[0] as any;const child=makeBundle(entry.manifest.libraryId,randomUUID(),portableMeeting({...meeting(),title:'Remote metadata'},queued.meetingId),[queued.revisionId]);f.provider.add(child);await f.library.discover();const result=await f.library.importSelected([child.manifest.revisionId]);expect(result.imported).toBe(1);expect(f.sessions.read(initial.id)?.title).toBe('Remote metadata');expect(f.sessions.read(initial.id)!.transcriptEditing!.candidates).toEqual(staged.transcriptEditing!.candidates);
});
test('replacement import supersedes held notes and cannot commit their late result',async()=>{
 const f=fixture(),entered=deferred(),release=deferred(),n=withNotes(f,async()=>{entered.resolve();await release.promise;return 'Obsolete generated notes';});n.settings.enabled=true;
 const initial=n.notes.create({...meeting(),aiNotes:''}),running=n.notes.tick();await entered.promise;const queued=await f.library.queueLocal(initial.id);
 const catalog=JSON.parse(readFileSync(join(f.options.root,'catalog/state.json'),'utf8')),entry=Object.values(catalog.entries)[0] as any;const child=makeBundle(entry.manifest.libraryId,randomUUID(),portableMeeting({...meeting(),aiNotes:'',transcript:'Remote recognized text',segments:[{speaker:'Ana',text:'Remote recognized text',start:0,end:12}]},queued.meetingId),[queued.revisionId]);f.provider.add(child);await f.library.discover();expect((await f.library.importSelected([child.manifest.revisionId])).imported).toBe(1);
 const accepted=f.sessions.read(initial.id)!;expect(accepted.transcriptVersion).toBe(initial.transcriptVersion!+1);expect(Object.values(accepted.notesJobs!).find(job=>job.sourceVersion===initial.transcriptVersion)?.status).toBe('superseded');release.resolve();await running;expect(f.sessions.read(initial.id)?.aiNotes).toBe('');expect(f.sessions.read(initial.id)?.transcript).toBe('Remote recognized text');
});
test('explicit conflict selection retains its admission guard across awaited local preparation',async()=>{
 const f=fixture(),n=withNotes(f),libraryId=randomUUID(),meetingId=randomUUID(),first=makeBundle(libraryId,randomUUID(),portableMeeting(meeting(),meetingId),[]);f.provider.add(first);await f.library.discover();await f.library.importSelected();const current=f.sessions.snapshot().sessions[0]!;
 const branch=makeBundle(libraryId,randomUUID(),portableMeeting({...meeting(),title:'Remote branch'},meetingId),[]);f.provider.add(branch);await f.library.discover();await f.library.importSelected();const entered=deferred(),release=deferred(),queue=(f.library as any).queueLocalRecord.bind(f.library);(f.library as any).queueLocalRecord=async(...args:any[])=>{const result=await queue(...args);entered.resolve();await release.promise;return result;};
 const selection=f.library.resolveConflict(branch.manifest.revisionId),settled=selection.catch(()=>{});await entered.promise;n.notes.commitTranscript(current.id,{...transcriptGuard(current),requestId:'selection-race',action:'edit',target:{kind:'segment',index:0},text:'Correction during selection'});const bytes=readFileSync(join(f.options.sessionsDir,`${current.id}.json`),'utf8');release.resolve();await expect(selection).rejects.toThrow('Transcript changed');await settled;expect(readFileSync(join(f.options.sessionsDir,`${current.id}.json`),'utf8')).toBe(bytes);expect(f.library.snapshot().previews.find(p=>p.revisionId===branch.manifest.revisionId)?.state).toBe('conflict');
});
