import {test,expect} from 'bun:test';import {randomUUID} from 'node:crypto';import {libraryResponse} from './portable-http';
const snapshot={configured:false,previews:[],imported:0,skipped:0,pending:0,complete:true};
const service:any={snapshot:()=>snapshot,discover:async()=>({...snapshot,configured:true}),importSelected:async()=>snapshot,queueLocal:()=>({revisionId:'fixture'}),publish:async()=>snapshot,resolveConflict:()=>({revisionId:'fixture'})};
const req=(body:unknown,origin='http://localhost:5001')=>new Request('http://localhost:5001/api/library',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
test('library snapshot works unconfigured and mutation controls are origin guarded',async()=>{expect(await (await libraryResponse(new Request('http://localhost:5001/api/library'),service)).json()).toEqual(snapshot);expect((await libraryResponse(req({action:'refresh'},'https://foreign.example'),service)).status).toBe(403);expect((await libraryResponse(req({action:'refresh',expectedProviderId:'fixture'}),{...service,snapshot:()=>({...snapshot,configured:true,providerId:'fixture'})})).status).toBe(200);});
test('malformed selections/unsupported actions fail closed, no path inputs accepted',async()=>{for(const body of [{action:'import',revisionIds:['../secret']},{action:'delete'},{action:'publish',path:'/private/file'},{action:'import',revisionIds:new Array(10001).fill('x')},null])expect((await libraryResponse(req(body),service)).status).toBe(400);});
test('quota blocked or unavailable playback reports accurate status without a local path',async()=>{const broken:any={...service,snapshot:()=>({...snapshot,configured:true,providerId:'fixture'}),requestAudio:async()=>{throw new Error('Managed meeting quota has insufficient available space');}};const response=await libraryResponse(req({action:'audio',sessionId:'session-1',expectedProviderId:'fixture'}),broken);expect(response.status).toBe(409);expect(await response.json()).toEqual({error:'Managed meeting quota has insufficient available space',code:'quota-blocked'});});
test('stale provider selection cannot publish or import to another configured destination',async()=>{let publishes=0,imports=0;const current:any={...service,snapshot:()=>({...snapshot,configured:true,providerId:'destination-b'}),publish:async()=>{publishes++;return snapshot;},importSelected:async()=>{imports++;return snapshot;}};for(const body of [{action:'publish',revisionId:'00000000-0000-4000-8000-000000000001',expectedProviderId:'destination-a'},{action:'import',revisionIds:[],expectedProviderId:'destination-a'},{action:'refresh',expectedProviderId:'destination-a'},{action:'audio',sessionId:'meeting',expectedProviderId:'destination-a'}])expect((await libraryResponse(req(body),current)).status).toBe(409);expect(publishes).toBe(0);expect(imports).toBe(0);});
test('publication requires the current provider identity and a stale tab cannot publish into a replacement',async()=>{let calls=0;const bound={...service,snapshot:()=>({...snapshot,configured:true,providerId:'destination-b'}),publish:async()=>{calls++;return snapshot;}};const revisionId='11111111-1111-4111-8111-111111111111';expect((await libraryResponse(req({action:'publish',revisionId}),bound)).status).toBe(400);expect((await libraryResponse(req({action:'publish',revisionId,expectedProviderId:'destination-a'}),bound)).status).toBe(409);expect(calls).toBe(0);expect((await libraryResponse(req({action:'publish',revisionId,expectedProviderId:'destination-b'}),bound)).status).toBe(200);expect(calls).toBe(1);});
test('physical deletion requires explicit confirmation and current exact destination; foreign origin wins before unsupported checks',async()=>{
 const destinationId='11111111-1111-4111-8111-111111111111',token='22222222-2222-4222-8222-222222222222';let calls=0;
 const deletion={...service,snapshot:()=>({...snapshot,providerId:'current',deletionCapabilities:{destinationVersion:2,destinationId}}),deletionJobs:()=>[],confirmDeletion:async()=>{calls++;return {id:token};},previewDeletion:async()=>({token})};
 expect((await libraryResponse(req({action:'delete-confirm',token,confirmed:true,expectedProviderId:'current',expectedDestinationId:destinationId},'https://foreign.example'),deletion)).status).toBe(403);
 for(const body of [{action:'delete-confirm',token,confirmed:false,expectedProviderId:'current',expectedDestinationId:destinationId},{action:'delete-confirm',token,confirmed:true,expectedProviderId:'old',expectedDestinationId:destinationId},{action:'delete-confirm',token,confirmed:true,expectedProviderId:'current',expectedDestinationId:'33333333-3333-4333-8333-333333333333'},{action:'delete-confirm',token,confirmed:true,expectedProviderId:'current',expectedDestinationId:destinationId,path:'../private'}])expect((await libraryResponse(req(body),deletion)).status).not.toBe(200);
 expect(calls).toBe(0);expect((await libraryResponse(req({action:'delete-confirm',token,confirmed:true,expectedProviderId:'current',expectedDestinationId:destinationId}),deletion)).status).toBe(200);expect(calls).toBe(1);
});
test('read-only original recovery and deletion status remain available during recording while mutation stays busy',async()=>{const library:any={snapshot:()=>({providerId:'synthetic-provider'}),recoveryTransactions:()=>[],deletionJobs:()=>[],reconcileTransaction:()=>{throw Error('Must not mutate during capture');}};for(const action of ['recovery-jobs','delete-jobs']){const response=await libraryResponse(new Request('http://localhost:5001/api/library',{method:'POST',body:JSON.stringify({action})}),library,undefined,()=>true);expect(response.status).toBe(200);}const response=await libraryResponse(new Request('http://localhost:5001/api/library',{method:'POST',body:JSON.stringify({action:'release-operation',operationId:randomUUID(),expectedProviderId:'synthetic-provider'})}),library,undefined,()=>true);expect(response.status).toBe(409);});
