import {afterAll,beforeAll,expect,test} from 'bun:test';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
let directory:string,recordings:string,base:string,app:ReturnType<typeof Bun.spawn>;
async function start(){app=Bun.spawn([process.execPath,resolve(import.meta.dir,'../server.ts')],{cwd:resolve(import.meta.dir,'../../..'),env:{...process.env,PORT:base.split(':').at(-1)!,HEED_APP_DIR:directory,HEED_RECORDINGS_DIR:recordings},stdout:'ignore',stderr:'ignore'});const end=Date.now()+8000;while(Date.now()<end){try{if((await fetch(`${base}/api/storage`)).status===200)return;}catch{}await Bun.sleep(25);}throw new Error('Isolated library server did not start');}
async function command(body:unknown,origin=base){return fetch(`${base}/api/library`,{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});}
beforeAll(async()=>{directory=mkdtempSync(join(tmpdir(),'heed-library-http-'));recordings=join(directory,'recordings');mkdirSync(recordings);const reserve=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response()});base=`http://127.0.0.1:${reserve.port}`;reserve.stop(true);await start();},10000);
afterAll(async()=>{app?.kill();if(app)await app.exited;if(directory)rmSync(directory,{recursive:true,force:true});});
test('real library route is unconfigured, uses shared quota and rejects cross-origin controls',async()=>{const response=await fetch(`${base}/api/library`);expect(response.status).toBe(200);expect((await response.json()).configured).toBe(false);expect((await command({action:'refresh'},'https://foreign.example')).status).toBe(403);expect((await command({action:'refresh'})).status).toBe(400);expect((await command({action:'audio',sessionId:'../secret'})).status).toBe(400);});
test('server migration and range playback use managed media; deleted queued meetings persist private tombstones',async()=>{const wav=join(recordings,'fixture.wav'),bytes=Buffer.alloc(48);bytes.write('RIFF');bytes.writeUInt32LE(40,4);bytes.write('WAVE',8);bytes.write('fmt ',12);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(16000,24);bytes.writeUInt32LE(32000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(4,40);writeFileSync(wav,bytes);const input={id:'portable-fixture',title:'Synthetic meeting',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcriptFinalized:true,transcript:'Prepare the review',segments:[],speakers:[],aiNotes:'',summary:'',pinned:false,files:{wav}};expect((await fetch(`${base}/api/sessions`,{method:'POST',body:JSON.stringify(input)})).status).toBe(200);const migration=await command({action:'migrate'});expect(migration.status).toBe(200);expect((await migration.json()).migrated).toBe(1);const audio=await fetch(`${base}/api/sessions/portable-fixture/audio`,{headers:{range:'bytes=0-3'}});expect(audio.status).toBe(206);expect(await audio.text()).toBe('RIFF');expect((await command({action:'queue',sessionId:'portable-fixture'})).status).toBe(200);expect((await fetch(`${base}/api/sessions?id=portable-fixture`,{method:'DELETE'})).status).toBe(200);const catalog=JSON.parse(readFileSync(join(directory,'library/catalog/state.json'),'utf8'));expect(Object.keys(catalog.tombstones)).toHaveLength(1);expect((await fetch(`${base}/api/storage`)).status).toBe(200);});
test('production corrected queue carries v2 history while candidates and local guards stay private',async()=>{
 const created=await fetch(`${base}/api/sessions`,{method:'POST',body:JSON.stringify({id:'corrected-portable-http',title:'Synthetic portable correction',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcriptFinalized:true,transcript:'Original',segments:[],speakers:[],aiNotes:'',summary:'',tags:[],pinned:false})});expect(created.status).toBe(200);const initial=await created.json();
 const response=await fetch(`${base}/api/sessions/${initial.id}/transcript/commands`,{method:'POST',headers:{origin:base,'Content-Type':'application/json'},body:JSON.stringify({expectedTranscriptRevision:initial.transcriptRevision,expectedTranscriptVersion:initial.transcriptVersion,requestId:'http-portable-edit',action:'edit',target:{kind:'document'},text:'Corrected'})});expect(response.status).toBe(200);const corrected=await response.json();
 const staged=await fetch(`${base}/api/sessions/${initial.id}/transcript/candidates`,{method:'POST',headers:{origin:base,'Content-Type':'application/json'},body:JSON.stringify({requestId:'http-portable-stage',base:{expectedTranscriptRevision:corrected.transcriptRevision,expectedTranscriptVersion:corrected.transcriptVersion},result:{success:true,finalized:true,text:'Candidate',segments:[],speakers:[],duration:1,wordCount:1,metadata:{language:'en',model:'new'},files:{wav:'/private/forbidden.wav',txt:'',srt:''}}})});expect(staged.status).toBe(200);
 expect((await command({action:'queue',sessionId:initial.id})).status).toBe(200);const catalog=JSON.parse(readFileSync(join(directory,'library/catalog/state.json'),'utf8')),entry=Object.values(catalog.entries).find((entry:any)=>entry.sessionId===initial.id) as any;
 const raw=readFileSync(join(directory,'library/catalog/revisions',entry.manifest.libraryId,entry.manifest.meetingId,entry.manifest.revisionId,'meeting.json'),'utf8'),payload=JSON.parse(raw);expect(payload.schemaVersion).toBe(2);expect(payload.transcript).toBe('Corrected');expect(payload.transcriptHistory.generations[0].transcript).toBe('Original');expect(payload.transcriptHistory.edits[0].changes[0].after).toBe('Corrected');for(const field of ['requestId','requestSignature','candidates','transcriptVersion','/private'])expect(raw).not.toContain(field);
 const durable=JSON.parse(readFileSync(join(directory,'sessions',`${initial.id}.json`),'utf8'));expect(durable.transcriptEditing.candidates).toHaveLength(1);expect(durable.transcriptVersion).toBe(corrected.transcriptVersion);
});
test('full protected text leaves sessions and settings available when library initialization cannot fit',async()=>{app.kill();await app.exited;rmSync(join(directory,'library/catalog'),{recursive:true,force:true});writeFileSync(join(directory,'config.json'),JSON.stringify({storage_limit_bytes:1_048_576}));writeFileSync(join(directory,'sessions','full-fixture.json'),JSON.stringify({id:'full-fixture',title:'Synthetic full text',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'x'.repeat(1_048_576),segments:[],speakers:[],tags:[],pinned:false,aiNotes:'',summary:'',transcriptFinalized:true}));await start();expect((await fetch(`${base}/api/library`)).status).toBe(409);expect((await fetch(`${base}/api/sessions`)).status).toBe(200);expect((await fetch(`${base}/api/storage`)).status).toBe(200);expect(JSON.parse(readFileSync(join(directory,'sessions/full-fixture.json'),'utf8')).transcript.length).toBe(1_048_576);},10000);
