import {afterEach,expect,test} from 'bun:test';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {PortableLibraryRuntime} from './portable-runtime';import {SessionTags} from './session-tags';import {ManagedQuota,MIN_MANAGED_LIMIT} from './managed-quota';import {setAtomicWriteBudget} from './atomic-json';
const roots:string[]=[];afterEach(()=>{setAtomicWriteBudget(undefined);for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
function fixture(){const root=mkdtempSync(join(tmpdir(),'heed-library-runtime-'));roots.push(root);const sessionsDir=join(root,'sessions'),recordingsDir=join(root,'recordings'),libraryRoot=join(root,'library');mkdirSync(sessionsDir);mkdirSync(recordingsDir);const sessions=new SessionTags(sessionsDir);let runtime:PortableLibraryRuntime;let limit=2_000_000;const quota=new ManagedQuota({ledgerPath:join(root,'quota.json'),roots:{text:[sessionsDir,join(libraryRoot,'catalog')],media:[recordingsDir,join(libraryRoot,'media')],staging:[join(libraryRoot,'staging')],indexes:[join(libraryRoot,'indexes')]},getLimit:()=>limit,setLimit:value=>{limit=value;},protectedPaths:()=>runtime?.protectedPaths()||[],onEvicted:paths=>{for(const session of sessions.snapshot().sessions)if(session.files?.wav&&paths.includes(session.files.wav))sessions.save({...session,files:{wav:''}});}});setAtomicWriteBudget((path,bytes,temporary)=>quota.atomicWriteBudget(path,bytes,temporary));runtime=new PortableLibraryRuntime({root:libraryRoot,recordingsDir,sessionsDir,sessions,quota});return {root,sessionsDir,recordingsDir,libraryRoot,sessions,quota,runtime};}
const meeting=(wav:string)=>({id:'capture-1',title:'Synthetic capture',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcriptFinalized:true,transcript:'Review tomorrow',speakers:[],tags:[],segments:[],aiNotes:'',summary:'',pinned:false,files:{wav}});
test('real quota protects pending audio across lazy runtime restart and allows eviction after verification',async()=>{const f=fixture(),wav=join(f.recordingsDir,'capture.wav'),bytes=Buffer.alloc(1_200_000);bytes.write('RIFF');bytes.write('WAVE',8);writeFileSync(wav,bytes);f.sessions.create(meeting(wav));const service=f.runtime.get(),preview=await service.queueLocal('capture-1');expect(f.quota.snapshot().protectedBytes).toBeGreaterThanOrEqual(bytes.length);const restarted=new PortableLibraryRuntime({root:f.libraryRoot,recordingsDir:f.recordingsDir,sessionsDir:f.sessionsDir,sessions:f.sessions,quota:f.quota});expect(restarted.protectedPaths()).toContain(wav);expect(()=>f.quota.preview(MIN_MANAGED_LIMIT)).toThrow();const statePath=join(f.libraryRoot,'catalog/state.json'),state=JSON.parse(readFileSync(statePath,'utf8'));Object.values(state.entries).forEach((entry:any)=>entry.preview.state='verified');writeFileSync(statePath,JSON.stringify(state));expect(restarted.protectedPaths()).not.toContain(wav);expect(restarted.protectedPaths([preview.revisionId])).toContain(wav);});
test('full protected text cannot crash startup or erase existing sessions when lazy library initializes',()=>{const f=fixture();writeFileSync(join(f.sessionsDir,'full.json'),'x'.repeat(2_000_000));expect(existsSync(join(f.libraryRoot,'catalog/state.json'))).toBe(false);expect(()=>f.runtime.get()).toThrow(/quota|space/i);expect(readFileSync(join(f.sessionsDir,'full.json'),'utf8').length).toBe(2_000_000);});
test('corrupt durable protection journals fail closed without requiring library initialization',()=>{const f=fixture();mkdirSync(join(f.libraryRoot,'catalog'),{recursive:true});writeFileSync(join(f.libraryRoot,'catalog/state.json'),'{broken');expect(f.runtime.protectedPaths()).toContain(f.recordingsDir);expect(f.runtime.protectedPaths()).toContain(join(f.libraryRoot,'media'));});
test('managed migration uses real quota and changes playback references only after verified copy',async()=>{const f=fixture(),path=join(f.recordingsDir,'legacy.wav');writeFileSync(path,'synthetic bytes');f.sessions.create(meeting(path));const result=await f.runtime.migrate();expect(result.migrated).toBe(1);const target=f.sessions.read('capture-1')?.files?.wav!;expect(target).toContain('/library/media/');expect(readFileSync(target,'utf8')).toBe('synthetic bytes');expect(existsSync(path)).toBe(false);expect(f.quota.snapshot().reservedBytes).toBe(0);});
test('real shared quota eviction preserves first-device archival availability and requested audio is restored',async()=>{
 const f=fixture(),wav=join(f.recordingsDir,'capture.wav'),bytes=Buffer.alloc(1_200_000);bytes.write('RIFF');bytes.write('WAVE',8);writeFileSync(wav,bytes);f.sessions.create(meeting(wav));const objects=new Map<string,Uint8Array>();const provider:any={id:'synthetic',name:'Synthetic destination',transport:'authenticated-network',async writeImmutable(path:string,data:Uint8Array){objects.set(path,data);},async writeObjectImmutable(path:string,_bytes:number,_hash:string,source:AsyncIterable<Uint8Array>){const chunks=[];for await(const chunk of source)chunks.push(Buffer.from(chunk));objects.set(path,Buffer.concat(chunks));},async confirm(){return 'remote-confirmed';},async read(path:string,max:number){const data=objects.get(path)!;if(!data||data.length>max)throw new Error('Invalid synthetic read');return data;},async *stream(path:string){yield objects.get(path)!;}};const library=f.runtime.get();library.selectProvider(provider);const queued=await library.queueLocal('capture-1');await library.publish(queued.revisionId);const reduction=f.quota.preview(MIN_MANAGED_LIMIT);f.quota.apply(MIN_MANAGED_LIMIT,reduction.token);expect(existsSync(wav)).toBe(false);expect(f.sessions.read('capture-1')?.files?.wav).toBe('');expect(f.sessions.read('capture-1')?.audioArchived).toBe(true);const increase=f.quota.preview(4_000_000);f.quota.apply(4_000_000,increase.token);const restored=await library.requestAudio('capture-1');expect(readFileSync(restored)).toEqual(bytes);expect(f.quota.snapshot().reservedBytes).toBe(0);expect(f.sessions.read('capture-1')?.transcript).toBe('Review tomorrow');
});
test('explicit local deletion releases pending audio protections before and after lazy restart',async()=>{const f=fixture(),wav=join(f.recordingsDir,'pending.wav'),bytes=Buffer.alloc(48);bytes.write('RIFF');bytes.write('WAVE',8);writeFileSync(wav,bytes);f.sessions.create(meeting(wav));const library=f.runtime.get(),queued=await library.queueLocal('capture-1');f.runtime.markDeleted('capture-1');f.sessions.remove('capture-1');expect(library.snapshot().previews[0]?.deleted).toBe(true);expect(f.runtime.protectedPaths([queued.revisionId])).not.toContain(wav);const restarted=new PortableLibraryRuntime({root:f.libraryRoot,recordingsDir:f.recordingsDir,sessionsDir:f.sessionsDir,sessions:f.sessions,quota:f.quota});expect(restarted.protectedPaths([queued.revisionId])).not.toContain(wav);});
