import {afterEach,expect,test} from 'bun:test';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {ProviderRegistry} from './provider-registry';import type {LibraryProvider} from './portable-provider';
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
function fixture(write?:ConstructorParameters<typeof ProviderRegistry>[0]['write']){const root=mkdtempSync(join(tmpdir(),'heed-provider-selection-'));roots.push(root);const path=join(root,'preference.json');let selected:LibraryProvider|undefined,busy=false;const library={snapshot:()=>({providerId:selected?.id}),isBusy:()=>busy,isMutationOwner:()=>false,withMutation:async(run:()=>Promise<unknown>)=>run(),selectProvider:(p?:LibraryProvider)=>{if(busy)throw new Error('Busy');selected=p;}};const options={path,getLibrary:()=>library,write};return {path,options,registry:new ProviderRegistry(options),selected:()=>selected,busy:(v:boolean)=>{busy=v;}};}
const provider=(id:string)=>({id,name:id} as LibraryProvider);
test('registering connectors cannot replace a preferred provider; restart restores only the preferred registered identity',()=>{const f=fixture();f.registry.register('smb',()=>provider('smb'));f.registry.register('drive',()=>provider('drive'));expect(f.selected()).toBeUndefined();f.registry.activate('drive');expect(f.selected()?.id).toBe('drive');f.options.getLibrary().selectProvider();const restart=new ProviderRegistry(f.options);restart.register('smb',()=>provider('smb'));expect(f.selected()).toBeUndefined();restart.register('drive',()=>provider('drive'));expect(f.selected()).toBeUndefined();restart.restore();expect(restart.preferredId()).toBe('drive');expect(f.selected()?.id).toBe('drive');expect(JSON.parse(readFileSync(f.path,'utf8'))).toEqual({version:1,preferredId:'drive'});});
test('disconnecting a different connector preserves preference and active provider; current disconnect clears both',()=>{const f=fixture();f.registry.register('smb',()=>provider('smb'));f.registry.register('drive',()=>provider('drive'));f.registry.activate('drive');f.registry.unregister('smb');expect(f.registry.preferredId()).toBe('drive');expect(f.selected()?.id).toBe('drive');f.registry.unregister('drive');expect(f.registry.preferredId()).toBeNull();expect(f.selected()).toBeUndefined();});
test('leased library rejects selection before persistence or connector mutation',()=>{const f=fixture();f.registry.register('smb',()=>provider('smb'));f.registry.register('drive',()=>provider('drive'));f.registry.activate('drive');f.busy(true);expect(()=>f.registry.activate('smb')).toThrow('running');expect(()=>f.registry.unregister('drive')).toThrow('running');expect(f.registry.preferredId()).toBe('drive');expect(JSON.parse(readFileSync(f.path,'utf8')).preferredId).toBe('drive');f.busy(false);f.registry.activate('drive');expect(f.selected()?.id).toBe('drive');});
test('preference persistence failures preserve selected provider and in-memory preference',()=>{let fail=false;const f=fixture((path,value)=>{if(fail)throw new Error('Disk full');require('./atomic-json').atomicWriteJson(path,value);});f.registry.register('smb',()=>provider('smb'));f.registry.register('drive',()=>provider('drive'));f.registry.activate('drive');fail=true;expect(()=>f.registry.activate('smb')).toThrow('Disk full');expect(f.registry.preferredId()).toBe('drive');expect(f.selected()?.id).toBe('drive');expect(()=>f.registry.deactivate('drive')).toThrow('Disk full');expect(f.selected()?.id).toBe('drive');});

test('provider registration rejects namespace collisions and mismatched factory identity',()=>{const f=fixture();f.registry.register('smb',()=>provider('smb'));expect(()=>f.registry.register('smb',()=>provider('drive'))).toThrow('registered');f.registry.register('drive',()=>provider('other'));expect(()=>f.registry.activate('drive')).toThrow('identity');expect(f.selected()).toBeUndefined();expect(f.registry.preferredId()).toBeNull();});
