import {test,expect,afterEach} from 'bun:test';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,unlinkSync,existsSync,rmSync} from 'node:fs';
import {dirname,join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import type {RemoteInventory,DeletionRecord,PublicationIntent,RevisionDeletionFence,ArtifactIdentity,Session} from '@heed/shared';
import type {LibraryProvider,RemoteTransaction} from './portable-provider';
import {makeBundle,portableMeeting,encode,sha256,revisionPath} from './portable-schema';
import {RemoteDeletion} from './remote-deletion';import {atomicWriteJson} from './atomic-json';
import {PortableLibrary} from './portable-library';import {SessionTags} from './session-tags';
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));
function fixture(){const root=mkdtempSync(join(tmpdir(),'heed-delete-'));roots.push(root);const remote=join(root,'remote');mkdirSync(remote);return {root,provider:new Files(remote)};}
class Files implements LibraryProvider,RemoteTransaction {
 id='synthetic-v2';name='Disposable share';transport='authenticated-network' as const;
 deletionCapabilities={connectionGeneration:'synthetic-1',revisionMetadata:true,sharedAudioGC:false,exclusion:'exclusive-create' as const,confirmation:'pending-verification' as const,destinationVersion:2 as const,destinationId:randomUUID()};
 data:RemoteInventory={commits:[],deletions:[],pending:[],complete:true};removed:string[]=[];checkpoints=0;failPath='';writes:string[]=[];active=false;requireOwner=false;intentsWritten=0;
 constructor(public root:string){}
 async withTransaction<T>(_context:any,run:(tx:RemoteTransaction)=>Promise<T>){if(this.active)throw Error('Remote transaction busy');this.active=true;try{return await run(this);}finally{this.active=false;}}
 async checkpoint(){this.checkpoints++;}
 async inventory(){return structuredClone(this.data);}
 async list(){return {commits:this.data.commits,next:null,complete:this.data.complete};}
 async read(path:string,max:number){if(this.requireOwner&&!this.active)throw Error('Missing whole transaction');const data=readFileSync(join(this.root,path));if(data.length>max)throw Error('Bounds');return data;}
 async *stream(path:string,max:number){yield await this.read(path,max);}
 async writeImmutable(path:string,data:Uint8Array){if(this.requireOwner&&!this.active)throw Error('Missing whole transaction');this.writes.push(path);const file=join(this.root,path);mkdirSync(dirname(file),{recursive:true});if(existsSync(file)){if(sha256(readFileSync(file))!==sha256(data))throw Error('Immutable conflict');return;}writeFileSync(file,data,{flag:'wx'});}
 async writeObjectImmutable(path:string,_bytes:number,_hash:string,data:AsyncIterable<Uint8Array>){const parts=[];for await(const chunk of data)parts.push(chunk);await this.writeImmutable(path,Buffer.concat(parts));}
 async confirm(){return 'remote-confirmed' as const;}
 async writeDeletion(record:DeletionRecord){await this.writeImmutable(`control/deletions/${record.jobId}.json`,encode(record));if(!this.data.deletions.some(r=>r.jobId===record.jobId))this.data.deletions.push(record);}
 async writeFence(record:RevisionDeletionFence){await this.writeImmutable(record.artifact.path,encode(record));}
 async writePending(intent:PublicationIntent){this.intentsWritten++;this.data.pending.push(intent);}
 async retirePending(intent:PublicationIntent){this.data.pending=this.data.pending.filter(i=>i.id!==intent.id);}
 async removeExact(_job:string,artifact:ArtifactIdentity){if(this.failPath===artifact.path)throw Error('Synthetic remove failure');const path=join(this.root,artifact.path);if(!existsSync(path))return 'already-removed' as const;const data=readFileSync(path);try{const fence=JSON.parse(data.toString());if(fence.kind==='heed-deleted-revision'&&fence.artifact.sha256===artifact.sha256)return 'already-removed' as const;}catch{}if(data.length!==artifact.bytes||sha256(data)!==artifact.sha256)throw Error('Expected content changed');unlinkSync(path);this.removed.push(artifact.path);return 'removed' as const;}
 async add(audio=Buffer.from('RIFF0000WAVEsynthetic audio'),libraryId=randomUUID(),meetingId=randomUUID(),parents:string[]=[]) {const session={id:'fixture',title:'Synthetic meeting',createdAt:'2026-10-06T00:00:00Z',duration:1,language:'en',transcript:'Synthetic text',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true} as Session;
  const payload=portableMeeting(session,meetingId,{sha256:sha256(audio),bytes:audio.length,format:'wav',mode:'archived',objectPath:`objects/${sha256(audio)}`}),bundle=makeBundle(libraryId,randomUUID(),payload,parents);await this.writeImmutable(payload.audio!.objectPath,audio);await this.writeImmutable(bundle.marker.manifestPath,encode(bundle.manifest));await this.writeImmutable(`${revisionPath(meetingId,bundle.marker.revisionId)}/meeting.json`,encode(payload));await this.writeImmutable(`commits/${bundle.marker.deviceId}/${bundle.marker.revisionId}.json`,encode(bundle.marker));this.data.commits.push(bundle.marker);return bundle;
 }
}
const selection=(f:ReturnType<typeof fixture>,bundles:Array<Awaited<ReturnType<Files['add']>>>)=>({providerId:f.provider.id,destinationId:f.provider.deletionCapabilities.destinationId,revisions:bundles.map(b=>({libraryId:b.manifest.libraryId,meetingId:b.manifest.meetingId,revisionId:b.manifest.revisionId}))});
function engine(f:ReturnType<typeof fixture>,write?:typeof atomicWriteJson,now=()=>Date.now()){return new RemoteDeletion({path:join(f.root,'private/deletions.json'),write,now});}
test('confirmed deletion physically unlinks selected metadata, preserves shared audio/other origins and writes canonical lineage fence',async()=>{
 const f=fixture(),first=await f.provider.add(),second=await f.provider.add(),e=engine(f);const preview=await e.preview(f.provider,f.provider,selection(f,[first]));expect(f.provider.removed).toHaveLength(0);expect(preview.retainedBytes).toBe(first.payload.audio!.bytes);
 const job=await e.confirm(f.provider,f.provider,preview.token,true);expect(job.state).toBe('pending-verification');expect(existsSync(join(f.provider.root,`${revisionPath(first.manifest.meetingId,first.manifest.revisionId)}/meeting.json`))).toBe(false);expect(JSON.parse(readFileSync(join(f.provider.root,first.marker.manifestPath),'utf8')).kind).toBe('heed-deleted-revision');expect(existsSync(join(f.provider.root,second.marker.manifestPath))).toBe(true);expect(existsSync(join(f.provider.root,first.payload.audio!.objectPath))).toBe(true);
 const count=f.provider.removed.length;expect((await e.confirm(f.provider,f.provider,preview.token,true)).id).toBe(job.id);expect(f.provider.removed).toHaveLength(count);
});
test('changed graph, expired token, unconfirmed request and changed destination have no physical effects',async()=>{
 const f=fixture(),first=await f.provider.add();let now=1000;const e=engine(f,undefined,()=>now),preview=await e.preview(f.provider,f.provider,selection(f,[first]));await expect(e.confirm(f.provider,f.provider,preview.token,false)).rejects.toThrow('Confirm');await f.provider.add();await expect(e.confirm(f.provider,f.provider,preview.token,true)).rejects.toThrow('changed');expect(f.provider.removed).toHaveLength(0);
 const fresh=await e.preview(f.provider,f.provider,selection(f,[first]));now+=600001;await expect(e.confirm(f.provider,f.provider,fresh.token,true)).rejects.toThrow('expired');now=1000;const other=await e.preview(f.provider,f.provider,selection(f,[first]));f.provider.deletionCapabilities.destinationId=randomUUID();await expect(e.confirm(f.provider,f.provider,other.token,true)).rejects.toThrow('destination');expect(f.provider.removed).toHaveLength(0);
});
test('incomplete scans and malformed references block preview and unsupported providers cannot delete',async()=>{
 const f=fixture(),first=await f.provider.add(),e=engine(f);f.provider.data.complete=false;await expect(e.preview(f.provider,f.provider,selection(f,[first]))).rejects.toThrow('incomplete');f.provider.data.complete=true;f.provider.data.pending=[{version:1,id:randomUUID(),deviceId:randomUUID(),revision:selection(f,[first]).revisions[0]!,audio:{path:'objects/../private',bytes:1,sha256:'a'.repeat(64)}}];await expect(e.preview(f.provider,f.provider,selection(f,[first]))).rejects.toThrow();f.provider.deletionCapabilities.destinationVersion=1 as any;await expect(e.preview(f.provider,f.provider,selection(f,[first]))).rejects.toThrow('v2');expect(f.provider.removed).toHaveLength(0);
});
test('restart after physical removal loses acknowledgment but safely retries exact job; missing fences do not authorize lease release',async()=>{
 const f=fixture(),first=await f.provider.add(),e=engine(f),preview=await e.preview(f.provider,f.provider,selection(f,[first]));f.provider.failPath=first.marker.manifestPath;const before=f.provider.checkpoints;const partial=await e.confirm(f.provider,f.provider,preview.token,true);expect(partial.state).toBe('incomplete');expect(f.provider.checkpoints).toBe(before);f.provider.failPath='';const restarted=engine(f),job=await restarted.retry(f.provider,f.provider,partial.id);expect(job.state).toBe('pending-verification');expect(f.provider.checkpoints).toBeGreaterThan(before);expect(readFileSync(join(f.provider.root,first.marker.manifestPath),'utf8')).toContain('heed-deleted-revision');
});
test('private prepared-job write failure cannot produce remote intent or physical effects',async()=>{
 const f=fixture(),first=await f.provider.add();let fail=false;const e=engine(f,(path,value)=>{if(fail&&(value as any).jobs&&Object.keys((value as any).jobs).length)throw Error('Disk full');atomicWriteJson(path,value);}),preview=await e.preview(f.provider,f.provider,selection(f,[first]));fail=true;await expect(e.confirm(f.provider,f.provider,preview.token,true)).rejects.toThrow('Disk');expect(f.provider.data.deletions).toHaveLength(0);expect(f.provider.removed).toHaveLength(0);
});
test('lost unlink acknowledgment is reconciled after restart without touching unselected artifacts',async()=>{
 const f=fixture(),first=await f.provider.add(),other=await f.provider.add(),e=engine(f),preview=await e.preview(f.provider,f.provider,selection(f,[first]));const remove=f.provider.removeExact.bind(f.provider);let interrupted=true;
 f.provider.removeExact=async(job,artifact)=>{const result=await remove(job,artifact);if(interrupted){interrupted=false;throw Error('Lost unlink acknowledgment');}return result;};const partial=await e.confirm(f.provider,f.provider,preview.token,true);expect(partial.state).toBe('incomplete');expect(partial.removed).toBe(0);const done=await engine(f).retry(f.provider,f.provider,partial.id);expect(done.state).toBe('pending-verification');expect(existsSync(join(f.provider.root,other.marker.manifestPath))).toBe(true);
});
test('a foreign unresolved publisher pins selected audio even for an explicitly enabled synthetic GC planner',async()=>{
 const f=fixture(),first=await f.provider.add();f.provider.deletionCapabilities.sharedAudioGC=true;f.provider.data.pending.push({version:1,id:randomUUID(),deviceId:randomUUID(),revision:{libraryId:randomUUID(),meetingId:randomUUID(),revisionId:randomUUID()},audio:{path:first.payload.audio!.objectPath,bytes:first.payload.audio!.bytes,sha256:first.payload.audio!.sha256}});const e=engine(f),preview=await e.preview(f.provider,f.provider,selection(f,[first]));expect(preview.retainedBytes).toBe(first.payload.audio!.bytes);await e.confirm(f.provider,f.provider,preview.token,true);expect(existsSync(join(f.provider.root,first.payload.audio!.objectPath))).toBe(true);
});
test('core discovery and full publication borrow one transaction; canonical admission precedes payload/media and pending references retire only after verification',async()=>{
 const f=fixture(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir),library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});const source=await f.provider.add();f.provider.requireOwner=true;const discovered=await library.discover();expect(discovered.complete).toBe(true);await library.importSelected();const imported=sessions.snapshot().sessions[0]!;expect(imported.transcript).toBe(source.payload.transcript);await library.requestAudio(imported.id);sessions.save({...imported,title:'Synthetic revised title',files:sessions.read(imported.id)!.files});const queued=await library.queueLocal(imported.id);f.provider.writes=[];await library.publish(queued.revisionId);expect(f.provider.writes[0]).toMatch(/manifest.json$/);expect(f.provider.intentsWritten).toBe(1);expect(f.provider.data.pending).toHaveLength(0);expect(f.provider.writes.at(-1)).toMatch(/^commits\//);
});
test('core deletion keeps local sessions, invalidates copy guarantees, and a stale inventory/new device cannot republish canonical fenced revision',async()=>{
 const f=fixture(),source=await f.provider.add(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir),library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});await library.discover();await library.importSelected();const imported=sessions.snapshot().sessions[0]!;const preview=await library.previewDeletion(selection(f,[source]));const job=await library.confirmDeletion(preview.token,true);expect(job.state).toBe('pending-verification');expect(sessions.read(imported.id)?.transcript).toBe(source.payload.transcript);const stale=structuredClone(f.provider.data.commits);f.provider.data.deletions=[];f.provider.data.commits=stale;await library.discover();expect(library.snapshot().previews.find(p=>p.revisionId===source.marker.revisionId)?.remoteDeleted).toBe(true);const snapshot=await library.publish(source.marker.revisionId);expect(snapshot.error||snapshot.previews.find(p=>p.revisionId===source.marker.revisionId)?.error).toBeTruthy();expect(readFileSync(join(f.provider.root,source.marker.manifestPath),'utf8')).toContain('heed-deleted-revision');
});
test('configuration generation changes reject an otherwise identical destination preview without remote effects',async()=>{const f=fixture(),source=await f.provider.add(),e=engine(f),preview=await e.preview(f.provider,f.provider,selection(f,[source]));f.provider.deletionCapabilities.connectionGeneration='synthetic-2';await expect(e.confirm(f.provider,f.provider,preview.token,true)).rejects.toThrow('configuration changed');expect(f.provider.removed).toHaveLength(0);expect(f.provider.data.deletions).toHaveLength(0);});
test('remote deletion suppresses automatic queueing but an explicit fresh revision retains deletion lineage and local transcript',async()=>{const f=fixture(),source=await f.provider.add(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir),library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});await library.discover();await library.importSelected();const local=sessions.snapshot().sessions[0]!;const preview=await library.previewDeletion(selection(f,[source]));await library.confirmDeletion(preview.token,true);expect(library.snapshot().localMeetings).toHaveLength(0);await expect(library.queueLocal(local.id)).rejects.toThrow('explicitly');const fresh=await library.queueLocal(local.id,undefined,true);expect(fresh.revisionId).not.toBe(source.marker.revisionId);const state=JSON.parse(readFileSync(join(f.root,'library/catalog/state.json'),'utf8'));expect(Object.values(state.entries).find((entry:any)=>entry.manifest.revisionId===fresh.revisionId)).toMatchObject({manifest:{parents:[source.marker.revisionId]}});expect(sessions.read(local.id)?.transcript).toBe(source.payload.transcript);});
test('private deletion journal refuses symlinks including dangling paths before any native effects',()=>{const f=fixture(),journal=join(f.root,'private/deletions.json');mkdirSync(dirname(journal));require('node:fs').symlinkSync(join(f.root,'missing'),journal);expect(()=>engine(f)).toThrow();});
test('pending iCloud propagation reconciles late original metadata using only the previously confirmed exact plan',async()=>{const f=fixture(),source=await f.provider.add(),other=await f.provider.add();f.provider.deletionCapabilities.confirmation='pending-propagation' as any;const e=engine(f),preview=await e.preview(f.provider,f.provider,selection(f,[source]));const done=await e.confirm(f.provider,f.provider,preview.token,true);expect(done.state).toBe('pending-propagation');const payloadPath=`${revisionPath(source.manifest.meetingId,source.manifest.revisionId)}/meeting.json`;writeFileSync(join(f.provider.root,source.marker.manifestPath),encode(source.manifest));writeFileSync(join(f.provider.root,payloadPath),encode(source.payload));writeFileSync(join(f.provider.root,`commits/${source.marker.deviceId}/${source.marker.revisionId}.json`),encode(source.marker));const resumed=await engine(f).retry(f.provider,f.provider,done.id);expect(resumed.state).toBe('pending-propagation');expect(existsSync(join(f.provider.root,payloadPath))).toBe(false);expect(readFileSync(join(f.provider.root,source.marker.manifestPath),'utf8')).toContain('heed-deleted-revision');expect(existsSync(join(f.provider.root,other.marker.manifestPath))).toBe(true);expect(existsSync(join(f.provider.root,source.payload.audio!.objectPath))).toBe(true);});
test('discovery reconciles one private confirmed iCloud job but never converts another device intent into destructive authority',async()=>{const f=fixture(),source=await f.provider.add();f.provider.deletionCapabilities.confirmation='pending-propagation' as any;const create=(id:string)=>{const sessionsDir=join(f.root,id,'sessions');mkdirSync(sessionsDir,{recursive:true});return new PortableLibrary({root:join(f.root,id,'library'),sessions:new SessionTags(sessionsDir),sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});};const original=create('original');await original.discover();const preview=await original.previewDeletion(selection(f,[source]));await original.confirmDeletion(preview.token,true);const payload=`${revisionPath(source.manifest.meetingId,source.manifest.revisionId)}/meeting.json`;const restore=()=>{writeFileSync(join(f.provider.root,source.marker.manifestPath),encode(source.manifest));writeFileSync(join(f.provider.root,payload),encode(source.payload));};restore();await original.discover();expect(existsSync(join(f.provider.root,payload))).toBe(false);expect(readFileSync(join(f.provider.root,source.marker.manifestPath),'utf8')).toContain('heed-deleted-revision');restore();const other=create('other'),before=f.provider.removed.length;await other.discover();expect(f.provider.removed).toHaveLength(before);expect(existsSync(join(f.provider.root,payload))).toBe(true);expect(other.deletionJobs()).toHaveLength(0);f.provider.deletionCapabilities.connectionGeneration='different-binding';await original.discover();expect(f.provider.removed).toHaveLength(before);expect(existsSync(join(f.provider.root,payload))).toBe(true);});
test('routine recovery reuses only the original private operation and its exact admitted revisions, excluding later queued sources',async()=>{const f=fixture(),source=await f.provider.add(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir),library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});await library.discover();await library.importSelected();await library.requestAudio(sessions.snapshot().sessions[0]!.id);const state=JSON.parse(readFileSync(join(f.root,'library/catalog/state.json'),'utf8')),operationId=randomUUID();(f.provider as any).pendingTransactions=()=>[{operationId,deviceId:state.deviceId,kind:'publish',recoverable:true,admissions:[{meetingId:source.manifest.meetingId,revisionId:source.manifest.revisionId,manifestHash:source.marker.manifestHash}]}];const top:string[]=[];f.provider.withTransaction=async(context:any,run:any)=>{if(f.provider.active)return run(f.provider);top.push(context.operationId);f.provider.active=true;try{return await run(f.provider);}finally{f.provider.active=false;}};sessions.create({...sessions.snapshot().sessions[0]!,id:'later-meeting',title:'Later meeting'});const later=await library.queueLocal('later-meeting');f.provider.writes=[];expect(library.recoveryTransactions()).toEqual([{operationId,kind:'publish',recoverable:true,releaseAvailable:true}]);await library.reconcileTransaction(operationId);expect(top).toEqual([operationId]);expect(f.provider.writes.some(path=>path.includes(later.revisionId))).toBe(false);(f.provider as any).pendingTransactions=()=>[{operationId,deviceId:state.deviceId,kind:'publish',recoverable:true,admissions:[{meetingId:source.manifest.meetingId,revisionId:source.manifest.revisionId,manifestHash:'0'.repeat(64)}]}];expect(library.recoveryTransactions()[0]?.recoverable).toBe(false);await expect(library.reconcileTransaction(operationId)).rejects.toThrow();await expect(library.reconcileTransaction(operationId,undefined,true)).rejects.toThrow('cannot be proven');expect(top).toHaveLength(1);});
test('a v2 publication interrupted after canonical admission persists unavailable state without authorizing lease release',async()=>{const f=fixture(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir);sessions.create({id:'synthetic',title:'Synthetic failure',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Approved synthetic publication',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true});const library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}}),queued=await library.queueLocal('synthetic');const write=f.provider.writeImmutable.bind(f.provider);f.provider.writeImmutable=async(path,data)=>{if(path.endsWith('/meeting.json'))throw Error('Synthetic transfer interrupted');return write(path,data);};const before=f.provider.checkpoints;await expect(library.publish(queued.revisionId)).rejects.toThrow('interrupted');expect(f.provider.checkpoints).toBe(before);expect(library.snapshot().previews.find(item=>item.revisionId===queued.revisionId)?.state).toBe('unavailable');expect(f.provider.data.pending).toHaveLength(1);expect(f.provider.writes.some(path=>path.startsWith('commits/'))).toBe(false);});
test('only a native-proved fresh no-effect collision can checkpoint after durable catalog error; a persistence fault retains the claim',async()=>{const f=fixture(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir);sessions.create({id:'synthetic',title:'Synthetic collision',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Approved synthetic publication',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true});let fail=false;const library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}},write:(path,value)=>{if(fail&&Object.values((value as any).entries||{}).some((entry:any)=>entry.preview.state==='unavailable'))throw Error('Private checkpoint unavailable');atomicWriteJson(path,value);}}),queued=await library.queueLocal('synthetic');f.provider.writeImmutable=async()=>{throw Object.assign(new Error('Canonical collision'),{code:'canonical-collision-noeffect'});};await expect(library.publish(queued.revisionId)).rejects.toThrow('collision');expect(f.provider.checkpoints).toBe(1);expect(f.provider.data.pending).toHaveLength(0);fail=true;await expect(library.publish(queued.revisionId)).rejects.toThrow('checkpoint');expect(f.provider.checkpoints).toBe(1);});
test('interrupted delete review without a durable destructive job is visible and can only release its exact original claim',async()=>{
 const f=fixture(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const library=new PortableLibrary({root:join(f.root,'library'),sessions:new SessionTags(sessionsDir),sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});const state=JSON.parse(readFileSync(join(f.root,'library/catalog/state.json'),'utf8')),operationId=randomUUID();
 (f.provider as any).pendingTransactions=()=>[{operationId,deviceId:state.deviceId,kind:'delete',releaseOnly:true,recoverable:true,admissions:[]}];
 const before=f.provider.checkpoints;expect(library.recoveryTransactions()).toEqual([{operationId,kind:'delete',recoverable:true,releaseOnly:true}]);
 f.provider.inventory=async()=>{throw Error('A release-only recovery must not scan or create destructive authority');};await library.reconcileTransaction(operationId);expect(f.provider.checkpoints).toBe(before+1);expect(library.deletionJobs()).toHaveLength(0);expect(f.provider.removed).toHaveLength(0);
 (f.provider as any).pendingTransactions=()=>[{operationId,deviceId:state.deviceId,kind:'delete',releaseOnly:true,recoverable:false,admissions:[],blockedReason:'Original connection generation required'}];expect(library.recoveryTransactions()[0]?.blockedReason).toBe('Original connection generation required');await expect(library.reconcileTransaction(operationId)).rejects.toThrow();expect(f.provider.checkpoints).toBe(before+1);
});
test('deletion jobs from an older binding stay visible but cannot be retried under a changed generation',async()=>{const f=fixture(),source=await f.provider.add(),e=engine(f),preview=await e.preview(f.provider,f.provider,selection(f,[source]));f.provider.failPath=source.marker.manifestPath;const job=await e.confirm(f.provider,f.provider,preview.token,true);f.provider.deletionCapabilities.connectionGeneration='other-generation';expect(e.jobs(f.provider)[0]?.blockedReason).toBe('Original connection generation required');await expect(e.retry(f.provider,f.provider,job.id)).rejects.toThrow('configuration changed');});
test('completed local-only publications are observed without re-admitting canonical manifests or blocking a later revision',async()=>{
 const f=fixture(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir);sessions.create({id:'synthetic',title:'Synthetic cloud publication',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Approved synthetic publication',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true});const library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});(f.provider as any).capabilities={durability:'local-only'};f.provider.confirm=async()=> 'local-only' as any;const first=await library.queueLocal('synthetic');await library.publish(first.revisionId);const before=f.provider.writes.length,write=f.provider.writeImmutable.bind(f.provider);f.provider.writeImmutable=async(path,bytes)=>{if(path.includes(first.revisionId))throw Error('Completed canonical admission must not be repeated');return write(path,bytes);};await library.publish(first.revisionId);expect(f.provider.writes).toHaveLength(before);expect(library.snapshot().previews.find(p=>p.revisionId===first.revisionId)?.state).toBe('pending');sessions.save({...sessions.read('synthetic')!,title:'Later revision'});const later=await library.queueLocal('synthetic');await library.publish(later.revisionId);expect(f.provider.writes.some(path=>path.includes(later.revisionId)&&path.startsWith('commits/'))).toBe(true);
});
test('a completed confirmed deletion with a checkpointed but unreleased claim remains visible for release-only recovery',async()=>{const f=fixture(),source=await f.provider.add(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const library=new PortableLibrary({root:join(f.root,'library'),sessions:new SessionTags(sessionsDir),sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});const preview=await library.previewDeletion(selection(f,[source])),done=await library.confirmDeletion(preview.token,true),state=JSON.parse(readFileSync(join(f.root,'library/catalog/state.json'),'utf8'));(f.provider as any).pendingTransactions=()=>[{operationId:done.id,deviceId:state.deviceId,kind:'delete',releaseOnly:true,recoverable:true,admissions:[]}];expect(library.recoveryTransactions()).toEqual([{operationId:done.id,kind:'delete',releaseOnly:true,recoverable:true}]);const before=f.provider.removed.length;f.provider.inventory=async()=>{throw Error('Completed deletion release must not rediscover or repeat removal');};await library.reconcileTransaction(done.id);expect(f.provider.removed).toHaveLength(before);});
test('a fully catalog-matched original publication remains release-only recoverable after its local source is deleted',async()=>{const f=fixture(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);const sessions=new SessionTags(sessionsDir);sessions.create({id:'synthetic',title:'Synthetic deleted source',createdAt:'2026-01-01T00:00:00Z',duration:1,language:'en',transcript:'Synthetic publication',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true});const library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}}),queued=await library.queueLocal('synthetic'),state=JSON.parse(readFileSync(join(f.root,'library/catalog/state.json'),'utf8')),entry=Object.values(state.entries)[0] as any,operationId=randomUUID();sessions.remove('synthetic');(f.provider as any).pendingTransactions=()=>[{operationId,deviceId:state.deviceId,kind:'publish',recoverable:true,admissions:[{meetingId:entry.manifest.meetingId,revisionId:queued.revisionId,manifestHash:entry.marker.manifestHash}]}];expect(library.recoveryTransactions()[0]).toMatchObject({recoverable:true,releaseOnly:true});f.provider.inventory=async()=>{throw Error('Deleted source recovery must never scan or replay');};const checkpoint=f.provider.checkpoint.bind(f.provider);f.provider.checkpoint=async()=>{throw Error('Native admission proof changed');};await expect(library.reconcileTransaction(operationId)).rejects.toThrow('Native admission proof changed');expect(f.provider.checkpoints).toBe(0);expect(library.recoveryTransactions()[0]?.releaseOnly).toBe(true);f.provider.checkpoint=checkpoint;await library.reconcileTransaction(operationId);expect(f.provider.checkpoints).toBe(1);});
test.each(['local-only','remote-confirmed'] as const)('a validated imported %s revision is observed without a new canonical admission on the importing device',async(confirmation)=>{const f=fixture(),source=await f.provider.add(),sessionsDir=join(f.root,'sessions');mkdirSync(sessionsDir);(f.provider as any).capabilities={durability:confirmation==='local-only'?'local-only':'share-readback'};f.provider.confirm=async()=>confirmation;const sessions=new SessionTags(sessionsDir),library=new PortableLibrary({root:join(f.root,'library'),sessions,sessionsDir,provider:f.provider,quota:{reserve(){},release(){}}});await library.discover();expect(library.hasLocalPublication(source.manifest.revisionId)).toBe(false);await library.importSelected();const queued=await library.queueLocal(sessions.snapshot().sessions[0]!.id);expect(queued.revisionId).toBe(source.manifest.revisionId);f.provider.data.pending.push({version:1,id:source.manifest.revisionId,deviceId:source.marker.deviceId,revision:{libraryId:source.manifest.libraryId,meetingId:source.manifest.meetingId,revisionId:source.manifest.revisionId}});const writes=f.provider.writes.length;f.provider.writeImmutable=async()=>{throw Error('Import has no original canonical admission receipt');};await library.publish(queued.revisionId);expect(f.provider.writes).toHaveLength(writes);expect(library.hasLocalPublication(queued.revisionId)).toBe(true);expect(f.provider.data.pending).toHaveLength(1);expect(f.provider.intentsWritten).toBe(0);f.provider.deletionCapabilities.connectionGeneration='changed-generation';await expect(library.publish(queued.revisionId)).rejects.toThrow('no original');});

test('direct v3 admits explicit exact deletion capabilities and preserves stale-generation protection',async()=>{
 const f=fixture(),source=await f.provider.add(),e=engine(f);f.provider.deletionCapabilities.destinationVersion=3 as any;(f.provider as any).observationDigest=async()=> '1'.repeat(64);const preview=await e.preview(f.provider,f.provider,selection(f,[source]));f.provider.deletionCapabilities.connectionGeneration='replacement';await expect(e.confirm(f.provider,f.provider,preview.token,true)).rejects.toThrow('configuration changed');expect(f.provider.removed).toHaveLength(0);
});
test('v3 deletion refuses unsupported exclusion before inventory or effects',async()=>{
 const f=fixture(),source=await f.provider.add(),e=engine(f);f.provider.deletionCapabilities.destinationVersion=3 as any;f.provider.deletionCapabilities.exclusion='none' as any;let reads=0;f.provider.inventory=async()=>{reads++;return f.provider.data;};await expect(e.preview(f.provider,f.provider,selection(f,[source]))).rejects.toThrow();expect(reads).toBe(0);expect(f.provider.removed).toHaveLength(0);
});

test('v3 confirmed preview refuses same-byte replacement represented by native stable observation digest',async()=>{
 const f=fixture(),source=await f.provider.add(),e=engine(f);f.provider.deletionCapabilities.destinationVersion=3 as any;let digest='1'.repeat(64);(f.provider as any).observationDigest=async()=>digest;const preview=await e.preview(f.provider,f.provider,selection(f,[source]));digest='2'.repeat(64);await expect(e.confirm(f.provider,f.provider,preview.token,true)).rejects.toThrow('changed');expect(f.provider.removed).toHaveLength(0);expect(f.provider.data.deletions).toHaveLength(0);
});
