import {expect,test} from 'bun:test';
import {mkdtempSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
async function fixture(){
 const root=mkdtempSync(join(tmpdir(),'heed-retrieval-chat-http-')),prompts:any[]=[];let app:Bun.Subprocess|undefined,hold=false,held=false,release:()=>void=()=>{};
 const model=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(req){const path=new URL(req.url).pathname;if(path==='/api/tags')return Response.json({models:[{name:'fixture:local'}]});const body=await req.json() as any;if(path==='/api/show')return Response.json({details:{family:'llama'},model_info:{'llama.context_length':8192},capabilities:['completion']});if(!body.prompt)return Response.json({done:true});const input=JSON.parse(body.prompt);prompts.push({body,input});if(hold){held=true;await new Promise<void>(resolve=>release=resolve);hold=false;}return Response.json({response:JSON.stringify({claims:input.evidence?.length?[{text:'Delivery is confirmed.',evidenceIds:[input.evidence[0].id]}]:[],notFound:!input.evidence?.length}),done:true,done_reason:'stop'});}});
 const reserve=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response()}),port=reserve.port;await reserve.stop(true);const base=`http://127.0.0.1:${port}`;
 const call=async(path:string,body?:unknown,extra:RequestInit={})=>{const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),...extra});return {status:response.status,body:await response.json() as any};};
 const wait=async(check:()=>Promise<boolean>)=>{for(let i=0;i<250;i++){if(await check())return;await Bun.sleep(20);}throw new Error('Retrieval HTTP condition timed out');};
 try{app=Bun.spawn([process.execPath,'run',join(import.meta.dir,'..','server.ts')],{cwd:join(import.meta.dir,'../../..'),env:{...process.env,HEED_APP_DIR:root,HEED_RECORDINGS_DIR:join(root,'recordings'),HEED_MODEL:'',HEED_API_PORT:String(port),PORT:String(port),HEED_UI_PORT:'48101',HEED_TRANSCRIPTION_PORT:'48102',HEED_TRANSCRIPTION_URL:base,VITE_API_BASE:base,OLLAMA_HOST:`http://127.0.0.1:${model.port}`},stdout:'ignore',stderr:'ignore'});await wait(async()=>{try{return (await call('/api/sessions')).status===200;}catch{return false;}});}catch(error){app?.kill('SIGTERM');if(app)await app.exited;model.stop(true);rmSync(root,{recursive:true,force:true});throw error;}
 const add=async(id:string,tags=['Work'],text='Delivery confirmed. Low-risk rollout.')=>{const response=await call('/api/sessions',{id,title:id,tags,duration:4,language:'en',transcriptFinalized:true,transcript:text,segments:[{speaker:'Ana',text,start:1,end:4}],speakers:['Ana']});expect(response.status).toBe(200);return response.body;};
 return {root,prompts,call,wait,add,hold:()=>{hold=true;held=false;},held:()=>held,release:()=>release(),close:async()=>{release();app?.kill('SIGTERM');if(app)await app.exited;await model.stop(true);rmSync(root,{recursive:true,force:true});}};
}
const scope={mode:'labels',labels:['Work'],match:'any'};
const guard=(source:any)=>({expectedTranscriptRevision:source.transcriptRevision,expectedTranscriptVersion:source.transcriptVersion});
test('production chat uses current SQLite evidence and truthful counters, zero hits never call the model',async()=>{
 const f=await fixture();try{const source=await f.add('allowed');await f.add('excluded',['Other'],'EXCLUDED_ONLY secret delivery rejected.');await f.wait(async()=>existsSync(join(f.root,'library/indexes/retrieval/active.json')));
 const send=await f.call('/api/sessions/allowed/chat',{action:'send',requestId:'grounded',question:'Delivery?',model:'fixture:local',expectedSourceRevision:source.transcriptRevision});expect(send.status).toBe(200);await f.wait(async()=>(await f.call('/api/sessions/allowed/chat')).body.turns[0]?.status==='completed');const turn=(await f.call('/api/sessions/allowed/chat')).body.turns[0];expect(turn.answer.coverage).toMatchObject({complete:false,retrieval:{selectedMeetings:1,selectedEvidence:1,indexedEvidence:1,searchedMeetings:1,searchedEvidence:1,matchedEvidence:1,retrievedEvidence:1,suppliedEvidence:1,citedEvidence:1,indexComplete:true,lookupComplete:true,generationComplete:true}});expect(turn.answer.claims[0].citations[0]).toMatchObject({sessionId:'allowed',quote:'Delivery confirmed. Low-risk rollout.',start:1,end:4});
 const context=await f.call('/api/library-chat/context',{scope});expect(context.status).toBe(200);expect((await f.call('/api/library-chat/command',{scope,command:{action:'send',requestId:'scoped',question:'Delivery?',model:'fixture:local',expectedSourceRevision:context.body.preview.snapshot.key}})).status).toBe(200);await f.wait(async()=>(await f.call('/api/library-chat/context',{scope})).body.thread.turns[0]?.status==='completed');expect(JSON.stringify(f.prompts)).not.toContain('EXCLUDED_ONLY');expect(f.prompts.length).toBe(2);for(const prompt of f.prompts)expect(Buffer.byteLength(prompt.body.system+prompt.body.prompt)).toBeLessThanOrEqual(5500);
 expect((await f.call('/api/sessions/allowed/chat',{action:'send',requestId:'zero',question:'zebra?',model:'fixture:local',expectedSourceRevision:source.transcriptRevision})).status).toBe(200);await f.wait(async()=>(await f.call('/api/sessions/allowed/chat')).body.turns[1]?.status==='completed');const zero=(await f.call('/api/sessions/allowed/chat')).body.turns[1];expect(zero.answer.claims).toEqual([]);expect(zero.answer.coverage.retrieval).toMatchObject({searchedEvidence:1,matchedEvidence:0,retrievedEvidence:0,suppliedEvidence:0,citedEvidence:0});expect(f.prompts.length).toBe(2);
 }finally{await f.close();}
},15000);
test('held production generation rejects durable edit/revert ABA and non-hash candidate replacement version changes',async()=>{
 const f=await fixture();try{let source=await f.add('allowed');for(const change of ['aba','candidate'] as const){f.hold();const thread=(await f.call('/api/sessions/allowed/chat')).body;expect((await f.call('/api/sessions/allowed/chat',{action:'send',requestId:change,question:'Delivery?',model:'fixture:local',expectedSourceRevision:source.transcriptRevision,expectedThreadRevision:thread.revision})).status).toBe(200);await f.wait(async()=>f.held());const before=source.transcriptRevision;
 if(change==='aba'){let edited=await f.call('/api/sessions/allowed/transcript/commands',{...guard(source),requestId:'edit-aba',action:'edit',target:{kind:'segment',index:0},text:'Delivery rejected.'});expect(edited.status).toBe(200);source=edited.body;const reverted=await f.call('/api/sessions/allowed/transcript/commands',{...guard(source),requestId:'revert-aba',action:'revert',editId:source.transcriptEditing.edits[0].id});expect(reverted.status).toBe(200);source=reverted.body;expect(source.transcriptRevision).toBe(before);}else{const staged=await f.call('/api/sessions/allowed/transcript/candidates',{requestId:'nonhash-stage',base:guard(source),result:{success:true,finalized:true,text:source.transcript,segments:source.segments,speakers:source.speakers,duration:(source.duration??0)+1,metadata:{language:source.language,model:'fixture'},files:{wav:'',txt:'',srt:''},wordCount:8}});expect(staged.status).toBe(200);const response=await f.call('/api/sessions/allowed/transcript/commands',{...guard(staged.body),requestId:'nonhash-accept',action:'accept-candidate',candidateId:staged.body.transcriptEditing.candidates[0].id});expect(response.status).toBe(200);source=response.body;expect(source.transcriptRevision).toBe(before);}
 f.release();await f.wait(async()=>['failed','cancelled'].includes((await f.call('/api/sessions/allowed/chat')).body.turns.at(-1)?.status));const latest=(await f.call('/api/sessions/allowed/chat')).body.turns.at(-1);expect(latest.reason).toBe('source-changed');expect(latest.answer).toBeUndefined();expect(latest.stale).toBe(true);
 }
 }finally{await f.close();}
},15000);
test('held production scoped generation rejects renamed membership and stale public snapshot requests',async()=>{
 const f=await fixture();try{const source=await f.add('allowed'),before=await f.call('/api/library-chat/context',{scope});f.hold();expect((await f.call('/api/library-chat/command',{scope,command:{action:'send',requestId:'held-scope',question:'Delivery?',model:'fixture:local',expectedSourceRevision:before.body.preview.snapshot.key}})).status).toBe(200);await f.wait(async()=>f.held());expect((await f.call('/api/sessions?id=allowed',{tags:['Other'],tagsRevision:source.tagsRevision},{method:'PATCH'})).status).toBe(200);f.release();await f.wait(async()=>(await f.call('/api/library-chat/context',{scope})).body.thread.turns[0]?.status==='failed');const changed=(await f.call('/api/library-chat/context',{scope})).body;expect(changed.thread.turns[0].reason).toBe('scope-changed');expect(changed.thread.turns[0].answer).toBeUndefined();expect((await f.call('/api/library-chat/command',{scope,command:{action:'send',requestId:'stale',question:'Delivery?',model:'fixture:local',expectedSourceRevision:before.body.preview.snapshot.key}})).status).toBe(409);
 }finally{await f.close();}
},15000);
test('held production generation rejects speaker renames and cannot resurrect deleted chat',async()=>{
 const f=await fixture();try{let source=await f.add('allowed');f.hold();expect((await f.call('/api/sessions/allowed/chat',{action:'send',requestId:'speaker',question:'Delivery?',model:'fixture:local',expectedSourceRevision:source.transcriptRevision})).status).toBe(200);await f.wait(async()=>f.held());
 const renamed=await f.call('/api/sessions?id=allowed',{...guard(source),speakers:['Bruno'],segments:source.segments.map((segment:any)=>({...segment,speaker:'Bruno'}))},{method:'PATCH'});expect(renamed.status).toBe(200);source=renamed.body;f.release();await f.wait(async()=>(await f.call('/api/sessions/allowed/chat')).body.turns[0]?.status==='failed');expect((await f.call('/api/sessions/allowed/chat')).body.turns[0]).toMatchObject({reason:'source-changed',stale:true});
 f.hold();expect((await f.call('/api/sessions/allowed/chat',{action:'send',requestId:'delete',question:'Delivery?',model:'fixture:local',expectedSourceRevision:source.transcriptRevision})).status).toBe(200);await f.wait(async()=>f.held());expect((await f.call('/api/sessions?id=allowed',undefined,{method:'DELETE'})).status).toBe(200);f.release();await Bun.sleep(40);expect((await f.call('/api/sessions/allowed/chat')).status).toBe(404);expect(existsSync(join(f.root,'chat','allowed.json'))).toBe(false);
 }finally{await f.close();}
},15000);
