import { afterEach, expect, test } from 'bun:test';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, symlinkSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { sessionAudioResponse } from './session-audio';
const dirs:string[]=[];
afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true});});
function fixture(){const root=mkdtempSync(join(tmpdir(),'heed-audio-'));dirs.push(root);const sessions=join(root,'sessions'),audio=join(root,'recordings');mkdirSync(sessions);mkdirSync(audio);const path=join(audio,'meeting.wav');writeFileSync(path,'0123456789');writeFileSync(join(sessions,'session-1.json'),JSON.stringify({files:{wav:path}}));return {root,sessions,audio,path};}
function request(headers:Record<string,string>={},method='GET'){return new Request('http://localhost:5001/api/sessions/session-1/audio',{headers,method});}
test('serve áudio completo e HEAD sem corpo',async()=>{const f=fixture();const r=await sessionAudioResponse(request(),'session-1',f.sessions,f.audio);expect(r.status).toBe(200);expect(r.headers.get('content-type')).toBe('audio/wav');expect(await r.text()).toBe('0123456789');const h=await sessionAudioResponse(request({},'HEAD'),'session-1',f.sessions,f.audio);expect(h.headers.get('content-length')).toBe('10');expect(await h.text()).toBe('');});
test('permite avançar com intervalos e sufixos',async()=>{const f=fixture();for(const [range,body] of [['bytes=2-5','2345'],['bytes=7-','789'],['bytes=-3','789']]){const r=await sessionAudioResponse(request({Range:range}),'session-1',f.sessions,f.audio);expect(r.status).toBe(206);expect(await r.text()).toBe(body);expect(r.headers.get('accept-ranges')).toBe('bytes');}});
test('rejeita intervalos inválidos',async()=>{const f=fixture();for(const range of ['bytes=10-','bytes=5-2','bytes=0-1,3-4','bytes=-0']){const r=await sessionAudioResponse(request({Range:range}),'session-1',f.sessions,f.audio);expect(r.status).toBe(416);expect(r.headers.get('content-range')).toBe('bytes */10');}});
test('áudio expirado ou sessão ausente retorna 404',async()=>{const f=fixture();rmSync(f.path);expect((await sessionAudioResponse(request(),'session-1',f.sessions,f.audio)).status).toBe(404);expect((await sessionAudioResponse(request(),'missing',f.sessions,f.audio)).status).toBe(404);});
test('bloqueia travessia, caminhos externos e escapes por symlink',async()=>{const f=fixture();expect((await sessionAudioResponse(request(),'../session-1',f.sessions,f.audio)).status).toBe(403);const outside=join(f.root,'secret.wav');writeFileSync(outside,'secret');for(const path of [outside,join(f.audio,'link.wav')]){if(path!==outside)symlinkSync(outside,path);writeFileSync(join(f.sessions,'session-1.json'),JSON.stringify({files:{wav:path}}));expect((await sessionAudioResponse(request(),'session-1',f.sessions,f.audio)).status).toBe(403);}});
test('bloqueia sessão com symlink externo e caminho não confiável inexistente',async()=>{const f=fixture();writeFileSync(join(f.sessions,'session-1.json'),JSON.stringify({files:{wav:join(f.root,'inexistente.wav')}}));expect((await sessionAudioResponse(request(),'session-1',f.sessions,f.audio)).status).toBe(403);const outside=join(f.root,'external.json');writeFileSync(outside,JSON.stringify({files:{wav:f.path}}));rmSync(join(f.sessions,'session-1.json'));symlinkSync(outside,join(f.sessions,'session-1.json'));expect((await sessionAudioResponse(request(),'session-1',f.sessions,f.audio)).status).toBe(403);});
test('HEAD com intervalo conserva os metadados sem corpo',async()=>{const f=fixture();const r=await sessionAudioResponse(request({Range:'bytes=2-99'},'HEAD'),'session-1',f.sessions,f.audio);expect(r.status).toBe(206);expect(r.headers.get('content-range')).toBe('bytes 2-9/10');expect(r.headers.get('content-length')).toBe('8');expect(await r.text()).toBe('');});
