import { afterEach, expect, test } from 'bun:test';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, symlinkSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { sessionAudioResponse } from './session-audio';
const dirs:string[]=[];
afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true});});
function fixture(){const root=mkdtempSync(join(tmpdir(),'heed-audio-'));dirs.push(root);const sessions=join(root,'sessions'),audio=join(root,'recordings');mkdirSync(sessions);mkdirSync(audio);const path=join(audio,'meeting.wav');writeFileSync(path,'0123456789');writeFileSync(join(sessions,'session-1.json'),JSON.stringify({files:{wav:path}}));return {root,sessions,audio,path};}
function request(headers:Record<string,string>={},method='GET'){return new Request('http://localhost:5001/api/sessions/session-1/audio',{headers,method});}
test('serves complete audio and HEAD without a body',async()=>{const f=fixture();const r=await sessionAudioResponse(request(),'session-1',f.sessions,f.audio);expect(r.status).toBe(200);expect(r.headers.get('content-type')).toBe('audio/wav');expect(await r.text()).toBe('0123456789');const h=await sessionAudioResponse(request({},'HEAD'),'session-1',f.sessions,f.audio);expect(h.headers.get('content-length')).toBe('10');expect(await h.text()).toBe('');});
test('supports seeking with ranges and suffixes',async()=>{const f=fixture();for(const [range,body] of [['bytes=2-5','2345'],['bytes=7-','789'],['bytes=-3','789']]){const r=await sessionAudioResponse(request({Range:range}),'session-1',f.sessions,f.audio);expect(r.status).toBe(206);expect(await r.text()).toBe(body);expect(r.headers.get('accept-ranges')).toBe('bytes');}});
test('rejects invalid ranges',async()=>{const f=fixture();for(const range of ['bytes=10-','bytes=5-2','bytes=0-1,3-4','bytes=-0']){const r=await sessionAudioResponse(request({Range:range}),'session-1',f.sessions,f.audio);expect(r.status).toBe(416);expect(r.headers.get('content-range')).toBe('bytes */10');}});
test('expired audio or missing session returns 404',async()=>{const f=fixture();rmSync(f.path);expect((await sessionAudioResponse(request(),'session-1',f.sessions,f.audio)).status).toBe(404);expect((await sessionAudioResponse(request(),'missing',f.sessions,f.audio)).status).toBe(404);});
test('blocks traversal, external paths, and symlink escapes',async()=>{const f=fixture();expect((await sessionAudioResponse(request(),'../session-1',f.sessions,f.audio)).status).toBe(403);const outside=join(f.root,'secret.wav');writeFileSync(outside,'secret');for(const path of [outside,join(f.audio,'link.wav')]){if(path!==outside)symlinkSync(outside,path);writeFileSync(join(f.sessions,'session-1.json'),JSON.stringify({files:{wav:path}}));expect((await sessionAudioResponse(request(),'session-1',f.sessions,f.audio)).status).toBe(403);}});
test('blocks external session symlinks and missing untrusted paths',async()=>{const f=fixture();writeFileSync(join(f.sessions,'session-1.json'),JSON.stringify({files:{wav:join(f.root,'missing.wav')}}));expect((await sessionAudioResponse(request(),'session-1',f.sessions,f.audio)).status).toBe(403);const outside=join(f.root,'external.json');writeFileSync(outside,JSON.stringify({files:{wav:f.path}}));rmSync(join(f.sessions,'session-1.json'));symlinkSync(outside,join(f.sessions,'session-1.json'));expect((await sessionAudioResponse(request(),'session-1',f.sessions,f.audio)).status).toBe(403);});
test('HEAD with a range preserves metadata without a body',async()=>{const f=fixture();const r=await sessionAudioResponse(request({Range:'bytes=2-99'},'HEAD'),'session-1',f.sessions,f.audio);expect(r.status).toBe(206);expect(r.headers.get('content-range')).toBe('bytes 2-9/10');expect(r.headers.get('content-length')).toBe('8');expect(await r.text()).toBe('');});
test('managed library media supports seeking while adjacent catalog and symlink escapes remain blocked',async()=>{const f=fixture(),media=join(f.root,'library','media');mkdirSync(media,{recursive:true});const wav=join(media,'verified.wav');writeFileSync(wav,'0123456789');writeFileSync(join(f.sessions,'session-1.json'),JSON.stringify({files:{wav:wav}}));const response=await sessionAudioResponse(request({Range:'bytes=1-3'}),'session-1',f.sessions,[f.audio,media]);expect(response.status).toBe(206);expect(await response.text()).toBe('123');const secret=join(f.root,'library','private.wav');writeFileSync(secret,'secret');symlinkSync(secret,join(media,'escape.wav'));for(const path of [secret,join(media,'escape.wav')]){writeFileSync(join(f.sessions,'session-1.json'),JSON.stringify({files:{wav:path}}));expect((await sessionAudioResponse(request(),'session-1',f.sessions,[f.audio,media])).status).toBe(403);}});
test('transcript-only pending and completed meetings deny GET and HEAD even if owned audio still exists',async()=>{const f=fixture();for(const status of ['pending','completed'])for(const method of ['GET','HEAD']){writeFileSync(join(f.sessions,'session-1.json'),JSON.stringify({meetingMode:'transcript-only',audioCleanup:{status},files:{wav:f.path}}));const response=await sessionAudioResponse(request({},method),'session-1',f.sessions,f.audio);expect(response.status).toBe(410);expect(response.headers.get('X-Heed-Audio-Unavailable-Reason')).toBe('transcript-only');expect(await response.text()).not.toBe('0123456789');}});
