import {test,expect,spyOn} from 'bun:test';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,rmSync,realpathSync,watch} from 'node:fs';
import {join,dirname} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID,createHash} from 'node:crypto';
import {SmbProvider,MacSmbNative,type SmbBinding} from './smb-provider';
import {fileURLToPath} from 'node:url';
const digest=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
async function waitForFixtureFlag(flag:string,operation:Promise<unknown>,timeoutMs=5000){
 let watcher:ReturnType<typeof watch>|undefined,timer:ReturnType<typeof setTimeout>|undefined;
 try {
  await new Promise<void>((resolve,reject)=>{
   watcher=watch(dirname(flag),()=>{if(existsSync(flag))resolve();});
   watcher.on('error',reject);
   timer=setTimeout(()=>reject(Error('Synthetic guardian did not reach the injected fault before the readiness deadline')),timeoutMs);
   // Observe errors immediately, rather than mistaking invalid Python or native failures for slow startup.
   operation.then(()=>reject(Error('Synthetic guardian completed before the injected fault')),reject);
   if(existsSync(flag))resolve();
  });
 } finally {clearTimeout(timer);watcher?.close();}
}

test.each([0,1250])('lost checkpoint acknowledgement with admitted metadata exposes release-only recovery without publication replay (startup delay %ims)',async startupDelayMs=>{
 const f=fixture(),deviceId=randomUUID(),b=bundle(deviceId),context={operationId:randomUUID(),deviceId,kind:'publish' as const},controller=new AbortController();
 try {
  const wrapper=join(f.root,'guardian.py'),flag=join(f.root,'checkpoint-fault');
  const interrupted=readFileSync(wrapper,'utf8').replace('m.serve_transaction(r,',`import time\nfrom pathlib import Path\noriginal=m.Transaction.checkpoint\ndef interrupted(self):\n    original(self)\n    flag=Path(${JSON.stringify(flag)})\n    if self.journal['admissions'] and not flag.exists():\n        flag.write_text('fault')\n        time.sleep(60)\nm.Transaction.checkpoint=interrupted\nm.serve_transaction(r,`);
  // Exercise cold fixture startup without changing production guardian deadlines.
  writeFileSync(wrapper, startupDelayMs ? `import time\ntime.sleep(${startupDelayMs/1000})\n${interrupted}` : interrupted);
  const operation=f.provider.withTransaction!(context,async tx=>{await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);await tx.checkpoint();},controller.signal);
  await waitForFixtureFlag(flag,operation);
  expect(existsSync(flag)).toBe(true);
  controller.abort();await expect(operation).rejects.toThrow();
  expect(f.provider.pendingTransactions()[0]).toMatchObject({operationId:context.operationId,releaseOnly:true,recoverable:true});
  await f.provider.withTransaction!(context,tx=>tx.checkpoint());
  expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);
  expect(readFileSync(join(f.share,b.marker.manifestPath))).toEqual(b.manifest);
 } finally {await f.cleanup();}
},15000);
test('fixture readiness reports an invalid guardian immediately instead of a startup timeout',async()=>{
 const f=fixture();
 try {
  writeFileSync(join(f.root,'guardian.py'),'invalid Python syntax!\n');
  const operation=f.provider.withTransaction!({operationId:randomUUID(),deviceId:randomUUID(),kind:'read'},tx=>tx.checkpoint());
  await expect(waitForFixtureFlag(join(f.root,'never-created'),operation)).rejects.toThrow('SMB operation unavailable');
 } finally {await f.cleanup();}
});
test('lost whole-claim release acknowledgement resumes only original cleanup and returns success without replay',async()=>{const f=fixture(),context={operationId:randomUUID(),deviceId:randomUUID(),kind:'read' as const};try{const wrapper=join(f.root,'guardian.py'),flag=join(f.root,'release-fault');writeFileSync(wrapper,readFileSync(wrapper,'utf8').replace('m.serve_transaction(r,',`from pathlib import Path\noriginal=m.Transaction.finish_release\ndef interrupted(self):\n    flag=Path(${JSON.stringify(flag)})\n    if not flag.exists():\n        flag.write_text('fault')\n        raise OSError('Injected release cleanup interruption')\n    return original(self)\nm.Transaction.finish_release=interrupted\nm.serve_transaction(r,`));await expect(f.provider.withTransaction!(context,tx=>tx.checkpoint())).rejects.toThrow();expect(f.provider.pendingTransactions()[0]).toMatchObject({operationId:context.operationId,releaseOnly:true,recoverable:true});await f.provider.withTransaction!(context,async tx=>{await tx.checkpoint();await expect(f.provider.read('objects/'+'a'.repeat(64),100)).rejects.toThrow('closed');});expect(f.provider.pendingTransactions()).toEqual([]);expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);}finally{await f.cleanup();}});
test('persistent guardian has no fixed lifetime deadline and idle checkpointed cancellation releases it',async()=>{const f=fixture(),controller=new AbortController(),timer=spyOn(globalThis,'setTimeout');let resolve!:()=>void;try{const operation=f.provider.withTransaction!({operationId:randomUUID(),deviceId:randomUUID(),kind:'publish'},async()=>{await new Promise<void>(r=>resolve=r);},controller.signal);for(let i=0;i<100&&!resolve;i++)await Bun.sleep(10);expect(timer.mock.calls.filter(args=>args[1]===120_000)).toHaveLength(1);controller.abort(Error('Recording priority'));resolve();await operation;expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);expect((await Promise.all(f.children.map(child=>child.exited))).every(code=>typeof code==='number')).toBe(true);}finally{timer.mockRestore();await f.cleanup();}});
test('interrupted empty publication and deletion review expose exact release-only recovery; changed generation remains visible and blocked',async()=>{const f=fixture(),deviceId=randomUUID(),context={operationId:randomUUID(),deviceId,kind:'publish' as const},entered=join(f.root,'rpc-entered');try{const wrapper=join(f.root,'guardian.py');writeFileSync(wrapper,readFileSync(wrapper,'utf8').replace('m.serve_transaction(r,',`import time\nfrom pathlib import Path\ndef blocked(self,*args):\n    Path(${JSON.stringify(entered)}).write_text('entered')\n    time.sleep(60)\nm.Transaction.inventory=blocked\nm.serve_transaction(r,`));const controller=new AbortController(),operation=f.provider.withTransaction!(context,tx=>tx.inventory(controller.signal),controller.signal);for(let i=0;i<100&&!existsSync(entered);i++)await Bun.sleep(10);controller.abort();await expect(operation).rejects.toThrow();expect(f.provider.pendingTransactions()[0]).toMatchObject({operationId:context.operationId,recoverable:true,releaseOnly:true});const changed=new SmbProvider({...f.binding,connectionGeneration:randomUUID()},new MacSmbNative(),undefined,f.app);expect(changed.pendingTransactions()[0]).toMatchObject({operationId:context.operationId,recoverable:false,blockedReason:expect.any(String)});await f.provider.withTransaction!(context,tx=>tx.checkpoint());expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);rmSync(entered);const review={operationId:randomUUID(),deviceId,kind:'delete' as const},reviewAbort=new AbortController(),reviewRun=f.provider.withTransaction!(review,tx=>tx.inventory(reviewAbort.signal),reviewAbort.signal);for(let i=0;i<100&&!existsSync(entered);i++)await Bun.sleep(10);reviewAbort.abort();await expect(reviewRun).rejects.toThrow();expect(f.provider.pendingTransactions()[0]).toMatchObject({operationId:review.operationId,kind:'delete',releaseOnly:true,recoverable:true});await f.provider.withTransaction!(review,tx=>tx.checkpoint());expect(f.provider.pendingTransactions()).toEqual([]);}finally{await f.cleanup();}});
function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),'heed-smb-v2-'))),share=join(root,'share'),app=join(root,'app');mkdirSync(share);mkdirSync(app);const binding:SmbBinding={id:randomUUID(),name:'Synthetic v2',root:share,identity:{type:'smbfs',fsid:'1:2',sourceHash:'a'.repeat(64),mountPath:share,readOnly:false},destinationId:randomUUID(),destinationVersion:2,readOnly:false,security:'signed'};writeFileSync(join(share,'heed-library.json'),JSON.stringify({format:'heed-portable-library',schemaVersion:2,destinationId:binding.destinationId}));const helper=fileURLToPath(new URL('../native/smb-filesystem.py',import.meta.url)),wrapper=join(root,'guardian.py');writeFileSync(wrapper,`import importlib.util,json,sys,signal\ns=importlib.util.spec_from_file_location('native',${JSON.stringify(helper)});m=importlib.util.module_from_spec(s);s.loader.exec_module(m)\nsignal.signal(signal.SIGTERM,lambda a,b:sys.exit(1))\nr=json.loads(sys.stdin.buffer.readline(16385))\nif r.get('action')=='probe':\n    print(json.dumps({'identity':r['identity'],'security':'signed','dialect':'SMB_3.1.1','authentication':'macOS-session','atomicOperations':True}),flush=True);sys.exit(0)\nm.serve_transaction(r,sys.stdin.buffer,sys.stdout.buffer,factory=lambda app,r:m.Transaction(app,r,probe=lambda fd:r['identity'],physical=lambda:'11111111-1111-4111-8111-111111111111',security=lambda path:{'security':'signed'}))\n`);const spawn=Bun.spawn.bind(Bun);let count=0;const children:ReturnType<typeof Bun.spawn>[]=[];const spy=spyOn(Bun,'spawn').mockImplementation((command:any,options:any)=>{count++;const child=spawn(['/usr/bin/python3',wrapper],options);children.push(child);return child as any;});return {root,share,app,binding,provider:new SmbProvider(binding,new MacSmbNative(),undefined,app),count:()=>count,children,cleanup:async()=>{spy.mockRestore();for(const child of children){child.kill();await child.exited;}rmSync(root,{recursive:true,force:true});}};}
function bundle(deviceId:string){const libraryId=randomUUID(),meetingId=randomUUID(),revisionId=randomUUID(),prefix=`meetings/${meetingId}/revisions/${revisionId}`,payload=Buffer.from(JSON.stringify({schemaVersion:1,meetingId,title:'Known synthetic fixture'})),manifest=Buffer.from(JSON.stringify({schemaVersion:1,libraryId,meetingId,revisionId,parents:[],artifacts:[{path:'meeting.json',bytes:payload.length,sha256:digest(payload)}]})),marker={schemaVersion:1 as const,libraryId,meetingId,revisionId,deviceId,manifestPath:`${prefix}/manifest.json`,manifestHash:digest(manifest)};return {prefix,payload,manifest,marker};}
test('v2 raw calls fail without a transaction; one tracked guardian spans nested I/O and refuses escaped contexts',async()=>{const f=fixture(),deviceId=randomUUID(),b=bundle(deviceId);try{await expect(f.provider.read('objects/'+'a'.repeat(64),4)).rejects.toThrow('transaction');expect(f.count()).toBe(0);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let escaped:Promise<unknown>|undefined;await f.provider.withTransaction({operationId:randomUUID(),deviceId,kind:'publish'},async tx=>{await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);await f.provider.writeImmutable(`${b.prefix}/meeting.json`,b.payload);await f.provider.withTransaction({operationId:randomUUID(),deviceId,kind:'read'},async inner=>{expect((await inner.inventory()).complete).toBe(true);});await f.provider.writeImmutable(`commits/${deviceId}/${b.marker.revisionId}.json`,Buffer.from(JSON.stringify(b.marker)));expect((await tx.inventory()).commits).toEqual([b.marker]);escaped=(async()=>{await gate;return f.provider.read(b.marker.manifestPath,65536);})();escaped.catch(()=>{});await tx.checkpoint();});expect(f.count()).toBe(1);expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);release();await expect(escaped!).rejects.toThrow('transaction');expect(f.count()).toBe(1);}finally{await f.cleanup();}});
test('later effect revokes prior checkpoint and error retains native claim until exact original operation recovery',async()=>{const f=fixture(),deviceId=randomUUID(),b=bundle(deviceId),context={operationId:randomUUID(),deviceId,kind:'publish' as const};try{await expect(f.provider.withTransaction(context,async tx=>{await tx.checkpoint();await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);throw Error('Private persistence failed');})).rejects.toThrow('Private persistence failed');expect(existsSync(join(f.share,'.heed-v2-lease/owner.json'))).toBe(true);expect(f.provider.pendingTransactions()).toEqual([{operationId:context.operationId,deviceId,kind:'publish',recoverable:true,admissions:[{meetingId:b.marker.meetingId,revisionId:b.marker.revisionId,manifestHash:b.marker.manifestHash}]}]);await f.provider.withTransaction(context,async tx=>{await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);await tx.checkpoint();});expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);expect(readFileSync(join(f.share,b.marker.manifestPath))).toEqual(b.manifest);}finally{await f.cleanup();}});
test('actual metadata delete/fence is idempotent; production caps never offer shared audio GC or remote confirmation',async()=>{const f=fixture(),deviceId=randomUUID(),b=bundle(deviceId);try{expect(f.provider.deletionCapabilities.sharedAudioGC).toBe(false);expect(f.provider.deletionCapabilities.confirmation).toBe('pending-verification');await f.provider.withTransaction({operationId:randomUUID(),deviceId,kind:'publish'},async tx=>{await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);await f.provider.writeImmutable(`${b.prefix}/meeting.json`,b.payload);await f.provider.writeImmutable(`commits/${deviceId}/${b.marker.revisionId}.json`,Buffer.from(JSON.stringify(b.marker)));await tx.checkpoint();});const jobId=randomUUID(),revision={libraryId:b.marker.libraryId,meetingId:b.marker.meetingId,revisionId:b.marker.revisionId,manifestHash:b.marker.manifestHash,parents:[]},artifacts=[{path:`commits/${deviceId}/${b.marker.revisionId}.json`,bytes:Buffer.from(JSON.stringify(b.marker)).length,sha256:digest(Buffer.from(JSON.stringify(b.marker)))},{path:`${b.prefix}/meeting.json`,bytes:b.payload.length,sha256:digest(b.payload)},{path:b.marker.manifestPath,bytes:b.manifest.length,sha256:digest(b.manifest)}],record={version:1 as const,jobId,destinationId:f.binding.destinationId,revisions:[revision],artifacts};await f.provider.withTransaction({operationId:jobId,deviceId,kind:'delete'},async tx=>{await tx.writeDeletion(record);for(const a of artifacts){expect(await tx.removeExact(jobId,a)).toBe('removed');expect(await tx.removeExact(jobId,a)).toBe('already-removed');}await tx.writeFence({kind:'heed-deleted-revision',version:1,jobId,destinationId:record.destinationId,revision,artifact:artifacts[2]!});await tx.checkpoint();});expect(existsSync(join(f.share,`${b.prefix}/meeting.json`))).toBe(false);expect(JSON.parse(readFileSync(join(f.share,b.marker.manifestPath),'utf8')).kind).toBe('heed-deleted-revision');await expect(f.provider.withTransaction({operationId:randomUUID(),deviceId:randomUUID(),kind:'publish'},async()=>{await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);})).rejects.toThrow();}finally{await f.cleanup();}});
test('a rejected canonical collision can durably checkpoint its error and release without stranding a fresh claim',async()=>{const f=fixture(),deviceId=randomUUID(),b=bundle(deviceId);try{await f.provider.withTransaction({operationId:randomUUID(),deviceId,kind:'publish'},async tx=>{await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);await tx.checkpoint();});await f.provider.withTransaction({operationId:randomUUID(),deviceId,kind:'publish'},async tx=>{await expect(f.provider.writeImmutable(b.marker.manifestPath,b.manifest)).rejects.toMatchObject({code:'canonical-collision-noeffect'});await tx.checkpoint();});expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);}finally{await f.cleanup();}});
test('actual malformed early native response kills/reaps before awaiting a blocked large pipe producer',async()=>{const f=fixture(),deviceId=randomUUID(),body=Buffer.alloc(32*1024*1024,7);try{writeFileSync(join(f.root,'guardian.py'),"import sys,json,time\nr=json.loads(sys.stdin.buffer.readline())\nif r.get('action')=='probe':\n    print(json.dumps({'identity':r['identity'],'security':'signed','dialect':'SMB_3.1.1','authentication':'macOS-session','atomicOperations':True}),flush=True);sys.exit(0)\nprint(json.dumps({'ok':True,'ready':True,'checkpointed':False}),flush=True)\nc=json.loads(sys.stdin.buffer.readline())\nprint(json.dumps({'id':c['id']+1,'ok':True}),flush=True)\ntime.sleep(60)\n");const operation=f.provider.withTransaction({operationId:randomUUID(),deviceId,kind:'publish'},async()=>{await f.provider.writeImmutable(`meetings/${randomUUID()}/revisions/${randomUUID()}/manifest.json`,body);});await expect(Promise.race([operation,Bun.sleep(2000).then(()=>{throw Error('Early rejection cleanup deadlocked');})])).rejects.toThrow('SMB operation unavailable');expect((await Promise.all(f.children.map(child=>child.exited))).every(code=>typeof code==='number')).toBe(true);}finally{await f.cleanup();}});
test('capture-style cancellation of a blocked actual guardian reaps it and retains the unconfirmed claim',async()=>{const f=fixture(),deviceId=randomUUID(),controller=new AbortController(),entered=join(f.root,'write-entered');try{const wrapper=join(f.root,'guardian.py');let code=readFileSync(wrapper,'utf8');code=code.replace('m.serve_transaction(r,',`import time\nfrom pathlib import Path\ndef blocked(self,*args):\n    Path(${JSON.stringify(entered)}).write_text('entered')\n    time.sleep(60)\nm.Transaction.write=blocked\nm.serve_transaction(r,`);writeFileSync(wrapper,code);const operation=f.provider.withTransaction({operationId:randomUUID(),deviceId,kind:'publish'},async()=>{await f.provider.writeImmutable(`meetings/${randomUUID()}/revisions/${randomUUID()}/manifest.json`,Buffer.alloc(5*1024*1024),controller.signal);},controller.signal);for(let i=0;i<100&&!existsSync(entered);i++)await Bun.sleep(10);expect(existsSync(join(f.share,'.heed-v2-lease/owner.json'))).toBe(true);controller.abort(Error('Recording priority'));await expect(Promise.race([operation,Bun.sleep(2000).then(()=>{throw Error('Cancellation cleanup deadlocked');})])).rejects.toThrow();expect((await Promise.all(f.children.map(child=>child.exited))).every(code=>typeof code==='number')).toBe(true);expect(existsSync(join(f.share,'.heed-v2-lease/owner.json'))).toBe(true);}finally{await f.cleanup();}});
test('a real managed quota reservation precedes native effects and is released only after guardian exit',async()=>{const {ManagedQuota}=await import('./managed-quota'),f=fixture();try{const catalog=join(f.app,'library/catalog');mkdirSync(catalog,{recursive:true});let limit=4_000_000;const quota=new ManagedQuota({ledgerPath:join(f.app,'quota.json'),roots:{text:[catalog]},getLimit:()=>limit,setLimit:value=>limit=value,protectedPaths:()=>[]}),provider=new SmbProvider(f.binding,new MacSmbNative(),undefined,f.app,quota),context={operationId:randomUUID(),deviceId:randomUUID(),kind:'read' as const};await expect(provider.withTransaction!(context,async()=>{})).rejects.toThrow('insufficient');expect(f.count()).toBe(0);limit=32_000_000;await provider.withTransaction!(context,async tx=>{expect(quota.allocation('smb-transaction-'+context.operationId)?.bytes).toBe(8_000_000);await tx.checkpoint();});expect((await Promise.all(f.children.map(child=>child.exited))).every(code=>typeof code==='number')).toBe(true);expect(quota.allocation('smb-transaction-'+context.operationId)).toBeNull();}finally{await f.cleanup();}});
test('actual core publication, preview and physical confirm preserve local transcript and shared WAV',async()=>{const {PortableLibrary}=await import('./portable-library'),{SessionTags}=await import('./session-tags'),f=fixture();try{const sessionsDir=join(f.app,'sessions'),recordingsDir=join(f.app,'recordings');mkdirSync(sessionsDir);mkdirSync(recordingsDir);const sessions=new SessionTags(sessionsDir),wav=join(recordingsDir,'synthetic.wav');writeFileSync(wav,Buffer.from('RIFF0000WAVEknown synthetic audio'));const session=sessions.create({id:randomUUID(),title:'Disposable synthetic QA',createdAt:'2026-10-06T00:00:00Z',duration:1,language:'en',transcript:'Known synthetic text only',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true,files:{wav}}),library=new PortableLibrary({root:join(f.app,'library'),sessions,sessionsDir,recordingsDir,provider:f.provider,quota:{reserve(){},release(){}}});const queued=await library.queueLocal(session.id);const published=await library.publish(queued.revisionId);expect(published.previews.find(p=>p.revisionId===queued.revisionId)?.state).toBe('verified');const preview=await library.previewDeletion({providerId:f.provider.id,destinationId:f.binding.destinationId,revisions:[{libraryId:queued.libraryId,meetingId:queued.meetingId,revisionId:queued.revisionId}]});const job=await library.confirmDeletion(preview.token,true);expect(job.state).toBe('pending-verification');expect(existsSync(join(f.share,`meetings/${queued.meetingId}/revisions/${queued.revisionId}/meeting.json`))).toBe(false);expect(sessions.read(session.id)?.transcript).toBe('Known synthetic text only');expect(existsSync(wav)).toBe(true);expect(readFileSync(join(f.share,`meetings/${queued.meetingId}/revisions/${queued.revisionId}/manifest.json`),'utf8')).toContain('heed-deleted-revision');expect(f.provider.pendingTransactions()).toEqual([]);}finally{await f.cleanup();}});
test('dangling private transaction ancestry fails closed and read-only v2 never starts a helper',async()=>{const {symlinkSync}=await import('node:fs'),f=fixture();try{mkdirSync(join(f.app,'library/catalog'),{recursive:true});symlinkSync(join(f.root,'missing'),join(f.app,'library/catalog/transactions'));expect(()=>f.provider.pendingTransactions()).toThrow('Invalid SMB transaction');expect(f.count()).toBe(0);const readonly=new SmbProvider({...f.binding,readOnly:true},new MacSmbNative(),undefined,f.app);expect(readonly.deletionCapabilities.revisionMetadata).toBe(false);await expect(readonly.withTransaction!({operationId:randomUUID(),deviceId:randomUUID(),kind:'read'},async()=>{})).rejects.toThrow('coordination');expect(f.count()).toBe(0);}finally{await f.cleanup();}});

test('silent guardian initialization has an independent bounded deadline and reaps without effects',async()=>{const f=fixture(),original=setTimeout,timer=spyOn(globalThis,'setTimeout').mockImplementation(((fn:any,ms:any,...args:any[])=>original(fn,ms===120_000?150:ms,...args)) as any);try{writeFileSync(join(f.root,'guardian.py'),"import sys,json,time\nr=json.loads(sys.stdin.buffer.readline())\nif r.get('action')=='probe':\n    print(json.dumps({'identity':r['identity'],'security':'signed','dialect':'SMB_3.1.1','authentication':'macOS-session','atomicOperations':True}),flush=True);sys.exit(0)\ntime.sleep(60)\n");await expect(Promise.race([f.provider.withTransaction!({operationId:randomUUID(),deviceId:randomUUID(),kind:'read'},async()=>{}),Bun.sleep(1000).then(()=>{throw Error('Unbounded initialization');})])).rejects.toThrow('SMB operation unavailable');expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);expect((await Promise.all(f.children.map(c=>c.exited))).every(code=>typeof code==='number')).toBe(true);}finally{timer.mockRestore();await f.cleanup();}});
test.each([0,1250])('serialized heartbeats permit a slow RPC but cannot extend its independent absolute deadline (startup delay %ims)',async startupDelayMs=>{
 const f=fixture(),original=setTimeout;
 const withShortRpcTimers=async<T>(run:()=>Promise<T>)=>{
  const timer=spyOn(globalThis,'setTimeout').mockImplementation(((fn:any,ms:any,...args:any[])=>original(fn,ms===120_000?500:ms===600_000?1200:ms,...args)) as any);
  try{return await run();}finally{timer.mockRestore();}
 };
 try{
  const wrapper=join(f.root,'guardian.py');
  let code=readFileSync(wrapper,'utf8').replace('m.serve_transaction(r,',"import time\ndef slow(self):\n    time.sleep(.7)\n    return {'commits':[],'deletions':[],'pending':[],'complete':True}\nm.Transaction.inventory=slow\nm.serve_transaction(r,").replace('factory=lambda app,r:', 'heartbeat_interval=.03,factory=lambda app,r:');
  if(startupDelayMs)code=`import time\ntime.sleep(${startupDelayMs/1000})\n${code}`;
  writeFileSync(wrapper,code);
  await f.provider.withTransaction!({operationId:randomUUID(),deviceId:randomUUID(),kind:'read'},async tx=>{expect((await withShortRpcTimers(()=>tx.inventory())).complete).toBe(true);await tx.checkpoint();});
  expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);
  writeFileSync(wrapper,readFileSync(wrapper,'utf8').replace('time.sleep(.7)','time.sleep(60)'));
  await expect(f.provider.withTransaction!({operationId:randomUUID(),deviceId:randomUUID(),kind:'read'},tx=>Promise.race([withShortRpcTimers(()=>tx.inventory()),Bun.sleep(2500).then(()=>{throw Error('Heartbeat removed absolute deadline');})]))).rejects.toThrow(/SMB operation unavailable|SMB transaction is closed/);
  expect(f.provider.pendingTransactions()[0]).toMatchObject({releaseOnly:true,recoverable:true});
 }finally{await f.cleanup();}
},15000);
test('opening preemption waits only a bounded receipt window and releases a known fresh acquisition without running caller effects',async()=>{const f=fixture(),controller=new AbortController(),entered=join(f.root,'opening');let ran=false;try{const wrapper=join(f.root,'guardian.py');writeFileSync(wrapper,readFileSync(wrapper,'utf8').replace('m.serve_transaction(r,',`import time\nfrom pathlib import Path\noriginal=m.Transaction.__init__\ndef slow(self,*args,**kwargs):\n    original(self,*args,**kwargs)\n    Path(${JSON.stringify(entered)}).write_text('known receipt')\n    time.sleep(.25)\nm.Transaction.__init__=slow\nm.serve_transaction(r,`));const operation=f.provider.withTransaction!({operationId:randomUUID(),deviceId:randomUUID(),kind:'publish'},async()=>{ran=true;},controller.signal);for(let i=0;i<100&&!existsSync(entered);i++)await Bun.sleep(10);expect(existsSync(entered)).toBe(true);controller.abort(Error('Recording priority'));await expect(operation).rejects.toThrow('Recording priority');expect(ran).toBe(false);expect(existsSync(join(f.share,'.heed-v2-lease'))).toBe(false);expect(f.provider.pendingTransactions()).toEqual([]);expect((await Promise.all(f.children.map(c=>c.exited))).every(code=>typeof code==='number')).toBe(true);}finally{await f.cleanup();}});
test('a hung checkpointed release cannot delay recording cleanup and retains exact release-only recovery',async()=>{const f=fixture(),original=setTimeout,timer=spyOn(globalThis,'setTimeout').mockImplementation(((fn:any,ms:any,...args:any[])=>original(fn,ms===1500?150:ms,...args)) as any);try{const wrapper=join(f.root,'guardian.py'),source=readFileSync(wrapper,'utf8');writeFileSync(wrapper,source.replace('m.serve_transaction(r,',"import time\ndef blocked(self):\n    time.sleep(60)\nm.Transaction.release=blocked\nm.serve_transaction(r,"));const context={operationId:randomUUID(),deviceId:randomUUID(),kind:'read' as const};await expect(Promise.race([f.provider.withTransaction!(context,tx=>tx.checkpoint()),Bun.sleep(1000).then(()=>{throw Error('Release cleanup unbounded');})])).rejects.toThrow('SMB operation unavailable');expect(f.provider.pendingTransactions()[0]).toMatchObject({operationId:context.operationId,releaseOnly:true,recoverable:true});writeFileSync(wrapper,source);await f.provider.withTransaction!(context,tx=>tx.checkpoint());expect(f.provider.pendingTransactions()).toEqual([]);}finally{timer.mockRestore();await f.cleanup();}});
test('unsupported volume native preflight creates no remote claim or journal and never runs caller effects',async()=>{const f=fixture();try{const wrapper=join(f.root,'guardian.py');writeFileSync(wrapper,readFileSync(wrapper,'utf8').replace('m.serve_transaction(r,',"m.volume_atomic_operations=lambda fd:False\nm.serve_transaction(r,"));const names=(await import('node:fs')).readdirSync(f.share);await expect(f.provider.withTransaction!({operationId:randomUUID(),deviceId:randomUUID(),kind:'publish'},async()=>{throw Error('Caller should never run');})).rejects.toMatchObject({code:'unsupported-filesystem'});expect(f.count()).toBe(1);expect((await import('node:fs')).readdirSync(f.share)).toEqual(names);expect(f.provider.pendingTransactions()).toEqual([]);expect((await import('node:fs')).readdirSync(join(f.app,'library/catalog/transactions'))).toEqual([f.binding.destinationId+'.guard']);expect((await Promise.all(f.children.map(c=>c.exited))).every(code=>typeof code==='number')).toBe(true);}finally{await f.cleanup();}});
test('actual RPC heartbeat thread cannot deliver SIGTERM inside canonical CREATE-to-receipt critical section',async()=>{const f=fixture(),b=bundle(randomUUID()),context={operationId:randomUUID(),deviceId:randomUUID(),kind:'publish' as const},controller=new AbortController(),created=join(f.root,'stage-created');try{const wrapper=join(f.root,'guardian.py'),source=readFileSync(wrapper,'utf8');writeFileSync(wrapper,source.replace('m.serve_transaction(r,',`import os,time\nfrom pathlib import Path\noriginal=m.os.open\ndef opened(path,*args,**kwargs):\n    fd=original(path,*args,**kwargs)\n    if isinstance(path,str) and path.endswith('.stage'):\n        Path(${JSON.stringify(created)}).write_text('created')\n        time.sleep(.35)\n    return fd\nm.os.open=opened\nm.serve_transaction(r,`));const operation=f.provider.withTransaction!(context,async()=>{await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);},controller.signal);for(let i=0;i<100&&!existsSync(created);i++)await Bun.sleep(10);expect(existsSync(created)).toBe(true);controller.abort(Error('Recording priority'));await expect(operation).rejects.toThrow();expect(f.provider.pendingTransactions()[0]).toMatchObject({recoverable:true,admissions:[{manifestHash:b.marker.manifestHash}]});writeFileSync(wrapper,source);await f.provider.withTransaction!(context,async tx=>{await f.provider.writeImmutable(b.marker.manifestPath,b.manifest);await tx.checkpoint();});expect(readFileSync(join(f.share,b.marker.manifestPath))).toEqual(b.manifest);expect(f.provider.pendingTransactions()).toEqual([]);}finally{await f.cleanup();}});
