import {expect,test} from 'bun:test';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
test('production router and desktop poll expose correlated SMB folder controls without capture or private data',async()=>{
 const root=mkdtempSync(join(tmpdir(),'heed-smb-router-'));const sidecar=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({whisper:true})});const reservation=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response()});const base=`http://127.0.0.1:${reservation.port}`;reservation.stop(true);
 const child=Bun.spawn([process.execPath,resolve(import.meta.dir,'../server.ts')],{cwd:resolve(import.meta.dir,'../../..'),env:{...process.env,PORT:base.split(':').at(-1)!,HEED_APP_DIR:root,HEED_RECORDINGS_DIR:join(root,'recordings'),HEED_TRANSCRIPTION_URL:`http://127.0.0.1:${sidecar.port}`},stdout:'ignore',stderr:'pipe'});
 const request=(path:string,body?:unknown,origin?:string)=>fetch(base+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(origin?{origin}:{})},body:body?JSON.stringify(body):undefined});
 try{const deadline=Date.now()+8000;let ready=false;while(Date.now()<deadline){try{if((await request('/api/smb')).ok){ready=true;break;}}catch{}await Bun.sleep(30);}expect(ready).toBe(true);
  expect((await request('/api/smb',undefined,'https://outside.example')).status).toBe(403);expect((await request('/api/smb',{action:'folder'},'https://outside.example')).status).toBe(403);
  expect((await (await request('/api/smb',{action:'folder'})).json()).desktopPending).toBe(true);const poll=await (await request('/api/desktop/control/poll',{client:'synthetic'})).json();expect(poll.command).toBeNull();expect(poll.status.smbCommand.action).toBe('folder');expect(poll.status.recording).toBe(false);
  expect((await request('/api/smb',{action:'desktop-report',id:poll.status.smbCommand.id,folder:root,failed:false})).status).toBe(200);const failed=await request('/api/smb',{action:'test',folder:root});expect(failed.status).toBe(503);expect(await failed.text()).not.toContain(root);expect((await (await request('/api/recording/status')).json()).state).toBe('idle');expect((await request('/api/library')).status).toBe(200);
 }finally{child.kill();await child.exited;sidecar.stop(true);rmSync(root,{recursive:true,force:true});}
},12000);
test.each(['provider-preference.json','library/catalog/smb-connections.json'])('corrupt optional %s fails closed while local meetings, capture status and media protection survive',async(relative)=>{
 const root=mkdtempSync(join(tmpdir(),'heed-smb-corrupt-'));const corrupt=join(root,relative);const {mkdirSync,writeFileSync,readFileSync}=await import('node:fs');const {dirname}=await import('node:path');mkdirSync(dirname(corrupt),{recursive:true});writeFileSync(corrupt,'{corrupt');mkdirSync(join(root,'sessions'));mkdirSync(join(root,'recordings'));const wav=join(root,'recordings','source.wav');writeFileSync(wav,Buffer.alloc(1200000));writeFileSync(join(root,'sessions','fixture.json'),JSON.stringify({id:'fixture',title:'Retained local meeting',createdAt:'2026-10-05T00:00:00Z',duration:1,language:'en',transcript:'Retained complete transcript',segments:[],speakers:[],tags:[],aiNotes:'Retained notes',summary:'',pinned:false,transcriptFinalized:true,files:{wav}}));writeFileSync(join(root,'config.json'),JSON.stringify({storage_limit_bytes:4000000}));
 const sidecar=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>Response.json({whisper:true})}),reservation=Bun.serve({hostname:'127.0.0.1',port:0,fetch:()=>new Response()}),base=`http://127.0.0.1:${reservation.port}`;reservation.stop(true);const child=Bun.spawn([process.execPath,resolve(import.meta.dir,'../server.ts')],{cwd:resolve(import.meta.dir,'../../..'),env:{...process.env,PORT:base.split(':').at(-1)!,HEED_APP_DIR:root,HEED_RECORDINGS_DIR:join(root,'recordings'),HEED_TRANSCRIPTION_URL:`http://127.0.0.1:${sidecar.port}`},stdout:'ignore',stderr:'ignore'});
 try{let ready=false;const deadline=Date.now()+2500;while(Date.now()<deadline){try{if((await fetch(base+'/api/recording/status')).ok){ready=true;break;}}catch{}await Bun.sleep(30);}expect(ready).toBe(true);expect((await fetch(base+'/api/smb')).status).toBe(503);expect((await fetch(base+'/api/library')).status).toBe(503);expect((await fetch(base+'/api/library',{headers:{origin:'https://outside.example'}})).status).toBe(403);expect((await (await fetch(base+'/api/sessions')).json())[0].transcript).toBe('Retained complete transcript');expect((await (await fetch(base+'/api/recording/status')).json()).state).toBe('idle');const reduction=await fetch(base+'/api/storage/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({limitBytes:1048576})});expect(reduction.status).toBe(409);expect(readFileSync(corrupt,'utf8')).toBe('{corrupt');expect(readFileSync(wav).length).toBe(1200000);}finally{child.kill();await child.exited;sidecar.stop(true);rmSync(root,{recursive:true,force:true});}
},8000);
