import {describe,expect,test} from 'bun:test';import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {SmbConnections,smbAddress} from './smb-connections';import type {SmbNative,SmbRequest} from './smb-provider';
class NativeFixture implements SmbNative {
 destinationId:string|null=null;readonly=false;fsid='1:2';security:'signed'|'unknown'='signed';available=true;
 async json(r:SmbRequest){if(!this.available)throw new Error('private credential-bearing native diagnostics must be suppressed');if(r.action==='probe')return {identity:{type:'smbfs',fsid:this.fsid,sourceHash:'a'.repeat(64),mountPath:'/fixture/share',readOnly:this.readonly},security:this.security,dialect:'SMB_3.1.1',authentication:'macOS-session'};if(r.action==='header'||r.action==='library')return this.destinationId?{format:'heed-portable-library',schemaVersion:1,destinationId:this.destinationId}:null;if(r.action==='create')this.destinationId=(r.header as {destinationId:string}).destinationId;if(r.action==='test-write'&&this.readonly)throw new Error('denied');return {};}
 async read(){return Buffer.alloc(0);}async *stream(){yield Buffer.alloc(0);}async write(){}
}
const setup=()=>{const root=mkdtempSync(join(tmpdir(),'heed-smb-')),native=new NativeFixture();let provider:unknown;const library:ConstructorParameters<typeof SmbConnections>[0]['library']={selectProvider:(p:unknown)=>{provider=p;},snapshot:()=>({localMeetings:[{id:'synthetic',title:'Meeting'}],previews:[],imported:1,skipped:0,complete:true}),discover:async()=>{},importSelected:async()=>{},queueLocal:async()=>({revisionId:randomUUID(),state:'pending'}),publish:async()=>({previews:[]})};const service=new SmbConnections({path:join(root,'smb.json'),native,library,busy:()=>false});return {root,native,service,library,provider:()=>provider,clean:()=>{service.close();rmSync(root,{recursive:true,force:true});}};};
describe('SMB connection controls',()=>{
 test('guided addresses reject credentials, query, traversal and non-SMB schemes',()=>{expect(smbAddress('smb://server/Share')).toBe('smb://server/Share');for(const v of ['smb://user:secret@server/share','smb://user@server/share','https://server/share','smb://server/share?password=secret','smb://server/share/../other','smb://server/share#secret'])expect(()=>smbAddress(v)).toThrow();});
 test('creation requires current explicit confirmation, restart keeps device settings private',async()=>{const f=setup();try{const preview=await f.service.test('/fixture/share');expect(preview.needsCreation).toBe(true);await expect(f.service.connect({name:'Office',receipt:preview.receipt,create:false})).rejects.toThrow();const result=await f.service.connect({name:'Office',receipt:preview.receipt,create:true});expect(result.connections[0]!.destinationId).toBe(f.native.destinationId);expect(f.provider()).toBeDefined();const raw=readFileSync(join(f.root,'smb.json'),'utf8');expect(raw).not.toContain('password');const restored=new SmbConnections({path:join(f.root,'smb.json'),native:f.native,library:f.library,busy:()=>false});expect(restored.snapshot().connections).toHaveLength(1);restored.close();}finally{f.clean();}});
 test('replaced mount invalidates tested receipt and old configuration is unchanged',async()=>{const f=setup();try{f.native.destinationId=randomUUID();const receipt=await f.service.test('/fixture/share');f.native.fsid='3:4';await expect(f.service.connect({name:'Office',receipt:receipt.receipt,create:false})).rejects.toThrow();expect(f.service.snapshot().connections).toHaveLength(0);}finally{f.clean();}});
 test('rename/disable/disconnect never deletes meetings or changes recording preferences',async()=>{const f=setup();try{f.native.destinationId=randomUUID();const receipt=await f.service.test('/fixture/share');const connected=await f.service.connect({name:'Office',receipt:receipt.receipt,create:false});const id=connected.connections[0]!.id;f.service.rename(id,'Travel');expect(f.service.snapshot().connections[0]!.name).toBe('Travel');f.service.enable(id,false);expect(f.provider()).toBeUndefined();expect(f.service.snapshot().connections[0]!.enabled).toBe(false);f.service.disconnect(id);expect(f.service.snapshot().connections).toHaveLength(0);expect(f.library.snapshot().localMeetings).toHaveLength(1);}finally{f.clean();}});
 test('read-only imports never enqueue uploads and offline queue diagnostics are sanitized',async()=>{const f=setup();try{f.native.readonly=true;f.native.destinationId=randomUUID();const preview=await f.service.test('/fixture/share');expect(preview.readOnly).toBe(true);await f.service.connect({name:'Read only',receipt:preview.receipt,create:false});await f.service.tick();expect(f.service.snapshot().connections[0]!.pending).toBe(0);f.native.available=false;await f.service.tick();expect(JSON.stringify(f.service.snapshot())).not.toContain('credential-bearing');}finally{f.clean();}});
 test('persistence failure rolls configuration back',async()=>{const f=setup();try{f.native.destinationId=randomUUID();const service=new SmbConnections({path:join(f.root,'bad.json'),native:f.native,library:f.library,busy:()=>false,write:()=>{throw new Error('disk full');}});const receipt=await service.test('/fixture/share');await expect(service.connect({name:'Office',receipt:receipt.receipt,create:false})).rejects.toThrow();expect(service.snapshot().connections).toHaveLength(0);service.close();}finally{f.clean();}});
 test('publication acknowledgments belong to each destination, not global revision status',async()=>{const f=setup();try{f.native.destinationId=randomUUID();const revisionId=randomUUID();let publishes=0;f.library.queueLocal=async()=>({revisionId,state:'verified'});f.library.snapshot=()=>({localMeetings:[{id:'synthetic',title:'Meeting'}],previews:[{revisionId,state:'verified'}],imported:1,skipped:0,complete:true});f.library.publish=async()=>{publishes++;return {previews:[]};};let receipt=await f.service.test('/fixture/share');await f.service.connect({name:'First',receipt:receipt.receipt,create:false});await f.service.tick();expect(publishes).toBe(1);await f.service.tick();expect(publishes).toBe(1);f.native.destinationId=randomUUID();receipt=await f.service.test('/fixture/share');await f.service.connect({name:'Second',receipt:receipt.receipt,create:false});await f.service.tick();expect(publishes).toBe(2);}finally{f.clean();}});
 test('offline queue survives restart and recording busy skips all remote work',async()=>{const f=setup();try{f.native.destinationId=randomUUID();const revisionId=randomUUID();f.library.queueLocal=async()=>({revisionId,state:'pending'});const receipt=await f.service.test('/fixture/share');await f.service.connect({name:'Office',receipt:receipt.receipt,create:false});await f.service.tick();expect(f.service.snapshot().connections[0]!.pending).toBe(1);const restored=new SmbConnections({path:join(f.root,'smb.json'),native:f.native,library:f.library,busy:()=>true});f.native.available=false;await restored.tick();expect(restored.snapshot().connections[0]!.pending).toBe(1);expect(restored.snapshot().connections[0]!.error).not.toContain('credential');restored.close();}finally{f.clean();}});
});
