import {smbResponse} from './smb-http';
import {afterEach,expect,test} from 'bun:test';
import {mkdtempSync,realpathSync,mkdirSync,readFileSync,writeFileSync,rmSync,symlinkSync,truncateSync} from 'node:fs';
import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {SmbConnections} from './smb-connections';import {SmbProvider,type SmbNative,type SmbRequest} from './smb-provider';import {PortableLibrary} from './portable-library';import {ProviderRegistry} from './provider-registry';import {SessionTags} from './session-tags';import {ManagedQuota} from './managed-quota';import {atomicWriteJson} from './atomic-json';
const cleanups:(()=>void)[]=[];afterEach(()=>{for(const cleanup of cleanups.splice(0))cleanup();});
function fixture(){
 const root=realpathSync(mkdtempSync(join(tmpdir(),'heed-smb-recovery-')));mkdirSync(join(root,'sessions'));mkdirSync(join(root,'recordings'));const wav=join(root,'recordings','sole-source.wav');writeFileSync(wav,Buffer.alloc(1200000));const sessions=new SessionTags(join(root,'sessions'));sessions.create({id:'synthetic',title:'Retained meeting',createdAt:'2026-10-05T00:00:00Z',duration:1,language:'en',transcript:'Retained transcript',segments:[],speakers:[],tags:[],aiNotes:'',summary:'',pinned:false,transcriptFinalized:true,files:{wav}});
 let destinationId:string=randomUUID(),nativeCalls=0;const native:SmbNative={async json(request:SmbRequest){nativeCalls++;if(request.action==='probe')return {identity:{type:'smbfs',fsid:'1:2',sourceHash:'a'.repeat(64),mountPath:'/synthetic/share',readOnly:false},security:'encrypted',dialect:'SMB_3.1.1',authentication:'macOS-session'};if(['header','library'].includes(request.action))return {format:'heed-portable-library',schemaVersion:1,destinationId};if(request.action==='list')return [];return {};},async read(){return Buffer.alloc(0);},async *stream(){yield Buffer.alloc(0);},async write(){}};
 const library=new PortableLibrary({root:join(root,'library'),sessions,sessionsDir:join(root,'sessions'),recordingsDir:join(root,'recordings'),quota:{reserve(){},release(){}}});let rejectPreference=false,rejectRollback=false,rejectFinal=false;const registryPath=join(root,'provider-preference.json'),registry=new ProviderRegistry({path:registryPath,getLibrary:()=>library,write:(path,state)=>{if(rejectPreference)throw new Error('Synthetic preference persistence failure');atomicWriteJson(path,state);}}),path=join(root,'library/catalog/smb.json');const options={path,catalogPath:join(root,'library/catalog/state.json'),sessions:()=>sessions.snapshot().sessions,native,library,registry,busy:()=>false,write:(file:string,state:any)=>{if(!state.transition&&(rejectRollback||rejectFinal))throw new Error('Synthetic settings persistence failure');atomicWriteJson(file,state);}};const service=new SmbConnections(options);cleanups.push(()=>{service.close();rmSync(root,{recursive:true,force:true});});const connect=async()=>{const receipt=await service.test('/synthetic/share');return service.connect({name:'Synthetic SMB',receipt:receipt.receipt,create:false});};const quota=()=>new ManagedQuota({ledgerPath:join(root,'quota.json'),roots:{text:[join(root,'sessions'),join(root,'library/catalog')],media:[join(root,'recordings')]},getLimit:()=>4000000,setLimit(){},protectedPaths:()=>service.protectedLocalPaths()});return {root,wav,path,registryPath,options,registry,library,service,connect,quota,cached:()=>((library as any).options.provider as SmbProvider),calls:()=>nativeCalls,set destination(value:string){destinationId=value;},set rejectPreference(value:boolean){rejectPreference=value;},set rejectRollback(value:boolean){rejectRollback=value;},set rejectFinal(value:boolean){rejectFinal=value;}};
}
test.each(['disable','disconnect','selection'] as const)('failed %s rollback protects sole source and cached provider; unresolved intent survives restart',async action=>{const f=fixture();await f.connect();const id=f.service.snapshot().connections[0]!.id,cached=f.cached();f.rejectPreference=true;f.rejectRollback=true;if(action==='selection'){f.destination=randomUUID();await expect(f.connect()).rejects.toThrow();}else expect(()=>action==='disable'?f.service.enable(id,false):f.service.disconnect(id)).toThrow();expect((f.service as any).unavailable()).toBe(true);const response=await smbResponse(new Request('http://localhost:5001/api/smb'),f.service);expect(response.status).toBe(503);expect((await response.json()).error).toContain('recovery is required');expect(f.service.protectedLocalPaths()).toContain(f.wav);expect(()=>f.quota().preview(1048576)).toThrow('protected');const calls=f.calls();await expect(cached.list(null,10)).rejects.toThrow('recovery');expect(f.calls()).toBe(calls);const restartRegistry=new ProviderRegistry({path:f.registryPath,getLibrary:()=>f.library});expect(()=>new SmbConnections({...f.options,write:atomicWriteJson,registry:restartRegistry})).toThrow('recovery');expect(JSON.parse(readFileSync(f.path,'utf8')).transition).toBeDefined();expect(readFileSync(f.wav).length).toBe(1200000);});
test('failed final settings commit restores provider preference and original unqueued protection',async()=>{const f=fixture();await f.connect();const id=f.service.snapshot().connections[0]!.id;let failed=false;f.options.write=(path,state:any)=>{if(!state.transition&&!failed){failed=true;throw new Error('Synthetic final commit failure');}atomicWriteJson(path,state);};expect(()=>f.service.enable(id,false)).toThrow('final commit');expect(f.registry.preferredId()).toBe(id);expect(f.library.snapshot().providerId).toBe(id);expect(f.service.snapshot().connections[0]!.enabled).toBe(true);expect(f.service.protectedLocalPaths()).toContain(f.wav);expect(JSON.parse(readFileSync(f.path,'utf8')).transition).toBeUndefined();});
test('private SMB configuration and protection catalogs reject actual symlinks and oversize files',async()=>{const f=fixture();await f.connect();const alias=join(f.root,'alias.json');symlinkSync(f.path,alias);expect(()=>new SmbConnections({...f.options,path:alias,registry:new ProviderRegistry({path:f.registryPath,getLibrary:()=>f.library})})).toThrow('Invalid private');const catalog=f.options.catalogPath,target=join(f.root,'catalog-target.json');writeFileSync(target,JSON.stringify({version:1,entries:{},heads:{}}));require('node:fs').unlinkSync(catalog);symlinkSync(target,catalog);expect(()=>f.service.protectedRevisionIds()).toThrow('Invalid private');expect(f.service.protectedLocalPaths()).toContain(f.wav);require('node:fs').unlinkSync(catalog);writeFileSync(catalog,'{}');truncateSync(catalog,64000001);expect(()=>f.service.protectedRevisionIds()).toThrow('Invalid private');truncateSync(f.path,16000001);expect(()=>new SmbConnections({...f.options,registry:new ProviderRegistry({path:f.registryPath,getLibrary:()=>f.library})})).toThrow('Invalid private');});
