import {describe,expect,test,spyOn} from 'bun:test';
import {reapAll} from './process';
import {createHash,randomUUID} from 'node:crypto';
import {SmbProvider, MacSmbNative, type SmbNative, type SmbIdentity, type SmbRequest} from './smb-provider';
import {mkdtempSync,rmSync,readdirSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const hash=(value:Uint8Array)=>createHash('sha256').update(value).digest('hex');
const bytes=(value:unknown)=>Buffer.from(JSON.stringify(value));
class Fixture implements SmbNative {
 identity:SmbIdentity={type:'smbfs',fsid:'1:2',sourceHash:'a'.repeat(64),mountPath:'/synthetic/share',readOnly:false};
 destinationId=randomUUID(); security:'signed'|'encrypted'|'unknown'='signed';files=new Map<string,Uint8Array>();writes:string[]=[];
 async json(request:SmbRequest){if(request.action==='probe')return {identity:this.identity,security:this.security,dialect:'SMB_3.1.1',authentication:'macOS-session'};if(request.action==='header')return {format:'heed-portable-library',schemaVersion:1,destinationId:this.destinationId};if(request.action==='list')return [...this.files.keys()].filter(p=>p.startsWith('commits/'));return {};}
 async read(request:SmbRequest,max:number){const value=this.files.get(request.path!);if(!value||value.length>max)throw new Error('Fixture unavailable');return value;}
 async *stream(request:SmbRequest,max:number){yield await this.read(request,max);}
 async write(request:SmbRequest,source:AsyncIterable<Uint8Array>){const parts=[];for await(const part of source)parts.push(part);const result=Buffer.concat(parts);if(result.length!==request.bytes||hash(result)!==request.sha256)throw new Error('Fixture integrity');const previous=this.files.get(request.path!);if(previous&&hash(previous)!==hash(result))throw new Error('Fixture collision');this.files.set(request.path!,result);this.writes.push(request.path!);}
 provider(readOnly=false){return new SmbProvider({id:randomUUID(),name:'Synthetic SMB',root:'/synthetic/share/Heed Library',identity:structuredClone(this.identity),destinationId:this.destinationId,readOnly,security:this.security},this);}
}
describe('SMB immutable provider',()=>{
 test('actual native subprocess rejects local fixture without writes or raw diagnostics',async()=>{const root=mkdtempSync(join(tmpdir(),'heed-smb-native-'));try{const native=new MacSmbNative();await expect(native.json({action:'probe',root})).rejects.toThrow('SMB operation unavailable');expect(readdirSync(root)).toEqual([]);}finally{rmSync(root,{recursive:true,force:true});}});
 test('server supervisor reaps an in-flight native SMB helper',async()=>{const original=Bun.spawn.bind(Bun);let child:ReturnType<typeof Bun.spawn>|undefined;const spy=spyOn(Bun,'spawn').mockImplementation((...args:any[])=>{child=original(['/usr/bin/python3','-c','import time; time.sleep(120)'],args[1]);return child as any;});const pending=new MacSmbNative().json({action:'probe',root:'/synthetic/share'});const settled=pending.catch(()=>{});try{await Bun.sleep(20);spy.mockRestore();await reapAll(100);expect(child?.killed).toBe(true);await expect(pending).rejects.toThrow('SMB operation unavailable');}finally{spy.mockRestore();child?.kill();await child?.exited;await settled;}});
 test('readonly, insecure or replaced mount never uploads',async()=>{const fixture=new Fixture(),p=fixture.provider(true);await expect(p.writeImmutable('objects/a',Buffer.from('a'))).rejects.toThrow();expect(fixture.writes).toEqual([]);fixture.security='unknown';await expect(fixture.provider().read('objects/a',4)).rejects.toThrow();fixture.security='signed';const old=fixture.provider();fixture.identity.fsid='new';await expect(old.writeImmutable('objects/a',Buffer.from('a'))).rejects.toThrow();});
 test('destination replacement fails even with same mount',async()=>{const f=new Fixture(),p=f.provider();f.destinationId=randomUUID();await expect(p.writeImmutable('objects/a',Buffer.from('a'))).rejects.toThrow();expect(f.writes).toEqual([]);});
 test('immutable objects verify exact source length and hash',async()=>{const f=new Fixture(),p=f.provider();const content=Buffer.from('audio');await p.writeObjectImmutable('objects/'+hash(content),content.length,hash(content),(async function*(){yield content;})());await expect(p.writeObjectImmutable('objects/'+hash(content),3,hash(content),(async function*(){yield content;})())).rejects.toThrow();await expect(p.writeImmutable('../outside',content)).rejects.toThrow();});
 test('read-back confirms marker, manifest, transcript and referenced audio before acknowledgment',async()=>{const f=new Fixture(),p=f.provider(),meetingId=randomUUID(),revisionId=randomUUID(),deviceId=randomUUID(),libraryId=randomUUID();const prefix=`meetings/${meetingId}/revisions/${revisionId}`,audio=Buffer.from('audio'),meeting=bytes({audio:{objectPath:`objects/${hash(audio)}`,sha256:hash(audio),bytes:audio.length}}),manifest=bytes({libraryId,meetingId,revisionId,artifacts:[{path:'meeting.json',bytes:meeting.length,sha256:hash(meeting)}]}),marker={schemaVersion:1 as const,libraryId,meetingId,revisionId,deviceId,manifestPath:`${prefix}/manifest.json`,manifestHash:hash(manifest)};
  f.files.set(`${prefix}/meeting.json`,meeting);f.files.set(marker.manifestPath,manifest);f.files.set(`commits/${deviceId}/${revisionId}.json`,bytes(marker));await expect(p.confirm(marker)).rejects.toThrow();f.files.set(`objects/${hash(audio)}`,audio);expect(await p.confirm(marker)).toBe('remote-confirmed');f.files.set(`${prefix}/meeting.json`,Buffer.from('broken'));await expect(p.confirm(marker)).rejects.toThrow();
 });
 test('pagination bounded and rejects changed listing or malformed marker path',async()=>{const f=new Fixture(),p=f.provider();for(let index=0;index<3;index++){const deviceId=randomUUID(),revisionId=randomUUID(),meetingId=randomUUID();f.files.set(`commits/${deviceId}/${revisionId}.json`,bytes({schemaVersion:1,libraryId:randomUUID(),meetingId,revisionId,deviceId,manifestPath:`meetings/${meetingId}/revisions/${revisionId}/manifest.json`,manifestHash:'a'.repeat(64)}));}const first=await p.list(null,2);expect(first.commits).toHaveLength(2);expect(first.next).not.toBeNull();expect((await p.list(first.next,2)).commits).toHaveLength(1);f.files.delete([...f.files.keys()][0]!);await expect(p.list(first.next,2)).rejects.toThrow();});
});
